force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ProjectCurrency__c.field-meta.xml
<CustomField>
    <fullName>ProjectCurrency__c</fullName>
    <label>Project Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlobalProjectCurrency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectEmployeeRate__c/ProjectEmployeeRate__c.object-meta.xml
<CustomObject>
    <label>Project Employee Rate</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Project Employee Rate Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Employee Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectEmployeeRate__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Employee Rates</relationshipLabel>
    <relationshipName>ProjectEmployeeRates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectEmployeeRate__c/fields/ProjectCurrency__c.field-meta.xml
<CustomField>
    <fullName>ProjectCurrency__c</fullName>
    <formula>TEXT( Project__r.ProjectCurrency__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProjectEmployeeRate__c/fields/ProjectEmployee__c.field-meta.xml
<CustomField>
    <fullName>ProjectEmployee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Contact</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Employee Rates</relationshipLabel>
    <relationshipName>ProjectEmployeeRates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectEmployeeRate__c/fields/ProjectEmployeeRateHour__c.field-meta.xml
<CustomField>
    <fullName>ProjectEmployeeRateHour__c</fullName>
    <label>Project Employee Rate (Hour)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectEmployeeRate__c/fields/ProjectEmployeeRole__c.field-meta.xml
<CustomField>
    <fullName>ProjectEmployeeRole__c</fullName>
    <label>Project Employee Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ManagingDirector</fullName>
                <label>Managing Director</label>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Teamleader</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Trainee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/GlobalProjectCurrency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <masterLabel>Global Project Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectEmployeeRateSelector.cls
public with sharing class ProjectEmployeeRateSelector  extends fflib_SObjectSelector
  implements IProjectEmployeeRateSelector {

  public static IProjectEmployeeRateSelector newInstance() {
    return (IProjectEmployeeRateSelector) Application.Selector.newInstance(ProjectEmployeeRate__c.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
    	ProjectEmployeeRate__c.Id,
    	ProjectEmployeeRate__c.Project__c,
    	ProjectEmployeeRate__c.ProjectCurrency__c,
	    ProjectEmployeeRate__c.ProjectEmployee__c,
    	ProjectEmployeeRate__c.ProjectEmployeeRateHour__c,
      	ProjectEmployeeRate__c.ProjectEmployeeRole__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return ProjectEmployeeRate__c.sObjectType;
  }

  public List<ProjectEmployeeRate__c> selectByProjectId(Set<Id> ids){
    fflib_QueryFactory query = newQueryFactory();
    query.setCondition('Project__c in :ids');
    return (List<ProjectEmployeeRate__c>) Database.query(query.toSOQL());
  }
}