force-app/main/default/objects/SupplierCosts__c/SupplierCosts__c.object-meta.xml
<CustomObject>
    <label>Supplier Costs</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>Supplier Costs Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCosts__c/fields/SupplierCostsDate__c.field-meta.xml
<CustomField>
    <fullName>SupplierCostsDate__c</fullName>
    <label>Supplier Costs Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/SupplierCostsInvoicedPM__c.field-meta.xml
<CustomField>
    <fullName>SupplierCostsInvoicedPM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Supplier Costs invoiced (PM)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SupplierCostsSelector.cls
public with sharing class SupplierCostsSelector extends fflib_SObjectSelector
  implements ISupplierCostsSelector {

  public static ISupplierCostsSelector newInstance() {
    return (ISupplierCostsSelector) Application.Selector.newInstance(SupplierCosts__c.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      SupplierCosts__c.Id
    };
  }

  public Schema.SObjectType getSObjectType() {
    return SupplierCosts__c.sObjectType;
  }

  public override String getOrderBy() {
    return 'SupplierCostsDate__c DESC, SupplierCostsInvoicedPM__c ASC';
  }

}