force-app/main/default/objects/SupplierCosts__c/SupplierCosts__c.object-meta.xml
<CustomObject>
    <label>Supplier Costs</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>Supplier Costs Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCosts__c/fields/CostsSupplierCostsGrossCHF__c.field-meta.xml
<CustomField>
    <fullName>CostsSupplierCostsGrossCHF__c</fullName>
    <label>Costs - Supplier Costs Gross (CHF)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/recordTypes/SupplierCosts.recordType-meta.xml
<RecordType>
    <fullName>SupplierCosts</fullName>
    <active>true</active>
    <label>Supplier Costs</label>
</RecordType>

force-app/main/default/classes/TestSupplierCostsService.cls
@IsTest
private class TestSupplierCostsService {

  @IsTest
  private static void callingServiceShouldCallDomain() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    ISupplierCosts domainMock = new Mocks.SupplierCosts(mocks);

    //Given
    mocks.startStubbing();
    SupplierCosts__c sc = new SupplierCosts__c(CostsSupplierCostsGrossCHF__c = 10);
    mocks.when(domainMock.sObjectType()).thenReturn(SupplierCosts__c.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Domain.setMock(domainMock);

    // When
    SupplierCostsService.save(new List<SupplierCosts__c> {sc});

    // Then
    ((ISupplierCosts) mocks.verify(domainMock)).save(uowMock);
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock)).commitWork();

  }

}