force-app/main/default/objects/Pack__c/Pack__c.object-meta.xml
<CustomObject>
    <label>Bundle Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundle Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Package__c/Quote_Package__c.object-meta.xml
<CustomObject>
    <label>Quote Package</label>
    <nameField>
        <label>Quote Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineItem/fields/Quote_Package__c.field-meta.xml
<CustomField>
    <fullName>Quote_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Package</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.QuoteId</field>
            <operation>equals</operation>
            <valueField>Quote_Package__c.Quote__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote_Package__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuotePackageHandlerTest.cls
/*
*	@description Test class for QuotePackageHandler functionality.
*
*	@author ach
*	@copyright PARX
*/
@isTest
public with sharing class QuotePackageHandlerTest
{
	/*
	*	@description Test trigger logic.
	*/
	static testMethod void testMainFunctionality()
	{
		//Insert
		Id pricebookId = Test.getStandardPricebookId();
		Pack__c pack = TestFactory.createPackage(pricebookId);
		Account acc = TestFactory.createAccount();
		Opportunity opp = TestFactory.createOpportunity(acc, pricebookId);
		Quote quote = TestFactory.createQuote(opp);
		Quote_Package__c quotePackage = TestFactory.createQuotePackage(quote, pack); 
		List<Product2> products = new List<Product2>{TestFactory.createProduct(false), TestFactory.createProduct(false), TestFactory.createProduct(false)};
		insert products;

		List<QuoteLineItem> lineItems = new List<QuoteLineItem>{
			TestFactory.createQuoteLineItem(quote, products[0], false),
			TestFactory.createQuoteLineItem(quote, products[1], false),
			TestFactory.createQuoteLineItem(quote, products[2], false)
		};
		lineItems[0].Quote_Package__c = quotePackage.Id;
		lineItems[1].Quote_Package__c = quotePackage.Id;
		insert lineItems;
		
		Test.startTest();
		delete quotePackage;
		Test.stopTest();
		lineItems = [SELECT Id  FROM QuoteLineItem];
		System.assertEquals(1, lineItems.size(), 'Wrong number of QuoteLineItem records: 2 from 3 should be deleted.');
	}
}