force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/Insert__c.field-meta.xml
<CustomField>
    <fullName>Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Functions executes on record creation.</inlineHelpText>
    <label>Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/RelationshipField__c.field-meta.xml
<CustomField>
    <fullName>RelationshipField__c</fullName>
    <inlineHelpText>Lockup to field which defines the relation between Source and Target Object. 
Hint: As the you can use a relation like &quot;ProjectName__r.BillingViaCompany__c&quot; it is possible to have a relation more then one level deep.</inlineHelpText>
    <label>RelationshipField</label>
    <referenceTo>Field__mdt</referenceTo>
    <relationshipLabel>Inherited field values (RelationshipField)</relationshipLabel>
    <relationshipName>FieldValueInheritances1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/SourceObject__c.field-meta.xml
<CustomField>
    <fullName>SourceObject__c</fullName>
    <label>SourceObject</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipName>FieldValueInheritances1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/SourceQuery__c.field-meta.xml
<CustomField>
    <fullName>SourceQuery__c</fullName>
    <inlineHelpText>API Name to the referenced Field. 
Hint: As you can use a also a reference like &quot;ProjectName__r.BillingViaCompany__c&quot; it is possible to achieve a relation more then one level deep.</inlineHelpText>
    <label>SourceQuery</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/TargetField__c.field-meta.xml
<CustomField>
    <fullName>TargetField__c</fullName>
    <label>TargetField</label>
    <referenceTo>Field__mdt</referenceTo>
    <relationshipName>FieldValueInheritances</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/Update__c.field-meta.xml
<CustomField>
    <fullName>Update__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Execute the function on update of the Child record.</inlineHelpText>
    <label>Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/UserValuesWinsOnInsert__c.field-meta.xml
<CustomField>
    <fullName>UserValuesWinsOnInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Needed as example for Terms of Payment on Project, so if the user does not provide any value its taken (inherited) from the account. Usually it does not make sense to have this flag and Update turned on both.</description>
    <inlineHelpText>If the user provides a value in the user interface when creating a new record, the value will not be inherited from the parent record.</inlineHelpText>
    <label>User values wins (on insert)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object__mdt/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <label>APIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InheritedFieldValueMDT.cls
public with sharing class InheritedFieldValueMDT extends fflib_SObjectDomain
	implements IInheritedFieldValueMDT {

	public static IInheritedFieldValueMDT newInstance(List<InheritedFieldValue__mdt> records) {
		return (IInheritedFieldValueMDT) Application.Domain.newInstance(records);
	}

	public InheritedFieldValueMDT(List<InheritedFieldValue__mdt> records) {
		super(records);
	}

	public void go(fflib_ISObjectUnitOfWork uow, List<SObject> targets) {

		Map<String, fflib_QueryFactory> qFactories = new Map<String, fflib_QueryFactory>();
		Map<String, List<InheritedFieldValue__mdt>> inheritedFVMap = new Map<String, List<InheritedFieldValue__mdt>>();
		Map<String, Set<String>> relatedFieldMap = new Map<String, Set<String>>();

		for (InheritedFieldValue__mdt ifv: (List<InheritedFieldValue__mdt>) records) {

			for (SObject obj: targets) {

				Boolean isInsert = System.Test.isRunningTest() ? true : Trigger.isInsert; // trick for running our test

				//if UserValuesWinsOnInsert__c == true, this is a new record getting inserted and there is a supplied value from the user then don't inherit a value
				if(ifv.UserValuesWinsOnInsert__c == true && isInsert && obj.get(ifv.TargetField__r.APIName__c) != null){
					continue;
				}


				if ((ifv.Insert__c == true && isInsert) || (ifv.Update__c == true && Trigger.isUpdate)) {
					SObjectType sourceObjectType = Schema.getGlobalDescribe().get(ifv.SourceObject__r.APIName__c);
					fflib_QueryFactory qf = qFactories.get(ifv.SourceObject__r.APIName__c);

					if (qf == null) {
						qf = new fflib_QueryFactory(sourceObjectType);
						qFactories.put(ifv.SourceObject__r.APIName__c, qf);
					}

					qf.selectField(ifv.SourceQuery__c);

					String relatedField = (String) obj.get(ifv.RelationshipField__r.APIName__c);
					Set<String> relatedFields = relatedFieldMap.get(ifv.SourceObject__r.APIName__c);
					if (relatedFields == null) {
						relatedFieldMap.put(ifv.SourceObject__r.APIName__c, new Set<String>{relatedField});
					} else {
						relatedFields.add(relatedField);
					}

					List<InheritedFieldValue__mdt> ifvList = inheritedFVMap.get(ifv.SourceObject__r.APIName__c);
					if (!(obj.get(ifv.RelationshipField__r.APIName__c) instanceof Id)) {
						continue;
					}
					if (ifvList == null || ifvList.isEmpty()) {
						inheritedFVMap.put(ifv.SourceObject__r.APIName__c, new List<InheritedFieldValue__mdt> {ifv});
					} else {
						ifvList.add(ifv);
					}
				}
			}

		}

		Set<String> factoryKeys = qFactories.keySet();
		for (String key: factoryKeys) { 

			fflib_QueryFactory qf = qFactories.get(key);
			Set<String> relatedFields = relatedFieldMap.get(key);
			qf.setCondition('Id IN :relatedFields');
			System.debug('queryLook: '+qf.toSOQL());
			Map<Id, SObject> sourceObjsMap = new Map<Id, SObject>(Database.query(qf.toSOQL()));

			if (sourceObjsMap.size() > 0) {
				for (SObject obj: targets) {
					for (InheritedFieldValue__mdt ifv: inheritedFVMap.get(key)) {
						SObject sourceObject = sourceObjsMap.get((Id) obj.get(ifv.RelationshipField__r.APIName__c));
						if (sourceObject != null) {
							obj.put(ifv.TargetField__r.APIName__c, Utils.getSObjectValue(sourceObject, ifv.SourceQuery__c));
						}
					}

					if (uow != null) uow.registerDirty(obj);

				}
			}

		}

	}

	public class Constructor implements fflib_SObjectDomain.IConstructable {
		public fflib_SObjectDomain construct(List<SObject> sObjectList) {
			return new InheritedFieldValueMDT(sObjectList);
		}
	}

}