force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProjectEmployeeRate__c/ProjectEmployeeRate__c.object-meta.xml
<CustomObject>
    <label>Project Employee Rate</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Project Employee Rate Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Employee Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectEmployeeRate.cls
public with sharing class ProjectEmployeeRate  extends fflib_SObjectDomain
  implements IProjectEmployeeRate {

  public static IProjectEmployeeRate newInstance(List<ProjectEmployeeRate__c> records) {
    return (IProjectEmployeeRate) Application.Domain.newInstance(records);
  }

  public ProjectEmployeeRate(List<ProjectEmployeeRate__c> records) {
    super(records);
  }

  public override void onBeforeInsert() {
    callInheritedFieldValue(false);
    callUpdateExchangeRate(null);
  }

  public override void onBeforeUpdate(Map<Id,SObject> oldRecords) {
    callInheritedFieldValue(false);
    callUpdateExchangeRate(oldRecords);
  }

  public override void onAfterInsert() {
    callParentUpdate(null);
  }

  public override void onAfterUpdate(Map<Id,SObject> oldRecords) {
    callParentUpdate(oldRecords);
  }

  @TestVisible
  private void callUpdateExchangeRate(Map<Id,SObject> oldRecords){
    List<Object__mdt> objs = ObjectMDTSelector.newInstance().selectCurrencyFields(this.getSObjectType().getDescribe().getName());

      //if we have currency fields and currency conversion is endabled then update
      if(objs.size() > 0 && objs[0].Fields__r != null){
        IFieldMDT fieldDomain = FieldMDT.newInstance(objs[0].Fields__r);
        fieldDomain.updateExchangeRate(records, oldRecords);
      }
  }

  @TestVisible
  private void callParentUpdate(Map<Id,SObject> oldRecords) {
    fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
    List<ParentObjectUpdate__mdt> pous = ParentObjectUpdateMDTSelector.newInstance().selectBySourceObj(this.getSObjectType().getDescribe().getName());
    IParentObjectUpdateMDT pouDomain = ParentObjectUpdateMDT.newInstance(pous);

    pouDomain.go(uow, records, oldRecords);
    uow.commitWork();
  }

  public override void onBeforeDelete() {
    List<Field__mdt> fields = FieldMDTSelector.newInstance().selectDeletionControlFields(this.getSObjectType().getDescribe().getName());
    IFieldMDT fieldDomain = FieldMDT.newInstance(fields);
    fieldDomain.controlDeletion(records);
  }

  @TestVisible
  private void callInheritedFieldValue(Boolean isUpdate) {
    List<InheritedFieldValue__mdt> inheritedFValues = InheritedFieldValueMDTSelector.newInstance().selectByTargetObj(this.getSObjectType().getDescribe().getName());
    IInheritedFieldValueMDT inheritedFVDomain = InheritedFieldValueMDT.newInstance(inheritedFValues);

    if (isUpdate) {
      fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
      inheritedFVDomain.go(uow, records);
      uow.commitWork();
    } else {
      inheritedFVDomain.go(null, records);
    }

  }

  public class Constructor implements fflib_SObjectDomain.IConstructable {
		public fflib_SObjectDomain construct(List<SObject> sObjectList) {
			return new ProjectEmployeeRate(sObjectList);
		}
	}

}