force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/PermissionSetAssigment__mdt/PermissionSetAssigment__mdt.object-meta.xml
<CustomObject>
    <label>Permission set assigment</label>
    <pluralLabel>Permission set assigments</pluralLabel>
</CustomObject>

force-app/main/default/objects/PermissionSetAssigment__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <referenceTo>Field__mdt</referenceTo>
    <relationshipName>PermissionsetUserAssignments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/PermissionSetAssigment__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PermissionSetAssigment__mdt/fields/PermissionSet__c.field-meta.xml
<CustomField>
    <fullName>PermissionSet__c</fullName>
    <label>PermissionSet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PermissionSetAssignmentMDTSelector.cls
public with sharing class PermissionSetAssignmentMDTSelector  extends fflib_SObjectSelector
  implements IPermissionSetAssignmentMDTSelector {

  public static IPermissionSetAssignmentMDTSelector newInstance() {
    return (IPermissionSetAssignmentMDTSelector) Application.Selector.newInstance(PermissionSetAssigment__mdt.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
    	PermissionSetAssigment__mdt.DeveloperName,
      	PermissionSetAssigment__mdt.Field__c,
      	PermissionSetAssigment__mdt.Id,
      	PermissionSetAssigment__mdt.isActive__c,
      	PermissionSetAssigment__mdt.MasterLabel,
      	PermissionSetAssigment__mdt.NamespacePrefix,
      	PermissionSetAssigment__mdt.PermissionSet__c
    };
  }

  public List<PermissionSetAssigment__mdt> selectBySourceObj(String typeName) {
    fflib_QueryFactory query = newQueryFactory();
    query.selectField('Field__r.APIName__c');
    query.setCondition('isActive__c = true AND Field__r.Object__r.APIName__c = :typeName');
    return (List<PermissionSetAssigment__mdt>) Database.query(query.toSOQL());
  }


  public Schema.SObjectType getSObjectType() {
    return PermissionSetAssigment__mdt.sObjectType;
  }
}