force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/Insert__c.field-meta.xml
<CustomField>
    <fullName>Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Functions executes on record creation.</inlineHelpText>
    <label>Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Turns the function on and off</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/RelationshipField__c.field-meta.xml
<CustomField>
    <fullName>RelationshipField__c</fullName>
    <inlineHelpText>Lockup to field which defines the relation between Source and Target Object. 
Hint: As the you can use a relation like &quot;ProjectName__r.BillingViaCompany__c&quot; it is possible to have a relation more then one level deep.</inlineHelpText>
    <label>RelationshipField</label>
    <referenceTo>Field__mdt</referenceTo>
    <relationshipLabel>Inherited field values (RelationshipField)</relationshipLabel>
    <relationshipName>FieldValueInheritances1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/SourceObject__c.field-meta.xml
<CustomField>
    <fullName>SourceObject__c</fullName>
    <label>SourceObject</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipName>FieldValueInheritances1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/SourceQuery__c.field-meta.xml
<CustomField>
    <fullName>SourceQuery__c</fullName>
    <inlineHelpText>API Name to the referenced Field. 
Hint: As you can use a also a reference like &quot;ProjectName__r.BillingViaCompany__c&quot; it is possible to achieve a relation more then one level deep.</inlineHelpText>
    <label>SourceQuery</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/TargetField__c.field-meta.xml
<CustomField>
    <fullName>TargetField__c</fullName>
    <label>TargetField</label>
    <referenceTo>Field__mdt</referenceTo>
    <relationshipName>FieldValueInheritances</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/TargetObject__c.field-meta.xml
<CustomField>
    <fullName>TargetObject__c</fullName>
    <label>TargetObject</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipName>FieldValueInheritances</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/Update__c.field-meta.xml
<CustomField>
    <fullName>Update__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Execute the function on update of the Child record.</inlineHelpText>
    <label>Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/fields/UserValuesWinsOnInsert__c.field-meta.xml
<CustomField>
    <fullName>UserValuesWinsOnInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Needed as example for Terms of Payment on Project, so if the user does not provide any value its taken (inherited) from the account. Usually it does not make sense to have this flag and Update turned on both.</description>
    <inlineHelpText>If the user provides a value in the user interface when creating a new record, the value will not be inherited from the parent record.</inlineHelpText>
    <label>User values wins (on insert)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object__mdt/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <label>APIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/InheritedFieldValueMDTSelector.cls
public with sharing class InheritedFieldValueMDTSelector extends fflib_SObjectSelector
  implements IInheritedFieldValueMDTSelector {

  public static IInheritedFieldValueMDTSelector newInstance() {
    return (IInheritedFieldValueMDTSelector) Application.Selector.newInstance(InheritedFieldValue__mdt.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      InheritedFieldValue__mdt.DeveloperName,
      InheritedFieldValue__mdt.Id,
      InheritedFieldValue__mdt.Insert__c,
      InheritedFieldValue__mdt.isActive__c,
      InheritedFieldValue__mdt.Label,
      InheritedFieldValue__mdt.Language,
      InheritedFieldValue__mdt.MasterLabel,
      InheritedFieldValue__mdt.NamespacePrefix,
      InheritedFieldValue__mdt.QualifiedApiName,
      InheritedFieldValue__mdt.RelationshipField__c,
      InheritedFieldValue__mdt.SourceObject__c,
      InheritedFieldValue__mdt.SourceQuery__c,
      InheritedFieldValue__mdt.TargetField__c,
      InheritedFieldValue__mdt.TargetObject__c,
      InheritedFieldValue__mdt.Update__c,
      InheritedFieldValue__mdt.UserValuesWinsOnInsert__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return InheritedFieldValue__mdt.sObjectType;
  }

  public List<InheritedFieldValue__mdt> selectByTargetObj(String typeName) {
    fflib_QueryFactory query = newQueryFactory();

    query.selectField('TargetObject__r.APIName__c');
    query.selectField('SourceObject__r.APIName__c');
    query.selectField('RelationshipField__r.APIName__c');
    query.selectField('TargetField__r.APIName__c');
    query.setCondition('isActive__c = true AND TargetObject__r.APIName__c = :typeName');
    return (List<InheritedFieldValue__mdt>) Database.query(query.toSOQL());
  }

  public List<InheritedFieldValue__mdt> selectActives() {
    fflib_QueryFactory query = newQueryFactory();

    query.selectField('TargetObject__r.APIName__c');
    query.selectField('SourceObject__r.APIName__c');
    query.selectField('RelationshipField__r.APIName__c');
    query.selectField('TargetField__r.APIName__c');
    query.setCondition('isActive__c = true');
    return (List<InheritedFieldValue__mdt>) Database.query(query.toSOQL());
  }

  public List<InheritedFieldValue__mdt> getInheritedFieldValueMDTTest() {
    fflib_QueryFactory query = newQueryFactory();

    query.selectField('TargetObject__r.APIName__c');
    query.selectField('SourceObject__r.APIName__c');
    query.selectField('RelationshipField__r.APIName__c');
    query.selectField('TargetField__r.APIName__c');
    query.setCondition('SourceObject__r.APIName__c = \'Project__c\' AND SourceQuery__c = \'InvoiceDescription__c\'');
    return (List<InheritedFieldValue__mdt>) Database.query(query.toSOQL());
  }

}