force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/PermissionSetAssigment__mdt/PermissionSetAssigment__mdt.object-meta.xml
<CustomObject>
    <label>Permission set assigment</label>
    <pluralLabel>Permission set assigments</pluralLabel>
</CustomObject>

force-app/main/default/objects/PermissionSetAssigment__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <referenceTo>Field__mdt</referenceTo>
    <relationshipName>PermissionsetUserAssignments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/PermissionSetAssigment__mdt/fields/PermissionSet__c.field-meta.xml
<CustomField>
    <fullName>PermissionSet__c</fullName>
    <label>PermissionSet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PermissionSetAssignmentMDT.cls
public with sharing class PermissionSetAssignmentMDT   extends fflib_SObjectDomain
  implements IPermissionSetAssignmentMDT {
  
  public static IPermissionSetAssignmentMDT newInstance(List<PermissionSetAssigment__mdt> records) {
    return (IPermissionSetAssignmentMDT) Application.Domain.newInstance(records);
  }

  public PermissionSetAssignmentMDT(List<PermissionSetAssigment__mdt> records) {
    super(records);
  }

  public class Constructor implements fflib_SObjectDomain.IConstructable {
		public fflib_SObjectDomain construct(List<SObject> sObjectList) {
			return new PermissionSetAssignmentMDT(sObjectList);
		}
	}

  public void applyPermissionSets(fflib_ISObjectUnitOfWork uow, List<SObject> userRecords, List<PermissionSetAssignment> userPerms){
    //get a map of available permission sets to use when creating new assignments
    List<PermissionSet> permSets = PermissionSetSelector.newInstance().selectAll();
    Map<String, Id> permSetMap = new Map<String, Id>();
    for(PermissionSet s : permSets){
      permSetMap.put(s.Name, s.Id);
    }

    for(SObject obj : userRecords){
      //create a set of the user's permission sets
      Map<String, PermissionSetAssignment> userPermMap = new Map<String, PermissionSetAssignment>();
      for(PermissionSetAssignment p : userPerms){
        if(p.AssigneeId == (Id)obj.get('Id')){
          userPermMap.put(p.PermissionSet.Name, p);
        }
      }

      for(PermissionSetAssigment__mdt f: (List<PermissionSetAssigment__mdt>)records){
        if((Boolean)obj.get(f.Field__r.APIName__c) == true){
          //is there an existing permission set for this user?
          if(!userPermMap.containsKey(f.PermissionSet__c)){
            //if not create it
            PermissionSetAssignment assign = new PermissionSetAssignment();
            assign.AssigneeId = (Id)obj.get('Id');
            assign.PermissionSetId = (Id)permSetMap.get(f.PermissionSet__c);
            uow.registerNew(assign);
          }
         
        }

        if((Boolean)obj.get(f.Field__r.APIName__c) == false){
          //is there an existing permission set for this user?
          if(userPermMap.containsKey(f.PermissionSet__c)){
            //if so then remove it
            uow.registerDeleted(userPermMap.get(f.PermissionSet__c));
          }
        }
      }
    }
  }
}