force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/PackageRateHour__c.field-meta.xml
<CustomField>
    <fullName>PackageRateHour__c</fullName>
    <label>Package Rate (Hour)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageSpecificRate__c.field-meta.xml
<CustomField>
    <fullName>PackageSpecificRate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Package Specific Rate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageStatus__c.field-meta.xml
<CustomField>
    <fullName>PackageStatus__c</fullName>
    <label>Package Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>PartiallyOpen</fullName>
                <label>Partially open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageSubType__c.field-meta.xml
<CustomField>
    <fullName>PackageSubType__c</fullName>
    <inlineHelpText>Manufaktur only for SVH</inlineHelpText>
    <label>Package Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkTime</fullName>
                <label>Work Time</label>
            </value>
            <value>
                <fullName>TravelTime</fullName>
                <label>Travel Time</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>3rdPartyCosts</fullName>
                <label>3rd Party Costs</label>
            </value>
            <value>
                <fullName>ProjectResourceCosts</fullName>
                <label>Project Resource Costs</label>
            </value>
            <value>
                <fullName>AbacusInbox</fullName>
                <label>Abacus Inbox</label>
            </value>
            <value>
                <fullName>Manufaktur</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>LicenseDirect</fullName>
                <label>License (Direct)</label>
            </value>
            <value>
                <fullName>LicenseProvision</fullName>
                <label>License (Provision)</label>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Attention: You should not add a package to a Project with Status = Closed</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>PackagesProjectName</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Package__c/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Package__c/recordTypes/SupplierCosts.recordType-meta.xml
<RecordType>
    <fullName>SupplierCosts</fullName>
    <active>true</active>
    <label>Supplier Costs</label>
</RecordType>

force-app/main/default/objects/Package__c/recordTypes/Time.recordType-meta.xml
<RecordType>
    <fullName>Time</fullName>
    <active>true</active>
    <label>Time</label>
</RecordType>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ProjectRateHour__c.field-meta.xml
<CustomField>
    <fullName>ProjectRateHour__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName =&quot;Internal&quot;,200,null)</defaultValue>
    <inlineHelpText>Internal Projects: CHF 200.00</inlineHelpText>
    <label>Project Rate (Hour)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PackageDomain.cls
public with sharing class PackageDomain extends fflib_SObjectDomain
        implements IPackageDomain {

    public static String TYPE_GROUP = 'Group';
    public static String TYPE_TIME = 'Time';
    public static String TYPE_EXPENSE = 'Expense';
    public static String TYPE_SUPPLIER_COSTS = 'SupplierCosts';
    public static String SUB_TYPE_WORK_TIME = 'Work Time';
    public static String SUB_TYPE_3RD_PARTY = '3rd Party Costs';

    public static Map<String, Id> RecordTypeMap = new Map<String, Id>{
            TYPE_GROUP => Utils.getRecordTypeIdByDevName('Package__c', TYPE_GROUP),
            TYPE_TIME => Utils.getRecordTypeIdByDevName('Package__c', TYPE_TIME),
            TYPE_EXPENSE => Utils.getRecordTypeIdByDevName('Package__c', TYPE_EXPENSE),
            TYPE_SUPPLIER_COSTS => Utils.getRecordTypeIdByDevName('Package__c', TYPE_SUPPLIER_COSTS)
    };

    public static IPackageDomain newInstance(List<Package__c> records) {
        return (IPackageDomain) Application.Domain.newInstance(records);
    }

    public PackageDomain(List<Package__c> records) {
        super(records);
    }


    public override void onBeforeInsert() {
        callUpdateExchangeRate(null);
        updatePackageRates(null);
        callInheritedFieldValue(false);
    }

    public override void onBeforeUpdate(Map<Id, SObject> oldRecords) {
        callUpdateExchangeRate(oldRecords);
        updatePackageRates(oldRecords);
        callInheritedFieldValue(false);
    }

    public override void onBeforeDelete() {
        List<Field__mdt> fields = FieldMDTSelector.newInstance().selectDeletionControlFields(this.getSObjectType().getDescribe().getName());
        IFieldMDT fieldDomain = FieldMDT.newInstance(fields);
        fieldDomain.controlDeletion(records);
    }

    public override void onAfterInsert() {
        callParentUpdate(null);
    }

    public override void onAfterUpdate(Map<Id, SObject> oldRecords) {
        fflib_SObjectDomain.getTriggerEvent(PackageDomain.class).disableAfterUpdate();
        callParentUpdate(oldRecords);
    }

    public void save(fflib_ISObjectUnitOfWork uow) {

        for (Package__c p : (List<Package__c>) records) {
            setPicklistValues(p);

            if (p.Id != null) {
                uow.registerDirty(p);
            } else {
                uow.registerNew(p);
            }
        }

    }

    private void setPicklistValues(Package__c p) {
        if (p.PackageSubType__c != null)
            p.PackageSubType__c = Picklist.get(Package__c.PackageSubType__c, p.PackageSubType__c);

        if (p.PackageStatus__c != null)
            p.PackageStatus__c = Picklist.get(Package__c.PackageStatus__c, p.PackageStatus__c);
    }

    public void del(fflib_ISObjectUnitOfWork uow) {
        for (Package__c p : (List<Package__c>) records) {
            uow.registerDeleted(p);
        }
    }

    public void updatePackageRates(Map<Id, SObject> oldRecords) {

        if (oldRecords == null) {
            oldRecords = new Map<Id, SObject>();
        }

        // get project's Ids
        Set<Id> projectIds = new Set<Id>();

        // for every given project
        for (Package__c packageToFetchProjectFor : (List<Package__c>) records) {

            // get the old records
            Package__c oldPackage = (Package__c) oldRecords.get(packageToFetchProjectFor.Id);

            // only add project if the project rate field or project specific rate changed
            if (oldPackage == null || (packageToFetchProjectFor.PackageRateHour__c != oldPackage.PackageRateHour__c) || (packageToFetchProjectFor.PackageSpecificRate__c != oldPackage.PackageSpecificRate__c)) {
                projectIds.add(packageToFetchProjectFor.ProjectName__c);
            }

        }

        // fetch the projects
        List<Project__c> projects = (List<Project__c>) ProjectSelector.newInstance().selectSObjectsById(projectIds);

        // map projects so we can fetch rate later on
        Map<Id, Project__c> projectMap = new Map<Id, Project__c>();
        for (Project__c project : projects) {
            projectMap.put(project.Id, project);
        }

        // fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        for (Package__c packageToUpdate : (List<Package__c>) records) {

            // if it doesnt have a specific rate
            if (!packageToUpdate.PackageSpecificRate__c) {

                Project__c project = projectMap.get(packageToUpdate.ProjectName__c);

                //validate for packages with rates != projet rate but without out PackageSpecificRate__c set to true
                if (project != null && packageToUpdate.PackageRateHour__c != null && packageToUpdate.PackageRateHour__c != project.ProjectRateHour__c) {
                    packageToUpdate.addError(Label.Skywalk_PackageSpecificRateToTrue);
                    continue;
                }


                // set the package rate to the project rate
                if (project != null) {
                    packageToUpdate.PackageRateHour__c = project.ProjectRateHour__c;
                }

                // update!
                // uow.registerDirty(packageToUpdate);

            }

        }

        // uow.commitWork();


    }

    @TestVisible
    private void callUpdateExchangeRate(Map<Id, SObject> oldRecords) {
        List<Object__mdt> objs = ObjectMDTSelector.newInstance().selectCurrencyFields(this.getSObjectType().getDescribe().getName());

        //if we have currency fields and currency conversion is endabled then update
        if (objs.size() > 0 && objs[0].Fields__r != null) {
            IFieldMDT fieldDomain = FieldMDT.newInstance(objs[0].Fields__r);
            fieldDomain.updateExchangeRate(records, oldRecords);
        }
    }

    @TestVisible
    private void callParentUpdate(Map<Id, SObject> oldRecords) {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        List<ParentObjectUpdate__mdt> pous = ParentObjectUpdateMDTSelector.newInstance().selectBySourceObj(this.getSObjectType().getDescribe().getName());
        IParentObjectUpdateMDT pouDomain = ParentObjectUpdateMDT.newInstance(pous);

        pouDomain.go(uow, records, oldRecords);
        uow.commitWork();
    }

    @TestVisible
    private void callInheritedFieldValue(Boolean isUpdate) {
        List<InheritedFieldValue__mdt> inheritedFValues = InheritedFieldValueMDTSelector.newInstance().selectByTargetObj(this.getSObjectType().getDescribe().getName());
        IInheritedFieldValueMDT inheritedFVDomain = InheritedFieldValueMDT.newInstance(inheritedFValues);

        if (isUpdate) {
            fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
            inheritedFVDomain.go(uow, records);
            uow.commitWork();
        } else {
            inheritedFVDomain.go(null, records);
        }

    }

    public static String getSubType(String type) {
        String subType = 'None';

        if (type == PackageDomain.TYPE_TIME) {
            subType = PackageDomain.SUB_TYPE_WORK_TIME;
        } else if (type == 'SupplierCosts') {
            subType = PackageDomain.SUB_TYPE_3RD_PARTY;
        }

        return subType;
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new PackageDomain(sObjectList);
        }
    }
}