force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object__mdt/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <label>APIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/ParentObjectUpdate__mdt/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Has changed</fullName>
                <default>true</default>
                <label>Has changed</label>
            </value>
            <value>
                <fullName>Equals true</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ParentObjectUpdate__mdt/fields/ConditionField__c.field-meta.xml
<CustomField>
    <fullName>ConditionField__c</fullName>
    <label>ConditionField</label>
    <referenceTo>Field__mdt</referenceTo>
    <relationshipName>UpdateParentObjects</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ParentObjectUpdate__mdt/fields/Insert__c.field-meta.xml
<CustomField>
    <fullName>Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ParentObjectUpdate__mdt/fields/RelationField__c.field-meta.xml
<CustomField>
    <fullName>RelationField__c</fullName>
    <label>RelationField</label>
    <referenceTo>Field__mdt</referenceTo>
    <relationshipName>UpdateParentObjects2</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ParentObjectUpdate__mdt/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <label>Requirement</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ParentObjectUpdate__mdt/fields/SourceField__c.field-meta.xml
<CustomField>
    <fullName>SourceField__c</fullName>
    <label>SourceField</label>
    <referenceTo>Field__mdt</referenceTo>
    <relationshipName>UpdateParentObjects3</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ParentObjectUpdate__mdt/fields/SourceObject__c.field-meta.xml
<CustomField>
    <fullName>SourceObject__c</fullName>
    <label>SourceObject</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipName>UpdateParentObjects</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ParentObjectUpdate__mdt/fields/TargetField__c.field-meta.xml
<CustomField>
    <fullName>TargetField__c</fullName>
    <label>TargetField</label>
    <referenceTo>Field__mdt</referenceTo>
    <relationshipName>UpdateParentObjects1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ParentObjectUpdate__mdt/fields/TargetObject__c.field-meta.xml
<CustomField>
    <fullName>TargetObject__c</fullName>
    <label>TargetObject</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipName>UpdateParentObjects1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ParentObjectUpdate__mdt/fields/Update__c.field-meta.xml
<CustomField>
    <fullName>Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ParentObjectUpdateMDTSelector.cls
public with sharing class ParentObjectUpdateMDTSelector extends fflib_SObjectSelector
  implements IParentObjectUpdateMDTSelector {

  public static IParentObjectUpdateMDTSelector newInstance() {
    return (IParentObjectUpdateMDTSelector) Application.Selector.newInstance(ParentObjectUpdate__mdt.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      ParentObjectUpdate__mdt.Condition__c,
      ParentObjectUpdate__mdt.ConditionField__c,
      ParentObjectUpdate__mdt.DeveloperName,
      ParentObjectUpdate__mdt.Id,
      ParentObjectUpdate__mdt.Insert__c,
      ParentObjectUpdate__mdt.isActive__c,
      ParentObjectUpdate__mdt.Label,
      ParentObjectUpdate__mdt.Language,
      ParentObjectUpdate__mdt.MasterLabel,
      ParentObjectUpdate__mdt.NamespacePrefix,
      ParentObjectUpdate__mdt.QualifiedApiName,
      ParentObjectUpdate__mdt.RelationField__c,
      ParentObjectUpdate__mdt.Requirement__c,
      ParentObjectUpdate__mdt.SourceField__c,
      ParentObjectUpdate__mdt.SourceObject__c,
      ParentObjectUpdate__mdt.TargetField__c,
      ParentObjectUpdate__mdt.TargetObject__c,
      ParentObjectUpdate__mdt.Update__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return ParentObjectUpdate__mdt.sObjectType;
  }

  public List<ParentObjectUpdate__mdt> selectBySourceObj(String typeName) {
    fflib_QueryFactory query = newQueryFactory();

    query.selectField('TargetObject__r.APIName__c');
    query.selectField('SourceObject__r.APIName__c');
    query.selectField('ConditionField__r.APIName__c');
    query.selectField('SourceField__r.APIName__c');
    query.selectField('TargetField__r.APIName__c');
    query.selectField('RelationField__r.APIName__c');
    query.setCondition('isActive__c = true AND SourceObject__r.APIName__c = :typeName');
    return (List<ParentObjectUpdate__mdt>) Database.query(query.toSOQL());
  }

  public List<ParentObjectUpdate__mdt> selectActives() {
    fflib_QueryFactory query = newQueryFactory();

    query.selectField('TargetObject__r.APIName__c');
    query.selectField('SourceObject__r.APIName__c');
    query.selectField('ConditionField__r.APIName__c');
    query.selectField('SourceField__r.APIName__c');
    query.selectField('TargetField__r.APIName__c');
    query.selectField('RelationField__r.APIName__c');
    query.setCondition('isActive__c = true');
    return (List<ParentObjectUpdate__mdt>) Database.query(query.toSOQL());
  }

  public List<ParentObjectUpdate__mdt> getParentObjectMDTTest() {
    fflib_QueryFactory query = newQueryFactory();

    query.selectField('TargetObject__r.APIName__c');
    query.selectField('SourceObject__r.APIName__c');
    query.selectField('ConditionField__r.APIName__c');
    query.selectField('SourceField__r.APIName__c');
    query.selectField('TargetField__r.APIName__c');
    query.selectField('RelationField__r.APIName__c');
    query.setCondition('SourceObject__r.APIName__c = \'Contact\' AND SourceField__r.APIName__c = \'Id\'');
    return (List<ParentObjectUpdate__mdt>) Database.query(query.toSOQL());
  }


}