force-app/main/default/objects/OpportunityLineItem/fields/OpportunityPackage__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPackage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Package</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OpportunityPackage__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.OpportunityId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OpportunityPackage__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPackage__c/OpportunityPackage__c.object-meta.xml
<CustomObject>
    <label>Opportunity Package</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Opportunity Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pack__c/Pack__c.object-meta.xml
<CustomObject>
    <label>Bundle Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundle Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityPackageHandlerTest.cls
/*
*	@description Test class for OpportunityPackageHandler functionality.
*
*	@author ach
*	@copyright PARX
*/
@isTest
public with sharing class OpportunityPackageHandlerTest
{
	/*
	*	@description Test trigger logic
	*/
	static testMethod void testMainFunctionality()
	{
		Id pricebookId = Test.getStandardPricebookId();
		Pack__c pack = TestFactory.createPackage(pricebookId);
		Account acc = TestFactory.createAccount();
		Opportunity opp = TestFactory.createOpportunity(acc, pricebookId);
		List<Product2> products = new List<Product2>{TestFactory.createProduct(false), TestFactory.createProduct(false), TestFactory.createProduct(false)};
		insert products;
		OpportunityPackage__c oppPackage = TestFactory.createOpportunityPackage(opp, pack);
		List<OpportunityLineItem> lineItems = new  List<OpportunityLineItem>{
			TestFactory.createOppLineItem(opp, products[0], false),
			TestFactory.createOppLineItem(opp, products[1], false),
			TestFactory.createOppLineItem(opp, products[2], false)
		};
		lineItems[0].OpportunityPackage__c = oppPackage.Id;
		lineItems[1].OpportunityPackage__c = oppPackage.Id;
		insert lineItems;
		
		Test.startTest();
		delete oppPackage;
		Test.stopTest();
		
		lineItems = [SELECT Id  FROM OpportunityLineItem];
		System.assertEquals(1, lineItems.size(), 'Wrong number of OpportunityLineItem records: 2 from 3 should be deleted.');
	}
}