force-app/main/default/objects/OpportunityLineItem/fields/OpportunityPackage__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPackage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Package</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OpportunityPackage__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.OpportunityId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OpportunityPackage__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPackage__c/OpportunityPackage__c.object-meta.xml
<CustomObject>
    <label>Opportunity Package</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Opportunity Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPackage__c/fields/BundlePackage__c.field-meta.xml
<CustomField>
    <fullName>BundlePackage__c</fullName>
    <label>Bundle Package</label>
    <referenceTo>Pack__c</referenceTo>
    <relationshipLabel>Opportunity Packages</relationshipLabel>
    <relationshipName>Opportunity_Packages</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPackage__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Packages</relationshipLabel>
    <relationshipName>Opportunity_Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPackage__c/fields/Quote_Package__c.field-meta.xml
<CustomField>
    <fullName>Quote_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Package</label>
    <referenceTo>Quote_Package__c</referenceTo>
    <relationshipLabel>Opportunity Packages</relationshipLabel>
    <relationshipName>Opportunity_Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPackage__c/fields/SortNumber__c.field-meta.xml
<CustomField>
    <fullName>SortNumber__c</fullName>
    <label>Sort Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityPackage__c/fields/TotalAmmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmmount__c</fullName>
    <label>Total Ammount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pack__c/Pack__c.object-meta.xml
<CustomObject>
    <label>Bundle Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundle Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pack__c/fields/PriceBook__c.field-meta.xml
<CustomField>
    <fullName>PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pack__c/fields/SortNumber__c.field-meta.xml
<CustomField>
    <fullName>SortNumber__c</fullName>
    <externalId>true</externalId>
    <label>SortNumber</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Pack__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>PackageLine__c.Total_Price__c</summarizedField>
    <summaryForeignKey>PackageLine__c.Package__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/PackageLine__c/PackageLine__c.object-meta.xml
<CustomObject>
    <label>Package Line</label>
    <nameField>
        <label>Package Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PackageLine__c/fields/Defaultprice__c.field-meta.xml
<CustomField>
    <fullName>Defaultprice__c</fullName>
    <label>Default price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PackageLine__c/fields/Defaultquantity__c.field-meta.xml
<CustomField>
    <fullName>Defaultquantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Default Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PackageLine__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package</label>
    <referenceTo>Pack__c</referenceTo>
    <relationshipLabel>Package Lines</relationshipLabel>
    <relationshipName>Package_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PackageLine__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Package Lines</relationshipLabel>
    <relationshipName>Package_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PackageLine__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Fraction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>SupplierCosts</fullName>
                <label>Supplier Costs</label>
            </value>
            <value>
                <fullName>LicenseDirect</fullName>
                <label>License (Direct) / Trade</label>
            </value>
            <value>
                <fullName>LicenseProvision</fullName>
                <label>License (Provision)</label>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Package__c/Quote_Package__c.object-meta.xml
<CustomObject>
    <label>Quote Package</label>
    <nameField>
        <label>Quote Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Package__c/fields/Bundle_Package__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Package__c</fullName>
    <label>Bundle Package</label>
    <referenceTo>Pack__c</referenceTo>
    <relationshipLabel>Quote Packages</relationshipLabel>
    <relationshipName>Quote_Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Package__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Packages</relationshipLabel>
    <relationshipName>Quote_Packages</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Package__c/fields/SortNumber__c.field-meta.xml
<CustomField>
    <fullName>SortNumber__c</fullName>
    <label>Sort Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>SupplierCosts</fullName>
                <label>Supplier Costs</label>
            </value>
            <value>
                <fullName>LicenseDirect</fullName>
                <label>License (Direct) / Trade</label>
            </value>
            <value>
                <fullName>LicenseProvision</fullName>
                <label>License (Provision)</label>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Quote_Package__c.field-meta.xml
<CustomField>
    <fullName>Quote_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Package</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.QuoteId</field>
            <operation>equals</operation>
            <valueField>Quote_Package__c.Quote__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote_Package__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddBundlePackageController.cls
global with sharing class AddBundlePackageController {
    
    public static boolean isError;
    public static string isErrorText;
    public static string sortnumber{get;set;}
    public static string name {get; set;}
    public static id OpportunityId{get;set;}
    public  id QuoteId{get;set;}
    public static id PricebookId{get;set;}
    public static list<wrapperPackage> lst_wrapperPackageTemplates{get;set;}
    public final static String ERROR_NOPACKAGES = 'There are no packages available for the Opportunity Pricebook';
    public final static String ERROR_NOPRICEBOOK = 'There is no Pricebook assigned to the Opportunity, please select one first and try again';    
    public final static string BASICQUERIE = 'select id, name,SortNumber__c,Description__c,'
    										 +' (select id,Defaultprice__c,Defaultquantity__c,Product__r.name,ProductType__c' 
    										 +' From Package_Lines__r) from Pack__c '
    										 +' where PriceBook__c = \'REMOVEPRICEBOOK\' REMOVENAME REMOVESORT order by SortNumber__c';
    
    public final static string REMOVEPRICEBOOK = 'REMOVEPRICEBOOK'; 
    public final static string REMOVENAME = 'REMOVENAME'; 
    public final static string REMOVESORT = 'REMOVESORT'; 
    public final static string REPLACENAME = 'and name = ';
    public final static string REPLACESORT = 'and SortNumber__c =';
    public final static string BLANK = '';
    public final static string ERROR = 'ERROR';
    private final static string OPPPREFIX = '006';
    private final static string QUOTEPREFIX = '0Q0';
    
    global AddBundlePackageController (ApexPages.StandardController stdController) {
    	
    	if(stdController.getId().startsWith(OPPPREFIX)) {
    		Opportunity opp = (Opportunity)stdController.getRecord();
    		system.debug('....' + opp);
    		OpportunityId = stdController.getId();
    		PricebookId = [SELECT id,Pricebook2Id FROM Opportunity where id = :OpportunityId limit 1].Pricebook2Id;

    	}else if (stdController.getId().startsWith(QUOTEPREFIX)) {
    		Quote myquote = (Quote)stdController.getRecord();
    		system.debug('....' + myquote);
    		QuoteId = stdController.getId();
    		PricebookId = [SELECT id,Pricebook2Id FROM Quote where id = :QuoteId limit 1].Pricebook2Id;    	
    	}else {
    		isError = true;
    		isErrorText = ERROR_NOPACKAGES;
    	}
    	if(PricebookId == null) {
    		isError = true;
    		isErrorText = ERROR_NOPRICEBOOK;
    	}
    	
    	   	
    }
    
    @RemoteAction
    public static string queriePackages(string IncomingJson){
   		string result ='';
		try{
			system.debug('....' + IncomingJson);
	   		filterFields filters = (filterFields)JSON.deserialize(IncomingJson,filterFields.class);	   			   		
	   		string Querie = BASICQUERIE.replace(REMOVEPRICEBOOK,filters.pricebookEntry);
	   		Querie = (!String.isBlank(filters.name)) ? Querie.replace(REMOVENAME, REPLACENAME + +'\''+filters.name.trim()+'\''):  Querie.replace(REMOVENAME, BLANK);
	   		Querie = (!String.isBlank(filters.SortNumber)) ? Querie.replace(REMOVESORT, REPLACESORT+'\''+filters.SortNumber.trim()+'\''):  Querie.replace(REMOVESORT, BLANK);
	   		
	   		lst_wrapperPackageTemplates = new list<wrapperPackage>();
	   		system.debug('....' + Querie);
	   		List<sObject> sobjList = Database.query(Querie);
			list<Pack__c> lst_packs = (list<Pack__c>)sobjList;	
	   		for (Pack__c currentPack : lst_packs) {
										
				if (!currentPack.Package_Lines__r.isEmpty()) {
					lst_wrapperPackageTemplates.add(new WrapperPackage(currentPack));
				}					
			}
	   		
	   		lst_wrapperPackageTemplates = sortPackages(lst_wrapperPackageTemplates);
	   		
	   		result = json.serialize(lst_wrapperPackageTemplates);
	   		system.debug('....' + result);
	   		return result;
	   		
		}catch (Exception exc) {
			system.debug('....' + exc.getStackTraceString());
			system.debug('....' + exc.getLineNumber());
			return ERROR;
		}
   }   

    /*
     * @Author          :   Lisis Rodriguez <lisis.rodriguez@empaua.com>
     * @Created         :   22 Nov 2018
     * @Description     :   Deserialize Json and insert package into Opportunity
     */
    @RemoteAction
    
    public static string addToOpportunity(String jsonPackage){
    	system.debug('....' + jsonPackage);
    	jsonPackage = jsonPackage.replaceall('\"true\"','true');
    	system.debug('....' + jsonPackage);
        list<WrapperPackage> lst_wrapper = (list<WrapperPackage>) JSON.deserialize(jsonPackage, list<WrapperPackage>.class);
        List<OpportunityLineItem> olisToInsert = new List<OpportunityLineItem> ();
        
        map<integer,OpportunityPackage__c> map_possition_OpportunityPackage= new map<integer,OpportunityPackage__c>();
        map<integer,list<OpportunityLineItem>> map_position_listOLI= new map<integer,list<OpportunityLineItem>>();
        
        for (integer i = 0; i<lst_wrapper.size(); i++) {
        	
        	WrapperPackage currentWrapper = lst_wrapper[i];
        	
        	OpportunityPackage__c oP = new OpportunityPackage__c();
        	oP.BundlePackage__c = currentWrapper.bundlePackage;
        	oP.Opportunity__c = currentWrapper.OpportunityId;
        	oP.SortNumber__c = currentWrapper.sortNumber;
        	oP.TotalAmmount__c = Double.valueOf(currentWrapper.totalPrice);
        	
        	map_possition_OpportunityPackage.put(i,op);
        	map_position_listOLI.put(i,new list<OpportunityLineItem>());
        	
        	for (WrapperPackageItem currentLine :currentWrapper.listPackageItems) {
        		
        		OpportunityLineItem oli = new OpportunityLineItem();
          	    oli.Product2Id = currentLine.productId;
                oli.UnitPrice = Double.valueOf(currentLine.Defaultprice);
                if(oli.UnitPrice == 0){oli.UnitPrice = 1;}
                oli.Quantity = Double.valueOf(currentLine.Defaultquantity);
           		if(oli.Quantity == 0){oli.Quantity = 1;} 
             	//oli.TotalPrice = Double.valueOf(currentLine.Totalprice);
                oli.Opportunityid = currentWrapper.OpportunityId;
        		map_position_listOLI.get(i).add(oli);
        		
        		
        	}
        }
        insert map_possition_OpportunityPackage.values();
        system.debug('....' + map_possition_OpportunityPackage);
        list<OpportunityLineItem> list_opportunityLineItems = new list<OpportunityLineItem>();
        
        
        for (integer key:map_position_listOLI.keyset()) {
        	
        	for (OpportunityLineItem currentLine:map_position_listOLI.get(key)) {
        		
        		
        		currentLine.OpportunityPackage__c = map_possition_OpportunityPackage.get(Key).id;
        		list_opportunityLineItems.add(currentLine);
        	}
        }
        insert list_opportunityLineItems;
             
        return map_possition_OpportunityPackage.size()+' Package added. '+list_opportunityLineItems.size() + ' Products added';
    }

     /*
     * @Author          :   Lisis Rodriguez <lisis.rodriguez@empaua.com>
     * @Created         :   26 Nov 2018
     * @Description     :   Deserialize Json and insert package into Quote
     */
    @RemoteAction
    public static string addToQuote(String jsonPackage){
        system.debug('....' + jsonPackage);
        jsonPackage = jsonPackage.replaceall('\"true\"','true');
        system.debug('....' + jsonPackage);
        //WWrapperPackage is being using for Oportunity and Quote 
        list<WrapperPackage> lst_wrapper = (list<WrapperPackage>) JSON.deserialize(jsonPackage, list<WrapperPackage>.class);
        List<QuoteLineItem> olisToInsert = new List<QuoteLineItem> ();
        
        map<integer,Quote_Package__c> map_possition_QuotePackage= new map<integer,Quote_Package__c>();
        map<integer,list<QuoteLineItem>> map_position_listQLI= new map<integer,list<QuoteLineItem>>();
        Map<Id,Id> map_prodId_Pbe = new Map<Id, Id>();
        Set<Id>pricebookSet = new Set<Id>();
        
        for (integer i = 0; i<lst_wrapper.size(); i++) {
            
            WrapperPackage currentWrapper = lst_wrapper[i];
            
            Quote_Package__c qP = new Quote_Package__c();
            qP.Bundle_Package__c = currentWrapper.bundlePackage;
            qP.Quote__c = currentWrapper.quoteId;
            qP.Total_Amount__c = Double.valueOf(currentWrapper.totalPrice);
            qP.SortNumber__c = currentWrapper.sortNumber;
            
            map_possition_QuotePackage.put(i,qP);
            map_position_listQLI.put(i,new list<QuoteLineItem>());
            System.debug(loggingLevel.WARN, '....currentWrapper.PricebookId: ' + currentWrapper.PricebookId);
            pricebookSet.add(currentWrapper.PricebookId);
            
            for (WrapperPackageItem currentLine :currentWrapper.listPackageItems) {
                
                QuoteLineItem qli = new QuoteLineItem();
                qli.Product2Id = currentLine.productId;
                qli.UnitPrice = Double.valueOf(currentLine.Defaultprice);
                if(qli.UnitPrice == 0){qli.UnitPrice = 1;}
                qli.Quantity = Double.valueOf(currentLine.Defaultquantity);
                if(qli.Quantity == 0){qli.Quantity = 1;} 
                qli.QuoteId = currentWrapper.quoteId;
                map_position_listQLI.get(i).add(qli); 
                System.debug(loggingLevel.WARN, '....currentLine.productId: ' + currentLine.productId);
                map_prodId_Pbe.put(currentLine.productId, null);              
            }
        }
        insert map_possition_QuotePackage.values();
        system.debug('....' + map_possition_QuotePackage);
        
        list<QuoteLineItem> list_quoteLineItems = new list<QuoteLineItem>();
        for(PricebookEntry iPbe :[SELECT Id, Product2Id
                                FROM PricebookEntry
                                WHERE Pricebook2Id =: pricebookSet
                                AND Product2Id IN: map_prodId_Pbe.keySet()]){
            System.debug(loggingLevel.WARN, '....iPbe: ' + iPbe);
            map_prodId_Pbe.put(iPbe.Product2Id, iPbe.Id);
        }
        
        
        for (integer key:map_position_listQLI.keyset()) {
            
            for (QuoteLineItem currentLine:map_position_listQLI.get(key)) {
                currentLine.Quote_Package__c = map_possition_QuotePackage.get(Key).id;
                System.debug(loggingLevel.WARN, '....currentLine.Product2Id: ' + currentLine.Product2Id);
                currentLine.PriceBookEntryID = map_prodId_Pbe.get(currentLine.Product2Id);
                list_quoteLineItems.add(currentLine);
            }
        }
        insert list_quoteLineItems;
        return map_possition_QuotePackage.size()+' Package added. '+list_quoteLineItems.size() + ' Products added';
    }
	
	
	
    public class WrapperPackage {
    	boolean selected;
    	string name;
    	string sortNumber;
    	string description;
    	string totalPrice;
        string bundlePackage;
        @TestVisible
        string OpportunityId;
        @TestVisible
        string quoteId;
        @TestVisible
        string PricebookId;
        
    	list<WrapperPackageItem> listPackageItems;
    	
    	 public WrapperPackage(){
    	 	selected = false;
    	 	name = '';
    	 	sortNumber = '1';
    	 	description = '';
    	 	totalPrice = '0';
            bundlePackage = ' '; // cambiar
    	 	listPackageItems = new list<WrapperPackageItem>();
    	 }
    	 public WrapperPackage(pack__c pack){
    	 	selected = false;
    	 	name = pack.name;
    	 	sortNumber = pack.sortNumber__c;
    	 	description = pack.description__c;
    	 	totalPrice = '0';
            bundlePackage = pack.Id;
    	 	listPackageItems = new list<WrapperPackageItem>();
    	 	Decimal auxTotal= 0;
    	 	for (PackageLine__c packageLine :pack.Package_Lines__r) {
    	 		
    	 		system.debug('....' + 'Package Lines:'+ packageLine);
    	 		WrapperPackageItem auxPackageLineItem = new WrapperPackageItem(packageLine);
    	 		listPackageItems.add(auxPackageLineItem); 
    	 		auxTotal += Decimal.valueof(auxPackageLineItem.Totalprice);
    	 		
    	 	} 
    	 	totalPrice = String.valueof(auxTotal);
    	 }
    }
    public  class WrapperPackageItem {
    	boolean selected;
    	string name;
        string productId;
    	string ProductType;
    	string Defaultprice;
    	string Defaultquantity; 	
    	string Totalprice;
    	
    	
    	public WrapperPackageItem(PackageLine__c line) {
    		selected = false;
    		Defaultprice = String.valueof(line.Defaultprice__c);
    		Defaultquantity = String.valueof(line.Defaultquantity__c);
    		ProductType = line.ProductType__c;
    		name = line.product__r.name;
    		Totalprice = String.valueof(line.Defaultprice__c*line.Defaultquantity__c);   
            productId = line.Product__c;		
    	}
    	
    }
    
    public class filterFields {
    	@TestVisible
        string name;
        @TestVisible
    	string pricebookEntry;
        @TestVisible
    	string SortNumber;
        @TestVisible
    	string Opportunity;
    }
    private static list<WrapperPackage> sortPackages (list<WrapperPackage> listWP) {
		
		for (WrapperPackage WP:listWP) {
			
			WP.listPackageItems = sortPackageItems(WP.listPackageItems);
			
		}
		return listWP;
	}
	
	private static list<WrapperPackageItem> sortPackageItems (list<WrapperPackageItem> lst_wrapperPackageItems) {
		
		list<WrapperPackageItem> sortedList = new list<WrapperPackageItem>();
		map<string,WrapperPackageItem> map_key_item = new map<string,WrapperPackageItem>();
		list<string> listKeys = new list<string>();
		
		for(WrapperPackageItem item : lst_wrapperPackageItems) {
			
			string key = item.ProductType+item.name;
			map_key_item.put(key,item);
			listKeys.add(key);
			
		}
		listKeys.sort();
		
		for (string key : listKeys) {
			sortedList.add(map_key_item.get(key));
		}
		return sortedList;
		
	}
}