force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Attention: You should not add a package to a Project with Status = Closed</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>PackagesProjectName</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/DateFrom__c.field-meta.xml
<CustomField>
    <fullName>DateFrom__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date (From)</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/DateUntil__c.field-meta.xml
<CustomField>
    <fullName>DateUntil__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date (Until)</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/DurationHhMmN__c.field-meta.xml
<CustomField>
    <fullName>DurationHhMmN__c</fullName>
    <label>Duration</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Time__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RH_TimeToPTORequest_Helper_test.cls
@IsTest
public class RH_TimeToPTORequest_Helper_test {
    /*
    @isTest(SeeAllData=true)
    static void test_InsertAbsense() {
        User testuser = [SELECT Id FROM User WHERE Username like '%antonio.farati%'];
        System.runAs(testuser) {
            Project__c project = [SELECT Id FROM Project__c where Name = 'Abwesenheiten Antonio Farati' limit 1];
            Package__c service = [SELECT Id FROM Package__c where Name = 'Ferien' AND ProjectName__c = :project.Id];

            List<Time__c> timeentries = new List<Time__c>();
            timeentries.add(new Time__c(DateFrom__c = Date.valueOF('2014-06-09'),
                                        DateUntil__c = Date.valueOf('2014-06-09'),
                                        DurationHhMmN__c = 8,
                                        ProjectName__c = project.Id,
                                        Package__c = service.Id));
            timeentries.add(new Time__c(DateFrom__c = Date.valueOF('2014-06-10'),
                                        DateUntil__c = Date.valueOf('2014-06-10'),
                                        DurationHhMmN__c = 8,
                                        ProjectName__c = project.Id,
                                        Package__c = service.Id));
            timeentries.add(new Time__c(DateFrom__c = Date.valueOF('2014-06-11'),
                                        DateUntil__c = Date.valueOf('2014-06-11'),
                                        DurationHhMmN__c = 8,
                                        ProjectName__c = project.Id,
                                        Package__c = service.Id));
            Test.startTest();
            insert timeentries;
            Test.stopTest();

            List<ResourceHeroApp__Resource_Forecast__c> rfs = [SELECT Id, Name, ResourceHeroApp__PTO_Request__c, ResourceHeroApp__Forecast__c, ResourceHeroApp__Actual__c, ResourceHeroApp__Resource_Assignment__c, CreatedDate
                                                                FROM ResourceHeroApp__Resource_Forecast__c
                                                                WHERE ResourceHeroApp__ForecastDate__c >= :Date.valueOf('2014-06-08')
                                                                    AND ResourceHeroApp__ForecastDate__c <= :Date.valueOf('2014-06-12')
                                                                    AND ResourceHeroApp__PTO_Request__c != null];

            system.assertEquals(3, rfs.size());
        }
    }

    @isTest(SeeAllData=true)
    static void test_UpdateAbsense() {
        User testuser = [SELECT Id FROM User WHERE Username like '%antonio.farati%'];
        System.runAs(testuser) {
            Project__c project = [SELECT Id FROM Project__c where Name = 'Abwesenheiten Antonio Farati' limit 1];
            Package__c service = [SELECT Id FROM Package__c where Name = 'Ferien' AND ProjectName__c = :project.Id];

            List<Time__c> timeentries = new List<Time__c>();
            timeentries.add(new Time__c(DateFrom__c = Date.valueOF('2014-06-09'),
                                        DateUntil__c = Date.valueOf('2014-06-09'),
                                        DurationHhMmN__c = 8,
                                        ProjectName__c = project.Id,
                                        Package__c = service.Id));
            timeentries.add(new Time__c(DateFrom__c = Date.valueOF('2014-06-10'),
                                        DateUntil__c = Date.valueOf('2014-06-10'),
                                        DurationHhMmN__c = 8,
                                        ProjectName__c = project.Id,
                                        Package__c = service.Id));
            timeentries.add(new Time__c(DateFrom__c = Date.valueOF('2014-06-11'),
                                        DateUntil__c = Date.valueOf('2014-06-11'),
                                        DurationHhMmN__c = 8,
                                        ProjectName__c = project.Id,
                                        Package__c = service.Id));
            
            insert timeentries;
            Test.startTest();

            timeentries[1].DurationHhMmN__c = 4;
            update timeentries[1];
            Test.stopTest();

            List<ResourceHeroApp__Resource_Forecast__c> rfs = [SELECT Id, Name, ResourceHeroApp__PTO_Request__c, ResourceHeroApp__Forecast__c, ResourceHeroApp__Actual__c, ResourceHeroApp__Resource_Assignment__c, CreatedDate
                                                                FROM ResourceHeroApp__Resource_Forecast__c
                                                                WHERE ResourceHeroApp__ForecastDate__c = :Date.valueOf('2014-06-10')
                                                                    AND ResourceHeroApp__PTO_Request__c != null];

            system.assertEquals(1, rfs.size());
            system.assertEquals(4, rfs[0].ResourceHeroApp__Forecast__c);
        }
    }


    @isTest(SeeAllData=true)
    static void test_DeleteAbsense() {
        User testuser = [SELECT Id FROM User WHERE Username like '%antonio.farati%'];
        System.runAs(testuser) {
            Project__c project = [SELECT Id FROM Project__c where Name = 'Abwesenheiten Antonio Farati' limit 1];
            Package__c service = [SELECT Id FROM Package__c where Name = 'Ferien' AND ProjectName__c = :project.Id];

            List<Time__c> timeentries = new List<Time__c>();
            timeentries.add(new Time__c(DateFrom__c = Date.valueOF('2014-06-09'),
                                        DateUntil__c = Date.valueOf('2014-06-09'),
                                        DurationHhMmN__c = 8,
                                        ProjectName__c = project.Id,
                                        Package__c = service.Id));
            timeentries.add(new Time__c(DateFrom__c = Date.valueOF('2014-06-10'),
                                        DateUntil__c = Date.valueOf('2014-06-10'),
                                        DurationHhMmN__c = 8,
                                        ProjectName__c = project.Id,
                                        Package__c = service.Id));
            timeentries.add(new Time__c(DateFrom__c = Date.valueOF('2014-06-11'),
                                        DateUntil__c = Date.valueOf('2014-06-11'),
                                        DurationHhMmN__c = 8,
                                        ProjectName__c = project.Id,
                                        Package__c = service.Id));
            insert timeentries;
            Test.startTest();
            delete timeentries[1];
            Test.stopTest();

            List<ResourceHeroApp__Resource_Forecast__c> rfs = [SELECT Id, Name, ResourceHeroApp__PTO_Request__c, ResourceHeroApp__Forecast__c, ResourceHeroApp__Actual__c, ResourceHeroApp__Resource_Assignment__c, CreatedDate
                                                                FROM ResourceHeroApp__Resource_Forecast__c
                                                                WHERE ResourceHeroApp__ForecastDate__c = :Date.valueOf('2014-06-10')
                                                                    AND ResourceHeroApp__PTO_Request__c != null];

            system.assertEquals(0, rfs.size());
        }
    }
*/
}