force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/PackageStatus__c.field-meta.xml
<CustomField>
    <fullName>PackageStatus__c</fullName>
    <label>Package Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>PartiallyOpen</fullName>
                <label>Partially open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageSubType__c.field-meta.xml
<CustomField>
    <fullName>PackageSubType__c</fullName>
    <inlineHelpText>Manufaktur only for SVH</inlineHelpText>
    <label>Package Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkTime</fullName>
                <label>Work Time</label>
            </value>
            <value>
                <fullName>TravelTime</fullName>
                <label>Travel Time</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>3rdPartyCosts</fullName>
                <label>3rd Party Costs</label>
            </value>
            <value>
                <fullName>ProjectResourceCosts</fullName>
                <label>Project Resource Costs</label>
            </value>
            <value>
                <fullName>AbacusInbox</fullName>
                <label>Abacus Inbox</label>
            </value>
            <value>
                <fullName>Manufaktur</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>LicenseDirect</fullName>
                <label>License (Direct)</label>
            </value>
            <value>
                <fullName>LicenseProvision</fullName>
                <label>License (Provision)</label>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/IsProjectManager__c.field-meta.xml
<CustomField>
    <fullName>IsProjectManager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PS100 - Role Project Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PackageController.cls
public without sharing class PackageController {

  @AuraEnabled
  public static Boolean isUserAllowed() {
    User u = UserService.getLogged();
    return u == null ? false : u.IsProjectManager__c;
  }

  @AuraEnabled
  public static List<Package__c> get(Id projectId) {
    return PackageService.get(projectId);
  }

  @AuraEnabled
  public static void save(List<Package__c> packages) {
    PackageService.save(new List<Package__c> (packages));
  }

  @AuraEnabled
  public static void del(List<Package__c> packages) {
    PackageService.del(new List<Package__c> (packages));
  }

  @AuraEnabled
  public static Map<String, Map<String, List<String>>> getPicklists() {
    return Utils.getPicklistGroupedByRecordType('Package__c', new List<String> {'PackageSubType__c', 'PackageStatus__c'});
  }

}