force-app/main/default/objects/BLCTickets__c/BLCTickets__c.object-meta.xml
<CustomObject>
    <description>04.09.2017, ary: Objekt wurde nicht produktiv gestellt, da Prototyp. Ursprüngliche Idee war es, die Cases durch eine eigene Entwicklung abzulösen, damit alle User (Platform Lizenz) über Eingabemöglichkeiten direkt in Skywalk Tickets erfassen können.</description>
    <label>BLC Ticket</label>
    <nameField>
        <displayFormat>BT-{000000}</displayFormat>
        <label>BLC Ticket Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLC Tickets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLCTickets__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLCTickets__c/fields/EmailSender__c.field-meta.xml
<CustomField>
    <fullName>EmailSender__c</fullName>
    <inlineHelpText>This field will be automatically populated with the email address from &quot;Email-To-BLCTicket&quot; sender.</inlineHelpText>
    <label>Email Sender</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/BLCTickets__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>In Person</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLCTickets__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Re-Opened</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Waiting on Customer</fullName>
            </value>
            <value>
                <fullName>Forwarded 2nd Level</fullName>
            </value>
            <value>
                <fullName>Forwarded 3rd Level</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLCTickets__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLCTickets__c/recordTypes/It.recordType-meta.xml
<RecordType>
    <fullName>It</fullName>
    <active>true</active>
    <label>IT</label>
</RecordType>

force-app/main/default/classes/InboundEmailHandlerBLCTicket.cls
/**
* @author TSC
* @date 18.06.2016
* @description Email inbound class to create BLCTicket for incoming mail and add attachments
*/

global class InboundEmailHandlerBLCTicket implements Messaging.InboundEmailHandler {
    
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
        BLCTickets__c ticket = new BLCTickets__c();
        
        ticket.RecordTypeId = [SELECT Id, DeveloperName, SobjectType FROM RecordType where SobjectType = 'BLCTickets__c' and DeveloperName = 'It'].Id;
        ticket.Origin__c = 'Email';
        ticket.Status__c = 'New';
        
        ticket.Subject__c = email.Subject;
        ticket.Description__c = email.PlainTextBody;
        ticket.EmailSender__c = email.FromAddress;
        insert ticket;
        
        // Save attachments, if any
        if (email.textAttachments != null)
        {
            for(Messaging.Inboundemail.TextAttachment tAttachment : email.textAttachments)
            {
                Attachment attachment = new Attachment();
                
                attachment.Name = tAttachment.fileName;
                attachment.Body = Blob.valueOf(tAttachment.body);
                attachment.ParentId = ticket.Id;
                insert attachment;
            }
            
        }
        
        //Save any Binary Attachment
        
        if (email.binaryAttachments != null)
        {
            for(Messaging.Inboundemail.BinaryAttachment bAttachment : email.binaryAttachments) {
                Attachment attachment = new Attachment();
                
                attachment.Name = bAttachment.fileName;
                attachment.Body = bAttachment.body;
                attachment.ParentId = ticket.Id;
                insert attachment;
            }
        } 
        
        
        
        result.success = true;
        return result;
        
        
    }
}