force-app/main/default/objects/Purchasing__c/Purchasing__c.object-meta.xml
<CustomObject>
    <label>Purchasing / Order Mgmt.</label>
    <nameField>
        <label>Purchasing Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchasing / Order Mgmt.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchasing__c/fields/BillerAccountProjectNr__c.field-meta.xml
<CustomField>
    <fullName>BillerAccountProjectNr__c</fullName>
    <description>Mapping ID for Suppplier Cost to Purchasing Mapping via Trigger</description>
    <formula>Account__r.Id &amp;&quot;_&quot;&amp; Project__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Biller Account Project Nr.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PurchasingSelector.cls
public with sharing class PurchasingSelector extends fflib_SObjectSelector
  implements IPurchasingSelector {

  public static IPurchasingSelector newInstance() {
    return (IPurchasingSelector) Application.Selector.newInstance(Purchasing__c.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      Purchasing__c.Id,
      Purchasing__c.BillerAccountProjectNr__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Purchasing__c.SObjectType;
  }

  public override String getOrderBy() {
    return 'CreatedDate DESC';
  }

  public List<Purchasing__c> byBillerAccountProjectNr(Set<String> billerAccountProjNr) {
      fflib_QueryFactory query = newQueryFactory();
      query.setCondition('BillerAccountProjectNr__c IN :billerAccountProjNr');
      return (List<Purchasing__c>) Database.query(query.toSOQL());
  }

}