force-app/main/default/objects/ILVPos__c/ILVPos__c.object-meta.xml
<CustomObject>
    <label>ILV Pos</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>ILV Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ILV Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem/fields/OpportunityPackage__c.field-meta.xml
<CustomField>
    <fullName>OpportunityPackage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Package</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OpportunityPackage__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.OpportunityId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OpportunityPackage__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPackage__c/OpportunityPackage__c.object-meta.xml
<CustomObject>
    <label>Opportunity Package</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Opportunity Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPackage__c/fields/Quote_Package__c.field-meta.xml
<CustomField>
    <fullName>Quote_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Package</label>
    <referenceTo>Quote_Package__c</referenceTo>
    <relationshipLabel>Opportunity Packages</relationshipLabel>
    <relationshipName>Opportunity_Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPackage__c/fields/SortNumber__c.field-meta.xml
<CustomField>
    <fullName>SortNumber__c</fullName>
    <label>Sort Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pack__c/Pack__c.object-meta.xml
<CustomObject>
    <label>Bundle Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundle Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pack__c/fields/SortNumber__c.field-meta.xml
<CustomField>
    <fullName>SortNumber__c</fullName>
    <externalId>true</externalId>
    <label>SortNumber</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PackageLine__c/PackageLine__c.object-meta.xml
<CustomObject>
    <label>Package Line</label>
    <nameField>
        <label>Package Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PackageLine__c/fields/Defaultprice__c.field-meta.xml
<CustomField>
    <fullName>Defaultprice__c</fullName>
    <label>Default price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PackageLine__c/fields/Defaultquantity__c.field-meta.xml
<CustomField>
    <fullName>Defaultquantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Default Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PackageLine__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package</label>
    <referenceTo>Pack__c</referenceTo>
    <relationshipLabel>Package Lines</relationshipLabel>
    <relationshipName>Package_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PackageLine__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Package Lines</relationshipLabel>
    <relationshipName>Package_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PackageLine__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Fraction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>SupplierCosts</fullName>
                <label>Supplier Costs</label>
            </value>
            <value>
                <fullName>LicenseDirect</fullName>
                <label>License (Direct) / Trade</label>
            </value>
            <value>
                <fullName>LicenseProvision</fullName>
                <label>License (Provision)</label>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Package__c/Quote_Package__c.object-meta.xml
<CustomObject>
    <label>Quote Package</label>
    <nameField>
        <label>Quote Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Package__c/fields/SortNumber__c.field-meta.xml
<CustomField>
    <fullName>SortNumber__c</fullName>
    <label>Sort Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddBundlePackageControllerTest.cls
/*
*	@description Test class for AddBundlePackageController functionality.
*
*	@author ach
*	@copyright PARX
*/
@isTest
private class AddBundlePackageControllerTest
{
	
	@isTest static void testOpportunity()
	{
		Id pricebookId = Test.getStandardPricebookId();
		Pack__c pack = TestFactory.createPackage(pricebookId);
		Account acc = TestFactory.createAccount();
		Opportunity opp = TestFactory.createOpportunity(acc, pricebookId);
		Quote quote = TestFactory.createQuote(opp);
		Product2 prod = TestFactory.createProduct();
		/*insert new PricebookEntry(Pricebook2Id = pricebookId,
									Product2Id = prod.Id,
									UnitPrice = 100.00,
									IsActive = true);*/
		PackageLine__c packLine = TestFactory.createPackageLine(pack, prod);
		OpportunityLineItem oli = TestFactory.createOppLineItem(opp, prod);

		Test.startTest();
		AddBundlePackageController ctrl = new AddBundlePackageController(new ApexPages.StandardController(oli));
		System.assertEquals(AddBundlePackageController.ERROR_NOPRICEBOOK, AddBundlePackageController.isErrorText, 'Wrong errortext value');

		ctrl = new AddBundlePackageController(new ApexPages.StandardController(opp));
		ctrl = new AddBundlePackageController(new ApexPages.StandardController(quote));

		//####################### queriePackages ####################### 
		AddBundlePackageController.filterFields filter = new AddBundlePackageController.filterFields();
		filter.name = 'pack1';
    	filter.pricebookEntry = pricebookId;
    	filter.SortNumber = 'Test Sort';
    	filter.Opportunity = opp.Id;
		String result = AddBundlePackageController.queriePackages(JSON.serialize(filter));
		packLine = [SELECT Id, NAme FROM PackageLine__c WHERE Id =:packLine.Id];
		System.assertEquals(true, result.containsIgnoreCase('TESTDescription'), 'Wrong packages value');
		AddBundlePackageController.queriePackages('wrongJSON');
		
		pack = [SELECT id, name, SortNumber__c, Description__c, 
				(SELECT id, Defaultprice__c,Defaultquantity__c, Product__c, Product__r.name, ProductType__c FROM Package_Lines__r) FROM Pack__c WHERE ID = :pack.Id];
		
		//####################### addToOpportunity ####################### 
		AddBundlePackageController.WrapperPackage wrap = new AddBundlePackageController.WrapperPackage(pack);
		wrap.OpportunityId = opp.Id;
		result = AddBundlePackageController.addToOpportunity(JSON.serialize(new List<AddBundlePackageController.WrapperPackage>{wrap}));
		System.assertEquals('1 Package added. 1 Products added', result, 'Wrong value');
		List<OpportunityPackage__c> oppPackages = [SELECT Id  FROM OpportunityPackage__c ];
		System.assertEquals(1, oppPackages.size(), 'Wrong number of generated packages');

		//####################### addToQuote ####################### 
		wrap = new AddBundlePackageController.WrapperPackage(pack);
		wrap.quoteId = quote.Id;
		wrap.PricebookId = pricebookId;
		result = AddBundlePackageController.addToQuote(JSON.serialize(new List<AddBundlePackageController.WrapperPackage>{wrap}));
		System.assertEquals('1 Package added. 1 Products added', result, 'Wrong value');
		List<Quote_Package__c> quotePackages = [SELECT Id  FROM Quote_Package__c ];
		System.assertEquals(1, quotePackages.size(), 'Wrong number of generated packages');

		Test.stopTest();
		
	}

	 @IsTest(SeeAllData=true) static void testCoverage()
	{
		try
		{
			ILVPos__c test = [SELECT Id FROM ILVPos__c LIMIT 1];
			update test;
		} catch(Exception e)
		{
			System.debug('###:' + e.getMessage());
		}
	}
}