force-app/main/default/objects/ILVPos__c/ILVPos__c.object-meta.xml
<CustomObject>
    <label>ILV Pos</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>ILV Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ILV Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILVPos__c/fields/CostCenterILVReceiver__c.field-meta.xml
<CustomField>
    <fullName>CostCenterILVReceiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cost Center (ILV Receiver)</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/CostCenterNrILVReceiver__c.field-meta.xml
<CustomField>
    <fullName>CostCenterNrILVReceiver__c</fullName>
    <label>Cost Center Nr. (ILV Receiver)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/FinanceAccountILVGiver__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountILVGiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Account (ILV Giver)</label>
    <referenceTo>FinanceAccount__c</referenceTo>
    <relationshipLabel>ILV Pos (Finance Account (ILV Giver))</relationshipLabel>
    <relationshipName>ILV_Pos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/FinanceAccountILVReceiver__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountILVReceiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Account (ILV Receiver)</label>
    <referenceTo>FinanceAccount__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/FinanceAccountNrILVGiver__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountNrILVGiver__c</fullName>
    <label>Finance Account Nr. (ILV Giver)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/FinanceAccountNrILVReceiver__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountNrILVReceiver__c</fullName>
    <label>Finance Account Nr. (ILV Receiver)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/ILVPositionDate__c.field-meta.xml
<CustomField>
    <fullName>ILVPositionDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>ILV Position Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/ILVType__c.field-meta.xml
<CustomField>
    <fullName>ILVType__c</fullName>
    <label>ILV Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/InvoiceName__c.field-meta.xml
<CustomField>
    <fullName>InvoiceName__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/RelevantToRevenue__c.field-meta.xml
<CustomField>
    <fullName>RelevantToRevenue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Relevant to Revenue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ILVPosSelector.cls
public with sharing class ILVPosSelector extends fflib_SObjectSelector
  implements IILVPosSelector {

  public static IILVPosSelector newInstance() {
    return (IILVPosSelector) Application.Selector.newInstance(ILVPos__c.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      ILVPos__c.Id,
      ILVPos__c.RelevantToRevenue__c,
      ILVPos__c.ILVPositionDate__c,
      ILVPos__c.ILVType__c,
      ILVPos__c.FinanceAccountILVGiver__c,
      ILVPos__c.FinanceAccountNrILVGiver__c,
      ILVPos__c.CostCenterILVReceiver__c,
      ILVPos__c.FinanceAccountILVReceiver__c,
      ILVPos__c.FinanceAccountNrILVReceiver__c,
      ILVPos__c.CostCenterNrILVReceiver__c,
      ILVPos__c.PackageName__c,
      ILVPos__c.InvoiceName__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return ILVPos__c.sObjectType;
  }

  public List<ILVPos__c> selectWithRelated(Set<Id> ids, Set<String> related) {
    fflib_QueryFactory query = newQueryFactory();
    query.selectFields(related);

    query.setCondition('id in :ids').toSOQL();
    return (List<ILVPos__c>) Database.query(query.toSOQL());
  }

  public List<ILVPos__c> selectByInvoice(Set<Id> invoiceIds) {
    fflib_QueryFactory query = newQueryFactory(false, false, true);
    query.setCondition('InvoiceName__c in :invoiceIds').toSOQL();
    return (List<ILVPos__c>) Database.query(query.toSOQL());
  }

}