force-app/main/default/objects/Product2/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Option</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductSubType__c.field-meta.xml
<CustomField>
    <fullName>ProductSubType__c</fullName>
    <label>Product Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkTime</fullName>
                <label>Work Time</label>
            </value>
            <value>
                <fullName>TravelTime</fullName>
                <label>Travel Time</label>
            </value>
            <value>
                <fullName>3rdPartyCosts</fullName>
                <label>3rd Party Costs</label>
            </value>
            <value>
                <fullName>ProjectResourceCosts</fullName>
                <label>Project Resource Costs</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>LicenseDirect</fullName>
                <label>License (Direct)</label>
            </value>
            <value>
                <fullName>LicenseProvision</fullName>
                <label>License (Provision)</label>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>SupplierCosts</fullName>
                <label>Supplier Costs</label>
            </value>
            <value>
                <fullName>LicenseDirect</fullName>
                <label>License (Direct) / Trade</label>
            </value>
            <value>
                <fullName>LicenseProvision</fullName>
                <label>License (Provision)</label>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SortNr__c.field-meta.xml
<CustomField>
    <fullName>SortNr__c</fullName>
    <label>Sort Nr.</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SuperiorProduct__c.field-meta.xml
<CustomField>
    <fullName>SuperiorProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Superior Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ExpenseAllowancePackage__c.field-meta.xml
<CustomField>
    <fullName>ExpenseAllowancePackage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expense %</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Option</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductSubType__c.field-meta.xml
<CustomField>
    <fullName>ProductSubType__c</fullName>
    <label>Product Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ProductType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkTime</fullName>
                <label>Work Time</label>
            </value>
            <value>
                <fullName>TravelTime</fullName>
                <label>Travel Time</label>
            </value>
            <value>
                <fullName>3rdPartyCosts</fullName>
                <label>3rd Party Costs</label>
            </value>
            <value>
                <fullName>ProjectResourceCosts</fullName>
                <label>Project Resource Costs</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>LicenseDirect</fullName>
                <label>License (Direct)</label>
            </value>
            <value>
                <fullName>LicenseProvision</fullName>
                <label>License (Provision)</label>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>SupplierCosts</fullName>
                <label>Supplier Costs</label>
            </value>
            <value>
                <fullName>LicenseDirect</fullName>
                <label>License (Direct) / Trade</label>
            </value>
            <value>
                <fullName>LicenseProvision</fullName>
                <label>License (Provision)</label>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProjectManagementAllowancePackage__c.field-meta.xml
<CustomField>
    <fullName>ProjectManagementAllowancePackage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Project Management %</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/SortNr__c.field-meta.xml
<CustomField>
    <fullName>SortNr__c</fullName>
    <label>Sort Nr.</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/SuperiorQuoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>SuperiorQuoteLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Superior Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>SuperiorQuoteLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/SupplierCostsGroup__c.field-meta.xml
<CustomField>
    <fullName>SupplierCostsGroup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SC &gt;3K</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuoteLineItemsSelector.cls
/**
 * Created by dudunato on 30.11.17.
 */

public without sharing class QuoteLineItemsSelector extends fflib_SObjectSelector
        implements IQuoteLineItemsSelector {

    public static IQuoteLineItemsSelector newInstance() {
        return (IQuoteLineItemsSelector) Application.Selector.newInstance(QuoteLineItem.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                QuoteLineItem.Id,
                QuoteLineItem.Product2Id,
                QuoteLineItem.QuoteId,
                QuoteLineItem.Description,
                QuoteLineItem.ProductType__c,
                QuoteLineItem.ProductSubType__c,
                QuoteLineItem.SortNr__c,
                QuoteLineItem.SuperiorQuoteLineItem__c,
                QuoteLineItem.ProjectManagementAllowancePackage__c,
                QuoteLineItem.ExpenseAllowancePackage__c,
                QuoteLineItem.SupplierCostsGroup__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return QuoteLineItem.sObjectType;
    }

    public List<QuoteLineItem> byId(Set<Id> ids) {
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('Product2.SuperiorProduct__c');
        query.setCondition('Id IN :ids');

        return (List<QuoteLineItem>) Database.query(query.toSOQL());
    }

    public List<QuoteLineItem> byProduct(Set<Id> ids) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Product2Id IN :ids');

        return (List<QuoteLineItem>) Database.query(query.toSOQL());
    }

    public List<QuoteLineItem> byQuoteId(Set<Id> ids) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('QuoteId IN :ids AND ProductType__c != \'Text\' AND Option__c != true');
        List<SObject> items = Database.query(query.toSOQL());

        return (items == null || items.isEmpty())
                ? null
                : (List<QuoteLineItem>) Database.query(query.toSOQL());
    }


}