force-app/main/default/objects/Account/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TermsOfPayment__c.field-meta.xml
<CustomField>
    <fullName>TermsOfPayment__c</fullName>
    <label>Terms of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TermsOfPayment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VATPercent__c.field-meta.xml
<CustomField>
    <fullName>VATPercent__c</fullName>
    <label>VAT %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VATPercent</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/FinanceDateLimit__c.field-meta.xml
<CustomField>
    <fullName>FinanceDateLimit__c</fullName>
    <label>Finance Date Limit</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/InvoiceDateLimit__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDateLimit__c</fullName>
    <label>Invoice Date Limit</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/BillingViaCompany__c.field-meta.xml
<CustomField>
    <fullName>BillingViaCompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing via (Company)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Billing via (Company))</relationshipLabel>
    <relationshipName>InvoicesBillingViaCompany</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/FinanceDate__c.field-meta.xml
<CustomField>
    <fullName>FinanceDate__c</fullName>
    <label>Finance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceTitle__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTitle__c</fullName>
    <label>Invoice Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TermsOfPayment__c.field-meta.xml
<CustomField>
    <fullName>TermsOfPayment__c</fullName>
    <description>16.12.2016, ary: Neues Feld gemacht als Pickliste. Dieses Feld muss aus dem Apex raus, damit es gelöscht werden kann.</description>
    <label>Terms of Payment_do_not_use</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/VATPercent__c.field-meta.xml
<CustomField>
    <fullName>VATPercent__c</fullName>
    <label>VAT %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0%</fullName>
            </value>
            <value>
                <fullName>2.5%</fullName>
            </value>
            <value>
                <fullName>2.6%</fullName>
            </value>
            <value>
                <fullName>7.7%</fullName>
            </value>
            <value>
                <fullName>8%</fullName>
            </value>
            <value>
                <fullName>8.1%</fullName>
            </value>
            <value>
                <fullName>9%</fullName>
            </value>
            <value>
                <fullName>19%</fullName>
            </value>
            <value>
                <fullName>3.7%</fullName>
                <isActive>false</isActive>
                <label>3.7%</label>
            </value>
            <value>
                <fullName>3.8%</fullName>
                <isActive>false</isActive>
                <label>3.8%</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Credit.recordType-meta.xml
<RecordType>
    <fullName>Credit</fullName>
    <active>false</active>
    <description>15.12.2017, ary: Entscheid Finance, Gutschriften werden als -Minus Rechnungen ins Abacus übertragen.</description>
    <label>Credit</label>
</RecordType>

force-app/main/default/objects/Invoice__c/recordTypes/ILV.recordType-meta.xml
<RecordType>
    <fullName>ILV</fullName>
    <active>true</active>
    <label>ILV</label>
</RecordType>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/InvoicePos__c/InvoicePos__c.object-meta.xml
<CustomObject>
    <label>Invoice Pos</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Invoice Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePos__c/fields/InvoicePositionAmount__c.field-meta.xml
<CustomField>
    <fullName>InvoicePositionAmount__c</fullName>
    <label>Invoice Position - Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <label>Package Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/ShowInvoiceText__c.field-meta.xml
<CustomField>
    <fullName>ShowInvoiceText__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Invoice Text</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/ShowPosition__c.field-meta.xml
<CustomField>
    <fullName>ShowPosition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Position</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/ShowPositionAmount__c.field-meta.xml
<CustomField>
    <fullName>ShowPositionAmount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Position Amount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/VATPercent__c.field-meta.xml
<CustomField>
    <fullName>VATPercent__c</fullName>
    <label>VAT %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VATPercent</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/PackageSuperior__c.field-meta.xml
<CustomField>
    <fullName>PackageSuperior__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hint: Filter must be optional, otherwise Template Clone will not run (Project Name)</description>
    <label>Package (Superior)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.ProjectName__c</field>
            <operation>equals</operation>
            <valueField>Package__c.ProjectName__c</valueField>
        </filterItems>
        <filterItems>
            <field>Package__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>PackagesSuperior</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageType2__c.field-meta.xml
<CustomField>
    <fullName>PackageType2__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <description>Diese Feld wird verwendet für die Zuweisung von Finance Account im ILV Prozess (Name Mapping)</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package Type Finance Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <formula>ProjectName__r.ProjectCostCenter__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Cost Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Attention: You should not add a package to a Project with Status = Closed</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>PackagesProjectName</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ShowInvoiceText__c.field-meta.xml
<CustomField>
    <fullName>ShowInvoiceText__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Invoice Text</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ShowPosition__c.field-meta.xml
<CustomField>
    <fullName>ShowPosition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Position</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ShowPositionAmount__c.field-meta.xml
<CustomField>
    <fullName>ShowPositionAmount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Position Amount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Package__c/recordTypes/Time.recordType-meta.xml
<RecordType>
    <fullName>Time</fullName>
    <active>true</active>
    <label>Time</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/BillingViaCompany__c.field-meta.xml
<CustomField>
    <fullName>BillingViaCompany__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Billing via (Company)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Invoicing via (Company))</relationshipLabel>
    <relationshipName>ProjectsInvoicingViaCompany</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Internal Contract Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CostCenter__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/IsFinanceManager__c.field-meta.xml
<CustomField>
    <fullName>IsFinanceManager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PS130 - Role Finance Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/PS480FunctionValidationRulesActive__c.field-meta.xml
<CustomField>
    <fullName>PS480FunctionValidationRulesActive__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If checked, Validation Rules are active. If unchecked, Validation Rules are not considered.</inlineHelpText>
    <label>PS480 - Function Validation Rules Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/TermsOfPayment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <masterLabel>Terms of Payment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/VATPercent.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0%</fullName>
    </customValue>
    <customValue>
        <fullName>2.5%</fullName>
    </customValue>
    <customValue>
        <fullName>2.6%</fullName>
    </customValue>
    <customValue>
        <fullName>7.7%</fullName>
        <default>true</default>
        <label>7.7%</label>
    </customValue>
    <customValue>
        <fullName>8%</fullName>
    </customValue>
    <customValue>
        <fullName>8.1%</fullName>
    </customValue>
    <customValue>
        <fullName>9%</fullName>
    </customValue>
    <customValue>
        <fullName>19%</fullName>
    </customValue>
    <customValue>
        <fullName>3.7%</fullName>
        <isActive>false</isActive>
        <label>3.7%</label>
    </customValue>
    <customValue>
        <fullName>3.8%</fullName>
        <isActive>false</isActive>
        <label>3.8%</label>
    </customValue>
    <masterLabel>VAT %</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InvoiceController.cls
public with sharing class InvoiceController {

	@AuraEnabled
  	public static ProjectStructureBean getProjectStructure(Id projectId, String dateFrom, String dateTo) {
    	return InvoiceService.getProjectStructure(projectId, dateFrom, dateTo);
  	}

  	@AuraEnabled
  	public static void save(Invoice__c draft, List<Package__c> packages, List<InvoicePos__c> positions) {
    	
		System.debug('---InvoiceController.save--- draft: '+draft);
		System.debug('---InvoiceController.save--- packages: '+packages);
		System.debug('---InvoiceController.save--- positions: '+positions);

		User userSettings = [Select IsFinanceManager__c, PS480FunctionValidationRulesActive__c  From User Where Id = :UserInfo.getUserId()];

		if (Test.isRunningTest()) {
			userSettings.IsFinanceManager__c = false;
			userSettings.PS480FunctionValidationRulesActive__c = true;
		}

		System.debug('---InvoiceController.save--- userSettings: '+userSettings);

		// Perform some validations here so that they can be reported back to the user by the Lightning component.
		// The validations performed by Validation Rules are not reported back because the insert/update operations
		// are performed from a Future method.
		String errMsg;
		errMsg = validateInvoice(draft, userSettings, 'Billing');

		System.debug('---InvoiceController.save--- errMsg: '+errMsg);

		if (String.isEmpty(errMsg)) {
			errMsg = validateInvoicePosition(positions, userSettings);
		}

		if (String.isNotEmpty(errMsg)) {
			System.debug('---InvoiceController.save--- Throw error: '+errMsg);
			throw new AuraHandledException(errMsg);  
		}
		else {
			System.debug('---InvoiceController.save--- calling saveAsync');
			saveAsync(JSON.serialize(draft), JSON.serialize(packages), JSON.serialize(positions));
		}
  	}

	/**
	 * Prevent CPU time exceeded.
	 * @param draft : String 
	 * @param packages : String (List<Package__c> packages serialized)
	 * @param positions : String (List<InvoicePos__c> serialized)
	*/
	@future
	public static void saveAsync(String draft, String packages, String positions) {
		List<Package__c> auxPackages = (List<Package__c>) JSON.deserialize(packages, List<Package__c>.class);
    	List<InvoicePos__c> auxPositions = (List<InvoicePos__c>) JSON.deserialize(positions, List<InvoicePos__c>.class);

    	InvoiceService.save((Invoice__c) JSON.deserialize(draft, Invoice__c.class), auxPackages, auxPositions);
	}

	/**
	 * 
	 */
	@AuraEnabled
	public static Id cancel(Id invoiceId) {
		return InvoiceService.cancel(invoiceId).Id;
	}

	/**
	 * @description:	Pre-validate the Invoice.
	 * 					This duplicates some of the Invoice's Validation Rules. This is required because the insert/update
	 * 					operations are performed from a future method.
	 * 
	 * 					Note: This method is also called from the class ILVTabHelper.
	 * @When:	2023.11.23
	 * @Who:	david.sanchez@empaua.com
	 * 
	 * @param:	draft -- invoice draft to be created or updated
	 * 			userSettings -- user settings, some of which indicate whether validation can be overriden
	 * 			invoiceType -- indicates whether it is a 'Billing' or 'ILV' invoice.
	 * @return	If a validation fails, the error message; otherwise an empty string.
	 */
	public static String validateInvoice(Invoice__c draft, User userSettings, String invoiceType ) {
		
		if (String.isNotEmpty(draft.ProjectName__c)) {
			Project__c prj = [SELECT Id, ProjectCostCenter__c, TermsOfPayment__c, ValCountHasInvoiceDraft__c, VATPercent__c, BillingViaCompany__c, BillingViaCompany__r.AccountName__c
							  FROM Project__c WHERE Id = :draft.ProjectName__c];

			String VATPercent = draft.Id != null ? draft.VATPercent__c : prj.VATPercent__c;

			Invoice__c oldInvoice = new Invoice__c();
			if (draft.Id != null) {
				oldInvoice = [SELECT Id, VATPercent__c FROM Invoice__c WHERE id = :draft.Id];
			}

			Date fromFinanceDate = Date.newInstance(2024, 1, 1);
			Set<String> invalidVat = new Set<String>{'7.7%','2.5%','3.7%','8%'};
			
			System.debug('---InvoiceController.validateInvoiceLWC--- oldInvoice: '+oldInvoice);
			System.debug('---InvoiceController.validateInvoiceLWC--- FinanceDate__c: '+draft.FinanceDate__c);

			if (userSettings.PS480FunctionValidationRulesActive__c && !userSettings.IsFinanceManager__c) {
				
				CostCenter__c costCenter = [SELECT InvoiceDateLimit__c, FinanceDateLimit__c FROM CostCenter__c WHERE Id = :prj.ProjectCostCenter__c];

				String BillingViaCompanyAcctName = draft.Id != null ? draft.BillingViaCompany__r?.AccountName__c : prj.BillingViaCompany__r?.AccountName__c;

				System.debug('---InvoiceController.validateInvoiceLWC--- prj: '+prj);
				System.debug('---InvoiceController.validateInvoiceLWC--- costCenter: '+costCenter);
				System.debug('---InvoiceController.validateInvoiceLWC--- BillingViaCompanyAcctName: '+BillingViaCompanyAcctName);
				System.debug('---InvoiceController.validateInvoiceLWC--- VATPercent: '+VATPercent + ' old VATPercent: '+oldInvoice.VATPercent__c);

				if (draft.InvoiceDate__c < costCenter.InvoiceDateLimit__c) {
					return 'This invoice date is not allowed. Please get in touch with Finance.	(InvoiceController INO16)';
				}
				else if (draft.FinanceDate__c  < costCenter.FinanceDateLimit__c) {
					return 'This finance date is not allowed. Please get in touch with Finance.	(InvoiceController IN017)';
				}
				else if (prj.Id == null && prj.ValCountHasInvoiceDraft__c == 1) {
					return 'There is already an Invoice in Status "Draft". Please complete this invoice first. (InvoiceController IN012)';
				}
				else if (String.isEmpty(prj.TermsOfPayment__c)) {
					return 'Project must have a Terms of Payment. (InvoiceController IN015)';
				}
				else if (invoiceType == 'Billing') {
					if (draft.InvoiceTitle__c == null ||
						!draft.InvoiceTitle__c.containsIgnoreCase('Rechnung')   && !draft.InvoiceTitle__c.containsIgnoreCase('Invoice') &&
						!draft.InvoiceTitle__c.containsIgnoreCase('Gutschrift') && !draft.InvoiceTitle__c.containsIgnoreCase('Credit Note')) {
							return 'The Invoice Title must contain either "Rechnung" or "Invoice". (InvoiceController IN019)';
					}
				}
				else if (BillingViaCompanyAcctName != 'gateB (Singpore)' && VATPercent == '9%') {	// IN029_VAT_Not_9_Percent
					return 'You are not allowed to choose VAT 9%. Please get in touch with Finance. (InvoiceController IN029)';
				}
			}

			if (VATPercent != oldInvoice.VATPercent__c && draft.FinanceDate__c > fromFinanceDate && invalidVat.contains(VATPercent)) { //IN028_VAT_NewVATRates
				return 'You cannot use 7,7%, 2,5%, 3,7% or 8% as VAT from 01.01.2024 on. Please use instead 8,1%, 2,6%, 3,8% or respectively 9%. (InvoiceController IN028)';
			} 
		}

		return '';
	}

	/**
	 * Pre-validate the InvoicePosition.
	 */
	public static String validateInvoicePosition(List<InvoicePos__c> positions, User userSettings) {

		if (userSettings.PS480FunctionValidationRulesActive__c && !userSettings.IsFinanceManager__c) {
			Set<Id> posPkgIDs = new Set<Id>();
			Set<String> types = new Set<String>();
			for (InvoicePos__c invPos : positions) {
				posPkgIDs.add(invPos.PackageName__c);
			}

			Map<Id, Package__c> posPkg = new Map<Id, Package__c>([SELECT Id, PackageSuperior__c, RecordType.DeveloperName, 
																		 ProjectName__r.ProjectCostCenter__r.Name, PackageType__c, 
																		 PackageType2__c
																 FROM    Package__c WHERE Id IN :posPkgIDs]);

			for (InvoicePos__c invPos : positions) {
				Package__c pkg = posPkg.get(invPos.PackageName__c);
				System.debug('---InvoiceController.validateInvoicePosition--- InvoicePositionAmount__c: '+invPos.InvoicePositionAmount__c);
				if (invPos.PackageType__c != 'Group' && invPos.InvoicePositionAmount__c > 0 && !invPos.ShowPosition__c && String.isEmpty(pkg.PackageSuperior__c)) {
					return 'The Invoice Position with an Amount must be shown on the invoice. Please correct the checkboxes.';
				}
				else if ((invPos.ShowPositionAmount__c && !invPos.ShowPosition__c) || (invPos.ShowInvoiceText__c && !invPos.ShowPositionAmount__c && !invPos.ShowPosition__c) ) {
					return 'Checkboxes are not in line for billing template.';
				}
				else if (invPos.InvoicePositionAmount__c == null) {
					return 'The invoice position amount can not be empty. Please add a value or 0.';
				}
				// else if ((invPos.InvoicePositionAmount__c - invPos.InvoicePositionAmount__c.round(System.RoundingMode.DOWN)) != 0.0) {
				// 	System.debug('---InvoiceController.validateInvoicePosition--- InvoicePositionAmount__c Dec: '+(invPos.InvoicePositionAmount__c - invPos.InvoicePositionAmount__c.round(System.RoundingMode.DOWN)) );
				// 	return 'The Invoice Position must be without cents.';
				// }
			}
		}

		return '';
	}

}