force-app/main/default/objects/Account/fields/AccountManager__c.field-meta.xml
<CustomField>
    <fullName>AccountManager__c</fullName>
    <label>Account Manager</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerActual__c.field-meta.xml
<CustomField>
    <fullName>CustomerActual__c</fullName>
    <label>Customer (Actual)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Deputy__c.field-meta.xml
<CustomField>
    <fullName>Deputy__c</fullName>
    <description>Wird nur noch durch den UR Trigger von einer Löschung verhindert. 26.03.2016, ary</description>
    <label>Deputy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Network</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
/**
	Trigger handler for Account object
	
	@copyright PARX
	@author akr
*/
public with sharing class AccountTriggerHandler extends TriggerTemplateV2.TriggerHandlerAdapter
{
	public override void  onAfterUpdate (List<sObject> newList, Map<Id, sObject> newMap, List<sObject> oldList, Map<Id, sObject> oldMap)
	{
		//Updates accounts if the auto-fields data was updated.
		updateAccounts(newList, (Map<Id, Account>) oldMap);
	}

	/**
		Updates accounts if the auto-fields data was updated.
	*/
	private void updateAccounts(List<Account> theNewValuesList, Map<Id, Account> theOldValuesMap)
	{
		Set<Id> anAccIdSet = Utils.getModifiedObjectIds(new List<String>{'CustomerActual__c', 'Supplier__c', 'Partner__c', 'AccountManager__c', 'Deputy__c'}, theNewValuesList, theOldValuesMap);
		AccountSummary.getInstance().updateObjects(anAccIdSet);
	}
}