force-app/main/default/objects/Account/fields/AccountLanguage__c.field-meta.xml
<CustomField>
    <fullName>AccountLanguage__c</fullName>
    <label>Account Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <default>true</default>
                <label>D</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinanceAccount__c/FinanceAccount__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Account</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinanceAccount__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Finance Account</relationshipLabel>
    <relationshipName>FinanceAccount</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountLanguage__c.field-meta.xml
<CustomField>
    <fullName>AccountLanguage__c</fullName>
    <formula>CASE(TEXT(InvoiceReceiver__r.AccountLanguage__c),
 &apos;D&apos;, &apos;DE&apos;,
 &apos;E&apos;, &apos;EN&apos;,
 &apos;F&apos;, &apos;FR&apos;,
 &apos;I&apos;, &apos;IT&apos;,
 &apos;S&apos;, &apos;ES&apos;,
      &apos;EN&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingViaCompany__c.field-meta.xml
<CustomField>
    <fullName>BillingViaCompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing via (Company)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Billing via (Company))</relationshipLabel>
    <relationshipName>InvoicesBillingViaCompany</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectInvoiceCurrency__c.field-meta.xml
<CustomField>
    <fullName>ProjectInvoiceCurrency__c</fullName>
    <label>Project / Invoice Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <formula>ProjectName__r.ProjectCostCenter__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Cost Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Attention: You should not add a package to a Project with Status = Closed</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>PackagesProjectName</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/BillingViaCompany__c.field-meta.xml
<CustomField>
    <fullName>BillingViaCompany__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Billing via (Company)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Invoicing via (Company))</relationshipLabel>
    <relationshipName>ProjectsInvoicingViaCompany</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Internal Contract Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CostCenter__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QRGeneratorToolSettings__c/QRGeneratorToolSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to configure hierarchical settings in the QR Generator Tool to provide user-specific &amp; profile-specific customizations</description>
    <label>QR Generator Tool Settings</label>
</CustomObject>

force-app/main/default/objects/QRGeneratorToolSettings__c/fields/API_boundaryLineScissors__c.field-meta.xml
<CustomField>
    <fullName>API_boundaryLineScissors__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If scissors should be printed on the boundary lines. Only to be set to true if  Boundary Lines is set to true. - https://rest.qr-invoice.cloud/swagger-ui/index.html#/11%20Payment%20Part%20%26%20Receipt%20(QR%20Bill)/createPaymentPartReceipt</description>
    <inlineHelpText>Mark as true if scissors should be printed on the boundary lines. This can only be active if Boundary Lines is active.</inlineHelpText>
    <label>Add Boundary Line Scissors</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QRGeneratorToolSettings__c/fields/API_boundaryLinesMargins__c.field-meta.xml
<CustomField>
    <fullName>API_boundaryLinesMargins__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the boundary lines should include a margin and not extend to the border of the page. Printers usually are unable to print the lines completely otherwise. - https://rest.qr-invoice.cloud/swagger-ui/index.html#/11%20Payment%20Part%20%26%20Receipt%20(QR%20Bill)/createPaymentPartReceipt</description>
    <inlineHelpText>If the boundary lines should include a margin and not extend to the border of the page. Printers usually are unable to print the lines completely otherwise.</inlineHelpText>
    <label>Add Boundary Lines Margins</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QRGeneratorToolSettings__c/fields/API_normalizeInput__c.field-meta.xml
<CustomField>
    <fullName>API_normalizeInput__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, the input gets normalized. This means strings are trimmed, special quotations replaced with ASCII ones, and special characters replaced with semantically equal ones (e.g. œ -&gt; oe)</description>
    <inlineHelpText>If true, the input gets normalized. This means strings are trimmed, special quotations replaced with ASCII ones, and special characters replaced with semantically equal ones (e.g. œ -&gt; oe)
Documentation: https://rest.qr-invoice.cloud/swagger-ui/index.html#/11%20Payment%20Part%20%26%20Receipt%20(QR%20Bill)/createPaymentPartReceipt</inlineHelpText>
    <label>Normalize Input</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QRGeneratorToolSettings__c/fields/API_resolution__c.field-meta.xml
<CustomField>
    <fullName>API_resolution__c</fullName>
    <description>Output Resolution - https://rest.qr-invoice.cloud/swagger-ui/index.html#/11%20Payment%20Part%20%26%20Receipt%20(QR%20Bill)/createPaymentPartReceipt</description>
    <inlineHelpText>Output Resolution</inlineHelpText>
    <label>resolution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QRCodeServiceTest.cls
/*
 * @Class : QRCodeServiceTest
 *
 * @Author     : Lisis Rodriguez <lisis.rodriguez@empaua.com>
 * @Created    : 25 Oct 2023
 * @Description: Test class for QRCodeService
 */
@isTest
public with sharing  class QRCodeServiceTest {
    @TestSetup
    static void makeData(){
        TestFactory.makeData();
    }

    @isTest
    public static void generateQRCodeTest(){
        Test.setMock(HttpCalloutMock.class, new QRCodeServiceMockResponse());
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Project__c proj = [SELECT Id FROM Project__c LIMIT 1];
        CostCenter__c costCenter = [SELECT Id FROM CostCenter__c LIMIT 1];
        Package__c service = [SELECT Id FROM Package__c LIMIT 1];
        FinanceAccount__c finAcc = [SELECT Id FROM FinanceAccount__c LIMIT 1];
        
        Invoice__c inv = TestFactory.createInvoice(acc.Id, proj.Id, costCenter.Id);
        inv.ProjectInvoiceCurrency__c = 'EUR';
        insert inv; 
        
        String docName = Label.QRInvoicePrefix + '_' + Date.today().format();

        Test.startTest();
        //This line is not here because of testing purposes, just to avoid a Too Many queries exception
        insert TestFactory.createInvoicePosition(inv.Id, null, service.Id, finAcc.Id);
        
        //Invoking QRCodeService.generateQRCode from a future method to be able to call a web service after a DML operation
        generateQRCodeFuture(inv.Id);
        Test.stopTest();

        List<ContentDocumentLink> cdls = [SELECT Id, ContentDocument.Title FROM ContentDocumentLink WHERE LinkedEntityId =: inv.Id];

        System.assert(!cdls.isEmpty(), 'No ContentDocumentLink was generated');
        System.assertEquals(docName,cdls.get(0).ContentDocument.Title, 'Document title is the expected');

    }
    
    @future (callout=true)
    private static void generateQRCodeFuture(Id invId){
        Invoice__c inv = [SELECT Id,
                                ProjectInvoiceCurrency__c, 
                                AccountLanguage__c, 
                                BillingViaCompany__c, 
                                ProjectName__c, 
                                ProjectCostCenter__c 
                            FROM Invoice__c 
                            WHERE Id =: invId ];
        QRCodeService.generateQRCode(inv);
    }

    @isTest
    public static void createRequestBodyTest(){
        Test.setMock(HttpCalloutMock.class, new QRCodeServiceMockResponse());
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Project__c proj = [SELECT Id FROM Project__c LIMIT 1];
        CostCenter__c costCenter = [SELECT Id FROM CostCenter__c LIMIT 1];
        Package__c service = [SELECT Id FROM Package__c LIMIT 1];
        FinanceAccount__c finAcc = [SELECT Id FROM FinanceAccount__c LIMIT 1];
        
        Test.startTest();
        // This lines are not here because of testing purposes, just to avoid a Too Many queries exception caused 
        // by fflib module installed after the creation of the test data
        Invoice__c inv = TestFactory.createInvoice(acc.Id, proj.Id, costCenter.Id);
        inv.ProjectInvoiceCurrency__c = 'EUR';
        insert inv;
        insert TestFactory.createInvoicePosition(inv.Id, null, service.Id, finAcc.Id);

        String req = QRCodeService.createRequestBody(inv, 'en');

        Test.stopTest();
        System.assert(!String.isBlank(req), 'No request has been created');
    }

    @isTest
    public static void doPostTest(){
        Test.setMock(HttpCalloutMock.class, new QRCodeServiceMockResponse());
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Project__c proj = [SELECT Id FROM Project__c LIMIT 1];
        CostCenter__c costCenter = [SELECT Id FROM CostCenter__c LIMIT 1];
        Package__c service = [SELECT Id FROM Package__c LIMIT 1];
        
        Invoice__c inv = TestFactory.createInvoice(acc.Id, proj.Id, costCenter.Id);
        inv.ProjectInvoiceCurrency__c = 'EUR';
        insert inv; 
        
        List<String> queryParams = new List<String>{'resolution=MEDIUM_300_DPI', 'boundaryLinesMargins=true', 'boundaryLineScissors=true'};
        String body = 'testingBody';

        Test.startTest();
    
        QRCodeService.doPost(queryParams,body, 'en');
        try{
            queryParams.add('fail');
            QRCodeService.doPost(queryParams,body, 'en');
        }catch(HandledException ex){
            System.assert(ex != null);

        }
        Test.stopTest();
    }

    @isTest
    public static void buildQRCodeImageTest(){
        Test.setMock(HttpCalloutMock.class, new QRCodeServiceMockResponse());
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Project__c proj = [SELECT Id FROM Project__c LIMIT 1];
        CostCenter__c costCenter = [SELECT Id FROM CostCenter__c LIMIT 1];
        Package__c service = [SELECT Id FROM Package__c LIMIT 1];
        
        Invoice__c inv = TestFactory.createInvoice(acc.Id, proj.Id, costCenter.Id);
        inv.ProjectInvoiceCurrency__c = 'EUR';
        insert inv; 

        QRGeneratorToolSettings__c toolSet = new QRGeneratorToolSettings__c();
        toolSet.API_resolution__c = 'MEDIUM_300_DPI';
        toolSet.API_normalizeInput__c = true;
        toolSet.API_boundaryLinesMargins__c = true; 
        toolSet.API_boundaryLineScissors__c = true;

        Test.startTest();
    
        String qr = QRCodeService.buildQRCodeImage(inv);
        Test.stopTest();

        System.assert(!String.isBlank(qr), 'No request has been created');
    }
}