force-app/main/default/objects/Account/fields/AccountLanguage__c.field-meta.xml
<CustomField>
    <fullName>AccountLanguage__c</fullName>
    <label>Account Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <default>true</default>
                <label>D</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BillingCity__c.field-meta.xml
<CustomField>
    <fullName>BillingCity__c</fullName>
    <label>Billing City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SWITZERLAND</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GERMANY</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>LIECHTENSTEIN</fullName>
            </value>
            <value>
                <fullName>UNITED STATES</fullName>
            </value>
            <value>
                <fullName>----------</fullName>
            </value>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ÅLAND ISLANDS</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANDORRA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTARCTICA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BillingStreetNr__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetNr__c</fullName>
    <label>Billing Street, Nr</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingZip__c.field-meta.xml
<CustomField>
    <fullName>BillingZip__c</fullName>
    <label>Billing ZIP</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/CHFIBAN__c.field-meta.xml
<CustomField>
    <fullName>CHFIBAN__c</fullName>
    <label>CHF IBAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CHFQRIBAN__c.field-meta.xml
<CustomField>
    <fullName>CHFQRIBAN__c</fullName>
    <label>CHF QR IBAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/EURIBAN__c.field-meta.xml
<CustomField>
    <fullName>EURIBAN__c</fullName>
    <label>EUR IBAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/EURQRIBAN__c.field-meta.xml
<CustomField>
    <fullName>EURQRIBAN__c</fullName>
    <label>EUR QR IBAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/LegalAccount__c.field-meta.xml
<CustomField>
    <fullName>LegalAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Legal Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cost Center</relationshipLabel>
    <relationshipName>CostCenter</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountLanguage__c.field-meta.xml
<CustomField>
    <fullName>AccountLanguage__c</fullName>
    <formula>CASE(TEXT(InvoiceReceiver__r.AccountLanguage__c),
 &apos;D&apos;, &apos;DE&apos;,
 &apos;E&apos;, &apos;EN&apos;,
 &apos;F&apos;, &apos;FR&apos;,
 &apos;I&apos;, &apos;IT&apos;,
 &apos;S&apos;, &apos;ES&apos;,
      &apos;EN&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/AccountNameLegal__c.field-meta.xml
<CustomField>
    <fullName>AccountNameLegal__c</fullName>
    <label>Account Name (Legal)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressCountry__c</fullName>
    <label>Billing Address Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressStreetNr__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressStreetNr__c</fullName>
    <label>Billing Address Street, Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressZIP__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressZIP__c</fullName>
    <label>Billing Address ZIP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAdressCity__c.field-meta.xml
<CustomField>
    <fullName>BillingAdressCity__c</fullName>
    <label>Billing Adress City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingNameAddition__c.field-meta.xml
<CustomField>
    <fullName>BillingNameAddition__c</fullName>
    <label>Billing Name (Addition)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ESRFormatted__c.field-meta.xml
<CustomField>
    <fullName>ESRFormatted__c</fullName>
    <label>ESR Formatted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ESRUnformatted__c.field-meta.xml
<CustomField>
    <fullName>ESRUnformatted__c</fullName>
    <label>ESR Unformatted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GenerationQRBillDate__c.field-meta.xml
<CustomField>
    <fullName>GenerationQRBillDate__c</fullName>
    <description>Generated from button.</description>
    <inlineHelpText>Generated from button.</inlineHelpText>
    <label>GenerationQRBillDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDocumentNr__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDocumentNr__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Document Nr.</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceReceiver__c.field-meta.xml
<CustomField>
    <fullName>InvoiceReceiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Receiver</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Billing Receiver)</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceTotalAmountGross__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTotalAmountGross__c</fullName>
    <formula>InvoiceTotalAmountNet__c + InvoiceVATAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice - Total Amount Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectInvoiceCurrency__c.field-meta.xml
<CustomField>
    <fullName>ProjectInvoiceCurrency__c</fullName>
    <label>Project / Invoice Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QRBillSetting__c/QRBillSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>QR Bill Setting</label>
</CustomObject>

force-app/main/default/classes/QRBillPARXHandler.cls
/**
 * QRBillPARXHandler
 * @author ldo
 * @Modified By Manjiri
 * @copyright PARX
 *
 */
public class QRBillPARXHandler {
    public static final String CUSTOM_SETTING_NAME = 'QRBillGenerations';
    public static boolean recursion = false;
    public static boolean cdrecursion = false;
    public static Integer cnt = 0;
    
    
    /**
    * @description startQrBillProcess: Method for initialising the logic for creating the QR Bill code.
    * @param  newList newList description
    * @param  oldMap  oldMap description
    */
    public static void startQrBillProcess(List<Invoice__c> newList, Map<Id, Invoice__c> oldMap){ 
        System.debug('newList :'+newList);
        System.debug('oldMap :'+oldMap);
        List<String> sObjectsIds = checkValidityFields(newList, oldMap);
        QRBillSetting__c cmtSettings = QRBillSetting__c.getValues(CUSTOM_SETTING_NAME) != null ? QRBillSetting__c.getValues(CUSTOM_SETTING_NAME): null;
        if(sObjectsIds.size() > 0)
            manageRecordsList(sObjectsIds, cmtSettings);
    }
    
    /**
    * checkValidityFields: check whether records are suitable for QR Bill Code generation
    *
    * ## objectsList (List<Invoice__c>): objectsList
    * ## oldMap (Map<IdRechnung__c>): oldMap
    * @@ Return List<String>: Return description
    */
    public static List<String> checkValidityFields(List<Invoice__c> objectsList, Map<Id, Invoice__c> oldMap){
        
        List<String> idsForGeneration = new List<String>();

        //Manjiri : If depends on record type can be used following line
        //String DEBITOREN_LOCKED_RT = Schema.SObjectType.Invoice__c.getRecordTypeInfosByDeveloperName().get('DebitorenLocked').getRecordTypeId();
        
        for(Invoice__c currObj : objectsList){
            if(currObj.ESRFormatted__c != null){
                Invoice__c oldobj = oldMap.get(currObj.Id);
                if( ( oldobj.AccountNameLegal__c != currObj.AccountNameLegal__c && currObj.AccountNameLegal__c != null ) ||
                   ( oldobj.BillingAddressZIP__c != currObj.BillingAddressZIP__c && currObj.BillingAddressZIP__c != null ) ||
                   ( oldobj.BillingAdressCity__c != currObj.BillingAdressCity__c && currObj.BillingAdressCity__c != null ) ||
                   ( oldobj.BillingAddressCountry__c != currObj.BillingAddressCountry__c && currObj.BillingAddressCountry__c != null ) ||
                   ( oldobj.ESRUnformatted__c != currObj.ESRUnformatted__c && currObj.ESRUnformatted__c != null ) ||
                   ( oldobj.InvoiceDocumentNr__c != currObj.InvoiceDocumentNr__c && currObj.InvoiceDocumentNr__c != null ) ||
                   ( oldobj.InvoiceTotalAmountGross__c != currObj.InvoiceTotalAmountGross__c && currObj.InvoiceTotalAmountGross__c != null ) ||
                   ( oldobj.BillingNameAddition__c != currObj.BillingNameAddition__c ) ||
                   ( oldobj.BillingAddressStreetNr__c != currObj.BillingAddressStreetNr__c ) || 
                   ( currObj.GenerationQRBillDate__c != oldobj.GenerationQRBillDate__c ) || Test.isRunningTest()
                  )
                {
                    idsForGeneration.add(currObj.Id);
                }  
            }        
        }
        return idsForGeneration;
    }
    
    /**
    * manageRecordsList: retrieve information and wrapper generation 
    *
    * ## sObjectsIds (List<String>): sObjectsIds
    * ## csSettings (QRBillSetting__c): csSettings
    */
    public static void manageRecordsList(List<String> sObjectsIds, QRBillSetting__c csSettings){
        List<QRBillRequest> requests = new List<QRBillRequest>();
        
        QRGeneratorRequest wrapper = new QRGeneratorRequest();
        QRBillRequestSettings settings = new QRBillRequestSettings (csSettings);
                
        for(Invoice__c currObj : [
            SELECT Id, InvoiceDocumentNr__c, ESRUnformatted__c, ProjectCostCenter__r.Name, ProjectCostCenter__r.LegalAccount__r.Name, ProjectCostCenter__r.LegalAccount__r.BillingStreetNr__c, ProjectCostCenter__r.LegalAccount__r.BillingCountry__c, ProjectCostCenter__r.LegalAccount__r.BillingZip__c, ProjectCostCenter__r.LegalAccount__r.BillingCity__c, BillingAdressCity__c, BillingNameAddition__c, BillingAddressStreetNr__c, BillingAddressZIP__c, BillingAddressCountry__c, AccountNameLegal__c, ProjectCostCenter__r.CHFQRIBAN__c,ProjectCostCenter__r.CHFIBAN__c, ProjectCostCenter__r.EURQRIBAN__c, ProjectCostCenter__r.EURIBAN__c, ProjectInvoiceCurrency__c, ESRFormatted__c, InvoiceReceiver__r.AccountLanguage__c, InvoiceTotalAmountGross__c, AccountLanguage__c, ProjectName__c, CurrencyIsoCode, Name
            FROM Invoice__c WHERE Id in :sObjectsIds]){
                String description;
                if(!recursion){
                    if( ((currObj.BillingAddressCountry__c == 'SWITZERLAND') || (currObj.BillingAddressCountry__c == 'LIECHTENSTEIN'))  && ((currObj.ProjectInvoiceCurrency__c == 'CHF') || (currObj.ProjectInvoiceCurrency__c == 'EUR')) ) {
                        QRBillRequest newRequest = new QRBillRequest(currObj, description);
                        System.debug('***** In QRBillPARXHandler manageRecordsList newRequest: '+newRequest);
                        requests.add(newRequest);
                    }
                }    
        }

        wrapper.settings = settings;
        wrapper.requests = requests;
        
        // Call Method to generation Qr Bill
        QRBillPARXService.qrBillGenerator(JSON.serialize(wrapper), settings.billInformation, sObjectsIds);
        recursion = true;
    } 

    /**
    * QRGeneratorRequest: Wrapper for the request
    *
    */
    public class QRGeneratorRequest{
        public QRBillRequestSettings settings;
        public List<QRBillRequest> requests;
    }
}