force-app/main/default/objects/Account/fields/AccountNameShort__c.field-meta.xml
<CustomField>
    <fullName>AccountNameShort__c</fullName>
    <label>Account Name (Short)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AccountNr__c.field-meta.xml
<CustomField>
    <fullName>AccountNr__c</fullName>
    <description>20170415, ary, Feld wird nicht mehr verwendet, ist aber noch in einer Apex Klasse drin und kann daher nicht gelöscht werden.</description>
    <displayFormat>{000000}</displayFormat>
    <label>Account Nr. - do not use</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LocalCurrency__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrency__c</fullName>
    <formula>CASE( LocationCountry__c , &quot;SWITZERLAND&quot;,&quot;CHF&quot;,&quot;UNITED STATES&quot;,&quot;USD&quot;,&quot;EUR&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Inventory Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <label>Car</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/CreditCard__c.field-meta.xml
<CustomField>
    <fullName>CreditCard__c</fullName>
    <label>Credit Card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/ValAvailableInApp__c.field-meta.xml
<CustomField>
    <fullName>ValAvailableInApp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ValAvailableInApp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory__c/recordTypes/Car.recordType-meta.xml
<RecordType>
    <fullName>Car</fullName>
    <active>true</active>
    <label>Car</label>
</RecordType>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/AbacusTimeType__c.field-meta.xml
<CustomField>
    <fullName>AbacusTimeType__c</fullName>
    <label>Abacus Time Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>1036</fullName>
            </value>
            <value>
                <fullName>1037</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>1100</fullName>
            </value>
            <value>
                <fullName>1135</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>130</fullName>
            </value>
            <value>
                <fullName>140</fullName>
            </value>
            <value>
                <fullName>160</fullName>
            </value>
            <value>
                <fullName>200</fullName>
            </value>
            <value>
                <fullName>300</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageNr__c.field-meta.xml
<CustomField>
    <fullName>PackageNr__c</fullName>
    <displayFormat>PA-{000000}</displayFormat>
    <label>Package Nr.</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageSortNr__c.field-meta.xml
<CustomField>
    <fullName>PackageSortNr__c</fullName>
    <label>Package Sort Nr.</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageStatus__c.field-meta.xml
<CustomField>
    <fullName>PackageStatus__c</fullName>
    <label>Package Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>PartiallyOpen</fullName>
                <label>Partially open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageSubType__c.field-meta.xml
<CustomField>
    <fullName>PackageSubType__c</fullName>
    <inlineHelpText>Manufaktur only for SVH</inlineHelpText>
    <label>Package Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkTime</fullName>
                <label>Work Time</label>
            </value>
            <value>
                <fullName>TravelTime</fullName>
                <label>Travel Time</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>3rdPartyCosts</fullName>
                <label>3rd Party Costs</label>
            </value>
            <value>
                <fullName>ProjectResourceCosts</fullName>
                <label>Project Resource Costs</label>
            </value>
            <value>
                <fullName>AbacusInbox</fullName>
                <label>Abacus Inbox</label>
            </value>
            <value>
                <fullName>Manufaktur</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>LicenseDirect</fullName>
                <label>License (Direct)</label>
            </value>
            <value>
                <fullName>LicenseProvision</fullName>
                <label>License (Provision)</label>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectCurrency__c.field-meta.xml
<CustomField>
    <fullName>ProjectCurrency__c</fullName>
    <formula>TEXT( ProjectName__r.ProjectCurrency__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Attention: You should not add a package to a Project with Status = Closed</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>PackagesProjectName</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectNr__c.field-meta.xml
<CustomField>
    <fullName>ProjectNr__c</fullName>
    <formula>ProjectName__r.ProjectNr__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Nr.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Alte Lookup Beziehung, kann aufgrund Code in Lightning Page &quot;Project Structure&quot; (auskommentiert) nicht gelöscht werden. 04.12.2017, ary</description>
    <label>Segment_do_not_use</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Segment__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Segment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Segment Service</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Segment__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Package__c/recordTypes/Time.recordType-meta.xml
<RecordType>
    <fullName>Time</fullName>
    <active>true</active>
    <label>Time</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ContractPartner__c.field-meta.xml
<CustomField>
    <fullName>ContractPartner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Summary Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>ProjectsContractPartner</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectCurrency__c.field-meta.xml
<CustomField>
    <fullName>ProjectCurrency__c</fullName>
    <label>Project Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlobalProjectCurrency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectNameInternal__c.field-meta.xml
<CustomField>
    <fullName>ProjectNameInternal__c</fullName>
    <formula>ContractPartner__r.AccountNameShort__c &amp;&quot; - &quot; &amp;  Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name Internal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectNr__c.field-meta.xml
<CustomField>
    <fullName>ProjectNr__c</fullName>
    <displayFormat>P-{000000}</displayFormat>
    <externalId>true</externalId>
    <label>Project Nr.</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectPartner__c.field-meta.xml
<CustomField>
    <fullName>ProjectPartner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Summary Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Project Partner)</relationshipLabel>
    <relationshipName>ProjectsProjectPartner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectStatus__c.field-meta.xml
<CustomField>
    <fullName>ProjectStatus__c</fullName>
    <label>Project Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>PartiallOpenWOTimeEntry</fullName>
                <label>Partially open (w/o Time Entry)</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectSubType__c.field-meta.xml
<CustomField>
    <fullName>ProjectSubType__c</fullName>
    <label>Project Sub-Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HelpTime</fullName>
                <label>Help Time</label>
            </value>
            <value>
                <fullName>Absence</fullName>
            </value>
            <value>
                <fullName>InternalProject</fullName>
                <label>Internal Project</label>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Licence</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/GlobalProjectCurrency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <masterLabel>Global Project Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LookupController.cls
public with sharing class LookupController {

    @AuraEnabled
    public static List<sObject> searchLookup(String query, String type, Id filterById) {

        String name = '%' + query + '%';

        if(type == 'User'){

            String RecordTypeName = 'Internal Contact';
            String baseQuery = 'SELECT Id, Name, Account.Name, LocalCurrency__c, AccountId FROM Contact WHERE name LIKE :name and RecordType.Name = :RecordTypeName ';

            if(filterById != null){
                baseQuery += ' and AccountId = :filterById ';
            }

            baseQuery += ' ORDER BY Name ASC LIMIT 100';

            return Database.query(baseQuery);

        }

        if(type == 'Account'){
            return [SELECT id, name FROM Account WHERE name LIKE :name or AccountNameShort__c LIKE :name or AccountNr__c LIKE :name ORDER BY Name ASC LIMIT 100];
        }

        if(type == 'Internal Account'){
            return [SELECT id, name
                    FROM Account
                    WHERE ( name LIKE :name or AccountNameShort__c LIKE :name)
                    AND RecordType.Name = 'Internal Account'
                    ORDER BY Name ASC LIMIT 100];
        }

        if(type == 'Segment'){
            return [SELECT id, name FROM Segment__c WHERE name LIKE :name ORDER BY Name ASC LIMIT 100];
        }

        if(type == 'Project'){

            String ProjectStatus = 'Open';
            String ProjectSubType = 'Absence';

            String baseQuery = 'SELECT Id, Name, ProjectNr__c, ProjectPartner__r.Id, ProjectPartner__r.Name, ProjectCurrency__c FROM Project__c WHERE (name LIKE :name or ProjectNameInternal__c LIKE :name or ProjectNr__c LIKE :name or Id = :query) and ProjectStatus__c = :ProjectStatus and ProjectSubType__c != :ProjectSubType';

            if(filterById != null){
                baseQuery += ' and ContractPartner__c = :filterById ';
            }

            baseQuery += ' ORDER BY Name ASC LIMIT 100 ';

            return Database.query(baseQuery);

        }

        if(type == 'Expense Project' || type == 'all project'){

            String ProjectStatus = 'Open';
            String OrProjectStatus = 'Partially open (w/o Time Entry)';
            String ProjectSubType = 'Absence';

            String baseQuery = 'SELECT Id, Name, ProjectNr__c, ProjectPartner__r.Id, ProjectPartner__r.Name, ProjectCurrency__c FROM Project__c WHERE (name LIKE :name or ProjectNameInternal__c LIKE :name or ProjectNr__c LIKE :name or Id = :query) and (ProjectStatus__c = :ProjectStatus or ProjectStatus__c = :OrProjectStatus) and ProjectSubType__c != :ProjectSubType';

            if(filterById != null){
                baseQuery += ' and ContractPartner__c = :filterById ';
            }

            baseQuery += ' ORDER BY Name ASC LIMIT 100 ';

            return Database.query(baseQuery);

        }

        if(type == 'open and closed project'){

            String NotProjectSubType = 'Absence';
            String baseQuery = 'SELECT Id, Name, ProjectNr__c, ProjectPartner__r.Id, ProjectPartner__r.Name, ProjectCurrency__c FROM Project__c WHERE (name LIKE :name or ProjectNameInternal__c LIKE :name or ProjectNr__c LIKE :name or Id = :query) and ProjectSubType__c != :NotProjectSubType';

            if(filterById != null){
                baseQuery += ' and ContractPartner__c = :filterById ';
            }

            baseQuery += ' ORDER BY Name ASC LIMIT 100 ';

            return Database.query(baseQuery);

        }

        if(type == 'Package'){

            String baseQuery = 'SELECT Id, PackageNr__c, Name, ProjectName__c, ProjectName__r.Name, ProjectName__r.ProjectNr__c, ProjectName__r.ProjectPartner__r.Id, ProjectName__r.ProjectCurrency__c, ProjectName__r.ProjectPartner__r.Name, PackageSortNr__c FROM Package__c WHERE (name LIKE :name or PackageNr__c LIKE :name or Id = :query)';

            if(filterById != null){
                baseQuery += ' and ProjectName__c = :filterById ';
            }

            baseQuery += ' ORDER BY PackageSortNr__c, Name ASC LIMIT 100';

            return Database.query(baseQuery);

        }

        if(type == 'Work Package'){

            String packageStatus = 'Open';
            String RecordTypeName = 'Time';
            String SubType = 'WorkTime';
            String OrSubType = 'Manufaktur';
            String NotProjectSubType = 'Absence';
            String baseQuery = 'SELECT Id, PackageSubType__c, PackageNr__c, Name, ProjectName__c, ProjectName__r.Name, ProjectName__r.ProjectNr__c, ProjectName__r.ProjectPartner__r.Id, ProjectName__r.ProjectCurrency__c, ProjectName__r.ProjectPartner__r.Name, PackageSortNr__c FROM Package__c WHERE (name LIKE :name or PackageNr__c LIKE :name or Id = :query) and PackageStatus__c = :packageStatus and RecordType.Name = :RecordTypeName and (PackageSubType__c = :SubType or PackageSubType__c = :OrSubType)  and ProjectName__r.ProjectSubType__c != :NotProjectSubType';

            if(filterById != null){
                baseQuery += ' and ProjectName__c = :filterById ';
            }

            baseQuery += ' ORDER BY PackageSortNr__c, Name ASC LIMIT 100';

            return Database.query(baseQuery);

        }

        if(type == 'Travel Package'){

            String packageStatus = 'Open';
            String RecordTypeName = 'Time';
            String SubType = 'TravelTime';
            String NotProjectSubType = 'Absence';
            String baseQuery = 'SELECT Id, Name, PackageNr__c, ProjectName__c, ProjectName__r.Name, ProjectName__r.ProjectNr__c, ProjectName__r.ProjectPartner__r.Id, ProjectName__r.ProjectCurrency__c, ProjectName__r.ProjectPartner__r.Name, PackageSortNr__c FROM Package__c WHERE (name LIKE :name or PackageNr__c LIKE :name or Id = :query) and PackageStatus__c = :packageStatus and RecordType.Name = :RecordTypeName and PackageSubType__c = :SubType  and ProjectName__r.ProjectSubType__c != :NotProjectSubType';

            if(filterById != null){
                baseQuery += ' and ProjectName__c = :filterById ';
            }

            baseQuery += ' ORDER BY PackageSortNr__c, Name ASC LIMIT 100';

            return Database.query(baseQuery);

        }

        if(type == 'Expense Package'){

            String packageStatus = 'Open';
            String RecordTypeName = 'Expense';
            String baseQuery = 'SELECT Id, Name, PackageNr__c, ProjectName__c, ProjectName__r.Name, ProjectName__r.ProjectNr__c, ProjectName__r.ProjectPartner__r.Id, ProjectName__r.ProjectCurrency__c, ProjectName__r.ProjectPartner__r.Name, PackageSortNr__c FROM Package__c WHERE (name LIKE :name or PackageNr__c LIKE :name or Id = :query) and PackageStatus__c = :packageStatus and RecordType.Name = :RecordTypeName ';

            if(filterById != null){
                baseQuery += ' and ProjectName__c = :filterById ';
            }

            baseQuery += ' ORDER BY PackageSortNr__c, Name ASC LIMIT 100';

            return Database.query(baseQuery);

        }

        if(type == 'Internal Package'){

            String packageStatus = 'Open';
            String RecordTypeName = 'Time';
            String SubType = 'WorkTime';
            String NotAbacusTimeType = '200';
            String ProjectSubType = 'Absence';
            String baseQuery = 'SELECT Id, Name, PackageNr__c, ProjectName__c, ProjectName__r.Name, ProjectName__r.ProjectNr__c, ProjectName__r.ContractPartner__c, ProjectName__r.ProjectCurrency__c, ProjectName__r.ContractPartner__r.Name, PackageSortNr__c FROM Package__c WHERE (name LIKE :name or PackageNr__c LIKE :name) and PackageStatus__c = :packageStatus and RecordType.Name = :RecordTypeName and AbacusTimeType__c <> :NotAbacusTimeType and PackageSubType__c = :SubType and ProjectName__r.ProjectSubType__c = :ProjectSubType';

            if(filterById != null){
                baseQuery += ' and ProjectName__c = :filterById ';
            }

            baseQuery += ' ORDER BY PackageSortNr__c, Name ASC LIMIT 100';

            return Database.query(baseQuery);

        }

        // used on the absence tracker tab
        if(type == 'Internal Project'){

            return [SELECT id, ProjectNr__c, name FROM Project__c
                    WHERE (name LIKE :name or ProjectNr__c LIKE :name or Id = :query)
                    and RecordType.Name = 'Internal'
                    and ProjectStatus__c = 'Open'
                    ORDER BY Name ASC LIMIT 100];

        }

        // used on the expense tracker tab
        if(type == 'Credit Card'){

            return [SELECT Id, Name, CreditCard__c
                    FROM Inventory__c
                    WHERE (name LIKE :name or CreditCard__c LIKE :name)
                    AND RecordType.Name = 'Credit Card' 
                    AND ValAvailableInApp__c = true
                    limit 100];

        }

        // used on the expense tracker tab
        if(type == 'Car'){

            return [SELECT Id, Name, Car__c
                    FROM Inventory__c
                    WHERE (name LIKE :name or Car__c LIKE :name)
                    AND RecordType.Name = 'Car' 
                    AND ValAvailableInApp__c = true
                    limit 100];

        }

        return new List<sObject>();

    }

}