force-app/main/default/objects/Account/fields/AccountLanguage__c.field-meta.xml
<CustomField>
    <fullName>AccountLanguage__c</fullName>
    <label>Account Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <default>true</default>
                <label>D</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LegalNature__c.field-meta.xml
<CustomField>
    <fullName>LegalNature__c</fullName>
    <label>Legal Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporation / Limited Company</fullName>
            </value>
            <value>
                <fullName>Limited Partnership</fullName>
            </value>
            <value>
                <fullName>Association / Foundation</fullName>
            </value>
            <value>
                <fullName>Individual Company</fullName>
            </value>
            <value>
                <fullName>Natural Entity (Private Person)</fullName>
            </value>
            <value>
                <fullName>Public Administration / Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountLanguage__c.field-meta.xml
<CustomField>
    <fullName>AccountLanguage__c</fullName>
    <formula>CASE(TEXT(InvoiceReceiver__r.AccountLanguage__c),
 &apos;D&apos;, &apos;DE&apos;,
 &apos;E&apos;, &apos;EN&apos;,
 &apos;F&apos;, &apos;FR&apos;,
 &apos;I&apos;, &apos;IT&apos;,
 &apos;S&apos;, &apos;ES&apos;,
      &apos;EN&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ContentDocumentsTest.cls
/**
 * 
 */
@isTest
private class ContentDocumentsTest {

    @isTest
    static void test_addDocument() {
        Account acct = new Account(Name = 'TEST_ACCT', LegalNature__c = 'Corporation / Limited Company', AccountLanguage__c = 'D');
        insert acct;

        ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins.jpg',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true,
                FirstPublishLocationId = acct.Id
        );

        Test.startTest();
            insert contentVersion;
        Test.stopTest();
    }

    @isTest
    static void test_deleteNonInvoiceDocument() {
        Account acct = new Account(Name = 'TEST_ACCT', LegalNature__c = 'Corporation / Limited Company', AccountLanguage__c = 'D');
        insert acct;

        ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins.jpg',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true,
                FirstPublishLocationId = acct.Id
        );
        insert contentVersion;

        System.debug('---test_deleteNonInvoiceDocument--- contentVersion: '+contentVersion);

        contentVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id];

        ContentDocument cntDoc = new ContentDocument();
        cntDoc.Id = contentVersion.ContentDocumentId;

        Test.startTest();
            delete cntDoc;
        Test.stopTest();
    }

    @isTest
    static void test_deleteInvoiceDocument() {
        TestFactory.makeData();

        Account acc = [SELECT Id FROM Account LIMIT 1];
        Project__c proj = [SELECT Id FROM Project__c LIMIT 1];
        CostCenter__c costCenter = [SELECT Id FROM CostCenter__c LIMIT 1];
        Package__c service = [SELECT Id FROM Package__c LIMIT 1];
        
        Invoice__c inv = TestFactory.createInvoice(acc.Id, proj.Id, costCenter.Id);
        insert inv; 

        ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins.jpg',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true,
                FirstPublishLocationId = inv.Id
        );
        insert contentVersion;

        System.debug('---ContentDocumentsTest.test_deleteNonInvoiceDocument--- contentVersion: '+contentVersion);

        contentVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id];

        ContentDocument cntDoc = new ContentDocument();
        cntDoc.Id = contentVersion.ContentDocumentId;

        Test.startTest();
            try {
                delete cntDoc;
                system.assert(true,'ERROR: ContentDocumentsTest.test_deleteNonInvoiceDocument --- The deletion of a document related to an Invoice should have thrown an exception.');
            } catch (Exception e) {
                System.debug('All OK: ContentDocumentsTest.test_deleteNonInvoiceDocument --- Invoice documents cannot be deleted');
            }
        Test.stopTest();
    }
}