force-app/main/default/objects/Account/fields/AccountLanguage__c.field-meta.xml
<CustomField>
    <fullName>AccountLanguage__c</fullName>
    <label>Account Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <default>true</default>
                <label>D</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ESRAccountNr__c.field-meta.xml
<CustomField>
    <fullName>ESRAccountNr__c</fullName>
    <label>ESR Account Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ESRMergentNr__c.field-meta.xml
<CustomField>
    <fullName>ESRMergentNr__c</fullName>
    <label>ESR Mergent Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/CHFIBAN__c.field-meta.xml
<CustomField>
    <fullName>CHFIBAN__c</fullName>
    <label>CHF IBAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CHFQRIBAN__c.field-meta.xml
<CustomField>
    <fullName>CHFQRIBAN__c</fullName>
    <label>CHF QR IBAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountLanguage__c.field-meta.xml
<CustomField>
    <fullName>AccountLanguage__c</fullName>
    <formula>CASE(TEXT(InvoiceReceiver__r.AccountLanguage__c),
 &apos;D&apos;, &apos;DE&apos;,
 &apos;E&apos;, &apos;EN&apos;,
 &apos;F&apos;, &apos;FR&apos;,
 &apos;I&apos;, &apos;IT&apos;,
 &apos;S&apos;, &apos;ES&apos;,
      &apos;EN&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/AccountNameLegal__c.field-meta.xml
<CustomField>
    <fullName>AccountNameLegal__c</fullName>
    <label>Account Name (Legal)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressStreetNr__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressStreetNr__c</fullName>
    <label>Billing Address Street, Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressZIP__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressZIP__c</fullName>
    <label>Billing Address ZIP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAdressCity__c.field-meta.xml
<CustomField>
    <fullName>BillingAdressCity__c</fullName>
    <label>Billing Adress City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ESRAccountNr__c.field-meta.xml
<CustomField>
    <fullName>ESRAccountNr__c</fullName>
    <label>ESR Account Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ESRFormatted__c.field-meta.xml
<CustomField>
    <fullName>ESRFormatted__c</fullName>
    <label>ESR Formatted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ESRMergentNr__c.field-meta.xml
<CustomField>
    <fullName>ESRMergentNr__c</fullName>
    <label>ESR Mergent Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ESRUnformatted__c.field-meta.xml
<CustomField>
    <fullName>ESRUnformatted__c</fullName>
    <label>ESR Unformatted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDocumentNr__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDocumentNr__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Document Nr.</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceReceiver__c.field-meta.xml
<CustomField>
    <fullName>InvoiceReceiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Receiver</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Billing Receiver)</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceStatus__c.field-meta.xml
<CustomField>
    <fullName>InvoiceStatus__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceTotalAmountGross__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTotalAmountGross__c</fullName>
    <formula>InvoiceTotalAmountNet__c + InvoiceVATAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice - Total Amount Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectInvoiceCurrency__c.field-meta.xml
<CustomField>
    <fullName>ProjectInvoiceCurrency__c</fullName>
    <label>Project / Invoice Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/InvoiceReceiver__c.field-meta.xml
<CustomField>
    <fullName>InvoiceReceiver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Receiver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Summary Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Invoice Receiver)</relationshipLabel>
    <relationshipName>ProjectsInvoiceReceiver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Internal Contract Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CostCenter__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QRGeneratorToolSettings__c/QRGeneratorToolSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to configure hierarchical settings in the QR Generator Tool to provide user-specific &amp; profile-specific customizations</description>
    <label>QR Generator Tool Settings</label>
</CustomObject>

force-app/main/default/objects/QRGeneratorToolSettings__c/fields/API_boundaryLineScissors__c.field-meta.xml
<CustomField>
    <fullName>API_boundaryLineScissors__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If scissors should be printed on the boundary lines. Only to be set to true if  Boundary Lines is set to true. - https://rest.qr-invoice.cloud/swagger-ui/index.html#/11%20Payment%20Part%20%26%20Receipt%20(QR%20Bill)/createPaymentPartReceipt</description>
    <inlineHelpText>Mark as true if scissors should be printed on the boundary lines. This can only be active if Boundary Lines is active.</inlineHelpText>
    <label>Add Boundary Line Scissors</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QRGeneratorToolSettings__c/fields/API_boundaryLinesMargins__c.field-meta.xml
<CustomField>
    <fullName>API_boundaryLinesMargins__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the boundary lines should include a margin and not extend to the border of the page. Printers usually are unable to print the lines completely otherwise. - https://rest.qr-invoice.cloud/swagger-ui/index.html#/11%20Payment%20Part%20%26%20Receipt%20(QR%20Bill)/createPaymentPartReceipt</description>
    <inlineHelpText>If the boundary lines should include a margin and not extend to the border of the page. Printers usually are unable to print the lines completely otherwise.</inlineHelpText>
    <label>Add Boundary Lines Margins</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QRGeneratorToolSettings__c/fields/API_endpoint__c.field-meta.xml
<CustomField>
    <fullName>API_endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QRGeneratorToolSettings__c/fields/API_key__c.field-meta.xml
<CustomField>
    <fullName>API_key__c</fullName>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QRGeneratorToolSettings__c/fields/API_normalizeInput__c.field-meta.xml
<CustomField>
    <fullName>API_normalizeInput__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, the input gets normalized. This means strings are trimmed, special quotations replaced with ASCII ones, and special characters replaced with semantically equal ones (e.g. œ -&gt; oe)</description>
    <inlineHelpText>If true, the input gets normalized. This means strings are trimmed, special quotations replaced with ASCII ones, and special characters replaced with semantically equal ones (e.g. œ -&gt; oe)
Documentation: https://rest.qr-invoice.cloud/swagger-ui/index.html#/11%20Payment%20Part%20%26%20Receipt%20(QR%20Bill)/createPaymentPartReceipt</inlineHelpText>
    <label>Normalize Input</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QRGeneratorToolSettings__c/fields/API_resolution__c.field-meta.xml
<CustomField>
    <fullName>API_resolution__c</fullName>
    <description>Output Resolution - https://rest.qr-invoice.cloud/swagger-ui/index.html#/11%20Payment%20Part%20%26%20Receipt%20(QR%20Bill)/createPaymentPartReceipt</description>
    <inlineHelpText>Output Resolution</inlineHelpText>
    <label>resolution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QRCodeService.cls
/**
 * QRCodeService is responsible for generating QR codes for Invoice__c records.
 * It constructs the request payload using QRCodeRequestObj, performs the API callout,
 * and then associates the returned QR image with the invoice via ContentVersion and ContentDocumentLink.
 *
 * This class encapsulates the business logic and integration with the QR code generation API.
 *
 * @author 
 * @since Feb 2025
 * @documentation https://rest.qr-invoice.cloud/swagger-ui/index.html#/11%20Payment%20Part%20%26%20Receipt%20(QR%20Bill)/createPaymentPartReceipt
 */
public without sharing class QRCodeService {
    
    // Retrieve default tool settings for QR generation.
    static QRGeneratorToolSettings__c toolSettings = QRGeneratorToolSettings__c.getOrgDefaults();
    private static final String API_KEY_PARAM = '?api_key=';
    private static final String IMG_CONTENT_TYPE = 'image/jpeg';
    
    /**
     * Generates a QR code for the specified Invoice__c record.
     * Builds the QR code image, inserts it as a ContentVersion,
     * and creates a ContentDocumentLink to associate the image with the invoice.
     *
     * @param record The Invoice__c record for which the QR code is generated.
     */
    public static void generateQRCode(Invoice__c record) {
        // Validate that required custom settings are configured
        validateToolSettings();

        System.debug('---QRCodeService.generateQRCode--- invoice: ' + record);
        
        String qrCodeString = buildQRCodeImage(record);
        insertQRImage(record.Id, qrCodeString);
        
        Logger.info('QRCode generated.');
        Logger.saveLog();
    }
    
    /**
     * Validates that all required custom setting fields are configured.
     * @throws HandledException if any required field is missing.
     */
    private static void validateToolSettings() {
        // if (String.isBlank(toolSettings.API_endpoint__c)) {
        //     throw new HandledException('QR Generator API endpoint is not configured. Please configure the API_endpoint__c field in QRGeneratorToolSettings custom setting.');
        // }
        // if (String.isBlank(toolSettings.API_key__c)) {
        //     throw new HandledException('QR Generator API key is not configured. Please configure the API_key__c field in QRGeneratorToolSettings custom setting.');
        // }
    }
    
    /**
     * Inserts the QR image as a ContentVersion and creates a ContentDocumentLink
     * to associate the image with the given parent record. If there are existing
     * ContentDocumentLinks with the same title pattern for the same parentRecordId, they are deleted.
     *
     * @param parentRecordId The ID of the parent Invoice__c record.
     * @param base64 The Base64 encoded QR code image.
     */
    private static void insertQRImage(Id parentRecordId, String base64) {

        String docName = Label.QRInvoicePrefix + '_' + Date.today().format();
        String titlePattern = Label.QRInvoicePrefix + '_%';

       // 1) Insert new file and link it to the record
        ContentVersion cv = new ContentVersion(
            Title                 = docName,
            PathOnClient          = docName + '.' + 'jpg',
            VersionData           = EncodingUtil.base64Decode(base64),
            FirstPublishLocationId = parentRecordId
        );
        insert cv;

        // 2) Get the ContentDocumentId of the newly created file
        Id newContentDocumentId = [
            SELECT ContentDocumentId
            FROM ContentVersion
            WHERE Id = :cv.Id
            LIMIT 1
        ].ContentDocumentId;

        // 3) Find *other* documents with same Title/Extension
        //    and linked to this record
        List<ContentDocumentLink> oldLinks = [
            SELECT ContentDocumentId
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :parentRecordId
              AND ContentDocument.Title LIKE :titlePattern
              AND ContentDocument.FileExtension = 'JPG'
              AND ContentDocumentId != :newContentDocumentId
        ];

        System.debug('---QRCodeService.insertQRImage--- oldLinks: ' + oldLinks);
        System.debug('---QRCodeService.insertQRImage--- newContentDocumentId: '+newContentDocumentId);

        if (!oldLinks.isEmpty()) {
            Set<Id> oldDocIds = new Set<Id>();
            for (ContentDocumentLink cdl : oldLinks) {
                oldDocIds.add(cdl.ContentDocumentId);
            }

            // 4) Delete old ContentDocuments (this deletes ALL their versions + links)
            List<ContentDocument> docsToDelete = [
                SELECT Id
                FROM ContentDocument
                WHERE Id IN :oldDocIds
            ];
            if (!docsToDelete.isEmpty()) {
                delete docsToDelete;
            }
        }
    }
    
    /**
     * Builds the QR code image for the specified Invoice__c record by making an HTTP POST callout
     * to the external QR code generation service.
     *
     * @param record The Invoice__c record.
     * @return A Base64 encoded string representing the QR code image.
     * @throws HandledException if an error occurs during the callout or processing.
     */
    @TestVisible
    private static String buildQRCodeImage(Invoice__c record) {
        // Set language based on the invoice's account language.
        String language = (record.AccountLanguage__c == 'DE') ? 'de' : 'en';
        
        // Build query parameters from tool settings.
        List<String> queryParameters = buildQueryParameters();
        
        // Build the JSON request body using QRCodeRequestObj.
        String requestBody = createRequestBody(record, language);
        System.debug('+++ Request body: ' + requestBody);
        
        HttpResponse response;
        try {
            response = doPost(queryParameters, requestBody, language);
        } catch (Exception ex) {
            Logger.exception('Error on QRCodeService.generateQRCode.', ex);
            throw new HandledException('Generate QR service general error. Please review the logs.');
        }
        
        String qrCodeString = EncodingUtil.base64Encode(response.getBodyAsBlob());
        if (String.isBlank(qrCodeString)) {
            Logger.error('Response body is empty.');
            Logger.saveLog();
            throw new HandledException('Generate QR service error. Please review the logs.');
        }
        
        return qrCodeString;
    }
    
    /**
     * Builds query parameters based on tool settings.
     *
     * @return A list of query parameters.
     */
    @TestVisible
    private static List<String> buildQueryParameters() {
        List<String> params = new List<String>();
        if (String.isNotBlank(toolSettings.API_resolution__c)) {
            params.add('resolution=' + toolSettings.API_resolution__c);
        }
        if (toolSettings.API_normalizeInput__c) {
            params.add('normalizeInput=' + toolSettings.API_normalizeInput__c);
        }
        if (toolSettings.API_boundaryLinesMargins__c) {
            params.add('boundaryLinesMargins=' + toolSettings.API_boundaryLinesMargins__c);
        }
        if (toolSettings.API_boundaryLineScissors__c) {
            params.add('boundaryLineScissors=' + toolSettings.API_boundaryLineScissors__c);
        }
        return params;
    }
    
    /**
     * Executes an HTTP POST callout to the QR code generation API.
     *
     * @param queryParameters A list of query parameters to be appended to the endpoint URL.
     * @param body The JSON request body.
     * @param language The language code for the request (e.g., 'en' or 'de').
     * @return The HttpResponse received from the API.
     * @throws HandledException if the response status code is not 200.
     */
    @TestVisible
    private static HttpResponse doPost(List<String> queryParameters, String body, String language) {
        HttpRequest request = new HttpRequest();
        request.setMethod('POST');
        
        String endpoint = toolSettings.API_endpoint__c + API_KEY_PARAM + toolSettings.API_key__c;
        if (!queryParameters.isEmpty()){
            endpoint += '&' + String.join(queryParameters, '&');
        }
        
        request.setEndpoint(endpoint);
        request.setHeader('accept', IMG_CONTENT_TYPE);
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Accept-Language', language);
        request.setBody(body);
        
        HttpResponse response = new Http().send(request);
        if (response.getStatusCode() != 200){
            Logger.error('Callout error. Status: ' + response.getStatus() + ' Code: ' + response.getStatusCode());
            Logger.info('Endpoint: ' + request.getEndpoint());
            Logger.info('Request body: ' + request.getBody());
            Logger.info('Response: ' + response.getBody());
            Logger.saveLog();
            throw new HandledException('Callout error. Status: ' + response.getStatus() + ' Code: ' + response.getStatusCode());
        }
        return response;
    }
    
    /**
     * Creates the JSON request body for the QR code generation API using the QRCodeRequestObj class.
     *
     * @param record The Invoice__c record.
     * @param language The language code for the request.
     * @return A JSON string representing the request payload.
     */
    @TestVisible
    private static String createRequestBody(Invoice__c record, String language) {
        // Query the invoice record to retrieve all necessary fields.
        record = [
            SELECT InvoiceReceiver__r.Name,
                   ProjectCostCenter__r.CHFIBAN__c,
                   ProjectCostCenter__r.CHFQRIBAN__c,
                   BillingAdressCity__c, 
                   BillingAddressStreetNr__c, 
                   BillingAddressZIP__c, 
                   InvoiceTotalAmountGross__c,
                   ProjectInvoiceCurrency__c, 
                   ProjectName__r.Name,
                   ESRFormatted__c,
                   ESRAccountNr__c,
                   ESRMergentNr__c,
                   ProjectCostCenter__r.Name,
                   AccountNameLegal__c,
                   InvoiceDocumentNr__c,
                   InvoiceStatus__c
            FROM Invoice__c
            WHERE Id = :record.Id
        ];

        // Retrieve organization information for address details.
        Organization companyInfo = [SELECT Name, Address FROM Organization LIMIT 1];
        
        String companyName = QRCodeUtils.getCompanyName(record.ProjectCostCenter__r.Name);
        String invoiceNameLabel = QRCodeUtils.getInvoiceNameLabel(record.InvoiceDocumentNr__c, language);
        if (String.isBlank(record.ProjectCostCenter__r.CHFQRIBAN__c)) {
            throw new HandledException('Missing CH-IBAN (ProjectCostCenter__r.CHFQRIBAN__c) for QR invoice.');
        }
        String iban = QRCodeUtils.cleanIban(record.ProjectCostCenter__r.CHFQRIBAN__c);
        
        // Build and populate the QRCodeRequestObj object.
        QRCodeRequestObj req = new QRCodeRequestObj();
        req.creditorInformation = new QRCodeRequestObj.CreditorInformation();
        req.creditorInformation.iban = iban;
        req.creditorInformation.creditor = new QRCodeRequestObj.Creditor();
        req.creditorInformation.creditor.addressType = 'STRUCTURED';
        req.creditorInformation.creditor.name = companyName;
        req.creditorInformation.creditor.streetName = companyInfo.Address.getStreet();
        req.creditorInformation.creditor.postalCode = companyInfo.Address.getPostalCode();
        req.creditorInformation.creditor.city = companyInfo.Address.getCity();
        req.creditorInformation.creditor.country = 'CH';
        
        req.ultimateDebtor = new QRCodeRequestObj.UltimateDebtor();
        req.ultimateDebtor.addressType = 'STRUCTURED';
        req.ultimateDebtor.name = record.AccountNameLegal__c;
        req.ultimateDebtor.streetName = record.BillingAddressStreetNr__c;
        req.ultimateDebtor.postalCode = record.BillingAddressZIP__c;
        req.ultimateDebtor.city = record.BillingAdressCity__c;
        req.ultimateDebtor.country = 'CH';
        
        req.paymentAmountInformation = new QRCodeRequestObj.PaymentAmountInformation();
        req.paymentAmountInformation.amount = record.InvoiceTotalAmountGross__c;
        req.paymentAmountInformation.currency_z = record.ProjectInvoiceCurrency__c;
        
        req.paymentReference = new QRCodeRequestObj.PaymentReference();
        req.paymentReference.additionalInformation = new QRCodeRequestObj.AdditionalInformation();
        // Validate the amount and set the unstructured message accordingly.
        if(req.paymentAmountInformation.amount != 0){
            req.paymentReference.additionalInformation.unstructuredMessage = invoiceNameLabel;
        } else {
            req.paymentReference.additionalInformation.unstructuredMessage = 'DO NOT USE FOR PAYMENT';
        }
        
        // If the IBAN is a QR-IBAN, generate a structured reference.
        if (QRCodeUtils.isQrIban(iban)) {
            if ((record.InvoiceStatus__c == 'Draft' || record.InvoiceStatus__c == 'Approval') && record.InvoiceDocumentNr__c == null)
            {
                record.InvoiceDocumentNr__c = 0;
                record.ESRFormatted__c = 'DRAFT Invoice';
            }

            System.debug('---QRCodeService.createRequestBody--- ESRFormatted__c:' + record.ESRFormatted__c);

            // Generate the invoice ESR Unformatted just in case any of the values used to generate it has changed.
            // Note the the field ESRUnformatted__c is not updated with the generated value. 
            // The generateded value is not saved back into Salesforce. Just doing this to ensure the ESR is always up to date in the generated QR-Bill
            String qrReference = EsrUtil.getESR(record.ESRAccountNr__c, record.ESRMergentNr__c, record.InvoiceDocumentNr__c, 
                                                    (System.Test.isRunningTest() ? 123 : record.InvoiceTotalAmountGross__c), EsrUtil.EsrFormat.UNFORMATTED);

            if (String.isBlank(qrReference)) {
                throw new HandledException('Missing InvoiceDocumentNr__c and ESRFormatted__c for QR reference generation.');
            }

            System.debug('---QRCodeService.createRequestBody--- qrReference:' + qrReference);
        
            req.paymentReference.reference = qrReference;
            req.paymentReference.referenceType = 'QRR';
        } else {
            System.debug('---QRCodeService.createRequestBody--- isQrIban == false');
            req.paymentReference.reference = '';
            req.paymentReference.referenceType = '';
        }

        System.debug('---QRCodeService.createRequestBody--- Json:' + req.toJson());
        
        return req.toJson();
    }
}