force-app/main/default/objects/Account/fields/AccountLanguage__c.field-meta.xml
<CustomField>
    <fullName>AccountLanguage__c</fullName>
    <label>Account Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <default>true</default>
                <label>D</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BillingCity__c.field-meta.xml
<CustomField>
    <fullName>BillingCity__c</fullName>
    <label>Billing City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SWITZERLAND</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GERMANY</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>LIECHTENSTEIN</fullName>
            </value>
            <value>
                <fullName>UNITED STATES</fullName>
            </value>
            <value>
                <fullName>----------</fullName>
            </value>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ÅLAND ISLANDS</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANDORRA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTARCTICA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BillingStreetNr__c.field-meta.xml
<CustomField>
    <fullName>BillingStreetNr__c</fullName>
    <label>Billing Street, Nr</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingZip__c.field-meta.xml
<CustomField>
    <fullName>BillingZip__c</fullName>
    <label>Billing ZIP</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/CHFQRIBAN__c.field-meta.xml
<CustomField>
    <fullName>CHFQRIBAN__c</fullName>
    <label>CHF QR IBAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/EURQRIBAN__c.field-meta.xml
<CustomField>
    <fullName>EURQRIBAN__c</fullName>
    <label>EUR QR IBAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/LegalAccount__c.field-meta.xml
<CustomField>
    <fullName>LegalAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Legal Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cost Center</relationshipLabel>
    <relationshipName>CostCenter</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountLanguage__c.field-meta.xml
<CustomField>
    <fullName>AccountLanguage__c</fullName>
    <formula>CASE(TEXT(InvoiceReceiver__r.AccountLanguage__c),
 &apos;D&apos;, &apos;DE&apos;,
 &apos;E&apos;, &apos;EN&apos;,
 &apos;F&apos;, &apos;FR&apos;,
 &apos;I&apos;, &apos;IT&apos;,
 &apos;S&apos;, &apos;ES&apos;,
      &apos;EN&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/AccountNameLegal__c.field-meta.xml
<CustomField>
    <fullName>AccountNameLegal__c</fullName>
    <label>Account Name (Legal)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressCountry__c</fullName>
    <label>Billing Address Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressStreetNr__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressStreetNr__c</fullName>
    <label>Billing Address Street, Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressZIP__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressZIP__c</fullName>
    <label>Billing Address ZIP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAdressCity__c.field-meta.xml
<CustomField>
    <fullName>BillingAdressCity__c</fullName>
    <label>Billing Adress City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingNameAddition__c.field-meta.xml
<CustomField>
    <fullName>BillingNameAddition__c</fullName>
    <label>Billing Name (Addition)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ESRUnformatted__c.field-meta.xml
<CustomField>
    <fullName>ESRUnformatted__c</fullName>
    <label>ESR Unformatted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDocumentNr__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDocumentNr__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Document Nr.</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceReceiver__c.field-meta.xml
<CustomField>
    <fullName>InvoiceReceiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Receiver</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Billing Receiver)</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceTotalAmountGross__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTotalAmountGross__c</fullName>
    <formula>InvoiceTotalAmountNet__c + InvoiceVATAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice - Total Amount Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectInvoiceCurrency__c.field-meta.xml
<CustomField>
    <fullName>ProjectInvoiceCurrency__c</fullName>
    <label>Project / Invoice Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QRCountryCode__mdt/QRCountryCode__mdt.object-meta.xml
<CustomObject>
    <label>QRCountryCode</label>
    <pluralLabel>QRCountryCodes</pluralLabel>
</CustomObject>

force-app/main/default/objects/QRCountryCode__mdt/fields/Countrycode__c.field-meta.xml
<CustomField>
    <fullName>Countrycode__c</fullName>
    <label>Countrycode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QRLanguageCode__mdt/QRLanguageCode__mdt.object-meta.xml
<CustomObject>
    <label>QRLanguageCode</label>
    <pluralLabel>QRLanguageCodes</pluralLabel>
</CustomObject>

force-app/main/default/objects/QRLanguageCode__mdt/fields/LanguageCode__c.field-meta.xml
<CustomField>
    <fullName>LanguageCode__c</fullName>
    <label>LanguageCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QRBillRequest.cls
/**
 * QRBillPARXHandler
 * @author ldo
 * @Modified By Manjiri
 * @copyright PARX
 *
 */
public class QRBillRequest {
    
    // Creditor information
    public String creditor_account;
    public String creditor_name;
    public String creditor_street;
    public String creditor_houseNumber;
    public String creditor_country;
    public String creditor_postalCode;
    public String creditor_town;

    // Debtor information
    public String debtor_name;
    public String debtor_street;
    public String debtor_houseNumber;
    public String debtor_country;
    public String debtor_postalCode;
    public String debtor_town;

    // Bill information
    public String billCurrency;
    public Decimal amount;
    public String creditorReference;
    public String additionlInformation;
    public String billLanguage;

    public String recordId;
    public String name;
    
    Map<String, QRCountryCode__mdt> mapCountryCodes = QRCountryCode__mdt.getAll();
    Map<String, QRLanguageCode__mdt> mapLanguageCodes = QRLanguageCode__mdt.getAll();
    
    public QRBillRequest(Invoice__c obj, String description){
        name = obj.Name;
        this.recordId = obj.Id;
		this.creditor_account = obj.ProjectInvoiceCurrency__c == 'CHF'? obj.ProjectCostCenter__r.CHFQRIBAN__c : obj.ProjectCostCenter__r.EURQRIBAN__c;
        //this.creditor_account = 'CH373000527314691801Z';
        //this.creditor_name = obj.ProjectCostCenter__r.Name;
        this.creditor_name = obj.ProjectCostCenter__r.LegalAccount__r.Name;
        this.creditor_street = obj.ProjectCostCenter__r.LegalAccount__r.BillingStreetNr__c;
        this.creditor_houseNumber = '';
        this.creditor_country = ( mapCountryCodes.get(obj.ProjectCostCenter__r.LegalAccount__r.BillingCountry__c) != null) ? mapCountryCodes.get(obj.ProjectCostCenter__r.LegalAccount__r.BillingCountry__c).CountryCode__c : ''; 
        this.creditor_postalCode = obj.ProjectCostCenter__r.LegalAccount__r.BillingZip__c;
        this.creditor_town = obj.ProjectCostCenter__r.LegalAccount__r.BillingCity__c;
        this.creditorReference = obj.ESRunformatted__c;
        //this.creditorReference = null;
        this.debtor_name = obj.AccountNameLegal__c;
        //this.debtor_name = 'Stiftung juristische Weiterbildung Zürich Zürcher Abfallverwertungs AG';
        this.debtor_street = (obj.BillingNameAddition__c != null) ? obj.BillingNameAddition__c+'\n'+obj.BillingAddressStreetNr__c : obj.BillingAddressStreetNr__c;
        this.debtor_houseNumber = '';
        this.debtor_country = ( mapCountryCodes.get(obj.BillingAddressCountry__c) != null) ? mapCountryCodes.get(obj.BillingAddressCountry__c).CountryCode__c : ''; 
        this.debtor_postalCode = obj.BillingAddressZIP__c;
        this.debtor_town = obj.BillingAdressCity__c;
        this.billCurrency = obj.ProjectInvoiceCurrency__c; 
        this.amount = obj.InvoiceTotalAmountGross__c;
        this.additionlInformation = ''+obj.InvoiceDocumentNr__c;
		this.billLanguage = ( mapLanguageCodes.get(obj.InvoiceReceiver__r.AccountLanguage__c) !=null ) ? mapLanguageCodes.get(obj.InvoiceReceiver__r.AccountLanguage__c).LanguageCode__c : '';

        system.debug('***** obj.ProjectInvoiceCurrency__c : *****'+obj.ProjectInvoiceCurrency__c);
        system.debug('***** obj.ProjectCostCenter__r.CHFQRIBAN__c : *****'+obj.ProjectCostCenter__r.CHFQRIBAN__c);
        system.debug('***** obj.ProjectCostCenter__r.EURQRIBAN__c : *****'+obj.ProjectCostCenter__r.EURQRIBAN__c);        
        system.debug('***** recordId             : *****'+this.recordId);
        system.debug('***** debtor_town          : *****'+this.debtor_town);
        system.debug('***** debtor_street        : *****'+this.debtor_street);
        system.debug('***** debtor_postalCode    : *****'+this.debtor_postalCode);
        system.debug('***** debtor_country       : *****'+this.debtor_country);
        system.debug('***** debtor_houseNumber   : *****'+this.debtor_houseNumber);
        system.debug('***** debtor_name          : *****'+this.debtor_name);
        system.debug('***** creditor_account     : *****'+this.creditor_account);
        system.debug('***** creditor_name        : *****'+this.creditor_name);
        system.debug('***** creditor_street      : *****'+this.creditor_street);
        system.debug('***** creditor_houseNumber : *****'+this.creditor_houseNumber);
        system.debug('***** creditor_country     : *****'+this.creditor_country);
        system.debug('***** creditor_postalCode  : *****'+this.creditor_postalCode);
        system.debug('***** creditor_town        : *****'+this.creditor_town);
        system.debug('***** creditorReference    : *****'+this.creditorReference);
        system.debug('***** billLanguage         : *****'+this.billLanguage);
        system.debug('***** this.additionlInformation         : *****'+this.additionlInformation);
    }  

}