force-app/main/default/objects/Account/fields/AccountLanguage__c.field-meta.xml
<CustomField>
    <fullName>AccountLanguage__c</fullName>
    <label>Account Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <default>true</default>
                <label>D</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LegalNature__c.field-meta.xml
<CustomField>
    <fullName>LegalNature__c</fullName>
    <label>Legal Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporation / Limited Company</fullName>
            </value>
            <value>
                <fullName>Limited Partnership</fullName>
            </value>
            <value>
                <fullName>Association / Foundation</fullName>
            </value>
            <value>
                <fullName>Individual Company</fullName>
            </value>
            <value>
                <fullName>Natural Entity (Private Person)</fullName>
            </value>
            <value>
                <fullName>Public Administration / Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TermsOfPayment__c.field-meta.xml
<CustomField>
    <fullName>TermsOfPayment__c</fullName>
    <label>Terms of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TermsOfPayment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/InternalAccount.recordType-meta.xml
<RecordType>
    <fullName>InternalAccount</fullName>
    <active>true</active>
    <description>Use this record type to create a BLC Unit</description>
    <label>Internal Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UnitRelevance__c.field-meta.xml
<CustomField>
    <fullName>UnitRelevance__c</fullName>
    <label>Unit Relevance</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BLC</fullName>
            </value>
            <value>
                <fullName>CY</fullName>
            </value>
            <value>
                <fullName>GBCH</fullName>
            </value>
            <value>
                <fullName>GBDE</fullName>
            </value>
            <value>
                <fullName>GBSGP</fullName>
            </value>
            <value>
                <fullName>GBUS</fullName>
            </value>
            <value>
                <fullName>HBC</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>HYS</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>VH</fullName>
            </value>
            <value>
                <fullName>XB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/LegalAccount__c.field-meta.xml
<CustomField>
    <fullName>LegalAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Legal Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cost Center</relationshipLabel>
    <relationshipName>CostCenter</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/PackageSortNr__c.field-meta.xml
<CustomField>
    <fullName>PackageSortNr__c</fullName>
    <label>Package Sort Nr.</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageSubType__c.field-meta.xml
<CustomField>
    <fullName>PackageSubType__c</fullName>
    <inlineHelpText>Manufaktur only for SVH</inlineHelpText>
    <label>Package Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkTime</fullName>
                <label>Work Time</label>
            </value>
            <value>
                <fullName>TravelTime</fullName>
                <label>Travel Time</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>3rdPartyCosts</fullName>
                <label>3rd Party Costs</label>
            </value>
            <value>
                <fullName>ProjectResourceCosts</fullName>
                <label>Project Resource Costs</label>
            </value>
            <value>
                <fullName>AbacusInbox</fullName>
                <label>Abacus Inbox</label>
            </value>
            <value>
                <fullName>Manufaktur</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>LicenseDirect</fullName>
                <label>License (Direct)</label>
            </value>
            <value>
                <fullName>LicenseProvision</fullName>
                <label>License (Provision)</label>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <formula>ProjectName__r.ProjectCostCenter__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Cost Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Attention: You should not add a package to a Project with Status = Closed</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>PackagesProjectName</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Internal Contract Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CostCenter__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectRateHour__c.field-meta.xml
<CustomField>
    <fullName>ProjectRateHour__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName =&quot;Internal&quot;,200,null)</defaultValue>
    <inlineHelpText>Internal Projects: CHF 200.00</inlineHelpText>
    <label>Project Rate (Hour)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/TermsOfPayment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <masterLabel>Terms of Payment</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestPackageSelector.cls
/**
 * Description: Unit test for PackageSelector
 * 
 * Note: Disactivate Process Builder "ProjectOwnerUpdateWithResponsible"
 */
@isTest
public class TestPackageSelector {

    @testSetup
    static void setupTestData() {

        Id acctRecTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('InternalAccount').getRecordTypeId();

        // Account acct = TestFactory.createAccount();
        Account acct = new Account(Name = TestFactory.NAME_ACC + Math.random());
        acct.recordTypeId = acctRecTypeId;
            acct.BillingStreet = 'Av. Del Parque 1';
            acct.BillingCity = 'Madrid';
            acct.BillingPostalCode = '28001';
            acct.BillingCountry = 'Spain';
            acct.LegalNature__c = 'Limited Partnership';
            acct.AccountLanguage__c = 'D';
            insert acct;

        CostCenter__c costC = TestFactory.createCostCenter(acct.Id);
        costC.LegalAccount__c = acct.Id;
        costC.Active__c = true;
        insert costC;

        Contact contact = TestFactory.createContact(acct.Id, costC.Id);
        // contact.UnitRelevance__c = 'GBFR';
        // contact.CostCenter__c = costC.Id;
        insert contact;

        Project__c project = TestFactory.createProject(acct.Id, contact.Id, costC.Id);
        project.TermsOfPayment__c = '1';
        project.ProjectRateHour__c = 110;
        project.ProjectCostCenter__c = costC.Id;
        insert project;

        // Create Packages
        List<Package__c> packages = new List<Package__c>();
        for (Integer i = 0; i < 5; i++) {
            String str_i = String.valueOf(i);
            packages.add(new Package__c(
                Name = 'Test Package ' + str_i,
                ProjectName__c = project.Id,
                PackageSubType__c = 'WorkTime',
                PackageSortNr__c = str_i
            ));
        }
        insert packages;
    }

    @isTest
    static void testSelectAll() {
        IPackageSelector selector = PackageSelector.newInstance();
        List<Package__c> results = selector.selectAll();

        System.assertEquals(5, results.size(), 'Should return 5 packages');
    }

    @isTest
    static void testSelectById() {
        List<Package__c> packages = [SELECT Id FROM Package__c LIMIT 5];
        Set<Id> ids = new Set<Id>();
        for (Package__c pkg : packages) {
            ids.add(pkg.Id);
        }

        IPackageSelector selector = PackageSelector.newInstance();
        List<Package__c> results = selector.selectById(ids);

        System.assertEquals(5, results.size(), 'Should return the packages with given ids');
    }

    @isTest
    static void testSelectByProjectId() {
        Project__c project = [SELECT Id FROM Project__c LIMIT 1];
        Set<Id> projectIds = new Set<Id>{project.Id};

        IPackageSelector selector = PackageSelector.newInstance();
        List<Package__c> results = selector.selectByProjectId(projectIds);

        System.assertNotEquals(0, results.size(), 'Should return packages for the given project id');
    }

    @isTest
    static void testSelectBySuperiorExcludedFields() {
        List<Package__c> packages = [SELECT Id FROM Package__c LIMIT 1];
        Set<Id> superiorIds = new Set<Id>{packages[0].Id};
        Set<String> excludedFields = new Set<String>{'Name'};

        IPackageSelector selector = PackageSelector.newInstance();
        List<Package__c> results = selector.selectBySuperiorExcludedFields(superiorIds, excludedFields);

        // System.assertNotEquals(0, results.size(), 'Should return packages excluding specified fields');
    }

    @isTest
    static void testSelectByProjectExcludedFields() {
        Project__c project = [SELECT Id FROM Project__c LIMIT 1];
        Set<Id> projectIds = new Set<Id>{project.Id};
        Set<String> excludedFields = new Set<String>{'Name'};

        IPackageSelector selector = PackageSelector.newInstance();
        List<Package__c> results = selector.selectByProjectExcludedFields(projectIds, excludedFields);

        System.assertNotEquals(0, results.size(), 'Should return packages excluding specified fields');
    }

    @isTest
    static void testSelectProjectStructure() {
        Project__c project = [SELECT Id FROM Project__c LIMIT 1];

        IPackageSelector selector = PackageSelector.newInstance();
        ProjectStructureBean result = selector.selectProjectStructure(project.Id, null, null);

        System.assertNotEquals(null, result, 'Project structure should be returned');
    }

    @isTest
    static void testSelectILVInfo() {
        Project__c project = [SELECT Id FROM Project__c LIMIT 1];

        IPackageSelector selector = PackageSelector.newInstance();
        ILVCreation result = selector.selectILVInfo(project.Id, null, null);

        System.assertNotEquals(null, result, 'ILV info should be returned');
    }

    @isTest
    static void testSelectFull() {
        Project__c project = [SELECT Id FROM Project__c LIMIT 1];
        PackageSelector.Params params = new PackageSelector.Params();
        params.projectId = project.Id;
        params.showTime = true;
        params.showExpense = true;
        params.showSupplierCosts = true;

        IPackageSelector selector = PackageSelector.newInstance();
        PackageSelector.Model model = selector.selectFull(params);

        System.assertNotEquals(null, model, 'Full model should be returned');
    }

}