force-app/main/default/objects/Account/fields/AccountLanguage__c.field-meta.xml
<CustomField>
    <fullName>AccountLanguage__c</fullName>
    <label>Account Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <default>true</default>
                <label>D</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LegalNature__c.field-meta.xml
<CustomField>
    <fullName>LegalNature__c</fullName>
    <label>Legal Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporation / Limited Company</fullName>
            </value>
            <value>
                <fullName>Limited Partnership</fullName>
            </value>
            <value>
                <fullName>Association / Foundation</fullName>
            </value>
            <value>
                <fullName>Individual Company</fullName>
            </value>
            <value>
                <fullName>Natural Entity (Private Person)</fullName>
            </value>
            <value>
                <fullName>Public Administration / Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TermsOfPayment__c.field-meta.xml
<CustomField>
    <fullName>TermsOfPayment__c</fullName>
    <label>Terms of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TermsOfPayment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/InternalAccount.recordType-meta.xml
<RecordType>
    <fullName>InternalAccount</fullName>
    <active>true</active>
    <description>Use this record type to create a BLC Unit</description>
    <label>Internal Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UnitRelevance__c.field-meta.xml
<CustomField>
    <fullName>UnitRelevance__c</fullName>
    <label>Unit Relevance</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BLC</fullName>
            </value>
            <value>
                <fullName>CY</fullName>
            </value>
            <value>
                <fullName>GBCH</fullName>
            </value>
            <value>
                <fullName>GBDE</fullName>
            </value>
            <value>
                <fullName>GBSGP</fullName>
            </value>
            <value>
                <fullName>GBUS</fullName>
            </value>
            <value>
                <fullName>HBC</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>HYS</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>VH</fullName>
            </value>
            <value>
                <fullName>XB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/LegalAccount__c.field-meta.xml
<CustomField>
    <fullName>LegalAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Legal Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cost Center</relationshipLabel>
    <relationshipName>CostCenter</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/FinanceAccount__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Account</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinanceAccount__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Finance Account</relationshipLabel>
    <relationshipName>FinanceAccount</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/FinanceAccountNr__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountNr__c</fullName>
    <label>Finance Account Nr.</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountLanguage__c.field-meta.xml
<CustomField>
    <fullName>AccountLanguage__c</fullName>
    <formula>CASE(TEXT(InvoiceReceiver__r.AccountLanguage__c),
 &apos;D&apos;, &apos;DE&apos;,
 &apos;E&apos;, &apos;EN&apos;,
 &apos;F&apos;, &apos;FR&apos;,
 &apos;I&apos;, &apos;IT&apos;,
 &apos;S&apos;, &apos;ES&apos;,
      &apos;EN&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/FinanceDate__c.field-meta.xml
<CustomField>
    <fullName>FinanceDate__c</fullName>
    <label>Finance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceTitle__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTitle__c</fullName>
    <label>Invoice Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PeriodFrom__c.field-meta.xml
<CustomField>
    <fullName>PeriodFrom__c</fullName>
    <label>Period (From)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PeriodUntil__c.field-meta.xml
<CustomField>
    <fullName>PeriodUntil__c</fullName>
    <label>Period (Until)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TermsOfPayment__c.field-meta.xml
<CustomField>
    <fullName>TermsOfPayment__c</fullName>
    <description>16.12.2016, ary: Neues Feld gemacht als Pickliste. Dieses Feld muss aus dem Apex raus, damit es gelöscht werden kann.</description>
    <label>Terms of Payment_do_not_use</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/InvoicePos__c/InvoicePos__c.object-meta.xml
<CustomObject>
    <label>Invoice Pos</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Invoice Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePos__c/fields/FinanceAccount__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Account</label>
    <referenceTo>FinanceAccount__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/FinanceAccountNr__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountNr__c</fullName>
    <label>Finance Account Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageSubType__c.field-meta.xml
<CustomField>
    <fullName>PackageSubType__c</fullName>
    <label>Package Sub-Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/PackageSubType__c.field-meta.xml
<CustomField>
    <fullName>PackageSubType__c</fullName>
    <inlineHelpText>Manufaktur only for SVH</inlineHelpText>
    <label>Package Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkTime</fullName>
                <label>Work Time</label>
            </value>
            <value>
                <fullName>TravelTime</fullName>
                <label>Travel Time</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>3rdPartyCosts</fullName>
                <label>3rd Party Costs</label>
            </value>
            <value>
                <fullName>ProjectResourceCosts</fullName>
                <label>Project Resource Costs</label>
            </value>
            <value>
                <fullName>AbacusInbox</fullName>
                <label>Abacus Inbox</label>
            </value>
            <value>
                <fullName>Manufaktur</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>LicenseDirect</fullName>
                <label>License (Direct)</label>
            </value>
            <value>
                <fullName>LicenseProvision</fullName>
                <label>License (Provision)</label>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <formula>ProjectName__r.ProjectCostCenter__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Cost Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Attention: You should not add a package to a Project with Status = Closed</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>PackagesProjectName</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Internal Contract Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CostCenter__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectRateHour__c.field-meta.xml
<CustomField>
    <fullName>ProjectRateHour__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName =&quot;Internal&quot;,200,null)</defaultValue>
    <inlineHelpText>Internal Projects: CHF 200.00</inlineHelpText>
    <label>Project Rate (Hour)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/TermsOfPayment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <masterLabel>Terms of Payment</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestInvoiceController.cls
/**
 * Description: Unit test for InvoiceController
 * 
 * Note: Disactivate Process Builder "ProjectOwnerUpdateWithResponsible"
 */
@IsTest
private class TestInvoiceController {

  @IsTest
  private static void callingGetProjectStructureShouldCallService() {

    // Create Mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();

    // Given
    Id projectId = fflib_IDGenerator.generate(Project__c.SObjectType);
    Mocks.InvoiceService mockInvoiceService = new Mocks.InvoiceService(mocks);
    Application.Service.setMock(IInvoiceService.class, mockInvoiceService);

    // When
    InvoiceController.getProjectStructure(projectId, '2016-12-01', '2016-12-01');

    // Then
    ((IInvoiceService) mocks.verify(mockInvoiceService)).getProjectStructure(projectId, '2016-12-01', '2016-12-01');

  }

  @IsTest
  private static void callingCancelShouldCallService() {

    // Create Mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();

    // Given
    Id invoiceId = fflib_IDGenerator.generate(Invoice__c.SOBjectType);
    Mocks.InvoiceService mockInvoiceService = new Mocks.InvoiceService(mocks);
    mocks.startStubbing();
    mocks.when(mockInvoiceService.cancel(invoiceId)).thenReturn(new Invoice__c(Id = fflib_IDGenerator.generate(Invoice__c.SOBjectType)));
    mocks.stopStubbing();
    Application.Service.setMock(IInvoiceService.class, mockInvoiceService);

    // When
    InvoiceController.cancel(invoiceId);

    // Then
    ((IInvoiceService) mocks.verify(mockInvoiceService)).cancel(invoiceId);

  }


  @IsTest
  private static void callingSaveShouldCallService() {

    // Create Mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();

    // Given
    Mocks.InvoiceService mockInvoiceService = new Mocks.InvoiceService(mocks);
    Application.Service.setMock(IInvoiceService.class, mockInvoiceService);

    // When
    InvoiceController.save(new Invoice__c(), new List<Package__c>(), new List<InvoicePos__c>());

    // Then
    // ((IInvoiceService) mocks.verify(mockInvoiceService)).save(new Invoice__c(), new List<Package__c>(), new List<InvoicePos__c>());

  }

  @IsTest
  private static void saveValidationTests() {

    Id projectId = fflib_IDGenerator.generate(Project__c.SObjectType);

    Id acctRecTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('InternalAccount').getRecordTypeId();
    Id pkgRecTypeId =  Schema.SObjectType.Package__c.getRecordTypeInfosByDeveloperName().get('Expense').getRecordTypeId();

    // Account acct = TestFactory.createAccount();
    Account acct = new Account(Name = TestFactory.NAME_ACC + Math.random());
    acct.recordTypeId = acctRecTypeId;
		acct.BillingStreet = 'Queen St 1';
		acct.BillingCity = 'Wollongong';
		//acc.BillingState = 'NSW';
		acct.BillingPostalCode = '2046';
		acct.BillingCountry = 'Spain';
    acct.LegalNature__c = 'Limited Partnership';
    acct.AccountLanguage__c = 'D';
		insert acct;

    CostCenter__c costC = TestFactory.createCostCenter(acct.Id);
    costC.LegalAccount__c = acct.Id;
    costC.Active__c = true;
    insert costC;

    Contact contact = TestFactory.createContact(acct.Id, costC.Id);
    // contact.UnitRelevance__c = 'GBFR';
    // contact.CostCenter__c = costC.Id;
    insert contact;

    Project__c project = TestFactory.createProject(acct.Id, contact.Id, costC.Id);
    project.TermsOfPayment__c = '1';
    project.ProjectRateHour__c = 110;
    project.ProjectCostCenter__c = costC.Id;
    insert project;
    System.debug('---saveValidationTests--- project: '+project);
    System.debug('---saveValidationTests--- SELECT project: '+[SELECT Id, Name, ValCountHasInvoiceDraft__c FROM Project__c]);


    Package__c pkg = TestFactory.createService(project.Id);
    pkg.PackageSubType__c = 'Expense';
    pkg.RecordTypeId = pkgRecTypeId;
    insert pkg;
    List<Package__c> lstPkg = new List<Package__c>();
    lstPkg.add(pkg);

    Invoice__c invoice = new Invoice__c();
    invoice.FinanceDate__c = Date.newInstance(2023, 10, 6);
    invoice.PeriodFrom__c = Date.newInstance(2023, 09, 1);
    invoice.InvoiceTitle__c = 'Title';
    invoice.ProjectName__c = project.Id;
    invoice.InvoiceDate__c = Date.newInstance(2023, 10, 26);
    invoice.PeriodUntil__c = Date.newInstance(2023, 09, 30);

    FinanceAccount__c fa = new FinanceAccount__c(
        // Id = fflib_IDGenerator.generate(FinanceAccount__c.SObjectType),
        Active__c = true,
        FinanceAccountNr__c = '001',
        FinanceClearingNr__c = '1001',
        CostCenter__c = project.ProjectCostCenter__c,
        TypeName__c = 'Expense',
        TypeName2__c = 'Expense'
    );
    insert fa;

    InvoicePos__c invPos = new InvoicePos__c();
    invPos.ShowInvoiceText__c = false;
    // invPos.InvoicePositionText__c = ' ';
    invPos.ShowPositionAmount__c = false;
    invPos.PackageType__c = 'Expense';
    invPos.ShowPosition__c = true;
    // invPos.Id = 'a0P7Y00000A6bviUAB';
    invPos.InvoicePositionAmount__c = 100;
    invPos.PackageName__c = pkg.Id;

    List<InvoicePos__c> invPosLst = new List<InvoicePos__c>();
    invPosLst.add(invPos);

    test.startTest();
      try {
        InvoiceController.save(invoice, lstPkg, new List<InvoicePos__c>());
      }
      catch (Exception ex) {
        System.debug('----All OK---- Invoice Validation');
      }
    test.stopTest();
    
    try {
      invoice.InvoiceTitle__c = 'Rechnung';
      InvoiceController.save(invoice, lstPkg, invPosLst);
    }
    catch (Exception ex) {
      System.debug('----All OK----Invoice Position Validation');
    }

  }
}