force-app/main/default/objects/Account/fields/AccountManager__c.field-meta.xml
<CustomField>
    <fullName>AccountManager__c</fullName>
    <label>Account Manager</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerActual__c.field-meta.xml
<CustomField>
    <fullName>CustomerActual__c</fullName>
    <label>Customer (Actual)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Deputy__c.field-meta.xml
<CustomField>
    <fullName>Deputy__c</fullName>
    <description>Wird nur noch durch den UR Trigger von einer Löschung verhindert. 26.03.2016, ary</description>
    <label>Deputy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Network</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AccountManager__c.field-meta.xml
<CustomField>
    <fullName>AccountManager__c</fullName>
    <formula>Account.AccountManager__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CustomerActual__c.field-meta.xml
<CustomField>
    <fullName>CustomerActual__c</fullName>
    <formula>Account.CustomerActual__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer (Actual)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <formula>Account.Supplier__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UnitRelation__c/UnitRelation__c.object-meta.xml
<CustomObject>
    <label>Unit Relation</label>
    <nameField>
        <displayFormat>UR-{000000}</displayFormat>
        <label>Unit Relation Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Segmentations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UnitRelation__c/fields/AccountManager__c.field-meta.xml
<CustomField>
    <fullName>AccountManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Unit Relations (Account Manager)</relationshipLabel>
    <relationshipName>AccountManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitRelation__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actual</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UnitRelation__c/fields/Deputy__c.field-meta.xml
<CustomField>
    <fullName>Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deputy</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Unit Relations (Deputy)</relationshipLabel>
    <relationshipName>Deputy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitRelation__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Network</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UnitRelation__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Supplier</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountSummary.cls
public with sharing class AccountSummary extends CommonSummary
{
	/**
	*	@description Generates an instance to be used for summary run.
	*/
	public static AccountSummary getInstance()
	{
		CommonSummary.ChildInfo aUnitRelationInfo = new CommonSummary.ChildInfo('Segmentations__r', new List<String>{'Id', 'Customer__c',
				'Supplier__c', 'Partner__c', 'AccountManager__c', 'Deputy__c', 'RecordType.Name', 'AccountManager__r.FirstName',
				'AccountManager__r.LastName', 'Deputy__r.FirstName', 'Deputy__r.LastName'}, null);
		return new AccountSummary(null, new List<CommonSummary.ChildInfo>{aUnitRelationInfo});
	}
	
	/**
	*	@description basic constructor.
	*/
	private AccountSummary(al.ConditionGroup theParentConditions, List<ChildInfo> theChildInfoList)
	{
		super('Account', null, theParentConditions, theChildInfoList);
	}
	
	/**
	*	@description 
	*/
	protected override sObject performCalculation(sObject theParent, Map<String, List<sObject>> theChildMap)
	{
		Account aResult = new Account(Id = theParent.Id);
		Map<String, Set<String>> aFieldsMapping = new Map<String, Set<String>>();
		for (String aField: new Set<String>{'CustomerActual__c', 'Supplier__c', 'Partner__c', 'AccountManager__c', 'Deputy__c'})
		{
			aFieldsMapping.put(aField, new Set<String>());
		}
		List<sObject> anUnitiChildren = theChildMap.get('Segmentations__r');
		if (anUnitiChildren != null)
		{
			for (UnitRelation__c aRel: (List<UnitRelation__c>) anUnitiChildren)
			{
				if (aRel.Customer__c == 'Actual')
				{
					aFieldsMapping.get('CustomerActual__c').add(aRel.RecordType.Name);
				}
				if (aRel.Supplier__c == true)
				{
					aFieldsMapping.get('Supplier__c').add(aRel.RecordType.Name);
				}
				if (aRel.Partner__c == true)
				{
					aFieldsMapping.get('Partner__c').add(aRel.RecordType.Name);
				}
				if (aRel.AccountManager__c != null)
				{
					Contact anAccManager = aRel.AccountManager__r;
					aFieldsMapping.get('AccountManager__c').add(getShortName(anAccManager));
				}
				if (aRel.Deputy__c != null)
				{
					Contact aDeputy = aRel.Deputy__r;
					aFieldsMapping.get('Deputy__c').add(getShortName(aDeputy));
				}
			}
		}
		for (String aField:aFieldsMapping.keySet())
		{
			Set<String> aValues = aFieldsMapping.get(aField);
			List<String> aValueList = new List<String>();
			aValueList.addAll(aValues);
			aValueList.sort();
			String aValue = String.join(aValueList, '; ');
			aResult.put(aField, aValue);
		}
		return aResult;
	}
	
	/**
	*	@description Returns an alias name of contact.
	*/
	public static String getShortName(Contact theContact)
	{
		String aShortName = (theContact.FirstName == null ? '' :(theContact.FirstName.substring(0, 1).toUpperCase())) + theContact.LastName;
		aShortName = aShortName.length() > 8 ? aShortName.substring(0, 8) : aShortName;
		return aShortName;
	}
}