force-app/main/default/objects/Account/fields/AccountManager__c.field-meta.xml
<CustomField>
    <fullName>AccountManager__c</fullName>
    <label>Account Manager</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Deputy__c.field-meta.xml
<CustomField>
    <fullName>Deputy__c</fullName>
    <description>Wird nur noch durch den UR Trigger von einer Löschung verhindert. 26.03.2016, ary</description>
    <label>Deputy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Network</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UnitRelation__c/UnitRelation__c.object-meta.xml
<CustomObject>
    <label>Unit Relation</label>
    <nameField>
        <displayFormat>UR-{000000}</displayFormat>
        <label>Unit Relation Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Segmentations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UnitRelation__c/fields/AccountManager__c.field-meta.xml
<CustomField>
    <fullName>AccountManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Unit Relations (Account Manager)</relationshipLabel>
    <relationshipName>AccountManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitRelation__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actual</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UnitRelation__c/fields/Deputy__c.field-meta.xml
<CustomField>
    <fullName>Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deputy</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Contact</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Unit Relations (Deputy)</relationshipLabel>
    <relationshipName>Deputy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitRelation__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Network</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UnitRelation__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Supplier</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UnitRelationTriggerHandler.cls
/**
	Trigger handler for UnitRelation__c object
	
	@copyright PARX
	@author akr
*/
public with sharing class UnitRelationTriggerHandler extends TriggerTemplateV2.TriggerHandlerAdapter
{
	public override void onBeforeInsert (List<sObject> newList)
	{
		//validates if unit relation can be added without duplication
		validateAccountUpdate(newList, null);
	}
	
	public override void onBeforeUpdate (List<sObject> newList, Map<Id, sObject> newMap, List<sObject> oldList, Map<Id, sObject> oldMap)
	{
		//validates if unit relation can be added without duplication
		validateAccountUpdate(newList, (Map<Id, UnitRelation__c>) oldMap);
	}
	
	public override void  onAfterInsert (List<sObject> newList, Map<Id, sObject> newMap)
	{
		//Update related accounts with new Unit Relations data
		updateAccounts(newList, null);
	}
	
	public override void  onAfterUpdate (List<sObject> newList, Map<Id, sObject> newMap, List<sObject> oldList, Map<Id, sObject> oldMap)
	{
		//Update related accounts with new Unit Relations data
		updateAccounts(newList, (Map<Id, UnitRelation__c>) oldMap);
	}
	
	public override void  onAfterDelete (List<sObject> oldList, Map<Id, sObject> oldMap)
	{
		//Update related accounts with new Unit Relations data
		updateAccounts(null, (Map<Id, UnitRelation__c>) oldMap);
	}

	public override void  onAfterUndelete (List<sObject> newList, Map<Id, sObject> newMap)
	{
		//Update related accounts with new Unit Relations data
		updateAccounts(newList, null);
	}
	
	/**
		Validates if unit relation can be added without duplication
	*/
	public void validateAccountUpdate(List<UnitRelation__c> theNewValuesList, Map<Id, UnitRelation__c> theOldValuesMap)
	{
		Set<Id> anAccSet = new Set<Id>();
		Set<Id> anRTSet = new Set<Id>();
		Set<Id> aNewUnits = theOldValuesMap == null ? new Set<Id>() : theOldValuesMap.keySet();
		for (UnitRelation__c anUnit: theNewValuesList)
		{
			if (anUnit.Account__c != null)
			{
				anAccSet.add(anUnit.Account__c);
				anRTSet.add(anUnit.RecordTypeId);
			}
		}
		List<UnitRelation__c> anExistingUnitRelations = [SELECT Id, Name, RecordTypeId, Account__c FROM UnitRelation__c
				WHERE Account__c IN : anAccSet AND RecordTypeId IN :anRTSet AND Id NOT IN :aNewUnits];
		Map<String, UnitRelation__c> aRelRes = new Map<String, UnitRelation__c>();
		for (UnitRelation__c aRel: anExistingUnitRelations)
		{
			aRelRes.put(aRel.Account__c + '-' + aRel.RecordTypeId, aRel);
		}
		Map<Id, RecordType> aRTList = new Map<Id, RecordType>([SELECT Id, Name FROM RecordType WHERE Id IN :anRTSet]);
		for (UnitRelation__c anUnit: theNewValuesList)
		{
			UnitRelation__c aCopyRes = aRelRes.get(anUnit.Account__c + '-' + anUnit.RecordTypeId);
			if (aCopyRes != null)
			{
				anUnit.addError('For the Unit' + aRTList.get(anUnit.RecordTypeId).Name + ' a record already exist on this Account'
						+ (aCopyRes.Id == null ? '' : ': <a href="/' + aCopyRes.Id + '">' + aCopyRes.Name + '</a>'), false);
			} else
			{
				aRelRes.put(anUnit.Account__c + '-' + anUnit.RecordTypeId, aCopyRes);
			}
		}
	}
	
	/**
		Updates related accounts with new Unit Relations data
	*/
	private void updateAccounts(List<UnitRelation__c> theNewValuesList, Map<Id, UnitRelation__c> theOldValuesMap)
	{
		Set<Id> anAccIdSet = Utils.getModifiedObjectParents(new List<String>{'AccountManager__c', 'Account__c', 'Deputy__c', 'RecordTypeId', 'Customer__c',
					 'Supplier__c', 'Partner__c', 'Customer__c'}, 'Account__c', theNewValuesList, theOldValuesMap);
		AccountSummary.getInstance().updateObjects(anAccIdSet);
	}
}