force-app/main/default/objects/Account/fields/ESRAccountNr__c.field-meta.xml
<CustomField>
    <fullName>ESRAccountNr__c</fullName>
    <label>ESR Account Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ESRMergentNr__c.field-meta.xml
<CustomField>
    <fullName>ESRMergentNr__c</fullName>
    <label>ESR Mergent Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastInvoiceNr__c.field-meta.xml
<CustomField>
    <fullName>LastInvoiceNr__c</fullName>
    <label>Last Invoice Nr.</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/LegalCode__c.field-meta.xml
<CustomField>
    <fullName>LegalCode__c</fullName>
    <label>Legal Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/ILVPos__c.object-meta.xml
<CustomObject>
    <label>ILV Pos</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>ILV Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ILV Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILVPos__c/fields/ILVPositionDate__c.field-meta.xml
<CustomField>
    <fullName>ILVPositionDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>ILV Position Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/InvoiceName__c.field-meta.xml
<CustomField>
    <fullName>InvoiceName__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/InvoiceStatus__c.field-meta.xml
<CustomField>
    <fullName>InvoiceStatus__c</fullName>
    <formula>TEXT( InvoiceName__r.InvoiceStatus__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/RelevantToRevenue__c.field-meta.xml
<CustomField>
    <fullName>RelevantToRevenue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Relevant to Revenue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AbacusTransfer__c.field-meta.xml
<CustomField>
    <fullName>AbacusTransfer__c</fullName>
    <label>Abacus Transfer</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingViaCompany__c.field-meta.xml
<CustomField>
    <fullName>BillingViaCompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing via (Company)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Billing via (Company))</relationshipLabel>
    <relationshipName>InvoicesBillingViaCompany</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CancellationDate__c.field-meta.xml
<CustomField>
    <fullName>CancellationDate__c</fullName>
    <inlineHelpText>Date of the corresponding Cancellation Invoice if this invoice has been cancelled</inlineHelpText>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CancellationInvoiceRelation__c.field-meta.xml
<CustomField>
    <fullName>CancellationInvoiceRelation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cancellation - Invoice Relation</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Cancellation</relationshipLabel>
    <relationshipName>Cancellation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ESRAccountNr__c.field-meta.xml
<CustomField>
    <fullName>ESRAccountNr__c</fullName>
    <label>ESR Account Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ESRCodeLine__c.field-meta.xml
<CustomField>
    <fullName>ESRCodeLine__c</fullName>
    <label>ESR Code Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ESRFormatted__c.field-meta.xml
<CustomField>
    <fullName>ESRFormatted__c</fullName>
    <label>ESR Formatted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ESRMergentNr__c.field-meta.xml
<CustomField>
    <fullName>ESRMergentNr__c</fullName>
    <label>ESR Mergent Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ESRUnformatted__c.field-meta.xml
<CustomField>
    <fullName>ESRUnformatted__c</fullName>
    <label>ESR Unformatted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDocumentNr__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDocumentNr__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Document Nr.</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceInvalid__c.field-meta.xml
<CustomField>
    <fullName>InvoiceInvalid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Invalid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceSentDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceSentDate__c</fullName>
    <label>Invoice Print Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceStatus__c.field-meta.xml
<CustomField>
    <fullName>InvoiceStatus__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceTotalAmountGross__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTotalAmountGross__c</fullName>
    <formula>InvoiceTotalAmountNet__c + InvoiceVATAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice - Total Amount Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceValutaDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceValutaDate__c</fullName>
    <description>Dieses Feld wird über eine manuelle Schnittstelle aus Abacus befüllt.</description>
    <label>Invoice Last Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PeriodFrom__c.field-meta.xml
<CustomField>
    <fullName>PeriodFrom__c</fullName>
    <label>Period (From)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PeriodUntil__c.field-meta.xml
<CustomField>
    <fullName>PeriodUntil__c</fullName>
    <label>Period (Until)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ValHasAttachment__c.field-meta.xml
<CustomField>
    <fullName>ValHasAttachment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ValHasAttachment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Cancellation.recordType-meta.xml
<RecordType>
    <fullName>Cancellation</fullName>
    <active>true</active>
    <label>Cancellation</label>
</RecordType>

force-app/main/default/objects/Invoice__c/recordTypes/Credit.recordType-meta.xml
<RecordType>
    <fullName>Credit</fullName>
    <active>false</active>
    <description>15.12.2017, ary: Entscheid Finance, Gutschriften werden als -Minus Rechnungen ins Abacus übertragen.</description>
    <label>Credit</label>
</RecordType>

force-app/main/default/objects/Invoice__c/recordTypes/ILV.recordType-meta.xml
<RecordType>
    <fullName>ILV</fullName>
    <active>true</active>
    <label>ILV</label>
</RecordType>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/InvoicePos__c/InvoicePos__c.object-meta.xml
<CustomObject>
    <label>Invoice Pos</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Invoice Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePos__c/fields/InvoiceName__c.field-meta.xml
<CustomField>
    <fullName>InvoiceName__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/InvoicePositionAmount__c.field-meta.xml
<CustomField>
    <fullName>InvoicePositionAmount__c</fullName>
    <label>Invoice Position - Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/InvoicePositionDate__c.field-meta.xml
<CustomField>
    <fullName>InvoicePositionDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Invoice Position Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/InvoicePositionSuperior__c.field-meta.xml
<CustomField>
    <fullName>InvoicePositionSuperior__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Position (Superior)</label>
    <referenceTo>InvoicePos__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>Invoice_Pos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/InvoiceStatus__c.field-meta.xml
<CustomField>
    <fullName>InvoiceStatus__c</fullName>
    <formula>TEXT(InvoiceName__r.InvoiceStatus__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/classes/Invoice.cls
public with sharing class Invoice extends fflib_SObjectDomain
    implements IInvoice {

    public static final String STATUS_APPROVAL = 'Approval';
    public static final String STATUS_DRAFT = 'Draft';
    public static final String STATUS_READY = 'Ready';
    public static final String STATUS_SENT = 'Sent';
    public static final String RECORD_TYPE_ILV = 'ILV';
    public static final String RECORD_TYPE_INVOICE = 'Invoice';
    public static final String RECORD_TYPE_CREDIT = 'Credit';
    public static final String RECORD_TYPE_CANCELLATION = 'Cancellation';

    public static Map<Id, String> RecordTypeMap = new  Map<Id, String>(
        Utils.getRecordTypeInfosName('Invoice__c')
    );

    public static IInvoice newInstance(List<Invoice__c> records) {
        return (IInvoice) Application.Domain.newInstance(records);
    }

    public Invoice(List<Invoice__c> records) {
        super(records);
    }

    public override void onBeforeInsert() {
        markRevenueRelevant();
        callInheritedFieldValue(false);

        System.debug('---Invoice.onBeforeInsert-------------');
        callUpdateExchangeRate(null);
        updateESRs(null);
    }

    public override void onBeforeUpdate(Map<Id,SObject> oldRecords) {
        markRevenueRelevant();
        callInheritedFieldValue(false);
        System.debug('---Invoice.onBeforeUpdate-------------');
        callUpdateExchangeRate(oldRecords);
        updateESRs(oldRecords);
    }

    public override void onAfterInsert() {
        generateInvoiceNr();
        callParentUpdate(null);
    }

    public override void onAfterUpdate(Map<Id,SObject> oldRecords) {
        generateInvoiceNr();
        replicateFields(oldRecords);
        callParentUpdate(oldRecords);
    }

    public override void onBeforeDelete() {
        controlDeletion();
        clearCancellationDate();
    }

    public void save(fflib_ISObjectUnitOfWork uow, String recordType) {

        for (Invoice__c inv: (List<Invoice__c>) records) {
            if (inv.Id != null) {
                uow.registerDirty(inv);
            } else {
                inv.RecordTypeId = Utils.getRecordTypeIdByDevName('Invoice__c', recordType);
                uow.registerNew(inv);
            }
        }

    }

    public void updateESRs(Map<Id,SObject> oldRecords){
        for (Invoice__c i : (List<Invoice__c>) records) {
            //do we have values in the ESR fields
            if(i.ESRMergentNr__c != null && i.InvoiceDocumentNr__c != null && i.ESRAccountNr__c  != null && (System.Test.isRunningTest()  || i.InvoiceTotalAmountGross__c != null)){
                //these are new records so create the ESR
                if(oldRecords == null){
                    updateESR(i);
                } else {
                    Invoice__c inv = (Invoice__c)oldRecords.get(i.Id);
                    //have any of the ESR fields changed? if so, update the ESR
                    if(i.ESRMergentNr__c != inv.ESRMergentNr__c || i.InvoiceDocumentNr__c != inv.InvoiceDocumentNr__c || i.ESRAccountNr__c != inv.ESRAccountNr__c || i.InvoiceTotalAmountGross__c != inv.InvoiceTotalAmountGross__c){
                        updateESR(i);
                    }
                }
            }
        }
    }

    public void updateESR(Invoice__c inv){
        System.debug('---Invoice.updateESR--- inv: ' + inv);
        //we are using a isRunningTest call to let us supply the value to the InvoiceTotalAmountGross__c formula field - ds
        //ESR Unformatted
        inv.ESRUnformatted__c = EsrUtil.getESR(inv.ESRAccountNr__c, inv.ESRMergentNr__c, inv.InvoiceDocumentNr__c, (System.Test.isRunningTest() ? 123 : inv.InvoiceTotalAmountGross__c), EsrUtil.EsrFormat.UNFORMATTED);
        //ESR Formatted
        inv.ESRFormatted__c = EsrUtil.getESR(inv.ESRAccountNr__c, inv.ESRMergentNr__c, inv.InvoiceDocumentNr__c, (System.Test.isRunningTest() ? 123 : inv.InvoiceTotalAmountGross__c), EsrUtil.EsrFormat.FORMATTED);
        //ESR Code Line
        inv.ESRCodeLine__c = EsrUtil.getESR(inv.ESRAccountNr__c, inv.ESRMergentNr__c, inv.InvoiceDocumentNr__c, (System.Test.isRunningTest() ? 123 : inv.InvoiceTotalAmountGross__c), EsrUtil.EsrFormat.CODE_LINE);
    }

    private void controlDeletion() {
        List<Field__mdt> fields = FieldMDTSelector.newInstance().selectDeletionControlFields(this.getSObjectType().getDescribe().getName());
        IFieldMDT fieldDomain = FieldMDT.newInstance(fields);
        fieldDomain.controlDeletion(records);
    }

    @TestVisible
    private void clearCancellationDate() {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        Id cancelRecordTypeId = Utils.getRecordTypeIdByDevName('Invoice__c', RECORD_TYPE_CANCELLATION);

        for (Invoice__c inv: (List<Invoice__c>) records) {

            if (cancelRecordTypeId == inv.RecordTypeId) {
                Invoice__c cancelInvRelated = new Invoice__c(
                    Id = inv.CancellationInvoiceRelation__c,
                    CancellationDate__c = null
                );
                uow.registerDirty(cancelInvRelated);
            }

        }

        uow.commitWork();
    }

    @TestVisible
    private void callParentUpdate(Map<Id,SObject> oldRecords) {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        List<ParentObjectUpdate__mdt> pous = ParentObjectUpdateMDTSelector.newInstance().selectBySourceObj(this.getSObjectType().getDescribe().getName());
        IParentObjectUpdateMDT pouDomain = ParentObjectUpdateMDT.newInstance(pous);

        pouDomain.go(uow, records, oldRecords);
        uow.commitWork();
    }

    @TestVisible
    private void callUpdateExchangeRate(Map<Id,SObject> oldRecords) {
        List<Object__mdt> objs = ObjectMDTSelector.newInstance().selectCurrencyFields(this.getSObjectType().getDescribe().getName());

        System.debug('---Invoice.callUpdateExchangeRate-------------');
        //if we have currency fields and currency conversion is endabled then update
        if(objs.size() > 0 && objs[0].Fields__r != null){
            IFieldMDT fieldDomain = FieldMDT.newInstance(objs[0].Fields__r);
            fieldDomain.updateExchangeRate(records, oldRecords);
        }
    }

    @TestVisible
    private void callInheritedFieldValue(Boolean isUpdate) {
        List<InheritedFieldValue__mdt> inheritedFValues = InheritedFieldValueMDTSelector.newInstance().selectByTargetObj(this.getSObjectType().getDescribe().getName());
        IInheritedFieldValueMDT inheritedFVDomain = InheritedFieldValueMDT.newInstance(inheritedFValues);

        if (isUpdate) {
            fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
            inheritedFVDomain.go(uow, records);
            uow.commitWork();
        } else {
            inheritedFVDomain.go(null, records);
        }

    }

    private void generateInvoiceNr() {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        Map<Id, Invoice__c> invoices = new Map<Id, Invoice__c>();
        for (Invoice__c i : (List<Invoice__c>) records) {
            invoices.put(i.Id, i);
        }

        Set<String> related = new Set<String> {
            'BillingViaCompany__r.LegalCode__c',
                'BillingViaCompany__r.LastInvoiceNr__c',
                'RecordType.Name'
        };

        List<Invoice__c> invoicesAccount = InvoiceSelector.newInstance().selectWithRelated(invoices.keySet(), related);

        for (Invoice__c i : invoicesAccount) {
            i.InvoiceStatus__c = Picklist.get(Invoice__c.InvoiceStatus__c, i.InvoiceStatus__c);

            if (i.InvoiceStatus__c != STATUS_DRAFT  && i.InvoiceStatus__c != STATUS_APPROVAL && i.InvoiceDocumentNr__c == null && i.RecordType.Name != RECORD_TYPE_ILV) {
                Account a = i.BillingViaCompany__r;
                a.LastInvoiceNr__c = a.LastInvoiceNr__c + 1;
                i.InvoiceDocumentNr__c = (a.LegalCode__c * 1000000) + (a.LastInvoiceNr__c);
                uow.registerDirty(i);
                uow.registerDirty(a);
            }
        }

        uow.commitWork();
    }

    @TestVisible
    private void markRevenueRelevant() {
        Map<Id, Schema.RecordTypeInfo> recordsType = Invoice__c.sObjectType.getDescribe().getRecordTypeInfosById();

        for (Invoice__c i : (List<Invoice__c>) records) {
            String rtName = RecordTypeMap.get(i.RecordTypeId);
            Boolean isRecordTypeOk = rtName.containsIgnoreCase(RECORD_TYPE_INVOICE) || rtName.containsIgnoreCase(RECORD_TYPE_CREDIT) || rtName.containsIgnoreCase(RECORD_TYPE_ILV);

            String status = Picklist.get(Invoice__c.InvoiceStatus__c, i.InvoiceStatus__c);
            Boolean isStatusOk = status == STATUS_READY || status == STATUS_SENT || status == STATUS_APPROVAL;

            Boolean isValid = i.CancellationDate__c == null && i.InvoiceInvalid__c == false;

            if (isRecordTypeOk && isStatusOk && isValid) {
                i.RelevantToRevenue__c = true;
            } else {
                i.RelevantToRevenue__c = false;
            }
        }

    }

    @TestVisible
    private void replicateFields(Map<Id,SObject> oldRecords) {

        for (Invoice__c i : (List<Invoice__c>) records) {
            Invoice__c old = (Invoice__c) oldRecords.get(i.Id);
            Boolean isRevenueChanged = i.RelevantToRevenue__c != old.RelevantToRevenue__c;
            Boolean isDateChanged = i.InvoiceDate__c != old.InvoiceDate__c;

            if (isRevenueChanged || isDateChanged) {
                fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
                Set<Id> ids = new Set<Id>{i.Id};
                List<InvoicePos__c> invoicesPos = InvoicePositionSelector.newInstance().selectByInvoice(ids);
                List<ILVPos__c> ilvsPos = ILVPosSelector.newInstance().selectByInvoice(ids);

                for (InvoicePos__c iPos : invoicesPos) {
                    if (isRevenueChanged) iPos.RelevantToRevenue__c = i.RelevantToRevenue__c;
                    if (isDateChanged) iPos.InvoicePositionDate__c = i.InvoiceDate__c;

                    uow.registerDirty(iPos);
                }

                for (ILVPos__c ilv : ilvsPos) {
                    if (isRevenueChanged) ilv.RelevantToRevenue__c = i.RelevantToRevenue__c;
                    if (isDateChanged) ilv.ILVPositionDate__c = i.InvoiceDate__c;

                    uow.registerDirty(ilv);
                }

                uow.commitWork();
            }

        }

    }

    public List<Invoice__c> cancel(fflib_ISObjectUnitOfWork uow) {
        List<Invoice__c> cancelled = new List<Invoice__c>();
        Map<Id, Invoice__c> invMap = new Map<Id, Invoice__c>();

        for (Invoice__c i : (List<Invoice__c>) records) {
            Invoice__c ic = i.clone(false, true);
            ic.RecordTypeId = Utils.getRecordTypeIdByDevName('Invoice__c', RECORD_TYPE_CANCELLATION);
            ic.InvoiceStatus__c = STATUS_DRAFT;
            ic.AbacusTransfer__c = null;
            ic.InvoiceDate__c = Date.today();
            ic.InvoiceDocumentNr__c = null;
            ic.InvoiceSentDate__c = null;
            ic.InvoiceValutaDate__c = null;
            ic.CancellationInvoiceRelation__c = i.Id;
            ic.PeriodFrom__c = i.PeriodFrom__c;
            ic.PeriodUntil__c = i.PeriodUntil__c;

            uow.registerNew(ic);
            cancelled.add(ic);
            invMap.put(i.Id, ic);
        }

        List<InvoicePos__c> invPoss = InvoicePositionSelector.newInstance().selectByInvoice(invMap.keySet());
        Map<Id, InvoicePos__c> possMap = new Map<Id, InvoicePos__c>();
/*
        for (InvoicePos__c pos: invPoss) {
            InvoicePos__c posClone = pos.clone(false, true);
            posClone.InvoicePositionAmount__c = -pos.InvoicePositionAmount__c;
            uow.registerNew(posClone, InvoicePos__c.InvoiceName__c, invMap.get(pos.InvoiceName__c));
            possMap.put(pos.Id, posClone);
        }

        uow.commitWork();

        fflib_ISObjectUnitOfWork uowPos = Application.UnitOfWork.newInstance();
        for (InvoicePos__c pos: invPoss) {
            if (pos.InvoicePositionSuperior__c != null) {
                InvoicePos__c posCloned = possMap.get(pos.Id);
                posCloned.InvoicePositionSuperior__c = possMap.get(pos.InvoicePositionSuperior__c).Id;
                uowPos.registerDirty(posCloned);
                System.debug('$$$$$$$$ ' + posCloned);
            }
        }
        uowPos.commitWork();
*/
         // insert invoicePos possition Superior First, this avoids make a query later to get the Invoicepossition fields updated by the flows
        for (InvoicePos__c pos: invPoss) {
            if (pos.InvoicePositionSuperior__c == null) {
                InvoicePos__c posClone = pos.clone(false, true);
                posClone.InvoicePositionAmount__c = -pos.InvoicePositionAmount__c;
                uow.registerNew(posClone, InvoicePos__c.InvoiceName__c, invMap.get(pos.InvoiceName__c));
                possMap.put(pos.Id, posClone);
            }
            
        }
        System.debug('First Insert '+possMap);
        uow.commitWork();
        // insert invoiceps wit a possition Superior.
        fflib_ISObjectUnitOfWork uowPos = Application.UnitOfWork.newInstance();
        for (InvoicePos__c pos: invPoss) {
            if (pos.InvoicePositionSuperior__c != null) {
                InvoicePos__c posClone = pos.clone(false, true);
                posClone.InvoicePositionSuperior__c = possMap.get(pos.InvoicePositionSuperior__c).Id;
                posClone.InvoicePositionAmount__c = -pos.InvoicePositionAmount__c;
                uowPos.registerNew(posClone, InvoicePos__c.InvoiceName__c, invMap.get(pos.InvoiceName__c));
                possMap.put(pos.Id, posClone);
            }
        }
        System.debug('second Insert');
        uowPos.commitWork();

        return cancelled;
    }

/*
    @TestVisible
    private void checkAttachments() {
        Map<Id, SObject> recordsMap = new Map<Id, SObject>(records);

        List<ContentDocumentLink> docs
                = InvoiceSelector.newInstance().selectDocuments(recordsMap.keySet());

        if (docs == null || docs.isEmpty()) return;

        for (ContentDocumentLink doc: docs) {
            Invoice__c inv = (Invoice__c) recordsMap.get(doc.LinkedEntityId);
            inv.ValHasAttachment__c = true;
        }
    }
*/

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Invoice(sObjectList);
        }
    }
}