force-app/main/default/objects/Account/fields/LastInvoiceNr__c.field-meta.xml
<CustomField>
    <fullName>LastInvoiceNr__c</fullName>
    <label>Last Invoice Nr.</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/LegalCode__c.field-meta.xml
<CustomField>
    <fullName>LegalCode__c</fullName>
    <label>Legal Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountSelector.cls
public with sharing class AccountSelector extends fflib_SObjectSelector
  implements IAccountSelector {

  public static IAccountSelector newInstance() {
    return (IAccountSelector) Application.Selector.newInstance(Account.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      Account.Id,
      Account.LegalCode__c,
      Account.LastInvoiceNr__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Account.sObjectType;
  }

}