force-app/main/default/objects/Account/fields/LegalCode__c.field-meta.xml
<CustomField>
    <fullName>LegalCode__c</fullName>
    <label>Legal Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/ClearingCostCenterNr__c.field-meta.xml
<CustomField>
    <fullName>ClearingCostCenterNr__c</fullName>
    <label>Clearing Cost Center Nr.</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenterNr__c.field-meta.xml
<CustomField>
    <fullName>CostCenterNr__c</fullName>
    <label>Cost Center Nr.</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/LegalAccount__c.field-meta.xml
<CustomField>
    <fullName>LegalAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Legal Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cost Center</relationshipLabel>
    <relationshipName>CostCenter</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/FinanceAccount__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Account</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinanceAccount__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Finance Account</relationshipLabel>
    <relationshipName>FinanceAccount</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/FinanceAccountNr__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountNr__c</fullName>
    <label>Finance Account Nr.</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/FinanceClearingNr__c.field-meta.xml
<CustomField>
    <fullName>FinanceClearingNr__c</fullName>
    <label>Finance Clearing Nr.</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/TypeName2__c.field-meta.xml
<CustomField>
    <fullName>TypeName2__c</fullName>
    <label>Type Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/TypeName__c.field-meta.xml
<CustomField>
    <fullName>TypeName__c</fullName>
    <label>Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/ILVPos__c.object-meta.xml
<CustomObject>
    <label>ILV Pos</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>ILV Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ILV Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILVPos__c/fields/CostCenterILVReceiver__c.field-meta.xml
<CustomField>
    <fullName>CostCenterILVReceiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cost Center (ILV Receiver)</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/CostCenterNrILVReceiver__c.field-meta.xml
<CustomField>
    <fullName>CostCenterNrILVReceiver__c</fullName>
    <label>Cost Center Nr. (ILV Receiver)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/FinanceAccountILVGiver__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountILVGiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Account (ILV Giver)</label>
    <referenceTo>FinanceAccount__c</referenceTo>
    <relationshipLabel>ILV Pos (Finance Account (ILV Giver))</relationshipLabel>
    <relationshipName>ILV_Pos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/FinanceAccountILVReceiver__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountILVReceiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Account (ILV Receiver)</label>
    <referenceTo>FinanceAccount__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/FinanceAccountNrILVGiver__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountNrILVGiver__c</fullName>
    <label>Finance Account Nr. (ILV Giver)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/FinanceAccountNrILVReceiver__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountNrILVReceiver__c</fullName>
    <label>Finance Account Nr. (ILV Receiver)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/ILVType__c.field-meta.xml
<CustomField>
    <fullName>ILVType__c</fullName>
    <label>ILV Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/InvoiceName__c.field-meta.xml
<CustomField>
    <fullName>InvoiceName__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/BillingViaLegalCode__c.field-meta.xml
<CustomField>
    <fullName>BillingViaLegalCode__c</fullName>
    <label>Billing via (Legal Code)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/ILV.recordType-meta.xml
<RecordType>
    <fullName>ILV</fullName>
    <active>true</active>
    <label>ILV</label>
</RecordType>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Internal Contract Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CostCenter__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ILVPos.cls
public with sharing class ILVPos extends fflib_SObjectDomain
        implements IILVPos {

    public static IILVPos newInstance(List<ILVPos__c> records) {
        return (IILVPos) Application.Domain.newInstance(records);
    }

    public ILVPos(List<ILVPos__c> records) {
        super(records);
    }

    public override void onBeforeInsert() {
        callInheritedFieldValue(false);
        callUpdateExchangeRate(null);
        setFinancialAccountInfo();
    }

    public override void onBeforeUpdate(Map<Id, SObject> oldRecords) {
        callInheritedFieldValue(false);
        callUpdateExchangeRate(oldRecords);
        setFinancialAccountInfo();
    }

    public override void onAfterInsert() {
        callParentUpdate(null);
    }

    public override void onAfterUpdate(Map<Id, SObject> oldRecords) {
        callParentUpdate(oldRecords);
    }

    public override void onBeforeDelete() {
        List<Field__mdt> fields = FieldMDTSelector.newInstance().selectDeletionControlFields(this.getSObjectType().getDescribe().getName());
        IFieldMDT fieldDomain = FieldMDT.newInstance(fields);
        fieldDomain.controlDeletion(records);
    }

    public void save(fflib_ISObjectUnitOfWork uow, Invoice__c inv) {

        for (ILVPos__c ip : (List<ILVPos__c>) records) {
            if (ip.Id != null) {
                uow.registerDirty(ip);
            } else {
                uow.registerNew(ip, ILVPos__c.InvoiceName__c, inv);
            }
        }

    }

    @TestVisible
    private void callParentUpdate(Map<Id, SObject> oldRecords) {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        List<ParentObjectUpdate__mdt> pous = ParentObjectUpdateMDTSelector.newInstance().selectBySourceObj(this.getSObjectType().getDescribe().getName());
        IParentObjectUpdateMDT pouDomain = ParentObjectUpdateMDT.newInstance(pous);

        pouDomain.go(uow, records, oldRecords);
        uow.commitWork();
    }

    @TestVisible
    private void callUpdateExchangeRate(Map<Id, SObject> oldRecords) {
        List<Object__mdt> objs = ObjectMDTSelector.newInstance().selectCurrencyFields(this.getSObjectType().getDescribe().getName());

        //if we have currency fields and currency conversion is endabled then update
        if (objs.size() > 0 && objs[0].Fields__r != null) {
            IFieldMDT fieldDomain = FieldMDT.newInstance(objs[0].Fields__r);
            fieldDomain.updateExchangeRate(records, oldRecords);
        }
    }

    @TestVisible
    private void callInheritedFieldValue(Boolean isUpdate) {
        List<InheritedFieldValue__mdt> inheritedFValues = InheritedFieldValueMDTSelector.newInstance().selectByTargetObj(this.getSObjectType().getDescribe().getName());
        IInheritedFieldValueMDT inheritedFVDomain = InheritedFieldValueMDT.newInstance(inheritedFValues);

        if (isUpdate) {
            fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
            inheritedFVDomain.go(uow, records);
            uow.commitWork();
        } else {
            inheritedFVDomain.go(null, records);
        }

    }

    private void setFinancialAccountInfo() {

        Set<String> invoiceRelated = new Set<String>{
                'ProjectName__r.ProjectCostCenter__c'
        };
        Set<String> centerRelated = new Set<String>{
                'LegalAccount__r.LegalCode__c'
        };

        Set<Id> invIds = Utils.listToMap(ILVPos__c.InvoiceName__c, records).keySet();
        Set<Id> centerIds = Utils.listToMap(ILVPos__c.CostCenterILVReceiver__c, records).keySet();

        Map<Id, Invoice__c> invoices = new Map<Id, Invoice__c>(
                InvoiceSelector.newInstance().selectWithRelated(invIds, invoiceRelated)
        );

        Map<Id, CostCenter__c> centers = new Map<Id, CostCenter__c>(
                CostCenterSelector.newInstance().selectWithRelated(centerIds, centerRelated)
        );

        Set<Id> ccIds = new Set<Id>();
        Set<String> types = new Set<String>();
        Set<String> subTypes = new Set<String>();

        for (Invoice__c inv : invoices.values())
            ccIds.add(inv.ProjectName__r.ProjectCostCenter__c);

        for (ILVPos__c ilv : (List<ILVPos__c>) records) {
            types.add(ilv.ILVType__c);
            subTypes.add(ilv.PackageSubType__c);
            ccIds.add(ilv.CostCenterILVReceiver__c);
        }

        List<FinanceAccount__c> financeAccounts = FinanceAccountSelector.newInstance().selectByCostCenterAndType(ccIds, types, subTypes);

        for (ILVPos__c ilv : (List<ILVPos__c>) records) {
            Invoice__c inv = invoices.get(ilv.InvoiceName__c);
            CostCenter__c centerReceiver = centers.get(ilv.CostCenterILVReceiver__c);

            if (inv == null || centerReceiver == null) continue;

            for (FinanceAccount__c fa : financeAccounts) {
                if (fa.CostCenter__c == inv.ProjectName__r.ProjectCostCenter__c
                        && fa.TypeName__c == ilv.ILVType__c
                        && fa.TypeName2__c == ilv.PackageSubType__c) {

                    ilv.FinanceAccountILVGiver__c = fa.Id;
                    ilv.FinanceAccountNrILVGiver__c = fa.FinanceAccountNr__c;
                }

                if (fa.CostCenter__c == ilv.CostCenterILVReceiver__c
                        && fa.TypeName__c == ilv.ILVType__c
                        && fa.TypeName2__c == ilv.PackageSubType__c) {

                    ilv.FinanceAccountILVReceiver__c = fa.Id;

                    if (centerReceiver.LegalAccount__r.LegalCode__c == inv.BillingViaLegalCode__c) {
                        ilv.FinanceAccountNrILVReceiver__c = fa.FinanceAccountNr__c;
                        ilv.CostCenterNrILVReceiver__c = centerReceiver.CostCenterNr__c;
                    } else {
                        ilv.FinanceAccountNrILVReceiver__c = fa.FinanceClearingNr__c;
                        ilv.CostCenterNrILVReceiver__c = centerReceiver.ClearingCostCenterNr__c;
                    }
                }

            }

        }

    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new ILVPos(sObjectList);
        }
    }
}