force-app/main/default/objects/Account/fields/LocationAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>LocationAddressLine2__c</fullName>
    <description>ACHTUNG: Field Label und API Name stimmen nicht überein. Grund sind aufwändige Trigger- und Schnittstellenanpassungen bei API Namenswechsel. lgu 12.11.2014</description>
    <label>Location Name Addition</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LocationCity__c.field-meta.xml
<CustomField>
    <fullName>LocationCity__c</fullName>
    <label>Location City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LocationCountry__c.field-meta.xml
<CustomField>
    <fullName>LocationCountry__c</fullName>
    <label>Location Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SWITZERLAND</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GERMANY</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>LIECHTENSTEIN</fullName>
            </value>
            <value>
                <fullName>UNITED STATES</fullName>
            </value>
            <value>
                <fullName>----------</fullName>
            </value>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ÅLAND ISLANDS</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANDORRA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTARCTICA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LocationPoBox__c.field-meta.xml
<CustomField>
    <fullName>LocationPoBox__c</fullName>
    <label>Location PO Box</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LocationState__c.field-meta.xml
<CustomField>
    <fullName>LocationState__c</fullName>
    <label>Location State</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LocationStreetNr__c.field-meta.xml
<CustomField>
    <fullName>LocationStreetNr__c</fullName>
    <label>Location Street, Nr</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LocationZip__c.field-meta.xml
<CustomField>
    <fullName>LocationZip__c</fullName>
    <label>Location ZIP</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Summary_Account.recordType-meta.xml
<RecordType>
    <fullName>Summary_Account</fullName>
    <active>true</active>
    <description>Do not use this record type to create any accounts</description>
    <label>Summary Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <description>Field is no longer productive, but used by the trigger.</description>
    <label>Function</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Art Director</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Brand Manager</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Chairman</fullName>
            </value>
            <value>
                <fullName>CIO</fullName>
            </value>
            <value>
                <fullName>CMO</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>Creative Director</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Headmaster</fullName>
            </value>
            <value>
                <fullName>Head of Communication</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Marketing Manager</fullName>
            </value>
            <value>
                <fullName>Member of the Board</fullName>
            </value>
            <value>
                <fullName>Order Manager</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>President</fullName>
            </value>
            <value>
                <fullName>Product Manager</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Public Relation</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/JobTitle__c.field-meta.xml
<CustomField>
    <fullName>JobTitle__c</fullName>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LocationAddressLine3__c.field-meta.xml
<CustomField>
    <fullName>LocationAddressLine3__c</fullName>
    <description>ACHTUNG: Field Label und API Name stimmen nicht überein. Grund sind aufwändige Trigger- und Schnittstellenanpassungen bei API Namenswechsel. lgu 12.11.2014</description>
    <label>Location Address Addition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LocationCity__c.field-meta.xml
<CustomField>
    <fullName>LocationCity__c</fullName>
    <label>Location City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LocationCountry__c.field-meta.xml
<CustomField>
    <fullName>LocationCountry__c</fullName>
    <label>Location Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SWITZERLAND</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GERMANY</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>LIECHTENSTEIN</fullName>
            </value>
            <value>
                <fullName>UNITED STATES</fullName>
            </value>
            <value>
                <fullName>----------</fullName>
            </value>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ÅLAND ISLANDS</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANDORRA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTARCTICA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LocationState__c.field-meta.xml
<CustomField>
    <fullName>LocationState__c</fullName>
    <label>Location State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LocationZip__c.field-meta.xml
<CustomField>
    <fullName>LocationZip__c</fullName>
    <label>Location ZIP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OtherAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>OtherAddressLine2__c</fullName>
    <description>ACHTUNG: Field Label und API Name stimmen nicht überein. Grund sind aufwändige Trigger- und Schnittstellenanpassungen bei API Namenswechsel. lgu 12.11.2014</description>
    <label>Other Name Addition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OtherAddressLine3__c.field-meta.xml
<CustomField>
    <fullName>OtherAddressLine3__c</fullName>
    <description>ACHTUNG: Field Label und API Name stimmen nicht überein. Grund sind aufwändige Trigger- und Schnittstellenanpassungen bei API Namenswechsel. lgu 12.11.2014</description>
    <label>Other Address Addition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OtherCity__c.field-meta.xml
<CustomField>
    <fullName>OtherCity__c</fullName>
    <label>Other City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OtherCountry__c.field-meta.xml
<CustomField>
    <fullName>OtherCountry__c</fullName>
    <label>Other Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SWITZERLAND</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GERMANY</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>LIECHTENSTEIN</fullName>
            </value>
            <value>
                <fullName>UNITED STATES</fullName>
            </value>
            <value>
                <fullName>----------</fullName>
            </value>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ÅLAND ISLANDS</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANDORRA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTARCTICA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/OtherPoBox__c.field-meta.xml
<CustomField>
    <fullName>OtherPoBox__c</fullName>
    <label>Other PO Box</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactService.cls
/**
*	@description Contact service. Class contains methods to change Contact records. 
*
*	@author dch
*	@copyright PARX
*/
public with sharing class ContactService 
{
	/**
	*	@description Set of filds that should be set to null once we attach contact to Account with "Summary Account" record type.
	*/
	private static Set<String> SUMMARY_CONTACT_NULL_FIELDS = new Set<String>{'Department', 'Email', 'Fax', 'MobilePhone', 'Phone', 
			'ReportsToId', 'Function__c', 'JobTitle__c', 'LocationAddressLine2__c', 'LocationAddressLine3__c', 'LocationCity__c', 
			'LocationCountry__c', 'LocationPoBox__c', 'LocationState__c', 'LocationStreetNr__c', 'LocationZip__c', 'OtherAddressLine2__c', 
			'OtherAddressLine3__c', 'OtherCity__c', 'OtherCountry__c', 'OtherPoBox__c', 'OtherState__c', 'OtherStreetNr__c', 'OtherZip__c'};

	/**
	*	@description Set of filds that should be set to null once we attach contact to Account with "Private Account" record type.
	*/
	public static Set<String> PRIVATE_CONTACT_NULL_FIELDS = new Set<String>{'OtherAddressLine2__c', 
			'OtherAddressLine3__c', 'OtherCity__c', 'OtherCountry__c', 'OtherPoBox__c', 'OtherState__c', 'OtherStreetNr__c', 'OtherZip__c',
			'Department', 'ReportsToId'};
	
	/**
	*	@description method is used query accounts to check account record type and call method to set right fields to null.
	*/
	public static void defineAccountRecordType(Set<sObject> contactsWithNewAccount)
	{
		Map<Id, List<Contact>> accountToContacts = Utils.getParentToChilrenMap('AccountId', contactsWithNewAccount);
		List<Account> accounts = [SELECT RecordTypeId FROM Account WHERE Id IN :accountToContacts.keySet()];
		for (Account account : accounts)
		{
			if (account.RecordTypeId == Utils.recordTypes.get('Account:Summary_Account'))
			{
				setContactsFieldsToNullValue(accountToContacts.get(account.Id), SUMMARY_CONTACT_NULL_FIELDS);
			} else if (account.RecordTypeId == Utils.recordTypes.get('Account:PrivateAccount'))
			{
				setContactsFieldsToNullValue(accountToContacts.get(account.Id), PRIVATE_CONTACT_NULL_FIELDS);
			}
		}
	}
	
	/**
	*	@description method is used to set target contacts specified fields to null.
	*/
	private static void setContactsFieldsToNullValue(List<Contact> contacts, Set<String> fields)
	{
		for (Contact contact : contacts)
		{
			//contact.RecordTypeId = Utils.recordTypes.get('Contact:PrivateContact');
			for (String field : fields)
			{
				contact.put(field, null);
			}
		}
	}
}