force-app/main/default/objects/Account/fields/LocationStreetNr__c.field-meta.xml
<CustomField>
    <fullName>LocationStreetNr__c</fullName>
    <label>Location Street, Nr</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Network</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/InternalAccount.recordType-meta.xml
<RecordType>
    <fullName>InternalAccount</fullName>
    <active>true</active>
    <description>Use this record type to create a BLC Unit</description>
    <label>Internal Account</label>
</RecordType>

force-app/main/default/objects/UnitRelation__c/UnitRelation__c.object-meta.xml
<CustomObject>
    <label>Unit Relation</label>
    <nameField>
        <displayFormat>UR-{000000}</displayFormat>
        <label>Unit Relation Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Segmentations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UnitRelation__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actual</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UnitRelation__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Network</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UnitRelation__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Supplier</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UnitRelation__c/recordTypes/BLC.recordType-meta.xml
<RecordType>
    <fullName>BLC</fullName>
    <active>true</active>
    <label>BLC</label>
</RecordType>

force-app/main/default/objects/UnitRelation__c/recordTypes/GbCh.recordType-meta.xml
<RecordType>
    <fullName>GbCh</fullName>
    <active>true</active>
    <label>GBCH</label>
</RecordType>

force-app/main/default/objects/UnitRelation__c/recordTypes/Hbc.recordType-meta.xml
<RecordType>
    <fullName>Hbc</fullName>
    <active>true</active>
    <label>HBC</label>
</RecordType>

force-app/main/default/classes/Test_UnitRelationTrigger.cls
@isTest
/**
*	@description Unit test for UnitRelationTrigger.
*	
*	@author akr
*	@copyright PARX
*/
private class Test_UnitRelationTrigger
{
	static testMethod void testValidation()
	{
		TriggerTemplateV2.setupUnitTest();
		Account anAcc = new Account(Name = 'Account New', RecordTypeId = Utils.recordTypes.get('Account:InternalAccount'), LocationStreetNr__c = '123');
		insert anAcc;
		
		UnitRelation__c aRelation1 = new UnitRelation__c(Account__c = anAcc.Id, Customer__c = 'Actual',
				Supplier__c = true, Partner__c = true, RecordTypeId = Utils.recordTypes.get('UnitRelation__c:Hbc'));
		UnitRelation__c aRelation2 = new UnitRelation__c(Account__c = anAcc.Id, Customer__c = 'Dis',
				Supplier__c = true, Partner__c = false, RecordTypeId = Utils.recordTypes.get('UnitRelation__c:GbCh'));
		insert new List<UnitRelation__c> {aRelation1, aRelation2};
		
		Test.startTest();
		TriggerTemplateV2.startUnitTest();
		UnitRelation__c aRelation3 = new UnitRelation__c(Account__c = anAcc.Id, Customer__c = 'Actual',
				Supplier__c = true, Partner__c = true, RecordTypeId = Utils.recordTypes.get('UnitRelation__c:Hbc'));
		Boolean isCorrect = false;
		try
		{
			insert aRelation3;
		} catch (Exception theExc)
		{
			System.assert(theExc.getMessage().contains('HBC') && theExc.getMessage().contains(aRelation1.Id),
					'Wrong error message was generated: ' + theExc.getMessage());
			isCorrect = true;
		}
		System.assert(isCorrect, 'The error message should be generated!');
		
		TriggerTemplateV2.startUnitTest();
		aRelation3.RecordTypeId = Utils.recordTypes.get('UnitRelation__c:BLC');
		insert aRelation3;
		Test.stopTest();
		
		System.assertNotEquals(null, aRelation3.Id, 'UnitRelation__c should be inserted without issues: ' + aRelation3);
	}
}