force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/IsProjectManager__c.field-meta.xml
<CustomField>
    <fullName>IsProjectManager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PS100 - Role Project Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/StartBillingButtonController.cls
public with sharing class StartBillingButtonController {

    @AuraEnabled
    public static Id get(Id recordId) {
        User u = UserService.getLogged();

        if (u == null || !u.IsProjectManager__c)
            return null;

        if (Project__c.SObjectType == recordId.getSObjectType())
            return recordId;

        Invoice__c inv = InvoiceService.get(recordId);
        return inv != null ? inv.ProjectName__c : null;
    }

}