force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AbacusInvoicePOSTotal__c.field-meta.xml
<CustomField>
    <fullName>AbacusInvoicePOSTotal__c</fullName>
    <description>05.12.2016, ary: Dieses Feld wird nicht mehr benötigt, da wir keine Unterscheidung mehr machen in Bezug auf verrechneten Umsatz und Umsatz, der ins Abacus fliesst.</description>
    <label>Abacus Invoice POS - Total</label>
    <summarizedField>InvoicePos__c.AbacusInvoicePositionAmount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoicePos__c.PackageType__c</field>
        <operation>equals</operation>
        <value>Time,Expense,Supplier Costs</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoicePos__c.InvoiceName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/AbacusTransfer__c.field-meta.xml
<CustomField>
    <fullName>AbacusTransfer__c</fullName>
    <label>Abacus Transfer</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/AccountNameLegal__c.field-meta.xml
<CustomField>
    <fullName>AccountNameLegal__c</fullName>
    <label>Account Name (Legal)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressAddition__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressAddition__c</fullName>
    <label>Billing Address Addition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressCountry__c</fullName>
    <label>Billing Address Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressPOBox__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressPOBox__c</fullName>
    <label>Billing Address PO Box</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressState__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressState__c</fullName>
    <label>Billing Address State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressStreetNr__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressStreetNr__c</fullName>
    <label>Billing Address Street, Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAddressZIP__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressZIP__c</fullName>
    <label>Billing Address ZIP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingAdressCity__c.field-meta.xml
<CustomField>
    <fullName>BillingAdressCity__c</fullName>
    <label>Billing Adress City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingNameAddition__c.field-meta.xml
<CustomField>
    <fullName>BillingNameAddition__c</fullName>
    <label>Billing Name (Addition)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingViaCompany__c.field-meta.xml
<CustomField>
    <fullName>BillingViaCompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing via (Company)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Billing via (Company))</relationshipLabel>
    <relationshipName>InvoicesBillingViaCompany</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingViaLegalCode__c.field-meta.xml
<CustomField>
    <fullName>BillingViaLegalCode__c</fullName>
    <label>Billing via (Legal Code)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CancellationInvoiceRelation__c.field-meta.xml
<CustomField>
    <fullName>CancellationInvoiceRelation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cancellation - Invoice Relation</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Cancellation</relationshipLabel>
    <relationshipName>Cancellation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CancellationReason__c.field-meta.xml
<CustomField>
    <fullName>CancellationReason__c</fullName>
    <label>Cancellation - Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ContractPartner__c.field-meta.xml
<CustomField>
    <fullName>ContractPartner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CurrencyRateToCHF__c.field-meta.xml
<CustomField>
    <fullName>CurrencyRateToCHF__c</fullName>
    <label>Currency Rate to CHF</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CustomerOrderNr__c.field-meta.xml
<CustomField>
    <fullName>CustomerOrderNr__c</fullName>
    <label>Customer Order Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CustomerReference__c.field-meta.xml
<CustomField>
    <fullName>CustomerReference__c</fullName>
    <label>Customer Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/FinanceDate__c.field-meta.xml
<CustomField>
    <fullName>FinanceDate__c</fullName>
    <label>Finance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ILVPOSTotalExpense__c.field-meta.xml
<CustomField>
    <fullName>ILVPOSTotalExpense__c</fullName>
    <label>ILV POS - Total Expense</label>
    <summarizedField>ILVPos__c.ILVPositionAmount__c</summarizedField>
    <summaryFilterItems>
        <field>ILVPos__c.ILVType__c</field>
        <operation>equals</operation>
        <value>Expense</value>
    </summaryFilterItems>
    <summaryForeignKey>ILVPos__c.InvoiceName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ILVPOSTotalExpenseCHF__c.field-meta.xml
<CustomField>
    <fullName>ILVPOSTotalExpenseCHF__c</fullName>
    <label>ILV POS - Total Expense (CHF)</label>
    <summarizedField>ILVPos__c.ILVPositionAmountCHF__c</summarizedField>
    <summaryFilterItems>
        <field>ILVPos__c.ILVType__c</field>
        <operation>equals</operation>
        <value>Expense</value>
    </summaryFilterItems>
    <summaryForeignKey>ILVPos__c.InvoiceName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ILVPOSTotalSupplierCost__c.field-meta.xml
<CustomField>
    <fullName>ILVPOSTotalSupplierCost__c</fullName>
    <label>ILV POS - Total Supplier Cost</label>
    <summarizedField>ILVPos__c.ILVPositionAmount__c</summarizedField>
    <summaryFilterItems>
        <field>ILVPos__c.ILVType__c</field>
        <operation>equals</operation>
        <value>SupplierCosts, LicenseDirect, LicenseProvision</value>
    </summaryFilterItems>
    <summaryForeignKey>ILVPos__c.InvoiceName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ILVPOSTotalSupplierCostCHF__c.field-meta.xml
<CustomField>
    <fullName>ILVPOSTotalSupplierCostCHF__c</fullName>
    <label>ILV POS - Total Supplier Cost (CHF)</label>
    <summarizedField>ILVPos__c.ILVPositionAmountCHF__c</summarizedField>
    <summaryFilterItems>
        <field>ILVPos__c.ILVType__c</field>
        <operation>equals</operation>
        <value>SupplierCosts, LicenseDirect, LicenseProvision</value>
    </summaryFilterItems>
    <summaryForeignKey>ILVPos__c.InvoiceName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ILVPOSTotalTime__c.field-meta.xml
<CustomField>
    <fullName>ILVPOSTotalTime__c</fullName>
    <label>ILV POS - Total Time</label>
    <summarizedField>ILVPos__c.ILVPositionAmount__c</summarizedField>
    <summaryFilterItems>
        <field>ILVPos__c.ILVType__c</field>
        <operation>equals</operation>
        <value>Time</value>
    </summaryFilterItems>
    <summaryForeignKey>ILVPos__c.InvoiceName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ILVPOSTotalTimeCHF__c.field-meta.xml
<CustomField>
    <fullName>ILVPOSTotalTimeCHF__c</fullName>
    <label>ILV POS - Total Time (CHF)</label>
    <summarizedField>ILVPos__c.ILVPositionAmountCHF__c</summarizedField>
    <summaryFilterItems>
        <field>ILVPos__c.ILVType__c</field>
        <operation>equals</operation>
        <value>Time</value>
    </summaryFilterItems>
    <summaryForeignKey>ILVPos__c.InvoiceName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDescription__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDescription__c</fullName>
    <label>Invoice Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDocumentNr__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDocumentNr__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Document Nr.</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceInvalid__c.field-meta.xml
<CustomField>
    <fullName>InvoiceInvalid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Invalid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoicePOSTotalExpense__c.field-meta.xml
<CustomField>
    <fullName>InvoicePOSTotalExpense__c</fullName>
    <label>Invoice POS - Total Expense</label>
    <summarizedField>InvoicePos__c.InvoicePositionAmount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoicePos__c.PackageType__c</field>
        <operation>equals</operation>
        <value>Expense</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoicePos__c.InvoiceName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoicePOSTotalExpenseCHF__c.field-meta.xml
<CustomField>
    <fullName>InvoicePOSTotalExpenseCHF__c</fullName>
    <label>Invoice POS - Total Expense (CHF)</label>
    <summarizedField>InvoicePos__c.InvoicePositionAmountCHF__c</summarizedField>
    <summaryFilterItems>
        <field>InvoicePos__c.PackageType__c</field>
        <operation>equals</operation>
        <value>Expense</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoicePos__c.InvoiceName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoicePOSTotalSupplierCost__c.field-meta.xml
<CustomField>
    <fullName>InvoicePOSTotalSupplierCost__c</fullName>
    <label>Invoice POS - Total Supplier Cost</label>
    <summarizedField>InvoicePos__c.InvoicePositionAmount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoicePos__c.PackageType__c</field>
        <operation>equals</operation>
        <value>SupplierCosts, LicenseDirect, LicenseProvision</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoicePos__c.InvoiceName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoicePOSTotalSupplierCostCHF__c.field-meta.xml
<CustomField>
    <fullName>InvoicePOSTotalSupplierCostCHF__c</fullName>
    <label>Invoice POS - Total Supplier Cost (CHF)</label>
    <summarizedField>InvoicePos__c.InvoicePositionAmountCHF__c</summarizedField>
    <summaryFilterItems>
        <field>InvoicePos__c.PackageType__c</field>
        <operation>equals</operation>
        <value>SupplierCosts, LicenseDirect, LicenseProvision</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoicePos__c.InvoiceName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoicePOSTotalTime__c.field-meta.xml
<CustomField>
    <fullName>InvoicePOSTotalTime__c</fullName>
    <label>Invoice POS - Total Time</label>
    <summarizedField>InvoicePos__c.InvoicePositionAmount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoicePos__c.PackageType__c</field>
        <operation>equals</operation>
        <value>Time</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoicePos__c.InvoiceName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoicePOSTotalTimeCHF__c.field-meta.xml
<CustomField>
    <fullName>InvoicePOSTotalTimeCHF__c</fullName>
    <label>Invoice POS - Total Time (CHF)</label>
    <summarizedField>InvoicePos__c.InvoicePositionAmountCHF__c</summarizedField>
    <summaryFilterItems>
        <field>InvoicePos__c.PackageType__c</field>
        <operation>equals</operation>
        <value>Time</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoicePos__c.InvoiceName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceReceiver__c.field-meta.xml
<CustomField>
    <fullName>InvoiceReceiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Receiver</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Billing Receiver)</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceSelector.cls
public with sharing class InvoiceSelector extends fflib_SObjectSelector
        implements IInvoiceSelector {

    public static IInvoiceSelector newInstance() {
        return (IInvoiceSelector) Application.Selector.newInstance(Invoice__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Invoice__c.AbacusInvoicePOSTotal__c,
                Invoice__c.AbacusTransfer__c,
                Invoice__c.AccountNameLegal__c,
                Invoice__c.BillingAddressAddition__c,
                Invoice__c.BillingAddressCountry__c,
                Invoice__c.BillingAddressPOBox__c,
                Invoice__c.BillingAddressState__c,
                Invoice__c.BillingAddressStreetNr__c,
                Invoice__c.BillingAddressZIP__c,
                Invoice__c.BillingAdressCity__c,
                Invoice__c.BillingNameAddition__c,
                Invoice__c.BillingViaCompany__c,
                Invoice__c.BillingViaLegalCode__c,
                Invoice__c.CancellationInvoiceRelation__c,
                Invoice__c.CancellationReason__c,
                Invoice__c.ConnectionReceivedId,
                Invoice__c.ConnectionSentId,
                Invoice__c.ContractPartner__c,
                Invoice__c.CreatedById,
                Invoice__c.CreatedDate,
                Invoice__c.CurrencyIsoCode,
                Invoice__c.CurrencyRateToCHF__c,
                Invoice__c.CustomerOrderNr__c,
                Invoice__c.CustomerReference__c,
                Invoice__c.FinanceDate__c,
                Invoice__c.ILVPOSTotalExpenseCHF__c,
                Invoice__c.ILVPOSTotalExpense__c,
                Invoice__c.ILVPOSTotalSupplierCostCHF__c,
                Invoice__c.ILVPOSTotalSupplierCost__c,
                Invoice__c.ILVPOSTotalTimeCHF__c,
                Invoice__c.ILVPOSTotalTime__c,
                Invoice__c.Id,
                Invoice__c.InvoiceDate__c,
                Invoice__c.InvoiceDescription__c,
                Invoice__c.InvoiceDocumentNr__c,
                Invoice__c.InvoiceInvalid__c,
                Invoice__c.InvoicePOSTotalExpenseCHF__c,
                Invoice__c.InvoicePOSTotalExpense__c,
                Invoice__c.InvoicePOSTotalSupplierCostCHF__c,
                Invoice__c.InvoicePOSTotalSupplierCost__c,
                Invoice__c.InvoicePOSTotalTimeCHF__c,
                Invoice__c.InvoicePOSTotalTime__c,
                Invoice__c.InvoiceReceiver__c,
                Invoice__c.InvoiceSentDate__c,
                Invoice__c.InvoiceStatus__c,
                Invoice__c.InvoiceTitle__c,
                Invoice__c.InvoiceTotalAmountGrossCHF__c,
                Invoice__c.InvoiceTotalAmountGross__c,
                Invoice__c.InvoiceTotalAmountNetCHF__c,
                Invoice__c.InvoiceTotalAmountNet__c,
                Invoice__c.InvoiceType__c,
                Invoice__c.InvoiceValutaDate__c,
                Invoice__c.IsDeleted,
                Invoice__c.LastActivityDate,
                Invoice__c.LastModifiedById,
                Invoice__c.LastModifiedDate,
                Invoice__c.LastReferencedDate,
                Invoice__c.LastViewedDate,
                Invoice__c.Name,
                Invoice__c.PeriodFrom__c,
                Invoice__c.PeriodUntil__c,
                Invoice__c.ProjectCostCenter__c,
                Invoice__c.ProjectInvoiceCurrency__c,
                Invoice__c.ProjectInvoiceDescription__c,
                Invoice__c.ProjectName__c,
                Invoice__c.ProjectNr__c,
                Invoice__c.RecordTypeId,
                Invoice__c.RelevantToRevenue__c,
                Invoice__c.ShowProjectInvoiceDescription__c,
                Invoice__c.SystemModstamp,
                Invoice__c.TermsOfPayment__c,
                Invoice__c.VATPercent__c,
                Invoice__c.ValCheckValidInvoice__c,
                Invoice__c.ValNoDeleteOverrideSysadmin__c,
                Invoice__c.ValNoDelete__c,
                Invoice__c.ZImportId__c,
                Invoice__c.ZImportSource__c,
                Invoice__c.ZImportTimeStamp__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Invoice__c.sObjectType;
    }

    public List<Invoice__c> selectWithRelated(Set<Id> ids, Set<String> related) {
        fflib_QueryFactory query = newQueryFactory();
        query.selectFields(related);

        query.setCondition('id in :ids');
        return (List<Invoice__c>) Database.query(query.toSOQL());
    }

    public Invoice__c draftByProject(Id projectId, String invoiceType) {
        fflib_QueryFactory query = newQueryFactory(false);
        query.selectFields(new Set<String>{
                'InvoiceTitle__c',
                'InvoiceDescription__c',
                'ProjectInvoiceDescription__c',
                'InvoiceDate__c',
                'FinanceDate__c',
                'InvoiceStatus__c',
                'PeriodFrom__c',
                'PeriodUntil__c',
                'AccountNameLegal__c',
                'BillingNameAddition__c',
                'BillingAddressStreetNr__c',
                'BillingAddressAddition__c',
                'BillingAddressPOBox__c',
                'BillingAddressZIP__c',
                'BillingAdressCity__c',
                'BillingAddressState__c',
                'BillingAddressCountry__c',
                'BillingViaCompany__c',
                'BillingViaCompany__r.AccountName__c',
                'InvoiceDate__c',
                'FinanceDate__c',
                'PeriodFrom__c',
                'PeriodUntil__c',
                'ProjectInvoiceCurrency__c',
                'VATPercent__c',
                'TermsOfPayment2__c',
                'CustomerOrderNr__c',
                'CustomerReference__c',
                'InvoiceTotalAmountNet__c',
                'InvoiceVatAmount__c',
                'InvoiceTotalAmountGross__c',
                'InvoiceVatAmount__c'
        });
        query.setCondition('ProjectName__c = :projectId AND InvoiceStatus__c = \'Draft\' AND RecordType.Name = :invoiceType');

        String soql = query.toSOQL()
                .replaceFirst('TermsOfPayment2__c', 'toLabel(TermsOfPayment2__c)');

        System.debug('---InvoiceSelector.draftByProject--- soql: '+soql);
        List<Invoice__c> invoices = (List<Invoice__c>) Database.query(soql);

        System.debug('---InvoiceSelector.draftByProject--- invoices: '+invoices);

        return invoices == null || invoices.isEmpty() ? null : invoices[0];
    }

    public List<ContentDocumentLink> selectDocuments(Set<Id> ids) {
        return [
                SELECT ContentDocumentId, LinkedEntityId
                FROM ContentDocumentLink
                WHERE LinkedEntityId IN  :ids
        ];
    }

}