force-app/main/default/objects/User/fields/BLCAbrechnungslisteFachberater__c.field-meta.xml
<CustomField>
    <fullName>BLCAbrechnungslisteFachberater__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PS170 - Role Fachberater Abrechnungslist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/CanTrackExpensesForOthers__c.field-meta.xml
<CustomField>
    <fullName>CanTrackExpensesForOthers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PS420 - Function Can Track Expenses for</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/CanTrackTimeForOthers__c.field-meta.xml
<CustomField>
    <fullName>CanTrackTimeForOthers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PS430 - Function Can Track Time for Othe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/CompensationTime__c.field-meta.xml
<CustomField>
    <fullName>CompensationTime__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PS440 - Function Time.Compensation Time</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/HourlyWage__c.field-meta.xml
<CustomField>
    <fullName>HourlyWage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PS450 - Function Time.Hourly Wage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/ID_18_digits__c.field-meta.xml
<CustomField>
    <fullName>ID_18_digits__c</fullName>
    <formula>CASESAFEID(  Id  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID 18 digits</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/InternalContactID__c.field-meta.xml
<CustomField>
    <fullName>InternalContactID__c</fullName>
    <label>Internal Contact ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/IsHRManager__c.field-meta.xml
<CustomField>
    <fullName>IsHRManager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PS120 - Role HR Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/IsProjectManager__c.field-meta.xml
<CustomField>
    <fullName>IsProjectManager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PS100 - Role Project Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/PasswordSent__c.field-meta.xml
<CustomField>
    <fullName>PasswordSent__c</fullName>
    <label>Password sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/Phone_external__c.field-meta.xml
<CustomField>
    <fullName>Phone_external__c</fullName>
    <label>Phone (external)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/PiketSpecial__c.field-meta.xml
<CustomField>
    <fullName>PiketSpecial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PS470 - Function Time.Piket Special</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/SFLicense__c.field-meta.xml
<CustomField>
    <fullName>SFLicense__c</fullName>
    <formula>Profile.UserLicense.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SF License</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Staff_Number_Old__c.field-meta.xml
<CustomField>
    <fullName>Staff_Number_Old__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>19.06.2017, ary: Wird nicht mehr benötigt, Staff-Nr. ist neu auf dem Kontakt.</description>
    <inlineHelpText>Abacus Employee ID</inlineHelpText>
    <label>Staff Nr. Old</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserSelector.cls
public with sharing class UserSelector  extends fflib_SObjectSelector
  implements IUserSelector {

  public static IUserSelector newInstance() {
    return (IUserSelector) Application.Selector.newInstance(User.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      User.BLCAbrechnungslisteFachberater__c,
      User.CanTrackExpensesForOthers__c,
      User.CanTrackTimeForOthers__c,
      User.CompensationTime__c,
      User.HourlyWage__c,
      User.ID_18_digits__c,
      User.InternalContactID__c,
      User.IsHRManager__c,
      User.IsProjectManager__c,
      User.Name,
      User.Username,
      User.PasswordSent__c,
      User.Phone_external__c,
      User.PiketSpecial__c,
      User.SFLicense__c,
      User.Staff_Number_Old__c,
      User.ProfileId
    };
  }

  public Schema.SObjectType getSObjectType() {
    return User.sObjectType;
  }

  public List<User> selectAll(){
    fflib_QueryFactory query = newQueryFactory();
    return (List<User>) Database.query(query.toSOQL());
  }

  public User selectById(Id userId){
    fflib_QueryFactory query = newQueryFactory();
    query.setCondition('Id = :userId');
    List<User> users = Database.query(query.toSOQL());
    return users.size() > 0 ? users[0] : null;
  }
}