force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinanceAccount__c/FinanceAccount__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Account</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinanceAccount__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Finance Account</relationshipLabel>
    <relationshipName>FinanceAccount</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/FinanceAccountNr__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountNr__c</fullName>
    <label>Finance Account Nr.</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/FinanceClearingNr__c.field-meta.xml
<CustomField>
    <fullName>FinanceClearingNr__c</fullName>
    <label>Finance Clearing Nr.</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/TypeName2__c.field-meta.xml
<CustomField>
    <fullName>TypeName2__c</fullName>
    <label>Type Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/TypeName__c.field-meta.xml
<CustomField>
    <fullName>TypeName__c</fullName>
    <label>Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FinanceAccountSelector.cls
public with sharing class FinanceAccountSelector extends fflib_SObjectSelector
  implements IFinanceAccountSelector {

  public static IFinanceAccountSelector newInstance() {
    return (IFinanceAccountSelector) Application.Selector.newInstance(FinanceAccount__c.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      FinanceAccount__c.Id,
      FinanceAccount__c.FinanceAccountNr__c,
      FinanceAccount__c.FinanceClearingNr__c,
      FinanceAccount__c.CostCenter__c,
      FinanceAccount__c.TypeName__c,
      FinanceAccount__c.TypeName2__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return FinanceAccount__c.sObjectType;
  }

  public FinanceAccount__c selectByCostCenterAndType(Id costCenter, String type) {
    fflib_QueryFactory query = newQueryFactory();
    query.setCondition('CostCenter__c = :costCenter AND TypeName__c = :type');
    List<FinanceAccount__c> financeAccounts = (List<FinanceAccount__c>) Database.query(query.toSOQL());
    return (financeAccounts != null && !financeAccounts.isEmpty()) ? financeAccounts[0] : null;
  }

  public List<FinanceAccount__c> selectByCostCenterAndType(Set<Id> ccIds, Set<String> types) {
    fflib_QueryFactory query = newQueryFactory();
    query.setCondition('CostCenter__c IN :ccIds AND TypeName__c IN :types');
    return (List<FinanceAccount__c>) Database.query(query.toSOQL());
  }

  public List<FinanceAccount__c> selectByCostCenterAndType(Set<Id> ccIds, Set<String> types, Set<String> subTypes) {
    fflib_QueryFactory query = newQueryFactory();
    query.setCondition('CostCenter__c IN :ccIds AND TypeName__c IN :types AND TypeName2__c IN :subTypes');
    return (List<FinanceAccount__c>) Database.query(query.toSOQL());
  }

}