force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/ClearingCostCenterNr__c.field-meta.xml
<CustomField>
    <fullName>ClearingCostCenterNr__c</fullName>
    <label>Clearing Cost Center Nr.</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenterNr__c.field-meta.xml
<CustomField>
    <fullName>CostCenterNr__c</fullName>
    <label>Cost Center Nr.</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CostCenterSelector.cls
public with sharing class CostCenterSelector extends fflib_SObjectSelector
  implements ICostCenterSelector {

  public static ICostCenterSelector newInstance() {
    return (ICostCenterSelector) Application.Selector.newInstance(CostCenter__c.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      CostCenter__c.Id,
      CostCenter__c.CostCenterNr__c,
      CostCenter__c.ClearingCostCenterNr__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return CostCenter__c.sObjectType;
  }

  public List<CostCenter__c> selectWithRelated(Set<Id> ids, Set<String> related) {
    fflib_QueryFactory query = newQueryFactory();
    query.selectFields(related);

    query.setCondition('id in :ids').toSOQL();
    return (List<CostCenter__c>) Database.query(query.toSOQL());
  }

}