force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/FinanceAccount__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Account</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinanceAccount__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Finance Account</relationshipLabel>
    <relationshipName>FinanceAccount</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/FinanceAccountNr__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountNr__c</fullName>
    <label>Finance Account Nr.</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/TypeName2__c.field-meta.xml
<CustomField>
    <fullName>TypeName2__c</fullName>
    <label>Type Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/TypeName__c.field-meta.xml
<CustomField>
    <fullName>TypeName__c</fullName>
    <label>Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/InvoicePos__c.object-meta.xml
<CustomObject>
    <label>Invoice Pos</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Invoice Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePos__c/fields/FinanceAccount__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Account</label>
    <referenceTo>FinanceAccount__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/FinanceAccountNr__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountNr__c</fullName>
    <label>Finance Account Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/InvoiceName__c.field-meta.xml
<CustomField>
    <fullName>InvoiceName__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/InvoicePositionAmount__c.field-meta.xml
<CustomField>
    <fullName>InvoicePositionAmount__c</fullName>
    <label>Invoice Position - Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/InvoicePositionSuperior__c.field-meta.xml
<CustomField>
    <fullName>InvoicePositionSuperior__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Position (Superior)</label>
    <referenceTo>InvoicePos__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>Invoice_Pos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageSubType__c.field-meta.xml
<CustomField>
    <fullName>PackageSubType__c</fullName>
    <label>Package Sub-Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <label>Package Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/PackageSubType__c.field-meta.xml
<CustomField>
    <fullName>PackageSubType__c</fullName>
    <inlineHelpText>Manufaktur only for SVH</inlineHelpText>
    <label>Package Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkTime</fullName>
                <label>Work Time</label>
            </value>
            <value>
                <fullName>TravelTime</fullName>
                <label>Travel Time</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>3rdPartyCosts</fullName>
                <label>3rd Party Costs</label>
            </value>
            <value>
                <fullName>ProjectResourceCosts</fullName>
                <label>Project Resource Costs</label>
            </value>
            <value>
                <fullName>AbacusInbox</fullName>
                <label>Abacus Inbox</label>
            </value>
            <value>
                <fullName>Manufaktur</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>LicenseDirect</fullName>
                <label>License (Direct)</label>
            </value>
            <value>
                <fullName>LicenseProvision</fullName>
                <label>License (Provision)</label>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageSuperior__c.field-meta.xml
<CustomField>
    <fullName>PackageSuperior__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hint: Filter must be optional, otherwise Template Clone will not run (Project Name)</description>
    <label>Package (Superior)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.ProjectName__c</field>
            <operation>equals</operation>
            <valueField>Package__c.ProjectName__c</valueField>
        </filterItems>
        <filterItems>
            <field>Package__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>PackagesSuperior</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <description>Diese Feld wird verwendet für die Zuweisung von Finance Account im ILV Prozess (Name Mapping)</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package Type Finance Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <formula>ProjectName__r.ProjectCostCenter__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Cost Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Attention: You should not add a package to a Project with Status = Closed</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>PackagesProjectName</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Internal Contract Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CostCenter__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestInvoicePosition.cls
@IsTest
private class TestInvoicePosition {

  @IsTest(SeeAllData=true)
  private static void testTrigger() {

    SObjectType t = InvoicePos__c.SObjectType;
    fflib_QueryFactory qf = new fflib_QueryFactory(t);
    qf.selectFields(t.getDescribe().fields.getMap().values());
    qf.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
    qf.setLimit(1);
    List<InvoicePos__c> theList = (List<InvoicePos__c>) Database.query(qf.toSOQL());

    if (!theList.isEmpty())
      update theList;
  }

  @IsTest
  private static void callingSaveShouldCallRegisterNew() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);

    //Given
    Invoice__c inv = new Invoice__c(
        Id = fflib_IDGenerator.generate(Invoice__c.SObjectType)
    );
    InvoicePos__c invP = new InvoicePos__c(
        InvoicePositionAmount__c = 10
    );
    Application.UnitOfWork.setMock(uowMock);

    // When
    IInvoicePosition invPDomain = InvoicePosition.newInstance(new List<InvoicePos__c> {invP});
    invPDomain.save(uowMock, inv);

    // Then
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock))
      .registerNew(
          fflib_Match.sObjectWith(
            new Map<SObjectField, Object>{
              InvoicePos__c.Id => invP.Id,
              InvoicePos__c.InvoicePositionAmount__c => 10
            }
          ),
          fflib_Match.eqSObjectField(InvoicePos__c.InvoiceName__c),
          fflib_Match.sObjectWith(
            new Map<SObjectField, Object>{
              Invoice__c.Id => inv.Id
            }
          )
      );

  }

  @IsTest
  private static void callingSaveShouldCallRegisterDirty() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);

    //Given
    InvoicePos__c invP = new InvoicePos__c(
        Id = fflib_IDGenerator.generate(InvoicePos__c.SObjectType),
        InvoicePositionAmount__c = 10
    );
    Application.UnitOfWork.setMock(uowMock);

    // When
    IInvoicePosition invPDomain = InvoicePosition.newInstance(new List<InvoicePos__c> {invP});
    invPDomain.save(uowMock, new Invoice__c());

    // Then
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock))
      .registerDirty(
          fflib_Match.sObjectWith(
            new Map<SObjectField, Object>{
              InvoicePos__c.Id => invP.Id,
              InvoicePos__c.InvoicePositionAmount__c => 10
            }
          )
      );

  }

  @IsTest
  private static void callingFindSuperiorShouldCallRegisterDirty() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);

    //Given
    Package__c pGroup = new Package__c(
        Id = fflib_IDGenerator.generate(Package__c.SObjectType)
    );
    Package__c pTime = new Package__c(
        Id = fflib_IDGenerator.generate(Package__c.SObjectType),
        PackageSuperior__c = pGroup.Id
    );
    InvoicePos__c invPGroup = new InvoicePos__c(
        Id = fflib_IDGenerator.generate(InvoicePos__c.SObjectType),
        PackageName__c = pGroup.Id
    );
    InvoicePos__c invPTime = new InvoicePos__c(
        Id = fflib_IDGenerator.generate(InvoicePos__c.SObjectType),
        PackageName__c = pTime.Id
    );
    Application.UnitOfWork.setMock(uowMock);

    // When
    IInvoicePosition invPDomain = InvoicePosition.newInstance(new List<InvoicePos__c> {invPGroup, invPTime});
    invPDomain.findSuperiors(uowMock, new List<Package__c> {pGroup, pTime});

    // Then
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock))
      .registerDirty(
          fflib_Match.sObjectWith(
            new Map<SObjectField, Object>{
              InvoicePos__c.Id => invPTime.Id,
              InvoicePos__c.InvoicePositionSuperior__c => invPGroup.Id
            }
          )
      );

  }

  @IsTest
  private static void callingCallInheritedFieldValueShouldCallDomainAndCommmitWork() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    IInheritedFieldValueMDT domainMock = new Mocks.InheritedFieldValueMDT(mocks);

    //Given
    mocks.startStubbing();
    mocks.when(domainMock.sObjectType()).thenReturn(InheritedFieldValue__mdt.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Domain.setMock(domainMock);

    // When
    new InvoicePosition(new List<InvoicePos__c> ()).callInheritedFieldValue(true);

    // Then
    ((IInheritedFieldValueMDT) mocks.verify(domainMock)).go(uowMock, new List<SObject>());
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock)).commitWork();
  }

  @IsTest
  private static void callingCallInheritedFieldValueShouldCallDomain() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    IInheritedFieldValueMDT domainMock = new Mocks.InheritedFieldValueMDT(mocks);

    //Given
    mocks.startStubbing();
    mocks.when(domainMock.sObjectType()).thenReturn(InheritedFieldValue__mdt.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Domain.setMock(domainMock);

    // When
    new InvoicePosition(new List<InvoicePos__c> ()).callInheritedFieldValue(false);

    // Then
    ((IInheritedFieldValueMDT) mocks.verify(domainMock)).go(null, new List<SObject>());
  }

  @IsTest
  private static void callingCallParentUpdateShouldCallDomainAndCommmitWork() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    IParentObjectUpdateMDTSelector selectorMock = new Mocks.ParentObjectUpdateMDTSelector(mocks);
    IParentObjectUpdateMDT domainMock = new Mocks.ParentObjectUpdateMDT(mocks);

    //Given
    mocks.startStubbing();
    mocks.when(selectorMock.sObjectType()).thenReturn(ParentObjectUpdate__mdt.SObjectType);
    mocks.when(selectorMock.selectBySourceObj(fflib_Match.anyString())).thenReturn(new List<ParentObjectUpdate__mdt>());
    mocks.when(domainMock.sObjectType()).thenReturn(ParentObjectUpdate__mdt.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Selector.setMock(selectorMock);
    Application.Domain.setMock(domainMock);

    // When
    new InvoicePosition(new List<InvoicePos__c> ()).callParentUpdate(new Map<Id, SObject>());

    // Then
    ((IParentObjectUpdateMDTSelector) mocks.verify(selectorMock)).selectBySourceObj(fflib_Match.anyString());
    ((IParentObjectUpdateMDT) mocks.verify(domainMock)).go(uowMock, new List<SObject>(), new Map<Id, SObject>());
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock)).commitWork();
  }

    @IsTest
  private static void callingCallUpdateExchangeRateShouldCallDomainAndCommmitWork() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    IObjectMDTSelector selectorMock = new Mocks.ObjectMDTSelector(mocks);
    IFieldMDT domainMock = new Mocks.FieldMDT(mocks);

    //Given
    Object__mdt obj
      = ((List<Object__mdt>) fflib_ApexMocksUtils.makeRelationship(
        List<Object__mdt>.class,
        new List<Object__mdt> {new Object__mdt()},
        Field__mdt.Object__c,
        new List<List<Field__mdt>> { new List<Field__mdt> {new Field__mdt()}}
      ))[0];
    mocks.startStubbing();
    mocks.when(selectorMock.sObjectType()).thenReturn(Object__mdt.SObjectType);
    mocks.when(selectorMock.selectCurrencyFields(fflib_Match.anyString())).thenReturn(new List<Object__mdt>{obj});
    mocks.when(domainMock.sObjectType()).thenReturn(Field__mdt.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Selector.setMock(selectorMock);
    Application.Domain.setMock(domainMock);

    // When
    new InvoicePosition(new List<InvoicePos__c> ()).callUpdateExchangeRate(new Map<Id, SObject>());

    // Then
    ((IObjectMDTSelector) mocks.verify(selectorMock)).selectCurrencyFields(fflib_Match.anyString());
    ((IFieldMDT) mocks.verify(domainMock)).updateExchangeRate(new List<SObject>(), new Map<Id, SObject>());
  }

  @IsTest
  private static void testSetFinancialAccountInfo() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    IInvoiceSelector iSelectorMock = new Mocks.InvoiceSelector(mocks);
    IFinanceAccountSelector fSelectorMock = new Mocks.FinanceAccountSelector(mocks);

    //Given
    mocks.startStubbing();
    Project__c proj = new Project__c(
        ProjectCostCenter__c = fflib_IDGenerator.generate(Account.SObjectType)
    );
    Invoice__c inv = new Invoice__c(Id = fflib_IDGenerator.generate(Invoice__c.SObjectType));
    inv.ProjectName__r = proj;
    InvoicePos__c invP = new InvoicePos__c(
        PackageType__c = 'Test',
        PackageSubType__c = 'SubTest',
        InvoiceName__c = inv.Id
    );
    FinanceAccount__c fa = new FinanceAccount__c(
        Id = fflib_IDGenerator.generate(FinanceAccount__c.SObjectType),
        FinanceAccountNr__c = '001',
        CostCenter__c = proj.ProjectCostCenter__c,
        TypeName__c = 'Test',
        TypeName2__c = 'SubTest'
    );
    mocks.when(iSelectorMock.sObjectType()).thenReturn(Invoice__c.SObjectType);
    mocks.when(iSelectorMock.selectWithRelated(new Set<Id>{invP.InvoiceName__c}, new Set<String> {'ProjectName__r.ProjectCostCenter__c'})).thenReturn(new List<Invoice__c>{inv});
    mocks.when(fSelectorMock.sObjectType()).thenReturn(FinanceAccount__c.SObjectType);
    mocks.when(fSelectorMock.selectByCostCenterAndType(new Set<Id>{inv.ProjectName__r.ProjectCostCenter__c}, new Set<String>{invP.PackageType__c}, new Set<String>{invP.PackageSubType__c})).thenReturn(new List<FinanceAccount__c>{fa});
    mocks.stopStubbing();
    Application.Selector.setMock(iSelectorMock);
    Application.Selector.setMock(fSelectorMock);

    // When
    new InvoicePosition(new List<InvoicePos__c> {invP}).setFinancialAccountInfo();

    // Then
    ((IInvoiceSelector) mocks.verify(iSelectorMock)).selectWithRelated(new Set<Id>{invP.InvoiceName__c}, new Set<String> {'ProjectName__r.ProjectCostCenter__c'});
    ((IFinanceAccountSelector) mocks.verify(fSelectorMock)).selectByCostCenterAndType(new Set<Id>{inv.ProjectName__r.ProjectCostCenter__c}, new Set<String>{invP.PackageType__c}, new Set<String>{invP.PackageSubType__c});
    System.assertEquals(invP.FinanceAccount__c, fa.Id);
    System.assertEquals(invP.FinanceAccountNr__c, fa.FinanceAccountNr__c);
  }

}