force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ILVPos__c/ILVPos__c.object-meta.xml
<CustomObject>
    <label>ILV Pos</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>ILV Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ILV Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILVPos__c/fields/ILVType__c.field-meta.xml
<CustomField>
    <fullName>ILVType__c</fullName>
    <label>ILV Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/ILV.recordType-meta.xml
<RecordType>
    <fullName>ILV</fullName>
    <active>true</active>
    <label>ILV</label>
</RecordType>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/PackageSuperior__c.field-meta.xml
<CustomField>
    <fullName>PackageSuperior__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hint: Filter must be optional, otherwise Template Clone will not run (Project Name)</description>
    <label>Package (Superior)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.ProjectName__c</field>
            <operation>equals</operation>
            <valueField>Package__c.ProjectName__c</valueField>
        </filterItems>
        <filterItems>
            <field>Package__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>PackagesSuperior</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageType2__c.field-meta.xml
<CustomField>
    <fullName>PackageType2__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <description>Diese Feld wird verwendet für die Zuweisung von Finance Account im ILV Prozess (Name Mapping)</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package Type Finance Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <formula>ProjectName__r.ProjectCostCenter__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Cost Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Attention: You should not add a package to a Project with Status = Closed</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>PackagesProjectName</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Internal Contract Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CostCenter__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/IsFinanceManager__c.field-meta.xml
<CustomField>
    <fullName>IsFinanceManager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PS130 - Role Finance Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/PS480FunctionValidationRulesActive__c.field-meta.xml
<CustomField>
    <fullName>PS480FunctionValidationRulesActive__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If checked, Validation Rules are active. If unchecked, Validation Rules are not considered.</inlineHelpText>
    <label>PS480 - Function Validation Rules Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ILVPosController.cls
public with sharing class ILVPosController {

  @AuraEnabled
  public static ILVCreation get(Id projectId, String dateFrom, String dateTo) {
    return ILVPosService.get(projectId, dateFrom, dateTo);
  }

  @AuraEnabled
  public static void save(Invoice__c draft, List<ILVPos__c> positions) {
	  List<ILVPos__c> auxPositions = new List<ILVPos__c>();
    auxPositions.addAll(positions);
    ILVPosService.save(draft, auxPositions);
  }

  @AuraEnabled
  public static Id getILVRecordTypeId() {
    return Utils.getRecordTypeIdByDevName('Invoice__c', 'ILV');
  }

	@AuraEnabled
	public static Id startQueueableJob(Invoice__c draft, List<ILVPos__c> positions) {

		System.debug('---ILVPosController.startQueueableJob--- draft: '+draft);
		System.debug('---ILVPosController.startQueueableJob--- positions: '+positions);

		User userSettings = [Select IsFinanceManager__c, PS480FunctionValidationRulesActive__c  From User Where Id = :UserInfo.getUserId()];

		if (Test.isRunningTest()) {
			userSettings.IsFinanceManager__c = false;
			userSettings.PS480FunctionValidationRulesActive__c = true;
		}

		// Perform some validations here so that they can be reported back to the user by the Lightning component.
		// The validations performed by Validation Rules are not reported back because the insert/update operations
		// are performed from a Future method.
		String errMsg;
		errMsg = InvoiceController.validateInvoice(draft, userSettings, 'ILV');

		System.debug('---ILVPosController.startQueueableJob--- errMsg: '+errMsg);

		if (String.isEmpty(errMsg)) {
			errMsg = validateILVPosition(positions, userSettings);
		}

		if (String.isNotEmpty(errMsg)) {
			System.debug('---ILVPosController.startQueueableJob--- Throw error: '+errMsg);
			throw new AuraHandledException(errMsg);  
		}
		else {
			ILVQueueable queueableJob = new ILVQueueable(draft, positions);

			Id jobId = System.enqueueJob(queueableJob);
			return jobId;
		}
	}

	@AuraEnabled
	public static Boolean checkIsJobFinished(Id jobId) {
		System.debug('---ILVPosController.checkIsJobFinished--- jobId: '+jobId);
		Boolean isFinished = false;

		List<AsyncApexJob> jobInfo = [SELECT Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobId];
		if (jobInfo.isEmpty() || jobInfo[0].Status == 'Aborted' || jobInfo[0].Status == 'Completed' || jobInfo[0].Status == 'Failed') {
			isFinished = true;
		}

		return isFinished;
	}

	/**
	 * Validates ILVPos records
	 */
	private static String validateILVPosition(List<ILVPos__c> positions, User userSettings) {

		if (userSettings.PS480FunctionValidationRulesActive__c && !userSettings.IsFinanceManager__c) {
			Set<Id> posPkgIDs = new Set<Id>();
			Set<String> types = new Set<String>();
			for (ILVPos__c invPos : positions) {
				posPkgIDs.add(invPos.PackageName__c);
			}

			System.debug('---ILVPosController.validateILVPosition--- posPkgIDs: '+posPkgIDs);

			Map<Id, Package__c> posPkg = new Map<Id, Package__c>([SELECT Id, PackageSuperior__c, RecordType.DeveloperName, 
																		 ProjectName__r.ProjectCostCenter__r.Name, PackageType__c,
																		 PackageType2__c
																  FROM   Package__c WHERE Id IN :posPkgIDs]);

			System.debug('---ILVPosController.validateILVPosition--- ILVType__c : '+posPkg);
			for (ILVPos__c invPos : positions) {
				System.debug('---ILVPosController.validateILVPosition--- posPkgIDs: '+invPos);
				Package__c pkg = posPkg.get(invPos.PackageName__c);
				if (pkg == null) continue;

				if (invPos.ILVType__c != pkg.RecordType.DeveloperName) {
					return 'The invoice position Package Type Name does not match the Package Record Type Name.' +
						   'Please get in touch with your Super User. [ILVPosController ILV003]';
				}
		
			}
		}

		return '';
	}
}