force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/FinanceAccount__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Account</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinanceAccount__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Finance Account</relationshipLabel>
    <relationshipName>FinanceAccount</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/fields/FinanceAccountNr__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountNr__c</fullName>
    <label>Finance Account Nr.</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/ILVPos__c.object-meta.xml
<CustomObject>
    <label>ILV Pos</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>ILV Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ILV Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILVPos__c/fields/CostCenterILVReceiver__c.field-meta.xml
<CustomField>
    <fullName>CostCenterILVReceiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cost Center (ILV Receiver)</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/ILVType__c.field-meta.xml
<CustomField>
    <fullName>ILVType__c</fullName>
    <label>ILV Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/InvoiceName__c.field-meta.xml
<CustomField>
    <fullName>InvoiceName__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/InvoiceStatus__c.field-meta.xml
<CustomField>
    <fullName>InvoiceStatus__c</fullName>
    <formula>TEXT( InvoiceName__r.InvoiceStatus__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/InvoiceStatus__c.field-meta.xml
<CustomField>
    <fullName>InvoiceStatus__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/InvoicePos__c.object-meta.xml
<CustomObject>
    <label>Invoice Pos</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Invoice Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePos__c/fields/FinanceAccount__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Account</label>
    <referenceTo>FinanceAccount__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/FinanceAccountNr__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccountNr__c</fullName>
    <label>Finance Account Nr.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/InvoiceName__c.field-meta.xml
<CustomField>
    <fullName>InvoiceName__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/InvoiceStatus__c.field-meta.xml
<CustomField>
    <fullName>InvoiceStatus__c</fullName>
    <formula>TEXT(InvoiceName__r.InvoiceStatus__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <label>Package Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Internal Contract Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CostCenter__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestILVPos.cls
@IsTest
private class TestILVPos {

  @IsTest(SeeAllData=true)
  private static void testTrigger() {

    SObjectType t = ILVPos__c.SObjectType;
    fflib_QueryFactory qf = new fflib_QueryFactory(t);
    qf.selectField('Id');
    qf.setCondition('InvoiceName__r.InvoiceStatus__c = \'Draft\'');
    qf.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
    qf.setLimit(1);
    List<ILVPos__c> theList = (List<ILVPos__c>) Database.query(qf.toSOQL());

    if (!theList.isEmpty())
      update theList;
  }

  @IsTest
  private static void callingSaveShouldCallRegisterNew() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);

    //Given
    Invoice__c inv = new Invoice__c(
        Id = fflib_IDGenerator.generate(Invoice__c.SObjectType)
    );
    ILVPos__c ip = new ILVPos__c();
    Application.UnitOfWork.setMock(uowMock);

    // When
    IILVPos ipDomain = ILVPos.newInstance(new List<ILVPos__c> {ip});
    ipDomain.save(uowMock, inv);

    // Then
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock))
      .registerNew(ip, ILVPos__c.InvoiceName__c, inv);

  }

  @IsTest
  private static void callingSaveShouldCallRegisterDirty() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);

    //Given
    ILVPos__c ip = new ILVPos__c(
        Id = fflib_IDGenerator.generate(ILVPos__c.SObjectType)
    );
    Application.UnitOfWork.setMock(uowMock);

    // When
    IILVPos ipDomain = ILVPos.newInstance(new List<ILVPos__c> {ip});
    ipDomain.save(uowMock, null);

    // Then
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock))
      .registerDirty(ip);

  }
	
  @IsTest
  private static void callingCallInheritedFieldValueShouldCallDomainAndCommmitWork() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    IInheritedFieldValueMDT domainMock = new Mocks.InheritedFieldValueMDT(mocks);

    //Given
    mocks.startStubbing();
    mocks.when(domainMock.sObjectType()).thenReturn(InheritedFieldValue__mdt.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Domain.setMock(domainMock);

    // When
    new ILVPos(new List<ILVPos__c> ()).callInheritedFieldValue(true);

    // Then
    ((IInheritedFieldValueMDT) mocks.verify(domainMock)).go(uowMock, new List<SObject>());
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock)).commitWork();
  }

  @IsTest
  private static void callingCallInheritedFieldValueShouldCallDomain() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    IInheritedFieldValueMDT domainMock = new Mocks.InheritedFieldValueMDT(mocks);

    //Given
    mocks.startStubbing();
    mocks.when(domainMock.sObjectType()).thenReturn(InheritedFieldValue__mdt.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Domain.setMock(domainMock);

    // When
    new ILVPos(new List<ILVPos__c> ()).callInheritedFieldValue(false);

    // Then
    ((IInheritedFieldValueMDT) mocks.verify(domainMock)).go(null, new List<SObject>());
  }

  @IsTest
  private static void callingCallParentUpdateShouldCallDomainAndCommmitWork() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    IParentObjectUpdateMDTSelector selectorMock = new Mocks.ParentObjectUpdateMDTSelector(mocks);
    IParentObjectUpdateMDT domainMock = new Mocks.ParentObjectUpdateMDT(mocks);

    //Given
    mocks.startStubbing();
    mocks.when(selectorMock.sObjectType()).thenReturn(ParentObjectUpdate__mdt.SObjectType);
    mocks.when(selectorMock.selectBySourceObj(fflib_Match.anyString())).thenReturn(new List<ParentObjectUpdate__mdt>());
    mocks.when(domainMock.sObjectType()).thenReturn(ParentObjectUpdate__mdt.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Selector.setMock(selectorMock);
    Application.Domain.setMock(domainMock);

    // When
    new ILVPos(new List<ILVPos__c> ()).callParentUpdate(new Map<Id, SObject>());

    // Then
    ((IParentObjectUpdateMDTSelector) mocks.verify(selectorMock)).selectBySourceObj(fflib_Match.anyString());
    ((IParentObjectUpdateMDT) mocks.verify(domainMock)).go(uowMock, new List<SObject>(), new Map<Id, SObject>());
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock)).commitWork();
  }

    @IsTest
  private static void callingCallUpdateExchangeRateShouldCallDomainAndCommmitWork() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    IObjectMDTSelector selectorMock = new Mocks.ObjectMDTSelector(mocks);
    IFieldMDT domainMock = new Mocks.FieldMDT(mocks);

    //Given
    Object__mdt obj
      = ((List<Object__mdt>) fflib_ApexMocksUtils.makeRelationship(
        List<Object__mdt>.class,
        new List<Object__mdt> {new Object__mdt()},
        Field__mdt.Object__c,
        new List<List<Field__mdt>> { new List<Field__mdt> {new Field__mdt()}}
      ))[0];
    mocks.startStubbing();
    mocks.when(selectorMock.sObjectType()).thenReturn(Object__mdt.SObjectType);
    mocks.when(selectorMock.selectCurrencyFields(fflib_Match.anyString())).thenReturn(new List<Object__mdt>{obj});
    mocks.when(domainMock.sObjectType()).thenReturn(Field__mdt.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Selector.setMock(selectorMock);
    Application.Domain.setMock(domainMock);

    // When
    new ILVPos(new List<ILVPos__c> ()).callUpdateExchangeRate(new Map<Id, SObject>());

    // Then
    ((IObjectMDTSelector) mocks.verify(selectorMock)).selectCurrencyFields(fflib_Match.anyString());
    ((IFieldMDT) mocks.verify(domainMock)).updateExchangeRate(new List<SObject>(), new Map<Id, SObject>());
  }

  /* @IsTest */
  /* private static void testSetFinancialAccountInfo() { */
  /*  */
  /*   // Create mocks */
  /*   fflib_ApexMocks mocks = new fflib_ApexMocks(); */
  /*   IInvoiceSelector iSelectorMock = new Mocks.InvoiceSelector(mocks); */
  /*   IFinanceAccountSelector fSelectorMock = new Mocks.FinanceAccountSelector(mocks); */
  /*   ICostCenterSelector ccSelectorMock = new Mocks.CostCenterSelector(mocks); */
  /*  */
  /*   //Given */
  /*   mocks.startStubbing(); */
  /*   Project__c proj = new Project__c( */
  /*       ProjectCostCenter__c = fflib_IDGenerator.generate(Account.SObjectType) */
  /*   ); */
  /*   Invoice__c inv = new Invoice__c(Id = fflib_IDGenerator.generate(Invoice__c.SObjectType)); */
  /*   inv.ProjectName__r = proj; */
  /*   CostCenter__c cc = new CostCenter__c(Id = fflib_IDGenerator.generate(CostCenter__c.SObjectType)); */
  /*   ILVPos__c invP = new ILVPos__c( */
  /*       ILVType__c = 'Test', */
  /*       InvoiceName__c = inv.Id, */
  /*       CostCenterILVReceiver__c = cc.Id */
  /*   ); */
  /*   FinanceAccount__c fa = new FinanceAccount__c( */
  /*       Id = fflib_IDGenerator.generate(FinanceAccount__c.SObjectType), */
  /*       FinanceAccountNr__c = '001' */
  /*   ); */
  /*   mocks.when(iSelectorMock.sObjectType()).thenReturn(Invoice__c.SObjectType); */
  /*   mocks.when(iSelectorMock.selectWithRelated(new Set<Id>{invP.InvoiceName__c}, new Set<String> {'ProjectName__r.ProjectCostCenter__c'})).thenReturn(new List<Invoice__c>{inv}); */
  /*   mocks.when(fSelectorMock.sObjectType()).thenReturn(FinanceAccount__c.SObjectType); */
  /*   mocks.when(fSelectorMock.selectByCostCenterAndType(inv.ProjectName__r.ProjectCostCenter__c, invP.PackageType__c)).thenReturn(fa); */
  /*   mocks.stopStubbing(); */
  /*   Application.Selector.setMock(iSelectorMock); */
  /*   Application.Selector.setMock(fSelectorMock); */
  /*  */
  /*   // When */
  /*   new InvoicePosition(new List<InvoicePos__c> {invP}).setFinancialAccountInfo(); */
  /*  */
  /*   // Then */
  /*   ((IInvoiceSelector) mocks.verify(iSelectorMock)).selectWithRelated(new Set<Id>{invP.InvoiceName__c}, new Set<String> {'ProjectName__r.ProjectCostCenter__c'}); */
  /*   ((IFinanceAccountSelector) mocks.verify(fSelectorMock)).selectByCostCenterAndType(inv.ProjectName__r.ProjectCostCenter__c, invP.PackageType__c); */
  /* } */

}