force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/DurationHhMmN__c.field-meta.xml
<CustomField>
    <fullName>DurationHhMmN__c</fullName>
    <label>Duration</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestTimeService.cls
@IsTest
private class TestTimeService {

  @IsTest
  private static void callingServiceShouldCallDomain() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    ITimeDomain domainMock = new Mocks.TimeDomain(mocks);

    //Given
    mocks.startStubbing();
    Time__c t = new Time__c(DurationHhMmN__c = 1);
    mocks.when(domainMock.sObjectType()).thenReturn(Time__c.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Domain.setMock(domainMock);

    // When
    TimeService.save(new List<Time__c> {t});

    // Then
    ((ITimeDomain) mocks.verify(domainMock)).save(uowMock);
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock)).commitWork();

  }

}