force-app/main/default/objects/QRBillSetting__c/QRBillSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>QR Bill Setting</label>
</CustomObject>

force-app/main/default/objects/QRBillSetting__c/fields/Document_Format__c.field-meta.xml
<CustomField>
    <fullName>Document_Format__c</fullName>
    <label>Document Format</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QRBillSetting__c/fields/Has_Debtor__c.field-meta.xml
<CustomField>
    <fullName>Has_Debtor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Debtor Information</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QRBillSetting__c/fields/Output_Size__c.field-meta.xml
<CustomField>
    <fullName>Output_Size__c</fullName>
    <label>Output Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QRBillSetting__c/fields/Paper_Format__c.field-meta.xml
<CustomField>
    <fullName>Paper_Format__c</fullName>
    <label>Paper Format</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QRBillSetting__c/fields/Separator_Lines__c.field-meta.xml
<CustomField>
    <fullName>Separator_Lines__c</fullName>
    <label>Separator Lines</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QRBillRequestSettings.cls
public class QRBillRequestSettings {
    
    public String separatorLines;
    public String outputSize;
    public String paperFormat;
    public String billInformation;
    public boolean hasDebtor;
    
    public QRBillRequestSettings(QRBillSetting__c csSettings){
        if(csSettings != null){
            this.separatorLines = csSettings.Separator_Lines__c;
            this.outputSize = csSettings.Output_Size__c;
            this.paperFormat = csSettings.Paper_Format__c;
            this.billInformation = csSettings.Document_Format__c;
            this.hasDebtor = csSettings.Has_Debtor__c;
        }
	}
}