force-app/main/default/objects/Opportunity/fields/DailyRate__c.field-meta.xml
<CustomField>
    <fullName>DailyRate__c</fullName>
    <label>Daily Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectEnd__c.field-meta.xml
<CustomField>
    <fullName>ProjectEnd__c</fullName>
    <label>End Project (Date)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectStart__c.field-meta.xml
<CustomField>
    <fullName>ProjectStart__c</fullName>
    <label>Start Project (Date)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ResourceForecast__c/ResourceForecast__c.object-meta.xml
<CustomObject>
    <label>Resource Forecast</label>
    <nameField>
        <displayFormat>RF-{000000}</displayFormat>
        <label>Resource Forecast Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ResourceForecast__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ResourceForecast__c/fields/DateFirstDayOfMonth__c.field-meta.xml
<CustomField>
    <fullName>DateFirstDayOfMonth__c</fullName>
    <label>Date (First Day of Month)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ResourceForecast__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <label>Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ResourceForecast__c/fields/ExpectedDays__c.field-meta.xml
<CustomField>
    <fullName>ExpectedDays__c</fullName>
    <label>Expected Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ResourceForecast__c/fields/ExpectedRevenue__c.field-meta.xml
<CustomField>
    <fullName>ExpectedRevenue__c</fullName>
    <label>Expected Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ResourceForecast__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <inlineHelpText>Resource Forecast records are automatically created from the opportunity. Change relevant field values on the opportunity in the project information section.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Resource Forecasts</relationshipLabel>
    <relationshipName>ResourceForecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OpportunityService.cls
/*
*	@description Opportunity service.
*
*	@author ach
*	@copyright PARX
*/
public with sharing class OpportunityService
{
	/**
	*	Update forecasts related to the opportunities.
	*/
	public static void updateForecasts(List<Opportunity> theOpportunities)
	{
		// delete existing forecasts
		delete [SELECT Id FROM ResourceForecast__c WHERE Opportunity__c IN : new Map<Id, Opportunity>(theOpportunities).keySet()];
		
		List<ResourceForecast__c> aForecasts = new List<ResourceForecast__c>();
		//generate new ones
		for (Opportunity anOpportunity : theOpportunities)
		{
			//'Amount', 'Probability', 'ProjectStart__c', 'ProjectEnd__c', 'DailyRate__c'
			if (anOpportunity.Amount != null && anOpportunity.Probability != null && anOpportunity.ProjectStart__c != null && 
					anOpportunity.ProjectEnd__c != null)
			{
				aForecasts.addAll(generateForecasts(anOpportunity));
			}
		}
		insert aForecasts;
	}
	
	/**
	*	Generate the forecasts for opportunity.
	*/
	private static List<ResourceForecast__c> generateForecasts(Opportunity theOpportunity)
	{
		List<ResourceForecast__c> aResult = new List<ResourceForecast__c>();
		Date anIterationDate = theOpportunity.ProjectStart__c;
		
		//Number of all days
		Integer projectDuration = theOpportunity.ProjectStart__c.daysBetween(theOpportunity.ProjectEnd__c)+1;
		system.debug('### projectDuration:' + projectDuration);
		//last day of the last month
		Date anEndOfPeriod = getLastDayInMonth(theOpportunity.ProjectEnd__c);
		
		//generate forecasts for all month in our period.
		while(anIterationDate <= anEndOfPeriod)
		{
			ResourceForecast__c aForecast = new ResourceForecast__c(Opportunity__c = theOpportunity.Id, 
					CurrencyIsoCode = theOpportunity.CurrencyIsoCode);
			
			Date aLastForecastDayInMonth = getLastDayInMonth(anIterationDate);
			// if we are in the last month of our period - we should use the ProjectEnd__c instead of calendar last day
			if (theOpportunity.ProjectEnd__c.monthsBetween(anIterationDate) == 0)
			{
				aLastForecastDayInMonth = theOpportunity.ProjectEnd__c;
			}
			system.debug('### aLastForecastDayInMonth:' + aLastForecastDayInMonth);
			Integer numberOfForecastDaysInMonth = anIterationDate.daysBetween(aLastForecastDayInMonth)+1;
			system.debug('### numberOfForecastDaysInMonth:' + numberOfForecastDaysInMonth);
			aForecast.Amount__c = (theOpportunity.Amount * numberOfForecastDaysInMonth / projectDuration).setScale(2);
			system.debug('### Amount__c:' + aForecast.Amount__c);
			aForecast.DateFirstDayOfMonth__c = anIterationDate.toStartOfMonth();
			if (theOpportunity.DailyRate__c != null && theOpportunity.DailyRate__c != 0)
			{
				aForecast.Days__c = aForecast.Amount__c / theOpportunity.DailyRate__c;
				aForecast.ExpectedDays__c = (theOpportunity.Probability * aForecast.Days__c / 100).setScale(2);
			}
			aForecast.ExpectedRevenue__c = (theOpportunity.Probability * aForecast.Amount__c/ 100).setScale(2);
			
			aResult.add(aForecast);
			//go to the nextMonth
			anIterationDate = getLastDayInMonth(aLastForecastDayInMonth).addDays(1);
		}
		
		return aResult;
	}
	
	/**
	*	Get the last day of the month.
	*/
	private static Date getLastDayInMonth(Date theDate)
	{
		Integer numberOfDays = Date.daysInMonth(theDate.year(), theDate.month());
		return Date.newInstance(theDate.year(), theDate.month(), numberOfDays);
	}
}