force-app/main/default/objects/Contact/fields/AbacusVisaNr__c.field-meta.xml
<CustomField>
    <fullName>AbacusVisaNr__c</fullName>
    <inlineHelpText>Data entered by Finance.</inlineHelpText>
    <label>Abacus Visa Nr.</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Purchasing__c/Purchasing__c.object-meta.xml
<CustomObject>
    <label>Purchasing / Order Mgmt.</label>
    <nameField>
        <label>Purchasing Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchasing / Order Mgmt.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchasing__c/fields/BillerAccountProjectNr__c.field-meta.xml
<CustomField>
    <fullName>BillerAccountProjectNr__c</fullName>
    <description>Mapping ID for Suppplier Cost to Purchasing Mapping via Trigger</description>
    <formula>Account__r.Id &amp;&quot;_&quot;&amp; Project__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Biller Account Project Nr.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/SupplierCosts__c.object-meta.xml
<CustomObject>
    <label>Supplier Costs</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>Supplier Costs Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCosts__c/fields/BillerAccountProjectNr__c.field-meta.xml
<CustomField>
    <fullName>BillerAccountProjectNr__c</fullName>
    <formula>SupplierInvoice__r.BillerAccount__r.Id &amp; &quot;_&quot; &amp;PackageName__r.ProjectName__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Biller Account Project Nr.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/CostsSupplierCostsGrossCHF__c.field-meta.xml
<CustomField>
    <fullName>CostsSupplierCostsGrossCHF__c</fullName>
    <label>Costs - Supplier Costs Gross (CHF)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/EmailAbacusVisa__c.field-meta.xml
<CustomField>
    <fullName>EmailAbacusVisa__c</fullName>
    <label>Email Abacus Visa</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/Purchasing__c.field-meta.xml
<CustomField>
    <fullName>Purchasing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchasing</label>
    <referenceTo>Purchasing__c</referenceTo>
    <relationshipLabel>Supplier Costs</relationshipLabel>
    <relationshipName>SupplierCosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/VisaNr__c.field-meta.xml
<CustomField>
    <fullName>VisaNr__c</fullName>
    <label>Visa Nr.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/recordTypes/SupplierCosts.recordType-meta.xml
<RecordType>
    <fullName>SupplierCosts</fullName>
    <active>true</active>
    <label>Supplier Costs</label>
</RecordType>

force-app/main/default/classes/TestSupplierCosts.cls
@IsTest
private class TestSupplierCosts {

    @IsTest(SeeAllData=true)
    private static void testTrigger() {
        SObjectType t = SupplierCosts__c.SObjectType;
        fflib_QueryFactory qf = new fflib_QueryFactory(t);
        qf.selectFields(t.getDescribe().fields.getMap().values());
        qf.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
        qf.setLimit(1);
        List<SupplierCosts__c> theList = (List<SupplierCosts__c>) Database.query(qf.toSOQL());

        if (!theList.isEmpty())
            update theList;
    }

    @IsTest
    private static void callingCallInheritedFieldValueShouldCallDomainAndCommmitWork() {

        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
        IInheritedFieldValueMDT domainMock = new Mocks.InheritedFieldValueMDT(mocks);

        //Given
        mocks.startStubbing();
        mocks.when(domainMock.sObjectType()).thenReturn(InheritedFieldValue__mdt.SObjectType);
        mocks.stopStubbing();
        Application.UnitOfWork.setMock(uowMock);
        Application.Domain.setMock(domainMock);

        // When
        new SupplierCosts(new List<SupplierCosts__c> ()).callInheritedFieldValue(true);

        // Then
        ((IInheritedFieldValueMDT) mocks.verify(domainMock)).go(uowMock, new List<SObject>());
        ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock)).commitWork();
    }

    @IsTest
    private static void callingCallInheritedFieldValueShouldCallDomain() {

        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
        IInheritedFieldValueMDT domainMock = new Mocks.InheritedFieldValueMDT(mocks);

        //Given
        mocks.startStubbing();
        mocks.when(domainMock.sObjectType()).thenReturn(InheritedFieldValue__mdt.SObjectType);
        mocks.stopStubbing();
        Application.UnitOfWork.setMock(uowMock);
        Application.Domain.setMock(domainMock);

        // When
        new SupplierCosts(new List<SupplierCosts__c> ()).callInheritedFieldValue(false);

        // Then
        ((IInheritedFieldValueMDT) mocks.verify(domainMock)).go(null, new List<SObject>());
    }

    @IsTest
    private static void callingCallParentUpdateShouldCallDomainAndCommmitWork() {

        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
        IParentObjectUpdateMDTSelector selectorMock = new Mocks.ParentObjectUpdateMDTSelector(mocks);
        IParentObjectUpdateMDT domainMock = new Mocks.ParentObjectUpdateMDT(mocks);

        //Given
        mocks.startStubbing();
        mocks.when(selectorMock.sObjectType()).thenReturn(ParentObjectUpdate__mdt.SObjectType);
        mocks.when(selectorMock.selectBySourceObj(fflib_Match.anyString())).thenReturn(new List<ParentObjectUpdate__mdt>());
        mocks.when(domainMock.sObjectType()).thenReturn(ParentObjectUpdate__mdt.SObjectType);
        mocks.stopStubbing();
        Application.UnitOfWork.setMock(uowMock);
        Application.Selector.setMock(selectorMock);
        Application.Domain.setMock(domainMock);

        // When
        new SupplierCosts(new List<SupplierCosts__c> ()).callParentUpdate(new Map<Id, SObject>());

        // Then
        ((IParentObjectUpdateMDTSelector) mocks.verify(selectorMock)).selectBySourceObj(fflib_Match.anyString());
        ((IParentObjectUpdateMDT) mocks.verify(domainMock)).go(uowMock, new List<SObject>(), new Map<Id, SObject>());
        ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock)).commitWork();
    }

    @IsTest
    private static void callingCallUpdateExchangeRateShouldCallDomainAndCommmitWork() {

        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
        IObjectMDTSelector selectorMock = new Mocks.ObjectMDTSelector(mocks);
        IFieldMDT domainMock = new Mocks.FieldMDT(mocks);

        //Given
        Object__mdt obj
            = ((List<Object__mdt>) fflib_ApexMocksUtils.makeRelationship(
                        List<Object__mdt>.class,
                        new List<Object__mdt> {new Object__mdt()},
                        Field__mdt.Object__c,
                        new List<List<Field__mdt>> { new List<Field__mdt> {new Field__mdt()}}
              ))[0];
        mocks.startStubbing();
        mocks.when(selectorMock.sObjectType()).thenReturn(Object__mdt.SObjectType);
        mocks.when(selectorMock.selectCurrencyFields(fflib_Match.anyString())).thenReturn(new List<Object__mdt>{obj});
        mocks.when(domainMock.sObjectType()).thenReturn(Field__mdt.SObjectType);
        mocks.stopStubbing();
        Application.UnitOfWork.setMock(uowMock);
        Application.Selector.setMock(selectorMock);
        Application.Domain.setMock(domainMock);

        // When
        new SupplierCosts(new List<SupplierCosts__c> ()).callUpdateExchangeRate(new Map<Id, SObject>());

        // Then
        ((IObjectMDTSelector) mocks.verify(selectorMock)).selectCurrencyFields(fflib_Match.anyString());
        ((IFieldMDT) mocks.verify(domainMock)).updateExchangeRate(new List<SObject>(), new Map<Id, SObject>());
    }

    @IsTest
    private static void callingSaveShouldRegisterNew() {

        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);

        //Given
        SupplierCosts__c sc = new SupplierCosts__c(
                CostsSupplierCostsGrossCHF__c = 10
                );
        Application.UnitOfWork.setMock(uowMock);

        // When
        ISupplierCosts scDomain = SupplierCosts.newInstance(new List<SupplierCosts__c> {sc});
        scDomain.save(uowMock);

        // Then
        ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock))
            .registerNew(
                    fflib_Match.sObjectWith(
                        new Map<SObjectField, Object>{
                            SupplierCosts__c.CostsSupplierCostsGrossCHF__c => sc.CostsSupplierCostsGrossCHF__c
                        }
                     )
             );
    }

    @IsTest
    private static void callingSaveShouldRegisterDirty() {

        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);

        //Given
        SupplierCosts__c sc = new SupplierCosts__c(
                Id = fflib_IDGenerator.generate(SupplierCosts__c.SObjectType),
                CostsSupplierCostsGrossCHF__c = 10
                );
        Application.UnitOfWork.setMock(uowMock);

        // When
        ISupplierCosts scDomain = SupplierCosts.newInstance(new List<SupplierCosts__c> {sc});
        scDomain.save(uowMock);

        // Then
        ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock))
            .registerDirty(
                    fflib_Match.sObjectWith(
                        new Map<SObjectField, Object>{
                            SupplierCosts__c.Id => sc.Id,
                                SupplierCosts__c.CostsSupplierCostsGrossCHF__c => sc.CostsSupplierCostsGrossCHF__c
                        }
                     )
             );
    }

    @IsTest
    private static void testSetEmailAbacusVisa() {

        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IContactSelector selectorMock = new Mocks.ContactSelector(mocks);

        //Given
        mocks.startStubbing();
        SupplierCosts__c sc = new SupplierCosts__c(
                VisaNr__c = 1000
        );
        String cleanVisaNr = sc.VisaNr__c.stripTrailingZeros().toPlainString();
        Contact con = new Contact(
                Email = 'test@test.com',
                AbacusVisaNr__c = '1000'
        );
        mocks.when(selectorMock.sObjectType()).thenReturn(Contact.SObjectType);
        mocks.when(selectorMock.byAbacusVisaNr(new Set<String>{cleanVisaNr})).thenReturn(new List<Contact>{con});
        mocks.stopStubbing();
        Application.Selector.setMock(selectorMock);

        // When
        new SupplierCosts(new List<SupplierCosts__c> {sc}).setEmailAbacusVisa();

        // Then
        ((IContactSelector) mocks.verify(selectorMock)).byAbacusVisaNr(new Set<String>{cleanVisaNr});
        System.assertEquals(sc.EmailAbacusVisa__c, con.Email);
    }

    @IsTest
    private static void testSetPurchasing() {

        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IPurchasingSelector selectorMock = new Mocks.PurchasingSelector(mocks);

        //Given
        mocks.startStubbing();
        JSONGenerator pJSON = JSON.createGenerator(true);
        pJSON.writeStartObject();
        pJSON.writeStringField('BillerAccountProjectNr__c', '0001A');
        pJSON.writeEndObject();
        SupplierCosts__c sc = (SupplierCosts__c) JSON.deserialize(pJSON.getAsString(), SupplierCosts__c.class);
        Purchasing__c purchasing = (Purchasing__c) JSON.deserialize(pJSON.getAsString(), Purchasing__c.class);
        purchasing.Id = fflib_IDGenerator.generate(Purchasing__c.SObjectType);

        mocks.when(selectorMock.sObjectType()).thenReturn(Purchasing__c.SObjectType);
        mocks.when(selectorMock.byBillerAccountProjectNr(new Set<String> {sc.BillerAccountProjectNr__c})).thenReturn(new List<Purchasing__c> {purchasing});
        mocks.stopStubbing();
        Application.Selector.setMock(selectorMock);

        // When
        new SupplierCosts(new List<SupplierCosts__c> {sc}).setPurchasing();

        // Then
        ((IPurchasingSelector) mocks.verify(selectorMock)).byBillerAccountProjectNr(new Set<String> {sc.BillerAccountProjectNr__c});
        System.assertEquals(purchasing.Id, sc.Purchasing__c);
    }


}