force-app/main/default/objects/Contact/fields/AbacusDefaultTimeType__c.field-meta.xml
<CustomField>
    <fullName>AbacusDefaultTimeType__c</fullName>
    <label>Abacus Default Time Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>200</fullName>
                <default>true</default>
                <label>200</label>
            </value>
            <value>
                <fullName>1100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/AbacusTimeType__c.field-meta.xml
<CustomField>
    <fullName>AbacusTimeType__c</fullName>
    <label>Abacus Time Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>1036</fullName>
            </value>
            <value>
                <fullName>1037</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>1100</fullName>
            </value>
            <value>
                <fullName>1135</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>130</fullName>
            </value>
            <value>
                <fullName>140</fullName>
            </value>
            <value>
                <fullName>160</fullName>
            </value>
            <value>
                <fullName>200</fullName>
            </value>
            <value>
                <fullName>300</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/EmployeeSpecificRate__c.field-meta.xml
<CustomField>
    <fullName>EmployeeSpecificRate__c</fullName>
    <defaultValue>true</defaultValue>
    <description>CR-001</description>
    <label>Employee Specific Rate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageRateHour__c.field-meta.xml
<CustomField>
    <fullName>PackageRateHour__c</fullName>
    <label>Package Rate (Hour)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Attention: You should not add a package to a Project with Status = Closed</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>PackagesProjectName</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Time.recordType-meta.xml
<RecordType>
    <fullName>Time</fullName>
    <active>true</active>
    <label>Time</label>
</RecordType>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectEmployeeRate__c/ProjectEmployeeRate__c.object-meta.xml
<CustomObject>
    <label>Project Employee Rate</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Project Employee Rate Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Employee Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectEmployeeRate__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Employee Rates</relationshipLabel>
    <relationshipName>ProjectEmployeeRates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectEmployeeRate__c/fields/ProjectEmployee__c.field-meta.xml
<CustomField>
    <fullName>ProjectEmployee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Contact</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Employee Rates</relationshipLabel>
    <relationshipName>ProjectEmployeeRates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectEmployeeRate__c/fields/ProjectEmployeeRateHour__c.field-meta.xml
<CustomField>
    <fullName>ProjectEmployeeRateHour__c</fullName>
    <label>Project Employee Rate (Hour)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/AbacusTimeType__c.field-meta.xml
<CustomField>
    <fullName>AbacusTimeType__c</fullName>
    <label>Abacus Time Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>1036</fullName>
            </value>
            <value>
                <fullName>1037</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>1100</fullName>
            </value>
            <value>
                <fullName>1135</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>130</fullName>
            </value>
            <value>
                <fullName>140</fullName>
            </value>
            <value>
                <fullName>150</fullName>
            </value>
            <value>
                <fullName>155</fullName>
            </value>
            <value>
                <fullName>160</fullName>
            </value>
            <value>
                <fullName>200</fullName>
            </value>
            <value>
                <fullName>300</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time__c/fields/DurationHhMm__c.field-meta.xml
<CustomField>
    <fullName>DurationHhMm__c</fullName>
    <label>Duration (hh:mm)</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/DurationHhMmN__c.field-meta.xml
<CustomField>
    <fullName>DurationHhMmN__c</fullName>
    <label>Duration</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Time__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/RateHour__c.field-meta.xml
<CustomField>
    <fullName>RateHour__c</fullName>
    <label>Rate (Hour)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/RateOrigin__c.field-meta.xml
<CustomField>
    <fullName>RateOrigin__c</fullName>
    <label>Rate Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PackageRate</fullName>
                <label>Package Rate</label>
            </value>
            <value>
                <fullName>EmployeeSpecificRate</fullName>
                <label>Employee Specific Rate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time__c/fields/Timetracker__c.field-meta.xml
<CustomField>
    <fullName>Timetracker__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Timetracker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Contact</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/InternalContactID__c.field-meta.xml
<CustomField>
    <fullName>InternalContactID__c</fullName>
    <label>Internal Contact ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TimeDomain.cls
public without sharing class TimeDomain extends fflib_SObjectDomain
  implements ITimeDomain {

  public static final String EMPLOYEE_RATE = 'EmployeeSpecificRate';
  public static final String PACKAGE_RATE = 'PackageRate';
  public static final String ABACUSTIME_TYPE_DEFAULT = 'Default';

  public static ITimeDomain newInstance(List<Time__c> records) {
    return (ITimeDomain) Application.Domain.newInstance(records);
  }

  public TimeDomain(List<Time__c> records) {
    super(records);
  }

  public override void onBeforeInsert() {
    setContactId();
    callInheritedFieldValue(false);
    callUpdateExchangeRate(null);
    setRate();
    setAbacusTimeType();
    setTimeDuration();
  }

  public override void onBeforeUpdate(Map<Id,SObject> oldRecords) {
    callInheritedFieldValue(false);
    callUpdateExchangeRate(oldRecords);
    setRate();
    setAbacusTimeType();
    setTimeDuration();
  }

  public override void onBeforeDelete() {
    List<Field__mdt> fields = FieldMDTSelector.newInstance().selectDeletionControlFields(this.getSObjectType().getDescribe().getName());
    IFieldMDT fieldDomain = FieldMDT.newInstance(fields);
    fieldDomain.controlDeletion(records);
  }

  public override void onAfterInsert() {
    callParentUpdate(null);
  }

  public override void onAfterUpdate(Map<Id,SObject> oldRecords) {
    fflib_SObjectDomain.getTriggerEvent(TimeDomain.class).disableAfterUpdate();
    callParentUpdate(oldRecords);
  }

  public void save(fflib_ISObjectUnitOfWork uow) {

    for (Time__c t: (List<Time__c>) records) {
      if (t.Id == null)
        uow.registerNew(t);
      else
        uow.registerDirty(t);
    }

  }

  @TestVisible
  private void setRate(){

    Set<Id> packageIds = new Set<Id>();
    for(Time__c t : (List<Time__c>) records){
      packageIds.add(t.Package__c);
    }

    Map<Id, Package__c> packageMap = New Map<Id,Package__c>(PackageSelector.newInstance().selectById(packageIds));

    Set<Id> projectIds = new Set<ID>();
    for(Package__c p : packageMap.values()){
      projectIds.add(p.ProjectName__c);
    }

    List<ProjectEmployeeRate__c> perList = ProjectEmployeeRateSelector.newInstance().selectByProjectId(projectIds);
    for(Time__c t : (List<Time__c>) records){
      Package__c p = packageMap.get(t.Package__c);

      t.RateHour__c = p.PackageRateHour__c;
      t.RateOrigin__c = PACKAGE_RATE;

      if (p.EmployeeSpecificRate__c){
        for(ProjectEmployeeRate__c per : perList){
          if(per.ProjectEmployee__c == t.Timetracker__c && per.Project__c == p.ProjectName__c){
            t.RateHour__c = per.ProjectEmployeeRateHour__c;
            t.RateOrigin__c = EMPLOYEE_RATE;
            break;
          }
        }
      }
    }
  }

  @TestVisible
  private void setContactId(){
    User u = UserSelector.newInstance().selectById(UserInfo.getUserId());
    for(Time__c t : (List<Time__c>) records){
      if (t.Timetracker__c == null){
        t.Timetracker__c = u.InternalContactID__c;
      }
    }
  }

  @TestVisible
  private void callParentUpdate(Map<Id,SObject> oldRecords) {
    fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
    List<ParentObjectUpdate__mdt> pous = ParentObjectUpdateMDTSelector.newInstance().selectBySourceObj(this.getSObjectType().getDescribe().getName());
    IParentObjectUpdateMDT pouDomain = ParentObjectUpdateMDT.newInstance(pous);

    pouDomain.go(uow, records, oldRecords);
    uow.commitWork();
  }

  @TestVisible
  private void callUpdateExchangeRate(Map<Id,SObject> oldRecords){
    List<Object__mdt> objs = ObjectMDTSelector.newInstance().selectCurrencyFields(this.getSObjectType().getDescribe().getName());

    if(objs.size() > 0 && objs[0].Fields__r != null){
      IFieldMDT fieldDomain = FieldMDT.newInstance(objs[0].Fields__r);
      fieldDomain.updateExchangeRate(records, oldRecords);
    }
  }

  @TestVisible
  private void callInheritedFieldValue(Boolean isUpdate) {
    List<InheritedFieldValue__mdt> inheritedFValues = InheritedFieldValueMDTSelector.newInstance().selectByTargetObj(this.getSObjectType().getDescribe().getName());
    IInheritedFieldValueMDT inheritedFVDomain = InheritedFieldValueMDT.newInstance(inheritedFValues);

    if (isUpdate) {
      fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
      inheritedFVDomain.go(uow, records);
      uow.commitWork();
    } else {
      inheritedFVDomain.go(null, records);
    }

  }

  @TestVisible
  private void setAbacusTimeType() {
    Map<Id, List<Time__c>> times = new Map<Id, List<Time__c>>();
    Set<Id> contactIds = new Set<Id>();

    for (Time__c t : (List<Time__c>) records) {
      List<Time__c> listTimes = times.get(t.Package__c);

      if (listTimes == null || listTimes.isEmpty()) {
        times.put(t.Package__c, new List<Time__c>{t});
      } else {
        listTimes.add(t);
      }
      contactIds.add(t.Timetracker__c);
    }
    System.debug('***contactIds ' + contactIds );

    List<Package__c> packages = PackageSelector.newInstance().selectById(times.keySet());
    Map<Id, Contact> contacts = new Map<Id, Contact>(ContactSelector.newInstance().selectById(contactIds));
    System.debug('***contacts ' + contacts);

    for (Package__c p : (List<Package__c>) packages) {

      for (Time__c t : times.get(p.Id)) {
        System.debug('***time ' + t );
        System.debug('***time ' + t.Timetracker__c );
        if (p.AbacusTimeType__c == ABACUSTIME_TYPE_DEFAULT) {
          t.AbacusTimeType__c = contacts.get(t.Timetracker__c).AbacusDefaultTimeType__c;
        } else {
          t.AbacusTimeType__c = p.AbacusTimeType__c;
        }
      }

    }

  }

  @TestVisible
  private void setTimeDuration() {

    for (Time__c t : (List<Time__c>) records) {
      if (t.DurationHhMm__c != null) {
        String[] brokenDuration = t.DurationHhMm__c.split(':');
        
        if (brokenDuration.size() != 2) continue;
            
        Double hours = Double.valueOf(brokenDuration[0]);
        Double minutes = Double.valueOf(brokenDuration[1]);

        t.DurationHhMmN__c = hours + (minutes / (6*10));
      }
    }

  }

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> sObjectList) {
      return new TimeDomain(sObjectList);
    }
  }
}