force-app/main/default/objects/Contact/fields/AbacusVisaNr__c.field-meta.xml
<CustomField>
    <fullName>AbacusVisaNr__c</fullName>
    <inlineHelpText>Data entered by Finance.</inlineHelpText>
    <label>Abacus Visa Nr.</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Purchasing__c/Purchasing__c.object-meta.xml
<CustomObject>
    <label>Purchasing / Order Mgmt.</label>
    <nameField>
        <label>Purchasing Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchasing / Order Mgmt.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchasing__c/fields/BillerAccountProjectNr__c.field-meta.xml
<CustomField>
    <fullName>BillerAccountProjectNr__c</fullName>
    <description>Mapping ID for Suppplier Cost to Purchasing Mapping via Trigger</description>
    <formula>Account__r.Id &amp;&quot;_&quot;&amp; Project__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Biller Account Project Nr.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/SupplierCosts__c.object-meta.xml
<CustomObject>
    <label>Supplier Costs</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>Supplier Costs Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCosts__c/fields/BillerAccountProjectNr__c.field-meta.xml
<CustomField>
    <fullName>BillerAccountProjectNr__c</fullName>
    <formula>SupplierInvoice__r.BillerAccount__r.Id &amp; &quot;_&quot; &amp;PackageName__r.ProjectName__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Biller Account Project Nr.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/EmailAbacusVisa__c.field-meta.xml
<CustomField>
    <fullName>EmailAbacusVisa__c</fullName>
    <label>Email Abacus Visa</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/Purchasing__c.field-meta.xml
<CustomField>
    <fullName>Purchasing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchasing</label>
    <referenceTo>Purchasing__c</referenceTo>
    <relationshipLabel>Supplier Costs</relationshipLabel>
    <relationshipName>SupplierCosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/VisaNr__c.field-meta.xml
<CustomField>
    <fullName>VisaNr__c</fullName>
    <label>Visa Nr.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/recordTypes/SupplierCosts.recordType-meta.xml
<RecordType>
    <fullName>SupplierCosts</fullName>
    <active>true</active>
    <label>Supplier Costs</label>
</RecordType>

force-app/main/default/classes/SupplierCosts.cls
public with sharing class SupplierCosts extends fflib_SObjectDomain
    implements ISupplierCosts {

    public static ISupplierCosts newInstance(List<SupplierCosts__c> records) {
        return (ISupplierCosts) Application.Domain.newInstance(records);
    }

    public SupplierCosts(List<SupplierCosts__c> records) {
        super(records);
    }

    public override void onBeforeInsert() {
        callInheritedFieldValue(false);
        callUpdateExchangeRate(null);
        setEmailAbacusVisa();
        setPurchasing();
    }

    public override void onBeforeUpdate(Map<Id,SObject> oldRecords) {
        callInheritedFieldValue(false);
        callUpdateExchangeRate(oldRecords);
    }

    public override void onBeforeDelete() {
        List<Field__mdt> fields = FieldMDTSelector.newInstance().selectDeletionControlFields(this.getSObjectType().getDescribe().getName());
        IFieldMDT fieldDomain = FieldMDT.newInstance(fields);
        fieldDomain.controlDeletion(records);
    }

    public override void onAfterInsert() {
        callParentUpdate(null);
    }

    public override void onAfterUpdate(Map<Id,SObject> oldRecords) {
        callParentUpdate(oldRecords);
    }

    public void save(fflib_ISObjectUnitOfWork uow) {

        for (SupplierCosts__c sc: (List<SupplierCosts__c>) records) {
            if (sc.Id == null)
                uow.registerNew(sc);
            else
                uow.registerDirty(sc);
        }

    }

    @TestVisible
    private void callUpdateExchangeRate(Map<Id,SObject> oldRecords){
        List<Object__mdt> objs = ObjectMDTSelector.newInstance().selectCurrencyFields(this.getSObjectType().getDescribe().getName());

        //if we have currency fields and currency conversion is endabled then update
        if(objs.size() > 0 && objs[0].Fields__r != null){
            IFieldMDT fieldDomain = FieldMDT.newInstance(objs[0].Fields__r);
            fieldDomain.updateExchangeRate(records, oldRecords);
        }
    }

    @TestVisible
    private void callParentUpdate(Map<Id,SObject> oldRecords) {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        List<ParentObjectUpdate__mdt> pous = ParentObjectUpdateMDTSelector.newInstance().selectBySourceObj(this.getSObjectType().getDescribe().getName());
        IParentObjectUpdateMDT pouDomain = ParentObjectUpdateMDT.newInstance(pous);

        pouDomain.go(uow, records, oldRecords);
        uow.commitWork();
    }

    @TestVisible
    private void callInheritedFieldValue(Boolean isUpdate) {
        List<InheritedFieldValue__mdt> inheritedFValues = InheritedFieldValueMDTSelector.newInstance().selectByTargetObj(this.getSObjectType().getDescribe().getName());
        IInheritedFieldValueMDT inheritedFVDomain = InheritedFieldValueMDT.newInstance(inheritedFValues);

        if (isUpdate) {
            fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
            inheritedFVDomain.go(uow, records);
            uow.commitWork();
        } else {
            inheritedFVDomain.go(null, records);
        }

    }

    @TestVisible
    private void setEmailAbacusVisa() {

        Map<String, List<SupplierCosts__c>> scVisaNrMap = new Map<String, List<SupplierCosts__c>>();

        for (SupplierCosts__c sc: (List<SupplierCosts__c>) records) {

            if (sc.VisaNr__c != null) {
                String cleanVisaNr = sc.VisaNr__c.stripTrailingZeros().toPlainString();

                List<SupplierCosts__c> listByVisaNr = scVisaNrMap.get(cleanVisaNr);

                if (listByVisaNr == null)
                    scVisaNrMap.put(cleanVisaNr, new List<SupplierCosts__c> {sc});
                else
                    listByVisaNr.add(sc);

            }

        }

        List<Contact> contacts = ContactSelector.newInstance().byAbacusVisaNr(scVisaNrMap.keySet());
        for (Contact con: contacts) {
            for (SupplierCosts__c sc: scVisaNrMap.get(con.AbacusVisaNr__c)) {
                sc.EmailAbacusVisa__c = con.Email;
            }
        }

    }

    @TestVisible
    private void setPurchasing() {
        Map<String, List<SupplierCosts__c>> scByBiller = new Map<String, List<SupplierCosts__c>>();

        for (SupplierCosts__c sc : (List<SupplierCosts__c>) records) {
            if (sc.BillerAccountProjectNr__c == null) continue;

            List<SupplierCosts__c> suppliersCosts = scByBiller.get(sc.BillerAccountProjectNr__c);

            if (suppliersCosts == null) {
                scByBiller.put(sc.BillerAccountProjectNr__c, new List<SupplierCosts__c> {sc});
            } else {
                suppliersCosts.add(sc);
            }
        }

        if (scByBiller.isEmpty()) return;

        List<Purchasing__c> purchasings = PurchasingSelector.newInstance().byBillerAccountProjectNr(
                scByBiller.keySet()
        );

        Set<String> purchasingsAdded = new Set<String>();
        for (Purchasing__c purchasing : purchasings) {
            if (purchasingsAdded.contains(purchasing.BillerAccountProjectNr__c)) continue;

            for (SupplierCosts__c sc: scByBiller.get(purchasing.BillerAccountProjectNr__c)) {
                sc.Purchasing__c = purchasing.Id;
                purchasingsAdded.add(purchasing.BillerAccountProjectNr__c);
            }
        }


    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new SupplierCosts(sObjectList);
        }
    }

}