force-app/main/default/objects/Contact/fields/AbacusDefaultTimeType__c.field-meta.xml
<CustomField>
    <fullName>AbacusDefaultTimeType__c</fullName>
    <label>Abacus Default Time Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>200</fullName>
                <default>true</default>
                <label>200</label>
            </value>
            <value>
                <fullName>1100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/AbacusTimeType__c.field-meta.xml
<CustomField>
    <fullName>AbacusTimeType__c</fullName>
    <label>Abacus Time Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>1036</fullName>
            </value>
            <value>
                <fullName>1037</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>1100</fullName>
            </value>
            <value>
                <fullName>1135</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>130</fullName>
            </value>
            <value>
                <fullName>140</fullName>
            </value>
            <value>
                <fullName>160</fullName>
            </value>
            <value>
                <fullName>200</fullName>
            </value>
            <value>
                <fullName>300</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/AbacusTimeType__c.field-meta.xml
<CustomField>
    <fullName>AbacusTimeType__c</fullName>
    <label>Abacus Time Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>1036</fullName>
            </value>
            <value>
                <fullName>1037</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>1100</fullName>
            </value>
            <value>
                <fullName>1135</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>130</fullName>
            </value>
            <value>
                <fullName>140</fullName>
            </value>
            <value>
                <fullName>150</fullName>
            </value>
            <value>
                <fullName>155</fullName>
            </value>
            <value>
                <fullName>160</fullName>
            </value>
            <value>
                <fullName>200</fullName>
            </value>
            <value>
                <fullName>300</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time__c/fields/DateFrom__c.field-meta.xml
<CustomField>
    <fullName>DateFrom__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date (From)</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/OutOfScope__c.field-meta.xml
<CustomField>
    <fullName>OutOfScope__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of Scope</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Time__c/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkTime</fullName>
                <label>Work Time</label>
            </value>
            <value>
                <fullName>TravelTime</fullName>
                <label>Travel Time</label>
            </value>
            <value>
                <fullName>Manufaktur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time__c/fields/Timetracker__c.field-meta.xml
<CustomField>
    <fullName>Timetracker__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Timetracker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Contact</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/TimeValidatedProjectResponsible__c.field-meta.xml
<CustomField>
    <fullName>TimeValidatedProjectResponsible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Time Validated - Project Responsible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TimeSelector.cls
public class TimeSelector extends fflib_SObjectSelector
  implements ITimeSelector {

  public static ITimeSelector newInstance() {
    return (ITimeSelector) Application.Selector.newInstance(Time__c.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      Time__c.Id,
      Time__c.Package__c,
      Time__c.AbacusTimeType__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Time__c.sObjectType;
  }

  public override String getOrderBy() {
    return 'Timetracker__r.Name ASC, DateFrom__c DESC, ServiceType__c DESC, OutOfScope__c ASC, TimeValidatedProjectResponsible__c ASC';
  }

  public List<Time__c> selectById(Set<Id> idSet) {
    fflib_QueryFactory query = newQueryFactory();
    query.selectFields(new Set<String>{'Timetracker__r.AbacusDefaultTimeType__c', 'Package__r.AbacusTimeType__c'});
    query.setCondition('id in :idSet').toSOQL();

    return (List<Time__c>) Database.query(query.toSOQL());
  }

}