force-app/main/default/objects/Contact/fields/AbacusDefaultTimeType__c.field-meta.xml
<CustomField>
    <fullName>AbacusDefaultTimeType__c</fullName>
    <label>Abacus Default Time Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>200</fullName>
                <default>true</default>
                <label>200</label>
            </value>
            <value>
                <fullName>1100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/AbacusVisaNr__c.field-meta.xml
<CustomField>
    <fullName>AbacusVisaNr__c</fullName>
    <inlineHelpText>Data entered by Finance.</inlineHelpText>
    <label>Abacus Visa Nr.</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ContactSelector.cls
public class ContactSelector extends fflib_SObjectSelector
    implements IContactSelector {

    public static IContactSelector newInstance() {
        return (IContactSelector) Application.Selector.newInstance(Contact.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Contact.Id,
            Contact.Email,
            Contact.AbacusDefaultTimeType__c,
            Contact.AbacusVisaNr__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Contact.sObjectType;
    }

    public List<Contact> selectById(Set<Id> idSet) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('id in :idSet');

        return (List<Contact>) Database.query(query.toSOQL());
    }

    public List<Contact> selectByAccount(Set<Id> accountIds) {
        fflib_QueryFactory query = newQueryFactory(false);
        query.selectField('Id');
        query.selectField('Name');
        query.selectField('Account.Name');
        query.selectField('AccundId');

        query.addOrdering('LastName', fflib_QueryFactory.SortOrder.ASCENDING);
        query.addOrdering('FirstName', fflib_QueryFactory.SortOrder.ASCENDING);

        query.setCondition('AccoundId in :accountIds');
        return (List<Contact>) Database.query(query.toSOQL());
    }

    public List<Contact> byAbacusVisaNr(Set<String> visaNrs) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('AbacusVisaNr__c in :visaNrs');
        return (List<Contact>) Database.query(query.toSOQL());
    }

}