force-app/main/default/objects/Contact/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EE-{000000}</displayFormat>
        <label>Expense Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/CurrencyRateToCHF__c.field-meta.xml
<CustomField>
    <fullName>CurrencyRateToCHF__c</fullName>
    <description>Currency Rate from Project to CHF</description>
    <label>Currency Rate to CHF</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseDate__c.field-meta.xml
<CustomField>
    <fullName>ExpenseDate__c</fullName>
    <label>Expense Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseGross__c.field-meta.xml
<CustomField>
    <fullName>ExpenseGross__c</fullName>
    <label>Expense Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseGrossApproved__c.field-meta.xml
<CustomField>
    <fullName>ExpenseGrossApproved__c</fullName>
    <label>Expense Gross - Approved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Package__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinanceAccount__c/FinanceAccount__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Account</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinanceAccount__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Finance Account</relationshipLabel>
    <relationshipName>FinanceAccount</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/ILVPos__c.object-meta.xml
<CustomObject>
    <label>ILV Pos</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>ILV Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ILV Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILVPos__c/fields/CurrencyRateToCHF__c.field-meta.xml
<CustomField>
    <fullName>CurrencyRateToCHF__c</fullName>
    <label>Currency Rate to CHF</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/InvoiceName__c.field-meta.xml
<CustomField>
    <fullName>InvoiceName__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/CurrencyRateToCHF__c.field-meta.xml
<CustomField>
    <fullName>CurrencyRateToCHF__c</fullName>
    <label>Currency Rate to CHF</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/PackageStatus__c.field-meta.xml
<CustomField>
    <fullName>PackageStatus__c</fullName>
    <label>Package Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>PartiallyOpen</fullName>
                <label>Partially open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Attention: You should not add a package to a Project with Status = Closed</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>PackagesProjectName</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Package__c/recordTypes/Time.recordType-meta.xml
<RecordType>
    <fullName>Time</fullName>
    <active>true</active>
    <label>Time</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/CurrencyRateToCHF__c.field-meta.xml
<CustomField>
    <fullName>CurrencyRateToCHF__c</fullName>
    <label>Currency Rate to CHF</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectEmployeeRate__c/ProjectEmployeeRate__c.object-meta.xml
<CustomObject>
    <label>Project Employee Rate</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Project Employee Rate Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Employee Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectEmployeeRate__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Employee Rates</relationshipLabel>
    <relationshipName>ProjectEmployeeRates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/SupplierCosts__c.object-meta.xml
<CustomObject>
    <label>Supplier Costs</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>Supplier Costs Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCosts__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <filterItems>
            <field>Package__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier Costs, License (Provision), License (Direct)</value>
        </filterItems>
        <filterItems>
            <field>Package__c.ProjectName__c</field>
            <operation>equals</operation>
            <valueField>$Source.ProjektName__c</valueField>
        </filterItems>
        <filterItems>
            <field>Package__c.ProjectName__r.ProjectNr__c</field>
            <operation>notEqual</operation>
            <value>P-105657</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Supplier Costs</relationshipLabel>
    <relationshipName>SupplierCosts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/DateFrom__c.field-meta.xml
<CustomField>
    <fullName>DateFrom__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date (From)</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/DateUntil__c.field-meta.xml
<CustomField>
    <fullName>DateUntil__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date (Until)</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Time__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TriggerCoverageTest.cls
/**
 * Minimal coverage for the 8 triggers that were excluded from the initial Apex deploy
 * due to 0% coverage. Each test inserts exactly one record to fire the trigger handler,
 * satisfying Salesforce's ≥1% per-trigger coverage requirement.
 * See TARGET_COMPAT_NOTES.md for context.
 */
@isTest
public class TriggerCoverageTest {

    @TestSetup
    static void makeData() {
        TestFactory.makeData();
    }

    @isTest
    static void expenseTrigger() {
        Project__c proj = [SELECT Id FROM Project__c LIMIT 1];
        // Expense__c.Package__c lookup filter requires RecordType = 'Expense'.
        // makeData creates a 'Time' package, so we create a separate 'Expense' one.
        Id expenseRtId = Schema.SObjectType.Package__c.getRecordTypeInfosByDeveloperName().get('Expense').getRecordTypeId();
        Package__c expPkg = new Package__c(ProjectName__c = proj.Id, RecordTypeId = expenseRtId, PackageStatus__c = 'Open');
        insert expPkg;

        // CurrencyRateToCHF__c and ExpenseGross__c must be non-null:
        // setSecExchangeRate multiplies ExpenseGrossApproved__c (set from ExpenseGross__c)
        // then divides by CurrencyRateToCHF__c — null arithmetic throws NPE.
        insert new Expense__c(
            Package__c = expPkg.Id,
            ExpenseDate__c = Date.today(),
            CurrencyRateToCHF__c = 1,
            ExpenseGross__c = 0
        );
    }

    @isTest
    static void timeTrigger() {
        Package__c pkg = [SELECT Id FROM Package__c LIMIT 1];
        insert new Time__c(
            Package__c = pkg.Id,
            DateFrom__c = Date.today(),
            DateUntil__c = Date.today()
        );
    }

    @isTest
    static void ilvPosTrigger() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Project__c proj = [SELECT Id FROM Project__c LIMIT 1];
        CostCenter__c cc = [SELECT Id FROM CostCenter__c LIMIT 1];
        Package__c pkg = [SELECT Id FROM Package__c LIMIT 1];
        FinanceAccount__c finAcc = [SELECT Id FROM FinanceAccount__c LIMIT 1];

        Invoice__c inv = TestFactory.createInvoice(acc.Id, proj.Id, cc.Id);
        insert inv;

        insert new ILVPos__c(
            InvoiceName__c = inv.Id,
            PackageName__c = pkg.Id
        );
    }

    @isTest
    static void supplierInvoiceTrigger() {
        insert new SupplierInvoice__c();
    }

    @isTest
    static void supplierCostsTrigger() {
        Package__c pkg = [SELECT Id FROM Package__c LIMIT 1];
        SupplierInvoice__c si = new SupplierInvoice__c();
        insert si;
        insert new SupplierCosts__c(
            PackageName__c = pkg.Id,
            SupplierInvoice__c = si.Id
        );
    }

    @isTest
    static void segmentTrigger() {
        insert new Segment__c();
    }

    @isTest
    static void projectEmployeeRateTrigger() {
        Project__c proj = [SELECT Id FROM Project__c LIMIT 1];
        Contact contact = [SELECT Id FROM Contact LIMIT 1];
        insert new ProjectEmployeeRate__c(
            Project__c = proj.Id,
            ProjectEmployee__c = contact.Id,
            ProjectEmployeeRateHour__c = 100
        );
    }

    @isTest
    static void qrBillUpdateEventTrigger() {
        Test.startTest();
        EventBus.publish(new QR_Bill_Update_Event__e());
        Test.stopTest();
    }

}