force-app/main/default/objects/Contact/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EE-{000000}</displayFormat>
        <label>Expense Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Package__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/FinanceAccount__c/FinanceAccount__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Account</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinanceAccount__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Finance Account</relationshipLabel>
    <relationshipName>FinanceAccount</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/ILVPos__c.object-meta.xml
<CustomObject>
    <label>ILV Pos</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>ILV Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ILV Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/InvoicePos__c/InvoicePos__c.object-meta.xml
<CustomObject>
    <label>Invoice Pos</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Invoice Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePos__c/fields/FinanceAccount__c.field-meta.xml
<CustomField>
    <fullName>FinanceAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Account</label>
    <referenceTo>FinanceAccount__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Alte Lookup Beziehung, kann aufgrund Code in Lightning Page &quot;Project Structure&quot; (auskommentiert) nicht gelöscht werden. 04.12.2017, ary</description>
    <label>Segment_do_not_use</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Segment__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Segment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Segment Service</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Segment__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Package__c/recordTypes/SupplierCosts.recordType-meta.xml
<RecordType>
    <fullName>SupplierCosts</fullName>
    <active>true</active>
    <label>Supplier Costs</label>
</RecordType>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/PermissionSetAssigment__mdt/PermissionSetAssigment__mdt.object-meta.xml
<CustomObject>
    <label>Permission set assigment</label>
    <pluralLabel>Permission set assigments</pluralLabel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectEmployeeRate__c/ProjectEmployeeRate__c.object-meta.xml
<CustomObject>
    <label>Project Employee Rate</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Project Employee Rate Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Employee Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectEmployeeRate__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Employee Rates</relationshipLabel>
    <relationshipName>ProjectEmployeeRates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchasing__c/Purchasing__c.object-meta.xml
<CustomObject>
    <label>Purchasing / Order Mgmt.</label>
    <nameField>
        <label>Purchasing Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchasing / Order Mgmt.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchasing__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Purchasing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCosts__c/SupplierCosts__c.object-meta.xml
<CustomObject>
    <label>Supplier Costs</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>Supplier Costs Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCosts__c/fields/Purchasing__c.field-meta.xml
<CustomField>
    <fullName>Purchasing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchasing</label>
    <referenceTo>Purchasing__c</referenceTo>
    <relationshipLabel>Supplier Costs</relationshipLabel>
    <relationshipName>SupplierCosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/SupplierInvoice__c.field-meta.xml
<CustomField>
    <fullName>SupplierInvoice__c</fullName>
    <label>Supplier Invoice</label>
    <referenceTo>SupplierInvoice__c</referenceTo>
    <relationshipLabel>Supplier Costs</relationshipLabel>
    <relationshipName>SupplierCosts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/recordTypes/SupplierCosts.recordType-meta.xml
<RecordType>
    <fullName>SupplierCosts</fullName>
    <active>true</active>
    <label>Supplier Costs</label>
</RecordType>

force-app/main/default/objects/SupplierInvoice__c/SupplierInvoice__c.object-meta.xml
<CustomObject>
    <label>Supplier Invoice</label>
    <nameField>
        <displayFormat>SI-{000000}</displayFormat>
        <label>Supplier Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/Application.cls
public with sharing class Application {

    // Configure and create the UnitOfWorkFactory for this Application
    public static final fflib_Application.UnitOfWorkFactory UnitOfWork =
            new fflib_Application.UnitOfWorkFactory(
                    new List<SObjectType>{
                            Account.SObjectType,
                            User.SObjectType,
                            Contact.SObjectType,
                            CostCenter__c.SObjectType,
                            FinanceAccount__c.SObjectType,
                            Project__c.SObjectType,
                            Package__c.SObjectType,
                            Time__c.SObjectType,
                            Expense__c.SObjectType,
                            SupplierCosts__c.SObjectType,
                            Invoice__c.SObjectType,
                            InvoicePos__c.SObjectType,
                            ILVPos__c.SObjectType,
                            PermissionSetAssignment.SObjectType,
                            Segment__c.SObjectType,
                            SupplierInvoice__c.SObjectType,
                            QuoteLineItem.SObjectType
                    }
            );

    // Configure and create the ServiceFactory for this Application
    public static final fflib_Application.ServiceFactory Service =
            new fflib_Application.ServiceFactory(
                    new Map<Type, Type>{
                            IUserService.class => UserServiceImpl.class,
                            IPackageService.class => PackageServiceImpl.class,
                            IInvoiceService.class => InvoiceServiceImpl.class,
                            IILVPosService.class => ILVPosServiceImpl.class
                    }
            );

    // Configure and create the SelectorFactory for this Application
    public static final fflib_Application.SelectorFactory Selector =
            new fflib_Application.SelectorFactory(
                    new Map<SObjectType, Type>{
                            DatedConversionRate.SObjectType => DatedConversionRateSelector.class,
                            Field__mdt.SObjectType => FieldMDTSelector.class,
                            InheritedFieldValue__mdt.SObjectType => InheritedFieldValueMDTSelector.class,
                            Object__mdt.SObjectType => ObjectMDTSelector.class,
                            ParentObjectUpdate__mdt.SObjectType => ParentObjectUpdateMDTSelector.class,
                            PermissionSet.SObjectType => PermissionSetSelector.class,
                            PermissionSetAssignment.SObjectType => PermissionSetAssignmentSelector.class,
                            PermissionSetAssigment__mdt.SObjectType => PermissionSetAssignmentMDTSelector.class,
                            ProjectEmployeeRate__c.SObjectType => ProjectEmployeeRateSelector.class,
                            User.SObjectType => UserSelector.class,
                            Project__c.SObjectType => ProjectSelector.class,
                            Package__c.SObjectType => PackageSelector.class,
                            Time__c.SObjectType => TimeSelector.class,
                            Account.SObjectType => AccountSelector.class,
                            Invoice__c.SObjectType => InvoiceSelector.class,
                            InvoicePos__c.SObjectType => InvoicePositionSelector.class,
                            ILVPos__c.SObjectType => ILVPosSelector.class,
                            FinanceAccount__c.SObjectType => FinanceAccountSelector.class,
                            CostCenter__c.SObjectType => CostCenterSelector.class,
                            Contact.SObjectType => ContactSelector.class,
                            Expense__c.SObjectType => ExpenseSelector.class,
                            SupplierCosts__c.SObjectType => SupplierCostsSelector.class,
                            Opportunity.SObjectType => OpportunitySelector.class,
                            OpportunityLineItem.SObjectType => OpportunityProductSelector.class,
                            Purchasing__c.SObjectType => PurchasingSelector.class,
                            QuoteLineItem.SObjectType => QuoteLineItemsSelector.class
                    }
            );

    // Configure and create the DomainFactory for this Application
    public static final fflib_Application.DomainFactory Domain =
            new fflib_Application.DomainFactory(
                    Application.Selector,
                    new Map<SObjectType, Type>{
                            Account.SObjectType => AccountDomain.Constructor.class,
                            User.SObjectType => UserDomain.Constructor.class,
                            Contact.SObjectType => ContactDomain.Constructor.class,
                            CostCenter__c.SObjectType => CostCenter.Constructor.class,
                            Field__mdt.SObjectType => FieldMDT.Constructor.class,
                            FinanceAccount__c.SObjectType => FinanceAccount.Constructor.class,
                            Invoice__c.SObjectType => Invoice.Constructor.class,
                            ILVPos__c.SObjectType => ILVPos.Constructor.class,
                            InheritedFieldValue__mdt.SObjectType => InheritedFieldValueMDT.Constructor.class,
                            InvoicePos__c.SObjectType => InvoicePosition.Constructor.class,
                            Package__c.SObjectType => PackageDomain.Constructor.class,
                            ParentObjectUpdate__mdt.SObjectType => ParentObjectUpdateMDT.Constructor.class,
                            PermissionSetAssignment.SObjectType => PermissionSetAssignmentDomain.Constructor.class,
                            PermissionSetAssigment__mdt.SObjectType => PermissionSetAssignmentMDT.Constructor.class,
                            Project__c.SObjectType => Project.Constructor.class,
                            ProjectEmployeeRate__c.SObjectType => ProjectEmployeeRate.Constructor.class,
                            Segment__c.SObjectType => Segment.Constructor.class,
                            SupplierCosts__c.SObjectType => SupplierCosts.Constructor.class,
                            SupplierInvoice__c.SObjectType => SupplierInvoice.Constructor.class,
                            Time__c.SObjectType => TimeDomain.Constructor.class,
                            Expense__c.SObjectType => Expense.Constructor.class,
                            QuoteLineItem.SObjectType => QuoteLineItems.Constructor.class,
                            ContentDocument.SObjectType => ContentDocuments.Constructor.class,
                            ContentDocumentLink.SObjectType => ContentDocumentLinks.Constructor.class
                    }
            );

}