force-app/main/default/objects/Contact/fields/LocalCurrency__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrency__c</fullName>
    <formula>CASE( LocationCountry__c , &quot;SWITZERLAND&quot;,&quot;CHF&quot;,&quot;UNITED STATES&quot;,&quot;USD&quot;,&quot;EUR&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EE-{000000}</displayFormat>
        <label>Expense Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/CostsExpenseGross__c.field-meta.xml
<CustomField>
    <fullName>CostsExpenseGross__c</fullName>
    <label>Costs - Expense Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/CostsExpenseNet__c.field-meta.xml
<CustomField>
    <fullName>CostsExpenseNet__c</fullName>
    <label>Costs - Expense Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/CurrencyRateToCHF__c.field-meta.xml
<CustomField>
    <fullName>CurrencyRateToCHF__c</fullName>
    <description>Currency Rate from Project to CHF</description>
    <label>Currency Rate to CHF</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/CurrencyRateToProjectCurrency__c.field-meta.xml
<CustomField>
    <fullName>CurrencyRateToProjectCurrency__c</fullName>
    <description>Only for information, no functionality in code / 06.09.2016, ary</description>
    <formula>LocalCurrencyToCHF__c *1/ CurrencyRateToCHF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Rate to Project Currency</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseDate__c.field-meta.xml
<CustomField>
    <fullName>ExpenseDate__c</fullName>
    <label>Expense Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseGross__c.field-meta.xml
<CustomField>
    <fullName>ExpenseGross__c</fullName>
    <label>Expense Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseGrossApproved__c.field-meta.xml
<CustomField>
    <fullName>ExpenseGrossApproved__c</fullName>
    <label>Expense Gross - Approved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expensetracker__c.field-meta.xml
<CustomField>
    <fullName>Expensetracker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expensetracker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Contact</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>ExpensesExpensetracker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseValidatedFinance__c.field-meta.xml
<CustomField>
    <fullName>ExpenseValidatedFinance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expense Validated - Finance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseValidatedProjectResponsible__c.field-meta.xml
<CustomField>
    <fullName>ExpenseValidatedProjectResponsible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expense Validated - Project Responsible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/LocalCurrency__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrency__c</fullName>
    <label>Local Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlobalProjectCurrency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ServiceExpenseNet__c.field-meta.xml
<CustomField>
    <fullName>ServiceExpenseNet__c</fullName>
    <label>Service - Expense Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/VATPercent__c.field-meta.xml
<CustomField>
    <fullName>VATPercent__c</fullName>
    <label>VAT %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0%</fullName>
                <default>true</default>
                <label>0%</label>
            </value>
            <value>
                <fullName>8%</fullName>
            </value>
            <value>
                <fullName>7.7%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/GlobalProjectCurrency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <masterLabel>Global Project Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ExpenseSelector.cls
public with sharing class ExpenseSelector extends fflib_SObjectSelector
  implements IExpenseSelector {

  public static IExpenseSelector newInstance() {
    return (IExpenseSelector) Application.Selector.newInstance(Expense__c.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      Expense__c.Id,
      Expense__c.ExpenseDate__c,
      Expense__c.LocalCurrency__c,
      Expense__c.LocalCurrencyToCHF__c,
      Expense__c.CurrencyRateToCHF__c,
      Expense__c.Distance__c,
      Expense__c.DistanceCompensation__c,
      Expense__c.ExpenseGross__c,
      Expense__c.ExpenseGrossApproved__c,
      Expense__c.ExpenseValidatedFinance__c,
      Expense__c.CostsExpenseGross__c,
      Expense__c.CurrencyRateToProjectCurrency__c,
      Expense__c.ExpenseValidatedProjectResponsible__c,
      Expense__c.ServiceExpenseNet__c,
      Expense__c.CostsExpenseNet__c,
      Expense__c.VATPercent__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Expense__c.sObjectType;
  }

  public override String getOrderBy() {
    return 'ExpenseTracker__r.Name ASC, ExpenseDate__c DESC, RecordType.Name DESC, ExpenseValidatedProjectResponsible__c ASC';
  }

}