force-app/main/default/objects/Contact/fields/LocalCurrency__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrency__c</fullName>
    <formula>CASE( LocationCountry__c , &quot;SWITZERLAND&quot;,&quot;CHF&quot;,&quot;UNITED STATES&quot;,&quot;USD&quot;,&quot;EUR&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EE-{000000}</displayFormat>
        <label>Expense Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/CostsExpenseGross__c.field-meta.xml
<CustomField>
    <fullName>CostsExpenseGross__c</fullName>
    <label>Costs - Expense Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/CostsExpenseNet__c.field-meta.xml
<CustomField>
    <fullName>CostsExpenseNet__c</fullName>
    <label>Costs - Expense Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/CurrencyRateToCHF__c.field-meta.xml
<CustomField>
    <fullName>CurrencyRateToCHF__c</fullName>
    <description>Currency Rate from Project to CHF</description>
    <label>Currency Rate to CHF</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseDate__c.field-meta.xml
<CustomField>
    <fullName>ExpenseDate__c</fullName>
    <label>Expense Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseGross__c.field-meta.xml
<CustomField>
    <fullName>ExpenseGross__c</fullName>
    <label>Expense Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseGrossApproved__c.field-meta.xml
<CustomField>
    <fullName>ExpenseGrossApproved__c</fullName>
    <label>Expense Gross - Approved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expensetracker__c.field-meta.xml
<CustomField>
    <fullName>Expensetracker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expensetracker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Contact</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>ExpensesExpensetracker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseValidatedFinance__c.field-meta.xml
<CustomField>
    <fullName>ExpenseValidatedFinance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expense Validated - Finance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseValidatedProjectResponsible__c.field-meta.xml
<CustomField>
    <fullName>ExpenseValidatedProjectResponsible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expense Validated - Project Responsible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/LocalCurrency__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrency__c</fullName>
    <label>Local Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlobalProjectCurrency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ServiceExpenseNet__c.field-meta.xml
<CustomField>
    <fullName>ServiceExpenseNet__c</fullName>
    <label>Service - Expense Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/VATPercent__c.field-meta.xml
<CustomField>
    <fullName>VATPercent__c</fullName>
    <label>VAT %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0%</fullName>
                <default>true</default>
                <label>0%</label>
            </value>
            <value>
                <fullName>8%</fullName>
            </value>
            <value>
                <fullName>7.7%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/User/fields/InternalContactID__c.field-meta.xml
<CustomField>
    <fullName>InternalContactID__c</fullName>
    <label>Internal Contact ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/GlobalProjectCurrency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <masterLabel>Global Project Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestExpense.cls
@IsTest
private class TestExpense {

  @IsTest(SeeAllData=true)
  private static void testTrigger() {
    SObjectType t = Expense__c.SObjectType;
    fflib_QueryFactory qf = new fflib_QueryFactory(t);
    qf.selectField('Id');
    qf.setCondition('ExpenseValidatedFinance__c = false AND ExpenseValidatedProjectResponsible__c = false AND Expensetracker__c != NULL AND Expensetracker__r.User__r.InternalContactID__c != NULL');
    qf.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
    qf.setLimit(1);

    List<Expense__c> theList = (List<Expense__c>) Database.query(qf.toSOQL());

    if (!theList.isEmpty())
      update theList;
  }

  @IsTest
  private static void callingSaveShouldRegisterNew() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);

    //Given
    Expense__c e = new Expense__c(
        CostsExpenseGross__c = 10
    );
    Application.UnitOfWork.setMock(uowMock);

    // When
    IExpense eDomain = Expense.newInstance(new List<Expense__c> {e});
    eDomain.save(uowMock);

    // Then
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock))
      .registerNew(
          fflib_Match.sObjectWith(
            new Map<SObjectField, Object>{
              Expense__c.CostsExpenseGross__c => e.CostsExpenseGross__c
            }
          )
      );
  }

  @IsTest
  private static void callingSaveShouldRegisterDirty() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);

    //Given
    Expense__c e = new Expense__c(
        Id = fflib_IDGenerator.generate(Expense__c.SObjectType),
        CostsExpenseGross__c = 10
    );
    Application.UnitOfWork.setMock(uowMock);

    // When
    IExpense eDomain = Expense.newInstance(new List<Expense__c> {e});
    eDomain.save(uowMock);

    // Then
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock))
      .registerDirty(
          fflib_Match.sObjectWith(
            new Map<SObjectField, Object>{
              Expense__c.Id => e.Id,
              Expense__c.CostsExpenseGross__c => e.CostsExpenseGross__c
            }
          )
      );
  }

    @IsTest
  private static void callingCallInheritedFieldValueShouldCallDomainAndCommmitWork() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    IInheritedFieldValueMDT domainMock = new Mocks.InheritedFieldValueMDT(mocks);

    //Given
    mocks.startStubbing();
    mocks.when(domainMock.sObjectType()).thenReturn(InheritedFieldValue__mdt.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Domain.setMock(domainMock);

    // When
    new Expense(new List<Expense__c> ()).callInheritedFieldValue(true);

    // Then
    ((IInheritedFieldValueMDT) mocks.verify(domainMock)).go(uowMock, new List<SObject>());
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock)).commitWork();
  }

  @IsTest
  private static void callingCallInheritedFieldValueShouldCallDomain() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    IInheritedFieldValueMDT domainMock = new Mocks.InheritedFieldValueMDT(mocks);

    //Given
    mocks.startStubbing();
    mocks.when(domainMock.sObjectType()).thenReturn(InheritedFieldValue__mdt.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Domain.setMock(domainMock);

    // When
    new Expense(new List<Expense__c> ()).callInheritedFieldValue(false);

    // Then
    ((IInheritedFieldValueMDT) mocks.verify(domainMock)).go(null, new List<SObject>());
  }

  @IsTest
  private static void callingCallParentUpdateShouldCallDomainAndCommmitWork() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    IParentObjectUpdateMDTSelector selectorMock = new Mocks.ParentObjectUpdateMDTSelector(mocks);
    IParentObjectUpdateMDT domainMock = new Mocks.ParentObjectUpdateMDT(mocks);

    //Given
    mocks.startStubbing();
    mocks.when(selectorMock.sObjectType()).thenReturn(ParentObjectUpdate__mdt.SObjectType);
    mocks.when(selectorMock.selectBySourceObj(fflib_Match.anyString())).thenReturn(new List<ParentObjectUpdate__mdt>());
    mocks.when(domainMock.sObjectType()).thenReturn(ParentObjectUpdate__mdt.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Selector.setMock(selectorMock);
    Application.Domain.setMock(domainMock);

    // When
    new Expense(new List<Expense__c> ()).callParentUpdate(new Map<Id, SObject>());

    // Then
    ((IParentObjectUpdateMDTSelector) mocks.verify(selectorMock)).selectBySourceObj(fflib_Match.anyString());
    ((IParentObjectUpdateMDT) mocks.verify(domainMock)).go(uowMock, new List<SObject>(), new Map<Id, SObject>());
    ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock)).commitWork();
  }

  @IsTest
  private static void callingCallUpdateExchangeRateShouldCallDomainAndCommmitWork() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
    IObjectMDTSelector selectorMock = new Mocks.ObjectMDTSelector(mocks);
    IFieldMDT domainMock = new Mocks.FieldMDT(mocks);

    //Given
    Object__mdt obj
      = ((List<Object__mdt>) fflib_ApexMocksUtils.makeRelationship(
        List<Object__mdt>.class,
        new List<Object__mdt> {new Object__mdt()},
        Field__mdt.Object__c,
        new List<List<Field__mdt>> { new List<Field__mdt> {new Field__mdt()}}
      ))[0];
    mocks.startStubbing();
    mocks.when(selectorMock.sObjectType()).thenReturn(Object__mdt.SObjectType);
    mocks.when(selectorMock.selectCurrencyFields(fflib_Match.anyString())).thenReturn(new List<Object__mdt>{obj});
    mocks.when(domainMock.sObjectType()).thenReturn(Field__mdt.SObjectType);
    mocks.stopStubbing();
    Application.UnitOfWork.setMock(uowMock);
    Application.Selector.setMock(selectorMock);
    Application.Domain.setMock(domainMock);

    // When
    new Expense(new List<Expense__c> ()).callUpdateExchangeRate(new Map<Id, SObject>());

    // Then
    ((IObjectMDTSelector) mocks.verify(selectorMock)).selectCurrencyFields(fflib_Match.anyString());
    ((IFieldMDT) mocks.verify(domainMock)).updateExchangeRate(new List<SObject>(), new Map<Id, SObject>());
  }

  @IsTest
  private static void testSetExpenseTracker() {

    // Create mocks
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    IUserSelector selectorMock = new Mocks.UserSelector(mocks);

    //Given
    mocks.startStubbing();
    User u = new User(InternalContactID__c = fflib_IDGenerator.generate(Contact.SObjectType));
    Expense__c e = new Expense__c();
    mocks.when(selectorMock.sObjectType()).thenReturn(User.SObjectType);
    mocks.when(selectorMock.selectById(fflib_Match.anyId())).thenReturn(u);
    mocks.stopStubbing();
    Application.Selector.setMock(selectorMock);

    // When
    new Expense(new List<Expense__c> {e}).setExpenseTracker();

    // Then
    ((IUserSelector) mocks.verify(selectorMock)).selectById(fflib_Match.anyId());
    System.assertEquals(u.InternalContactID__c, e.Expensetracker__c);
  }

  @IsTest
  private static void testSecExchangeRate() {

    Expense__c e = new Expense__c(
        ExpenseDate__c = Date.today(),
        LocalCurrency__c = 'CHF',
        VATPercent__c = '0%',
        CurrencyRateToCHF__c = 0.3,
        RecordTypeId = Utils.getRecordTypeIdByDevName('Expense__c', Expense.CAR_TRAVEL)
    );

    // When
    new Expense(new List<Expense__c> {e}).setSecExchangeRate();

    // Then
    System.assertEquals(0, e.Distance__c);
    System.assertEquals(0, e.DistanceCompensation__c);
    System.assertEquals(0, e.ExpenseGross__c);
    System.assertEquals(0, e.ExpenseGrossApproved__c);
    System.assertNotEquals(null, e.CostsExpenseNet__c);
    System.assertEquals(e.ServiceExpenseNet__c, e.CostsExpenseNet__c);
  }

  @IsTest
  private static void testGetExchangeRate() {

    List<DatedConversionRate> rates = DatedConversionRateSelector.newInstance().selectAll();
    Expense eDomain = new Expense(new List<Expense__c>{new Expense__c()});
    Double exchangeRate = eDomain.getExchangeRate(rates, System.today(), 'CHF');
    System.assert(exchangeRate > 0);

  }

}