force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/User/fields/InternalContactID__c.field-meta.xml
<CustomField>
    <fullName>InternalContactID__c</fullName>
    <label>Internal Contact ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestParentObjectUpdateMDT.cls
@IsTest
public class TestParentObjectUpdateMDT {

  @IsTest
  private static void callingGoShouldRegisterDirty() {

    // Create mock
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);

    // Given
    List<ParentObjectUpdate__mdt> meta = new ParentObjectUpdateMDTSelector().getParentObjectMDTTest();
    Contact c = new Contact(
        Id = fflib_IDGenerator.generate(Contact.SObjectType),
        User__c = fflib_IDGenerator.generate(User.SObjectType)
    ); // child

    Application.UnitOfWork.setMock(uowMock);

    // When
    IParentObjectUpdateMDT domain = ParentObjectUpdateMDT.newInstance(meta);
    domain.go(uowMock, new List<SObject> {c}, null);

    // Then
    ((fflib_ISObjectUnitOfWork)
     mocks.verify(uowMock)).registerDirty(
          fflib_Match.sObjectWith(
            new Map<SObjectField, Object> {
              User.InternalContactID__c => c.Id
            }
          )
     );

  }


}