force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EE-{000000}</displayFormat>
        <label>Expense Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/ControlsDeletion__c.field-meta.xml
<CustomField>
    <fullName>ControlsDeletion__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The field is true in case this field is responsible to control whether a record can be deleted or not. Typically you add a formula field which turns true as soon as the deletion of a record has to be prevented.</inlineHelpText>
    <label>Controls deletion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field__mdt/fields/CurrencyManagementFieldType__c.field-meta.xml
<CustomField>
    <fullName>CurrencyManagementFieldType__c</fullName>
    <description>Currency to CHF exchange rate field =&gt; In this field the Conversion Rate XYZ to CHF on Date ABC is stored
Currency to SDG exchange rate field =&gt; In this field the Conversion Rate XYZ to SGD on Date ABC is stored
Date of exchange rate field =&gt; Field that contains the date ABC used to get conversion rate
Currency field  =&gt; Field that contains the currency XYZ used to get conversion rate</description>
    <inlineHelpText>Turns Dated Currency Management on for this Object. All the Picklist fields have then be to assigned exactly once to one field</inlineHelpText>
    <label>Currency management field type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currency to CHF exchange rate field</fullName>
            </value>
            <value>
                <fullName>Date of exchange rate field</fullName>
            </value>
            <value>
                <fullName>Currency field</fullName>
            </value>
            <value>
                <fullName>Currency to SGD exchange rate field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field__mdt/fields/DeletionErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>DeletionErrorMessage__c</fullName>
    <inlineHelpText>Error message that is presented to the user in case the deletion is not allowed.
Used in Combination with the &quot;Controls deletion&quot; Checkbox</inlineHelpText>
    <label>Deletion error message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Field__mdt/fields/ExcludeFromTemplate__c.field-meta.xml
<CustomField>
    <fullName>ExcludeFromTemplate__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, the value will not be copied to a Project or Package using the Project Clone Function. For instance it can be set, that the Budget on the Source Package is not copied to the cloned Package.</inlineHelpText>
    <label>ExcludeFromTemplate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object__mdt/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <label>APIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FieldMDTSelector.cls
public with sharing class FieldMDTSelector extends fflib_SObjectSelector
  implements IFieldMDTSelector {

  public static IFieldMDTSelector newInstance() {
    return (IFieldMDTSelector) Application.Selector.newInstance(Field__mdt.SObjectType);
  }

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      Field__mdt.APIName__c,
      Field__mdt.ControlsDeletion__c,
      Field__mdt.CurrencyManagementFieldType__c,
	    Field__mdt.DeletionErrorMessage__c,
      Field__mdt.DeveloperName,
      Field__mdt.ExcludeFromTemplate__c,
      Field__mdt.Id,
      Field__mdt.MasterLabel,
      Field__mdt.NamespacePrefix,
      Field__mdt.Object__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Field__mdt.sObjectType;
  }

  public List<Field__mdt> selectDeletionControlFields(String typeName) {
    fflib_QueryFactory query = newQueryFactory();
    query.setCondition('Object__r.ApiName__c = :typeName AND ControlsDeletion__c = true');
    return (List<Field__mdt>) Database.query(query.toSOQL());
  }

  public Set<String> selectExcludedFromTemplate(String typeName) {
    fflib_QueryFactory query = newQueryFactory();
    query.setCondition('Object__r.ApiName__c = :typeName AND ExcludeFromTemplate__c = true');

    List<Field__mdt> fields = (List<Field__mdt>) Database.query(query.toSOQL());
    Set<String> fieldsExcluded = new Set<String>();

    for(Field__mdt f: fields) {
      fieldsExcluded.add(f.APIName__c);
    }

    return fieldsExcluded;
  }

  public List<Field__mdt> getFieldMDTTest() {
    fflib_QueryFactory query = newQueryFactory();
    query.setCondition('Object__r.APIName__c = \'Expense__c\' AND CurrencyManagementFieldType__c != NULL');
    return (List<Field__mdt>) Database.query(query.toSOQL());
  }
}