force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EE-{000000}</displayFormat>
        <label>Expense Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/CostsExpenseGross__c.field-meta.xml
<CustomField>
    <fullName>CostsExpenseGross__c</fullName>
    <label>Costs - Expense Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/CostsExpenseNet__c.field-meta.xml
<CustomField>
    <fullName>CostsExpenseNet__c</fullName>
    <label>Costs - Expense Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/CurrencyRateToCHF__c.field-meta.xml
<CustomField>
    <fullName>CurrencyRateToCHF__c</fullName>
    <description>Currency Rate from Project to CHF</description>
    <label>Currency Rate to CHF</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseDate__c.field-meta.xml
<CustomField>
    <fullName>ExpenseDate__c</fullName>
    <label>Expense Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseGross__c.field-meta.xml
<CustomField>
    <fullName>ExpenseGross__c</fullName>
    <label>Expense Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseGrossApproved__c.field-meta.xml
<CustomField>
    <fullName>ExpenseGrossApproved__c</fullName>
    <label>Expense Gross - Approved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseSubType__c.field-meta.xml
<CustomField>
    <fullName>ExpenseSubType__c</fullName>
    <label>Expense Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CarCompany</fullName>
                <label>Car (Company)</label>
            </value>
            <value>
                <fullName>CarPrivate</fullName>
                <label>Car (Private)</label>
            </value>
            <value>
                <fullName>PublicTransportation</fullName>
                <label>Public Transportation</label>
            </value>
            <value>
                <fullName>CarRental</fullName>
                <label>Car (Rental)</label>
            </value>
            <value>
                <fullName>Taxi</fullName>
            </value>
            <value>
                <fullName>Airplane</fullName>
            </value>
            <value>
                <fullName>Accomodation</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expensetracker__c.field-meta.xml
<CustomField>
    <fullName>Expensetracker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expensetracker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Contact</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>ExpensesExpensetracker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseValidatedFinance__c.field-meta.xml
<CustomField>
    <fullName>ExpenseValidatedFinance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expense Validated - Finance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ExpenseValidatedProjectResponsible__c.field-meta.xml
<CustomField>
    <fullName>ExpenseValidatedProjectResponsible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expense Validated - Project Responsible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/LocalCurrency__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrency__c</fullName>
    <label>Local Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlobalProjectCurrency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>CompanyCreditCard</fullName>
                <label>Company (Credit Card)</label>
            </value>
            <value>
                <fullName>CompanyCash</fullName>
                <label>Company (Cash)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ServiceExpenseNet__c.field-meta.xml
<CustomField>
    <fullName>ServiceExpenseNet__c</fullName>
    <label>Service - Expense Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/VATPercent__c.field-meta.xml
<CustomField>
    <fullName>VATPercent__c</fullName>
    <label>VAT %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0%</fullName>
                <default>true</default>
                <label>0%</label>
            </value>
            <value>
                <fullName>8%</fullName>
            </value>
            <value>
                <fullName>7.7%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/recordTypes/CarTravel.recordType-meta.xml
<RecordType>
    <fullName>CarTravel</fullName>
    <active>true</active>
    <label>Car Travel</label>
</RecordType>

force-app/main/default/objects/Field__mdt/Field__mdt.object-meta.xml
<CustomObject>
    <description>List all the relevant fields of a object and if they have any special function
&gt; currency mgmt, 
&gt; deletion control
&gt; ESR Number
&gt; Template Copy (Project / Package)
Also used to reference fields used on other MTD functions</description>
    <label>Field</label>
    <pluralLabel>Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/InheritedFieldValue__mdt/InheritedFieldValue__mdt.object-meta.xml
<CustomObject>
    <description>Before a record is inserted or / and updated (depending on the metadata settings) values from parent (source) object is populate to child (target) object. 

If the value on the Target Object changes, the Child record will not update automatically. It only updates if it is manually edited. So this function is typically used to freeze a certain value on a child object at the time a record is created or / and updated.

Example: Save the current timekeeper cost center on a time record at creation.</description>
    <label>Inherited field value</label>
    <pluralLabel>Inherited field values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Relevant salesforce standard and custom objects referenced in MTD</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/ParentObjectUpdate__mdt/ParentObjectUpdate__mdt.object-meta.xml
<CustomObject>
    <label>Parent object update</label>
    <pluralLabel>Parent object updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/User/fields/InternalContactID__c.field-meta.xml
<CustomField>
    <fullName>InternalContactID__c</fullName>
    <label>Internal Contact ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/GlobalProjectCurrency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <masterLabel>Global Project Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Expense.cls
public with sharing class Expense extends fflib_SObjectDomain
    implements IExpense {

    public static final String CAR_TRAVEL = 'CarTravel';

    public static IExpense newInstance(List<Expense__c> records) {
        return (IExpense) Application.Domain.newInstance(records);
    }

    public Expense(List<Expense__c> records) {
        super(records);
    }

    public override void onBeforeInsert() {
        setExpenseTracker();
        callInheritedFieldValue(false);
        callUpdateExchangeRate(null);
        setSecExchangeRate();
    }

    public override void onBeforeUpdate(Map<Id,SObject> oldRecords) {
        setExpenseTracker();
        callInheritedFieldValue(false);
        callUpdateExchangeRate(oldRecords);
        setSecExchangeRate();
    }

    public override void onBeforeDelete() {
        List<Field__mdt> fields = FieldMDTSelector.newInstance().selectDeletionControlFields(this.getSObjectType().getDescribe().getName());
        IFieldMDT fieldDomain = FieldMDT.newInstance(fields);
        fieldDomain.controlDeletion(records);
    }

    public override void onAfterInsert() {
        callParentUpdate(null);
    }

    public override void onAfterUpdate(Map<Id,SObject> oldRecords) {
        callParentUpdate(oldRecords);
    }

    public void save(fflib_ISObjectUnitOfWork uow) {

        for (Expense__c e: (List<Expense__c>) records) {
            //setPicklistValues(e);

            if (e.Id == null)
                uow.registerNew(e);
            else
                uow.registerDirty(e);
        }

    }

    private void setPicklistValues(Expense__c e) {
        if (e.PaymentType__c != null)
            e.PaymentType__c = Picklist.get(Expense__c.PaymentType__c, e.PaymentType__c);

        if (e.ExpenseSubType__c != null)
            e.ExpenseSubType__c = Picklist.get(Expense__c.ExpenseSubType__c, e.ExpenseSubType__c);
    }

    @TestVisible
    private void callParentUpdate(Map<Id,SObject> oldRecords) {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        List<ParentObjectUpdate__mdt> pous = ParentObjectUpdateMDTSelector.newInstance().selectBySourceObj(this.getSObjectType().getDescribe().getName());
        IParentObjectUpdateMDT pouDomain = ParentObjectUpdateMDT.newInstance(pous);

        pouDomain.go(uow, records, oldRecords);
        uow.commitWork();
    }

    @TestVisible
    private void callUpdateExchangeRate(Map<Id,SObject> oldRecords){
        List<Object__mdt> objs = ObjectMDTSelector.newInstance().selectCurrencyFields(this.getSObjectType().getDescribe().getName());

        //if we have currency fields and currency conversion is endabled then update
        if(objs.size() > 0 && objs[0].Fields__r != null){
            IFieldMDT fieldDomain = FieldMDT.newInstance(objs[0].Fields__r);
            fieldDomain.updateExchangeRate(records, oldRecords);
        }
    }

    @TestVisible
    private void callInheritedFieldValue(Boolean isUpdate) {
        List<InheritedFieldValue__mdt> inheritedFValues = InheritedFieldValueMDTSelector.newInstance().selectByTargetObj(this.getSObjectType().getDescribe().getName());
        IInheritedFieldValueMDT inheritedFVDomain = InheritedFieldValueMDT.newInstance(inheritedFValues);

        if (isUpdate) {
            fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
            inheritedFVDomain.go(uow, records);
            uow.commitWork();
        } else {
            inheritedFVDomain.go(null, records);
        }

    }

    @TestVisible
    private void setExpenseTracker() {
        User u = UserSelector.newInstance().selectById(UserInfo.getUserId());

        for (Expense__c e : (List<Expense__c>) records) {
            if (e.Expensetracker__c == null) {
                e.Expensetracker__c = u.InternalContactID__c;
            }
        }

    }

    @TestVisible
    private void setSecExchangeRate() {
        List<DatedConversionRate> rates = DatedConversionRateSelector.newInstance().selectAll();
        Id recordTypeCarTravel = Utils.getRecordTypeIdByDevName('Expense__c', CAR_TRAVEL);

        for (Expense__c e : (List<Expense__c>) records) {

            if (e.RecordTypeId == recordTypeCarTravel) {
                e.Distance__c = e.Distance__c == null ? 0 : e.Distance__c;
                e.DistanceCompensation__c = e.DistanceCompensation__c == null ? 0 : e.DistanceCompensation__c;
                e.ExpenseGross__c = e.Distance__c * e.DistanceCompensation__c;
            }

            if (!e.ExpenseValidatedFinance__c)
                e.ExpenseGrossApproved__c = e.ExpenseGross__c;

            e.LocalCurrencyToCHF__c = getExchangeRate(rates, e.ExpenseDate__c, e.LocalCurrency__c);
            e.CostsExpenseGross__c = e.ExpenseGrossApproved__c * ((e.LocalCurrencyToCHF__c *1) / e.CurrencyRateToCHF__c);

            if (e.VATPercent__c != null) {
                Double numberVAT = Double.valueOf(e.VATPercent__c.replace('%', ''));
                e.CostsExpenseNet__c = e.CostsExpenseGross__c / (1 + numberVAT/100);
            }

            if (!e.ExpenseValidatedProjectResponsible__c)
                e.ServiceExpenseNet__c = e.CostsExpenseNet__c;

        }


    }

    @TestVisible
    private Double getExchangeRate(List<DatedConversionRate> rates, Date dateOfRate, String isoCode) {
        Double exchangeRate = 0;
        for(DatedConversionRate r : rates) {
            if(r.IsoCode == isoCode && r.StartDate <= dateOfRate && r.NextStartDate > dateOfRate && r.ConversionRate > 0) {
                exchangeRate = 1/r.ConversionRate;
                break;
            }
        }
        return exchangeRate;
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Expense(sObjectList);
        }
    }
}