force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EE-{000000}</displayFormat>
        <label>Expense Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Package__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ServiceExpenseNet__c.field-meta.xml
<CustomField>
    <fullName>ServiceExpenseNet__c</fullName>
    <label>Service - Expense Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/InvoicePos__c.object-meta.xml
<CustomObject>
    <label>Invoice Pos</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Invoice Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePos__c/fields/InvoicePositionAmount__c.field-meta.xml
<CustomField>
    <fullName>InvoicePositionAmount__c</fullName>
    <label>Invoice Position - Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <label>Package Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/BudgetAssignPackage__c.field-meta.xml
<CustomField>
    <fullName>BudgetAssignPackage__c</fullName>
    <formula>CASE( RecordType.DeveloperName , 
&quot;Time&quot;,BudgetAssignTotalTime__c,
&quot;Expense&quot;, BudgetAssignTotalExpense__c ,
&quot;SupplierCosts&quot;, BudgetAssignTotalSupplierCosts__c ,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Budget Assign - Package</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/InvoicePOSTotalExpense__c.field-meta.xml
<CustomField>
    <fullName>InvoicePOSTotalExpense__c</fullName>
    <label>Invoice POS - Total Expense</label>
    <summarizedField>InvoicePos__c.InvoicePositionAmount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoicePos__c.PackageType__c</field>
        <operation>equals</operation>
        <value>Expense</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoicePos__c.PackageName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/InvoicePOSTotalSupplierCosts__c.field-meta.xml
<CustomField>
    <fullName>InvoicePOSTotalSupplierCosts__c</fullName>
    <label>Invoice POS - Total Supplier Costs</label>
    <summarizedField>InvoicePos__c.InvoicePositionAmount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoicePos__c.PackageType__c</field>
        <operation>equals</operation>
        <value>SupplierCosts, LicenseDirect, LicenseProvision</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoicePos__c.PackageName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/InvoicePOSTotalTime__c.field-meta.xml
<CustomField>
    <fullName>InvoicePOSTotalTime__c</fullName>
    <label>Invoice POS - Total Time</label>
    <summarizedField>InvoicePos__c.InvoicePositionAmount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoicePos__c.PackageType__c</field>
        <operation>equals</operation>
        <value>Time</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoicePos__c.PackageName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <description>Diese Feld wird verwendet für die Zuweisung von Finance Account im ILV Prozess (Name Mapping)</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package Type Finance Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ServicesTotalAmountCHF__c.field-meta.xml
<CustomField>
    <fullName>ServicesTotalAmountCHF__c</fullName>
    <formula>CASE( RecordType.DeveloperName , 
&quot;Time&quot;,ServicesTotalTimeCHF__c,
&quot;Expense&quot;,ServicesTotalExpenseCHF__c,
&quot;SupplierCosts&quot;,ServicesTotalSupplierCostsCHF__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Services - Total Amount (CHF)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Time.recordType-meta.xml
<RecordType>
    <fullName>Time</fullName>
    <active>true</active>
    <label>Time</label>
</RecordType>

force-app/main/default/objects/SupplierCosts__c/SupplierCosts__c.object-meta.xml
<CustomObject>
    <label>Supplier Costs</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>Supplier Costs Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCosts__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <filterItems>
            <field>Package__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier Costs, License (Provision), License (Direct)</value>
        </filterItems>
        <filterItems>
            <field>Package__c.ProjectName__c</field>
            <operation>equals</operation>
            <valueField>$Source.ProjektName__c</valueField>
        </filterItems>
        <filterItems>
            <field>Package__c.ProjectName__r.ProjectNr__c</field>
            <operation>notEqual</operation>
            <value>P-105657</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Supplier Costs</relationshipLabel>
    <relationshipName>SupplierCosts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/ServiceSupplierCostsNetPM__c.field-meta.xml
<CustomField>
    <fullName>ServiceSupplierCostsNetPM__c</fullName>
    <label>Service -  Supplier Costs Net (PM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Time__c/fields/ServiceTotalTime__c.field-meta.xml
<CustomField>
    <fullName>ServiceTotalTime__c</fullName>
    <formula>DurationHhMmN__c * RateHour__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service - Total Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestPackageBean.cls
@IsTest
private class TestPackageBean {

  @IsTest
  private static void testSetBudgetAndServicesTotal() {

    JSONGenerator gen = JSON.createGenerator(true);
    gen.writeStartObject();
    gen.writeNumberField('BudgetAssignPackage__c', 0);
    gen.writeNumberField('ServicesTotalAmountCHF__c', 0);
    gen.writeEndObject();

    Package__c pck = (Package__c) JSON.deserialize(gen.getAsString(), Package__c.class);

    PackageBean bpGroup = new PackageBean();
    bpGroup.budget = 1;
    bpGroup.servicesTotal = 1;

    PackageBean bp = new PackageBean();
    bp.pck = pck;
    bp.setBudgetAndServicesTotal(bpGroup);

    System.assertEquals(10, bp.budget);
    System.assertEquals(0, bp.servicesTotal);
    System.assertEquals(11, bpGroup.budget);
    System.assertEquals(1, bpGroup.servicesTotal);
  }

  @IsTest
  private static void testSetPositionShouldSumPostionAmountInPackageGroup() {

    Package__c pck = new Package__c(
      Id = fflib_IDGenerator.generate(Package__c.SObjectType)
    );

    InvoicePos__c pos = new InvoicePos__c(
      Id = fflib_IDGenerator.generate(InvoicePos__c.SObjectType),
      InvoicePositionAmount__c = 10
    );

    Package__c fullPck
      = ((List<Package__c>) fflib_ApexMocksUtils.makeRelationship(
        List<Package__c>.class,
        new List<Package__c> {pck},
        InvoicePos__c.PackageName__c,
        new List<List<InvoicePos__c>> { new List<InvoicePos__c> {pos}}
      ))[0];

    PackageBean bpGroup = new PackageBean();
    bpGroup.setPosition(null);

    System.assertEquals(0, bpGroup.position.InvoicePositionAmount__c);

    PackageBean bp = new PackageBean();
    bp.pck = fullPck;
    bp.setPosition(bpGroup);

    System.assertEquals(bp.position.Id, pos.Id);
    System.assertEquals(bpGroup.position.InvoicePositionAmount__c, pos.InvoicePositionAmount__c);

  }

  @IsTest
  private static void testSetInvoiceAndInvoiceNoDraftTypeTime() {

    JSONGenerator gen = JSON.createGenerator(true);
    gen.writeStartObject();
    gen.writeStringField('PackageType__c', 'Time');
    gen.writeNumberField('InvoicePOSTotalTime__c', 1);
    gen.writeEndObject();

    Package__c pck = (Package__c) JSON.deserialize(gen.getAsString(), Package__c.class);
    pck.Id = fflib_IDGenerator.generate(Package__c.SObjectType);

    InvoicePos__c pos = new InvoicePos__c(
      Id = fflib_IDGenerator.generate(InvoicePos__c.SObjectType),
      InvoicePositionAmount__c = 10
    );

    PackageBean bpGroup = new PackageBean();
    bpGroup.invoice = 10;
    bpGroup.invoiceNoDraft = 2;

    PackageBean bp = new PackageBean();
    bp.pck = pck;
    bp.position = pos;
    bp.setInvoiceAndInvoiceNoDraft(bpGroup);

    System.assertEquals(1, bp.invoice);
    System.assertEquals(1, bp.invoiceNoDraft);
    System.assertEquals(11, bpGroup.invoice);
    System.assertEquals(3, bpGroup.invoiceNoDraft);
  }

  @IsTest
  private static void testSetInvoiceAndInvoiceNoDraftTypeExpense() {

    JSONGenerator gen = JSON.createGenerator(true);
    gen.writeStartObject();
    gen.writeStringField('PackageType__c', PackageDomain.TYPE_EXPENSE);
    gen.writeNumberField('InvoicePOSTotalExpense__c', 1);
    gen.writeEndObject();

    Package__c pck = (Package__c) JSON.deserialize(gen.getAsString(), Package__c.class);
    pck.Id = fflib_IDGenerator.generate(Package__c.SObjectType);

    InvoicePos__c pos = new InvoicePos__c(
      Id = fflib_IDGenerator.generate(InvoicePos__c.SObjectType),
      InvoicePositionAmount__c = 10
    );

    PackageBean bpGroup = new PackageBean();
    bpGroup.invoice = 10;
    bpGroup.invoiceNoDraft = 2;

    PackageBean bp = new PackageBean();
    bp.pck = pck;
    bp.position = pos;
    bp.setInvoiceAndInvoiceNoDraft(bpGroup);

    System.assertEquals(1, bp.invoice);
    System.assertEquals(1, bp.invoiceNoDraft);
    System.assertEquals(11, bpGroup.invoice);
    System.assertEquals(3, bpGroup.invoiceNoDraft);
  }

  @IsTest
  private static void testSetInvoiceAndInvoiceNoDraftTypeSupplierCosts() {

    JSONGenerator gen = JSON.createGenerator(true);
    gen.writeStartObject();
    gen.writeStringField('PackageType__c', PackageDomain.TYPE_SUPPLIER_COSTS);
    gen.writeNumberField('InvoicePOSTotalSupplierCosts__c', 1);
    gen.writeEndObject();

    Package__c pck = (Package__c) JSON.deserialize(gen.getAsString(), Package__c.class);
    pck.Id = fflib_IDGenerator.generate(Package__c.SObjectType);

    InvoicePos__c pos = new InvoicePos__c(
      Id = fflib_IDGenerator.generate(InvoicePos__c.SObjectType),
      InvoicePositionAmount__c = 10
    );

    PackageBean bpGroup = new PackageBean();
    bpGroup.invoice = 10;
    bpGroup.invoiceNoDraft = 2;

    PackageBean bp = new PackageBean();
    bp.pck = pck;
    bp.position = pos;
    bp.setInvoiceAndInvoiceNoDraft(bpGroup);

    System.assertEquals(1, bp.invoice);
    System.assertEquals(1, bp.invoiceNoDraft);
    System.assertEquals(11, bpGroup.invoice);
    System.assertEquals(3, bpGroup.invoiceNoDraft);
  }

  @IsTest
  private static void testSetAvailableFunds() {

    JSONGenerator gen = JSON.createGenerator(true);
    gen.writeStartObject();
    gen.writeNumberField('BudgetAssignPackage__c', 10);
    gen.writeEndObject();

    Package__c pck = (Package__c) JSON.deserialize(gen.getAsString(), Package__c.class);

    PackageBean bpGroup = new PackageBean();

    PackageBean bp = new PackageBean();
    bp.pck = pck;
    bp.invoice = 5;
    bp.setAvaliableFunds(bpGroup);

    System.assertEquals(5, bp.availableFunds);
    System.assertEquals(5, bpGroup.availableFunds);
  }

  @IsTest
  private static void testSetServiceTotalDRTime() {

    JSONGenerator pJSON = JSON.createGenerator(true);
    pJSON.writeStartObject();
    pJSON.writeStringField('PackageType__c', PackageDomain.TYPE_TIME);
    pJSON.writeEndObject();

    Package__c pck = (Package__c) JSON.deserialize(pJSON.getAsString(), Package__c.class);
    pck.Id = fflib_IDGenerator.generate(Package__c.SObjectType);

    JSONGenerator tJSON = JSON.createGenerator(true);
    tJSON.writeStartObject();
    tJSON.writeNumberField('ServiceTotalTime__c', 10);
    tJSON.writeEndObject();

    Time__c t = (Time__c) JSON.deserialize(tJSON.getAsString(), Time__c.class);
    t.Id = fflib_IDGenerator.generate(Time__c.SObjectType);

    Package__c fullPck
      = ((List<Package__c>) fflib_ApexMocksUtils.makeRelationship(
        List<Package__c>.class,
        new List<Package__c> {pck},
        Time__c.Package__c,
        new List<List<Time__c>> { new List<Time__c> {t}}
      ))[0];

    PackageBean bpGroup = new PackageBean();
    bpGroup.servicesTotalDR = 5;

    PackageBean bp = new PackageBean();
    bp.pck = fullPck;
    bp.setServicesTotalDR(bpGroup);

    System.assertEquals(10, bp.servicesTotalDR);
    System.assertEquals(15, bpGroup.servicesTotalDR);

  }

  @IsTest
  private static void testSetServiceTotalDRExpenses() {

    JSONGenerator pJSON = JSON.createGenerator(true);
    pJSON.writeStartObject();
    pJSON.writeStringField('PackageType__c', PackageDomain.TYPE_EXPENSE);
    pJSON.writeEndObject();

    Package__c pck = (Package__c) JSON.deserialize(pJSON.getAsString(), Package__c.class);
    pck.Id = fflib_IDGenerator.generate(Package__c.SObjectType);

    JSONGenerator eJSON = JSON.createGenerator(true);
    eJSON.writeStartObject();
    eJSON.writeNumberField('ServiceExpenseNet__c', 10);
    eJSON.writeEndObject();

    Expense__c e = (Expense__c) JSON.deserialize(eJSON.getAsString(), Expense__c.class);
    e.Id = fflib_IDGenerator.generate(Expense__c.SObjectType);

    Package__c fullPck
      = ((List<Package__c>) fflib_ApexMocksUtils.makeRelationship(
        List<Package__c>.class,
        new List<Package__c> {pck},
        Expense__c.Package__c,
        new List<List<Expense__c>> { new List<Expense__c> {e}}
      ))[0];

    PackageBean bpGroup = new PackageBean();
    bpGroup.servicesTotalDR = 5;

    PackageBean bp = new PackageBean();
    bp.pck = fullPck;
    bp.setServicesTotalDR(bpGroup);

    System.assertEquals(10, bp.servicesTotalDR);
    System.assertEquals(15, bpGroup.servicesTotalDR);

  }

  @IsTest
  private static void testSetServiceTotalDRSuplierCosts() {

    JSONGenerator pJSON = JSON.createGenerator(true);
    pJSON.writeStartObject();
    pJSON.writeStringField('PackageType__c', PackageDomain.TYPE_SUPPLIER_COSTS);
    pJSON.writeEndObject();

    Package__c pck = (Package__c) JSON.deserialize(pJSON.getAsString(), Package__c.class);
    pck.Id = fflib_IDGenerator.generate(Package__c.SObjectType);

    JSONGenerator scJSON = JSON.createGenerator(true);
    scJSON.writeStartObject();
    scJSON.writeNumberField('ServiceSupplierCostsNetPM__c', 10);
    scJSON.writeEndObject();

    SupplierCosts__c sc = (SupplierCosts__c) JSON.deserialize(scJSON.getAsString(), SupplierCosts__c.class);
    sc.Id = fflib_IDGenerator.generate(SupplierCosts__c.SObjectType);

    Package__c fullPck
      = ((List<Package__c>) fflib_ApexMocksUtils.makeRelationship(
        List<Package__c>.class,
        new List<Package__c> {pck},
        SupplierCosts__c.PackageName__c,
        new List<List<SupplierCosts__c>> { new List<SupplierCosts__c> {sc}}
      ))[0];

    PackageBean bpGroup = new PackageBean();
    bpGroup.servicesTotalDR = 5;

    PackageBean bp = new PackageBean();
    bp.pck = fullPck;
    bp.setServicesTotalDR(bpGroup);

    System.assertEquals(10, bp.servicesTotalDR);
    System.assertEquals(15, bpGroup.servicesTotalDR);

  }

  @IsTest
  private static void testEquals() {
    Package__c pck = new Package__c(Id = fflib_IDGenerator.generate(Package__c.SObjectType));

    PackageBean pb1 = new PackageBean();
    PackageBean pb2 = new PackageBean();
    pb1.pck = pck;
    pb2.pck = pck;

    System.assert(pb1.equals(pb2), 'oh, they are equal!');
  }


  @IsTest
  private static void testHashCode() {
    Package__c pck = new Package__c(Id = fflib_IDGenerator.generate(Package__c.SObjectType));

    PackageBean pb1 = new PackageBean();
    PackageBean pb2 = new PackageBean();
    pb1.pck = pck;
    pb2.pck = pck;

    System.assert(pb1.hashCode() == pb1.hashCode(), 'oh, they are equal!');
  }


}