force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EE-{000000}</displayFormat>
        <label>Expense Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Package__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ServiceExpenseNet__c.field-meta.xml
<CustomField>
    <fullName>ServiceExpenseNet__c</fullName>
    <label>Service - Expense Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/InvoicePos__c.object-meta.xml
<CustomObject>
    <label>Invoice Pos</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Invoice Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePos__c/fields/InvoicePositionAmount__c.field-meta.xml
<CustomField>
    <fullName>InvoicePositionAmount__c</fullName>
    <label>Invoice Position - Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <label>Package Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/BudgetAssignPackage__c.field-meta.xml
<CustomField>
    <fullName>BudgetAssignPackage__c</fullName>
    <formula>CASE( RecordType.DeveloperName , 
&quot;Time&quot;,BudgetAssignTotalTime__c,
&quot;Expense&quot;, BudgetAssignTotalExpense__c ,
&quot;SupplierCosts&quot;, BudgetAssignTotalSupplierCosts__c ,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Budget Assign - Package</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/InvoicePOSTotalExpense__c.field-meta.xml
<CustomField>
    <fullName>InvoicePOSTotalExpense__c</fullName>
    <label>Invoice POS - Total Expense</label>
    <summarizedField>InvoicePos__c.InvoicePositionAmount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoicePos__c.PackageType__c</field>
        <operation>equals</operation>
        <value>Expense</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoicePos__c.PackageName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/InvoicePOSTotalSupplierCosts__c.field-meta.xml
<CustomField>
    <fullName>InvoicePOSTotalSupplierCosts__c</fullName>
    <label>Invoice POS - Total Supplier Costs</label>
    <summarizedField>InvoicePos__c.InvoicePositionAmount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoicePos__c.PackageType__c</field>
        <operation>equals</operation>
        <value>SupplierCosts, LicenseDirect, LicenseProvision</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoicePos__c.PackageName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/InvoicePOSTotalTime__c.field-meta.xml
<CustomField>
    <fullName>InvoicePOSTotalTime__c</fullName>
    <label>Invoice POS - Total Time</label>
    <summarizedField>InvoicePos__c.InvoicePositionAmount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoicePos__c.PackageType__c</field>
        <operation>equals</operation>
        <value>Time</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoicePos__c.PackageName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <description>Diese Feld wird verwendet für die Zuweisung von Finance Account im ILV Prozess (Name Mapping)</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package Type Finance Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/SupplierCosts__c/SupplierCosts__c.object-meta.xml
<CustomObject>
    <label>Supplier Costs</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>Supplier Costs Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCosts__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <filterItems>
            <field>Package__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier Costs, License (Provision), License (Direct)</value>
        </filterItems>
        <filterItems>
            <field>Package__c.ProjectName__c</field>
            <operation>equals</operation>
            <valueField>$Source.ProjektName__c</valueField>
        </filterItems>
        <filterItems>
            <field>Package__c.ProjectName__r.ProjectNr__c</field>
            <operation>notEqual</operation>
            <value>P-105657</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Supplier Costs</relationshipLabel>
    <relationshipName>SupplierCosts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/ServiceSupplierCostsNetPM__c.field-meta.xml
<CustomField>
    <fullName>ServiceSupplierCostsNetPM__c</fullName>
    <label>Service -  Supplier Costs Net (PM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Time__c/fields/ServiceTotalTime__c.field-meta.xml
<CustomField>
    <fullName>ServiceTotalTime__c</fullName>
    <formula>DurationHhMmN__c * RateHour__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service - Total Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PackageBean.cls
public with sharing class PackageBean {

  @AuraEnabled
  public Package__c pck {get; set;}

  @AuraEnabled
  public Double budget {get; set;}

  @AuraEnabled
  public Double invoice {get; set;}

  @AuraEnabled
  public Double availableFunds {get; set;}

  @AuraEnabled
  public Double servicesTotal {get; set;}

  @AuraEnabled
  public Double servicesTotalDR {get; set;}

  @AuraEnabled
  public Double invoiceNoDraft {get; set;}

  @AuraEnabled
  public Double invoiceInProgress {get; set;}

  @AuraEnabled
  public InvoicePos__c position {get; set;}

  /*
   * Dummy fields for the sake of LockerService
   */
  @AuraEnabled
  public Boolean showModalForBillingPositionText {get; set;}

  @AuraEnabled
  public Double calculatedAvailableFunds {get; set;}

  @AuraEnabled
  public Double allowanceTotal {get; set;}

  @AuraEnabled
  public Boolean showPosition {get; set;}

  @AuraEnabled
  public Boolean showPositionAmount {get; set;}

  @AuraEnabled
  public Boolean showInvoiceText {get; set;}

  @AuraEnabled
  public String packageBillingPositionText {get; set;}

  /**
  * Default constructor
  * mainly used for testing
  **/
  public PackageBean() {
    this.setDefaults();
  }

  /**
  * Group constructor
  * @p group package to be initialized
  **/
  public PackageBean(Package__c p) {
    this.pck = p;
    this.setDefaults();
    this.setPosition(null);
  }

  /**
  * Subgroup constructor
  * @p subpackage to be summed up
  * @pGroup parent package to be proccessed alongside to its subpackage
  **/
  public PackageBean(Package__c p, PackageBean pGroup) {
    this.pck = p;
    this.setDefaults();
    this.sumup(pGroup);
  }

  private void sumup(PackageBean pGroup) {
    setBudgetAndServicesTotal(pGroup);
    setPosition(pGroup);
    setInvoiceAndInvoiceNoDraft(pGroup);
    setAvaliableFunds(pGroup);
    setServicesTotalDR(pGroup);
  }

  public void setBudgetAndServicesTotal(PackageBean pGroup) {
    if (this.pck.BudgetAssignPackage__c != null) {
      this.budget = Test.isRunningTest() ? 10 : this.pck.BudgetAssignPackage__c;

      if (!isGroupNull(pGroup))
        pGroup.budget += Test.isRunningTest() ? 10 : this.pck.BudgetAssignPackage__c;
    }

    if (this.pck.ServicesTotalAmount__c != null) {
      this.servicesTotal = Test.isRunningTest() ? 10 : this.pck.ServicesTotalAmount__c;

      if (!isGroupNull(pGroup))
        pGroup.servicesTotal += Test.isRunningTest() ? 10 : this.pck.ServicesTotalAmount__c;
    }
  }

  public void setPosition(PackageBean pGroup) {
    Boolean isSubpackage = (pGroup != null);
    Boolean hasPosition = this.pck != null && this.pck.InvoicePos__r != null && this.pck.InvoicePos__r.size() == 1;

    if (hasPosition) {
      this.position = this.pck.InvoicePos__r;
      this.invoiceInProgress = this.position.InvoicePositionAmount__c;

      if (isSubpackage && !isGroupNull(pGroup)) {
        pGroup.position.InvoicePositionAmount__c += this.position.InvoicePositionAmount__c;
        pGroup.invoiceInProgress += this.position.InvoicePositionAmount__c;
      }
    } else {
      this.position = new InvoicePos__c(InvoicePositionAmount__c = 0);
    }
  }

  public void setInvoiceAndInvoiceNoDraft(PackageBean pGroup) {
    if (this.position != null) {

      if (this.pck.PackageType__c == PackageDomain.TYPE_TIME) {
        // this.invoice = this.pck.InvoicePOSTotalTime__c + this.position.InvoicePositionAmount__c;
        this.invoice = this.pck.InvoicePOSTotalTime__c;
        this.invoiceNoDraft = this.pck.InvoicePOSTotalTime__c;
      } else if (this.pck.PackageType__c == PackageDomain.TYPE_EXPENSE) {
        // this.invoice = this.pck.InvoicePOSTotalExpense__c + this.position.InvoicePositionAmount__c;
        this.invoice = this.pck.InvoicePOSTotalExpense__c;
        this.invoiceNoDraft = this.pck.InvoicePOSTotalExpense__c;
      } else if (this.pck.PackageType__c == PackageDomain.TYPE_SUPPLIER_COSTS) {
        // this.invoice = this.pck.InvoicePOSTotalSupplierCosts__c + this.position.InvoicePositionAmount__c;
        this.invoice = this.pck.InvoicePOSTotalSupplierCosts__c;
        this.invoiceNoDraft = this.pck.InvoicePOSTotalSupplierCosts__c;
      }

      if (!isGroupNull(pGroup)) {
        pGroup.invoice += this.invoice;
        pGroup.invoiceNoDraft += this.invoiceNoDraft;
      }
    }
  }

  public void setAvaliableFunds(PackageBean pGroup) {
    this.availableFunds = this.pck.BudgetAssignPackage__c - this.invoice;

    if (!isGroupNull(pGroup))
      pGroup.availableFunds += this.availableFunds;
  }

  public void setServicesTotalDR(PackageBean pGroup) {
    if (this.pck.PackageType__c == PackageDomain.TYPE_TIME) {
      for (Time__c t : this.pck.Time__r) {
        if (t.ServiceTotalTime__c != null)
          this.servicesTotalDR += t.ServiceTotalTime__c;
      }
    } else if (this.pck.PackageType__c == PackageDomain.TYPE_EXPENSE) {
      for (Expense__c e : this.pck.Expenses__r) {
        if (e.ServiceExpenseNet__c != null)
          this.servicesTotalDR += e.ServiceExpenseNet__c;
      }
    } else if (this.pck.PackageType__c == PackageDomain.TYPE_SUPPLIER_COSTS) {
      for (SupplierCosts__c sc : this.pck.SupplierCosts__r) {
        if (sc.ServiceSupplierCostsNetPM__c != null)
          this.servicesTotalDR += sc.ServiceSupplierCostsNetPM__c;
      }
    }

    if (!isGroupNull(pGroup))
      pGroup.servicesTotalDR += this.servicesTotalDR;
  }

  public Boolean equals(Object obj) {
    if (obj instanceof PackageBean) {
      PackageBean pb = (PackageBean) obj;
      return (this.pck.Id == pb.pck.Id);
    }
    return false;
  }

  public Integer hashCode() {
    return 31 * System.hashCode(String.valueOf(this.pck.Id));
  }

  private Boolean isGroupNull(PackageBean pGroup) {
    return pGroup == null;
  }

  private void setDefaults() {
    this.budget = 0;
    this.invoice = 0;
    this.availableFunds = 0;
    this.servicesTotal = 0;
    this.servicesTotalDR = 0;
    this.invoiceNoDraft = 0;
    this.invoiceInProgress = 0;

    this.showModalForBillingPositionText = false;
    this.calculatedAvailableFunds = 0;
    this.allowanceTotal = 0;
    this.showPosition = false;
    this.showPositionAmount = false;
    this.showInvoiceText = false;
    this.packageBillingPositionText = '';
  }

}