force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EE-{000000}</displayFormat>
        <label>Expense Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCosts__c/SupplierCosts__c.object-meta.xml
<CustomObject>
    <label>Supplier Costs</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>Supplier Costs Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCosts__c/recordTypes/SupplierCosts.recordType-meta.xml
<RecordType>
    <fullName>SupplierCosts</fullName>
    <active>true</active>
    <label>Supplier Costs</label>
</RecordType>

force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/AbacusTimeType__c.field-meta.xml
<CustomField>
    <fullName>AbacusTimeType__c</fullName>
    <label>Abacus Time Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>1036</fullName>
            </value>
            <value>
                <fullName>1037</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>1100</fullName>
            </value>
            <value>
                <fullName>1135</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>130</fullName>
            </value>
            <value>
                <fullName>140</fullName>
            </value>
            <value>
                <fullName>150</fullName>
            </value>
            <value>
                <fullName>155</fullName>
            </value>
            <value>
                <fullName>160</fullName>
            </value>
            <value>
                <fullName>200</fullName>
            </value>
            <value>
                <fullName>300</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time__c/fields/DateFrom__c.field-meta.xml
<CustomField>
    <fullName>DateFrom__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date (From)</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/DurationHhMmN__c.field-meta.xml
<CustomField>
    <fullName>DurationHhMmN__c</fullName>
    <label>Duration</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/Timetracker__c.field-meta.xml
<CustomField>
    <fullName>Timetracker__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Timetracker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal Contact</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/TimeValidatedHumanResources__c.field-meta.xml
<CustomField>
    <fullName>TimeValidatedHumanResources__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Time Validated - Human Resources</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HumanResourcesTabController.cls
public class HumanResourcesTabController {

  /*
   * Load the time entries
   */
  @AuraEnabled
  public static List<Time__c> listTimeEntries(String dateFrom, String dateUntil, Id timetracker) {

    Date parsedDateFrom = Date.valueOf(dateFrom);
    Date parsedDateUntil = Date.valueOf(dateUntil);

    return [
      SELECT AbacusTimeType__c, DateFrom__c, DurationHhMmN__c, Id, Timetracker__c, TimeValidatedHumanResources__c
      FROM Time__c
      WHERE Id != null
        AND Timetracker__c = :timetracker
        AND DateFrom__c >= :parsedDateFrom
        AND DateFrom__c <= :parsedDateUntil
      LIMIT 2000
    ];

  }

  /*
   * Load the contacts for an account so we can paginate through them
   */
  @AuraEnabled
  public static List<Contact> loadContactsForAccount(String filterById) {

    String recordTypeName = 'Internal Contact';
    String baseQuery = 'SELECT Id, Name, Account.Name, AccountId FROM Contact WHERE RecordType.Name = :recordTypeName ';

    if(filterById != null){
      baseQuery += ' and AccountId = :filterById ';
    }

    baseQuery += ' ORDER BY LastName, FirstName';

    return Database.query(baseQuery);
  }

  @AuraEnabled
  public static PackageSelector.Model get(String params) {
    PackageSelector.Params parameters = (PackageSelector.Params) JSON.deserialize(params, PackageSelector.Params.class);
    return PackageService.get(parameters);
  }

  @AuraEnabled
  public static void saveData(List<Time__c> times, List<Expense__c> expenses, List<SupplierCosts__c> scList) {

    if (times != null) {
        fflib_SObjectDomain.getTriggerEvent(TimeDomain.class).disableAll();
        TimeService.save(new List<Time__c>(times));
    }

    if (expenses != null) {
        fflib_SObjectDomain.getTriggerEvent(Expense.class).disableAll();
        ExpenseService.save(new List<Expense__c>(expenses));
    }

    if (scList != null) {
        fflib_SObjectDomain.getTriggerEvent(SupplierCosts.class).disableAll();
        SupplierCostsService.save(new List<SupplierCosts__c>(scList));
    }

  }

}