force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EE-{000000}</displayFormat>
        <label>Expense Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/ExpenseDate__c.field-meta.xml
<CustomField>
    <fullName>ExpenseDate__c</fullName>
    <label>Expense Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Package__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ServiceExpenseNet__c.field-meta.xml
<CustomField>
    <fullName>ServiceExpenseNet__c</fullName>
    <label>Service - Expense Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/FinanceDate__c.field-meta.xml
<CustomField>
    <fullName>FinanceDate__c</fullName>
    <label>Finance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/InvoicePos__c/InvoicePos__c.object-meta.xml
<CustomObject>
    <label>Invoice Pos</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Invoice Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePos__c/fields/InvoiceName__c.field-meta.xml
<CustomField>
    <fullName>InvoiceName__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/InvoicePositionAmount__c.field-meta.xml
<CustomField>
    <fullName>InvoicePositionAmount__c</fullName>
    <label>Invoice Position - Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <label>Package Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/BudgetAssignPackage__c.field-meta.xml
<CustomField>
    <fullName>BudgetAssignPackage__c</fullName>
    <formula>CASE( RecordType.DeveloperName , 
&quot;Time&quot;,BudgetAssignTotalTime__c,
&quot;Expense&quot;, BudgetAssignTotalExpense__c ,
&quot;SupplierCosts&quot;, BudgetAssignTotalSupplierCosts__c ,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Budget Assign - Package</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <description>Diese Feld wird verwendet für die Zuweisung von Finance Account im ILV Prozess (Name Mapping)</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package Type Finance Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/SupplierCosts__c/SupplierCosts__c.object-meta.xml
<CustomObject>
    <label>Supplier Costs</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>Supplier Costs Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCosts__c/fields/FinanceDate__c.field-meta.xml
<CustomField>
    <fullName>FinanceDate__c</fullName>
    <label>Finance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <filterItems>
            <field>Package__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier Costs, License (Provision), License (Direct)</value>
        </filterItems>
        <filterItems>
            <field>Package__c.ProjectName__c</field>
            <operation>equals</operation>
            <valueField>$Source.ProjektName__c</valueField>
        </filterItems>
        <filterItems>
            <field>Package__c.ProjectName__r.ProjectNr__c</field>
            <operation>notEqual</operation>
            <value>P-105657</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Supplier Costs</relationshipLabel>
    <relationshipName>SupplierCosts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/ServiceSupplierCostsNetPM__c.field-meta.xml
<CustomField>
    <fullName>ServiceSupplierCostsNetPM__c</fullName>
    <label>Service -  Supplier Costs Net (PM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/SupplierCostsDate__c.field-meta.xml
<CustomField>
    <fullName>SupplierCostsDate__c</fullName>
    <label>Supplier Costs Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/DateFrom__c.field-meta.xml
<CustomField>
    <fullName>DateFrom__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date (From)</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Time__c/fields/ServiceTotalTime__c.field-meta.xml
<CustomField>
    <fullName>ServiceTotalTime__c</fullName>
    <formula>DurationHhMmN__c * RateHour__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service - Total Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PackageILVCreation.cls
public with sharing class PackageILVCreation {

  @AuraEnabled
  public Package__c pck;

  @AuraEnabled
  public Double budget; // E1

  @AuraEnabled
  public Double services; // E2

  @AuraEnabled
  public Double invoice; // E3

  @AuraEnabled
  public Double billingRate; // E4

  @AuraEnabled
  public Double servicesDR; // F1 Date Range

  @AuraEnabled
  public Double invoiceDR; // F2

  @AuraEnabled
  public Double billingRateDR; // F3

  public List<InvoicePos__c> positions;

  /**
  * Group constructor
  * @p group package to be initialized
  **/
  public PackageILVCreation(Package__c p) {
    this.pck = p;
    this.setDefaults();
  }

  /**
   * Subgroup constructor
   * @p subpackage to be summed up
   * @pGroup parent package to be proccessed alongside to its subpackage
   **/
  public PackageILVCreation(Package__c p, PackageILVCreation pGroup, DateRange dates) {
    this.pck = p;
    this.setDefaults();
    this.sumup(pGroup, dates);
  }

  private void sumup(PackageILVCreation pGroup, DateRange dates) {
    setBudgetAndServices(pGroup);
    setInvoice(pGroup);
    setBillingRate(pGroup);
    setServicesDR(pGroup, dates);
    setInvoiceDR(pGroup, dates);
    setBillingRateDR(pGroup, dates);
  }

  public void setBudgetAndServices(PackageILVCreation pGroup) {
    if (this.pck.BudgetAssignPackage__c != null) {
      this.budget = Test.isRunningTest() ? 10 : this.pck.BudgetAssignPackage__c;

      if (!isGroupNull(pGroup))
        pGroup.budget += Test.isRunningTest() ? 10 : this.pck.BudgetAssignPackage__c;
    }

    if (this.pck.ServicesTotalAmount__c != null) {
      this.services = Test.isRunningTest() ? 10 : this.pck.ServicesTotalAmount__c;

      if (!isGroupNull(pGroup))
        pGroup.services += Test.isRunningTest() ? 10 : this.pck.ServicesTotalAmount__c;
    }
  }

  public void setInvoice(PackageILVCreation pGroup) {
    /* Boolean isSubpackage = (pGroup != null); */
    Boolean hasPositions = this.pck != null && this.pck.InvoicePos__r != null && this.pck.InvoicePos__r.size() > 0;

    if (hasPositions) {
      this.positions = this.pck.InvoicePos__r;

      for (InvoicePos__c pos: this.positions) {
          this.invoice += pos.InvoicePositionAmount__c;
      }

      if (!isGroupNull(pGroup)) {
          /* pGroup.position.InvoicePositionAmount__c += this.position.InvoicePositionAmount__c; */
          pGroup.invoice += this.invoice;
      }

    }
  }

  public void setBillingRate(PackageILVCreation pGroup) {
    if (this.services <= 0) return;

    this.billingRate = (this.invoice / this.services) * 100;

    if (!isGroupNull(pGroup))
      pGroup.billingRate += this.billingRate;
  }

  public void setServicesDR(PackageILVCreation pGroup, DateRange dates) {
    if (dates.isNull()) return;

    if (this.pck.PackageType__c == PackageDomain.TYPE_TIME) {
      for (Time__c t : this.pck.Time__r) {
        if (t.ServiceTotalTime__c != null && dates.isInBetween(t.DateFrom__c))
          this.servicesDR += t.ServiceTotalTime__c;
      }
    } else if (this.pck.PackageType__c == PackageDomain.TYPE_EXPENSE) {
      for (Expense__c e : this.pck.Expenses__r) {
        if (e.ServiceExpenseNet__c != null && dates.isInBetween(e.ExpenseDate__c))
          this.servicesDR += e.ServiceExpenseNet__c;
      }
    } else if (this.pck.PackageType__c == PackageDomain.TYPE_SUPPLIER_COSTS) {
      for (SupplierCosts__c sc : this.pck.SupplierCosts__r) {
        if (sc.ServiceSupplierCostsNetPM__c != null && dates.isInBetween(sc.SupplierCostsDate__c))
          this.servicesDR += sc.ServiceSupplierCostsNetPM__c;
      }
    }

    if (!isGroupNull(pGroup))
      pGroup.servicesDR += this.servicesDR;
  }

  public void setInvoiceDR(PackageILVCreation pGroup, DateRange dates) {
    if (dates.isNull()) return;

    if (this.positions != null) {

        for (InvoicePos__c pos: this.positions)
            if (dates.isInBetween(pos.InvoiceName__r.FinanceDate__c))
                this.invoiceDR += pos.InvoicePositionAmount__c;

        if (!isGroupNull(pGroup))
            pGroup.invoiceDR += this.invoiceDR;

    }
  }

  public void setBillingRateDR(PackageILVCreation pGroup, DateRange dates) {
    if (this.servicesDR <= 0 || dates.isNull()) return;

    this.billingRateDR = (this.invoiceDR / this.servicesDR) * 100;

    if (!isGroupNull(pGroup))
      pGroup.billingRateDR += this.billingRateDR;
  }

  private void setDefaults() {
    this.budget = 0;
    this.services = 0;
    this.invoice = 0;
    this.billingRate = 0;
    this.servicesDR = 0;
    this.invoiceDR = 0;
    this.billingRateDR = 0;
  }

  private Boolean isGroupNull(PackageILVCreation pGroup) {
    return pGroup == null;
  }

}