force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EE-{000000}</displayFormat>
        <label>Expense Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/ExpensetrackerCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ExpensetrackerCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Expensetracker Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Expenses (Expensetracker Cost Center)</relationshipLabel>
    <relationshipName>Expenses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Package__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ServiceExpenseNet__c.field-meta.xml
<CustomField>
    <fullName>ServiceExpenseNet__c</fullName>
    <label>Service - Expense Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/ILVPos__c.object-meta.xml
<CustomObject>
    <label>ILV Pos</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>ILV Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ILV Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ILVPos__c/fields/CostCenterILVReceiver__c.field-meta.xml
<CustomField>
    <fullName>CostCenterILVReceiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cost Center (ILV Receiver)</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/ILVType__c.field-meta.xml
<CustomField>
    <fullName>ILVType__c</fullName>
    <label>ILV Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/InvoiceName__c.field-meta.xml
<CustomField>
    <fullName>InvoiceName__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ILVPos__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>ILV Pos</relationshipLabel>
    <relationshipName>ILVPos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{000000}</displayFormat>
        <label>Invoice Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/InvoicePos__c/InvoicePos__c.object-meta.xml
<CustomObject>
    <label>Invoice Pos</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Invoice Pos Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Pos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePos__c/fields/InvoiceName__c.field-meta.xml
<CustomField>
    <fullName>InvoiceName__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Invoice Pos</relationshipLabel>
    <relationshipName>InvoicePos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePos__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <label>Package Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/PackageType__c.field-meta.xml
<CustomField>
    <fullName>PackageType__c</fullName>
    <description>Diese Feld wird verwendet für die Zuweisung von Finance Account im ILV Prozess (Name Mapping)</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package Type Finance Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <formula>ProjectName__r.ProjectCostCenter__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Cost Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.ProjectStatus__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <infoMessage>Attention: You should not add a package to a Project with Status = Closed</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>PackagesProjectName</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/Package__c/recordTypes/Time.recordType-meta.xml
<RecordType>
    <fullName>Time</fullName>
    <active>true</active>
    <label>Time</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Internal Contract Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CostCenter__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/SupplierCosts__c.object-meta.xml
<CustomObject>
    <label>Supplier Costs</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>Supplier Costs Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplierCosts__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <filterItems>
            <field>Package__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier Costs, License (Provision), License (Direct)</value>
        </filterItems>
        <filterItems>
            <field>Package__c.ProjectName__c</field>
            <operation>equals</operation>
            <valueField>$Source.ProjektName__c</valueField>
        </filterItems>
        <filterItems>
            <field>Package__c.ProjectName__r.ProjectNr__c</field>
            <operation>notEqual</operation>
            <value>P-105657</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Supplier Costs</relationshipLabel>
    <relationshipName>SupplierCosts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipName>SupplierCosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SupplierCosts__c/fields/ServiceSupplierCostsNetPM__c.field-meta.xml
<CustomField>
    <fullName>ServiceSupplierCostsNetPM__c</fullName>
    <label>Service -  Supplier Costs Net (PM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package Name</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Time__c/fields/ProjectCostCenter__c.field-meta.xml
<CustomField>
    <fullName>ProjectCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/ServiceTotalTime__c.field-meta.xml
<CustomField>
    <fullName>ServiceTotalTime__c</fullName>
    <formula>DurationHhMmN__c * RateHour__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service - Total Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/TimetrackerCostCenter__c.field-meta.xml
<CustomField>
    <fullName>TimetrackerCostCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Timetracker - Cost Center</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Time (Timetracker - Cost Center)</relationshipLabel>
    <relationshipName>TimeTracker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CostCenterILVCreation.cls
public with sharing class CostCenterILVCreation {

  @AuraEnabled
  public Id ccId;

  @AuraEnabled
  public String name; // CostCenter Name

  @AuraEnabled
  public Package__c pck;

  @AuraEnabled
  public Decimal services; // G1 & H1

  @AuraEnabled
  public Decimal revenue; // G2 & H2

  @AuraEnabled
  public Decimal revenueRate; // G3 & H3

  @AuraEnabled
  public Decimal servicesDR; // G4 & H4

  @AuraEnabled
  public Decimal revenueNew; // G5 & H5 always zero from apex side

  @AuraEnabled
  public Decimal revenueRateDR; // G6 & H6 always zero from apex side

  @AuraEnabled
  public ILVPos__c position; // it will be null for Leading CC

  public Invoice__c inv;
  public Boolean isLeading;


  /**
   * Group constructor
   * @p subpackage to be summed up
   * @isLeadingCC leading cost center flag
   * @dateFrom & @dateTo date range for the calculation
   **/
  public CostCenterILVCreation(Id ccId, String name, Package__c p, Invoice__c inv, Boolean isLeadingCC) {
    this.ccId = ccId;
    this.name = name;
    this.pck = p;
    this.inv = inv;
    this.isLeading = isLeadingCC;
    this.setDefaults();

    if (!isLeadingCC)
        this.setRevenueReceiving(null);
  }

  /**
   * Subgroup constructor
   * @p subpackage to be summed up
   * @pGroup parent package to be proccessed alongside to its subpackage
   * @isLeadingCC leading cost center flag
   * @dateFrom & @dateTo date range for the calculation
   **/
  public CostCenterILVCreation(Id ccId, String name, Package__c p, Invoice__c inv,
          CostCenterILVCreation ccGroup, Boolean isLeadingCC, DateRange dates) {
    this.ccId = ccId;
    this.name = name;
    this.pck = p;
    this.inv = inv;
    this.isLeading = isLeadingCC;
    this.setDefaults();
    this.sumup(ccGroup, dates);
  }

  private void sumup(CostCenterILVCreation ccGroup, DateRange dates) {
    if (isLeading) {
      setServicesLeading(ccGroup);
      setRevenueLeading(ccGroup);
      setRevenueRate(ccGroup);
      setServicesDRLeading(ccGroup, dates);
    } else {
      setServicesReceiving(ccGroup);
      setRevenueReceiving(ccGroup);
      setRevenueRate(ccGroup);
      setServicesDRReceiving(ccGroup, dates);
    }
  }

  public void setServicesLeading(CostCenterILVCreation ccGroup) {
    if (this.pck.PackageType__c == PackageDomain.TYPE_TIME) {
      for (Time__c t : this.pck.Time__r) {
        if (t.ServiceTotalTime__c != null && t.TimeTrackerCostCenter__c == ccId)
          this.services += t.ServiceTotalTime__c;
      }
    } else if (this.pck.PackageType__c == PackageDomain.TYPE_EXPENSE) {
      for (Expense__c e : this.pck.Expenses__r) {
        if (e.ServiceExpenseNet__c != null && e.ExpensetrackerCostCenter__c == ccId)
          this.services += e.ServiceExpenseNet__c;
      }
    } else if (this.pck.PackageType__c == PackageDomain.TYPE_SUPPLIER_COSTS) {
      for (SupplierCosts__c sc : this.pck.SupplierCosts__r) {
        if (sc.ServiceSupplierCostsNetPM__c != null && sc.ProjectCostCenter__c == ccId)
          this.services += sc.ServiceSupplierCostsNetPM__c;
      }
    }

    if (!isGroupNull(ccGroup))
      ccGroup.services += this.services;
  }

  public void setServicesReceiving(CostCenterILVCreation ccGroup) {
    if (this.pck.PackageType__c == PackageDomain.TYPE_TIME) {
      for (Time__c t : this.pck.Time__r) {
        if (t.ServiceTotalTime__c != null && t.TimeTrackerCostCenter__c == ccId)
          this.services += t.ServiceTotalTime__c;
      }
    }

    if (!isGroupNull(ccGroup))
      ccGroup.services += this.services;

  }

  public void setRevenueLeading(CostCenterILVCreation ccGroup) {
    Boolean isSubpackage = (ccGroup != null);
    Boolean hasInvPosition = this.pck != null && this.pck.InvoicePos__r != null && this.pck.InvoicePos__r.size() == 1;
    Boolean hasILVPosition = this.pck != null && this.pck.ILVPos__r != null && this.pck.ILVPos__r.size() > 0;

    if (hasInvPosition && hasILVPosition) {
      InvoicePos__c invPos = this.pck.InvoicePos__r;
      Decimal receivingRevenues = 0;

      for (ILVPos__c ip: this.pck.ILVPos__r) {
        if (ip.ILVType__c == 'Time' && ip.CostCenterILVReceiver__c != this.pck.ProjectName__r.ProjectCostCenter__c)
          receivingRevenues += ip.ILVPositionAmount__c;
      }

      if (receivingRevenues == 0)
        this.revenue = invPos.InvoicePositionAmount__c;
      else
        this.revenue = invPos.InvoicePositionAmount__c / receivingRevenues;

      if(isSubpackage && !isGroupNull(ccGroup))
        ccGroup.revenue += this.revenue;
    }

  }

  public void setRevenueReceiving(CostCenterILVCreation ccGroup) {
    Boolean isSubpackage = (ccGroup != null);
    Boolean hasILVPosition = this.pck != null && this.pck.ILVPos__r != null && this.pck.ILVPos__r.size() > 0;

    if (hasILVPosition) {

      for (ILVPos__c ip: this.pck.ILVPos__r) {
        if (ip.CostCenterILVReceiver__c == ccId) {
            if (inv != null && inv.Id == ip.InvoiceName__c)
                this.position = ip;

          if (ip.PackageSubType__c == 'WorkTime'
                  && ip.InvoiceName__r != null
                  && ip.InvoiceName__r.InvoiceStatus__c != Invoice.STATUS_DRAFT)
            this.revenue += ip.ILVPositionAmount__c;
        }
      }

      if(isSubpackage && !isGroupNull(ccGroup))
        ccGroup.revenue += this.revenue;
    }

  }

  public void setRevenueRate(CostCenterILVCreation ccGroup) {
    if (this.services <= 0) return;

    this.revenueRate = (this.revenue / this.services) * 100;

    if (!isGroupNull(ccGroup))
      ccGroup.revenueRate += this.revenueRate;
  }

  public void setServicesDRLeading(CostCenterILVCreation ccGroup, DateRange dates) {
    if (dates.isNull()) return;

    if (this.pck.PackageType__c == PackageDomain.TYPE_TIME) {
      for (Time__c t : this.pck.Time__r) {
        if (t.ServiceTotalTime__c != null && dates.isInBetween(t.DateFrom__c) && t.TimeTrackerCostCenter__c == ccId)
          this.servicesDR += t.ServiceTotalTime__c;
      }
    } else if (this.pck.PackageType__c == PackageDomain.TYPE_EXPENSE) {
      for (Expense__c e : this.pck.Expenses__r) {
        if (e.ServiceExpenseNet__c != null && dates.isInBetween(e.ExpenseDate__c) && e.ExpensetrackerCostCenter__c == ccId)
          this.servicesDR += e.ServiceExpenseNet__c;
      }
    } else if (this.pck.PackageType__c == PackageDomain.TYPE_SUPPLIER_COSTS) {
      for (SupplierCosts__c sc : this.pck.SupplierCosts__r) {
        if (sc.ServiceSupplierCostsNetPM__c != null && dates.isInBetween(sc.SupplierCostsDate__c) && sc.ProjectCostCenter__c == ccId)
          this.servicesDR += sc.ServiceSupplierCostsNetPM__c;
      }
    }

    if (!isGroupNull(ccGroup))
      ccGroup.servicesDR += this.servicesDR;
  }

  public void setServicesDRReceiving(CostCenterILVCreation ccGroup, DateRange dates) {
    if (dates.isNull()) return;

    if (this.pck.PackageType__c == PackageDomain.TYPE_TIME) {
      for (Time__c t : this.pck.Time__r) {
        if (t.ServiceTotalTime__c != null && dates.isInBetween(t.DateFrom__c) && t.TimeTrackerCostCenter__c == ccId)
          this.servicesDR += t.ServiceTotalTime__c;
      }
    }

    if (!isGroupNull(ccGroup))
      ccGroup.servicesDR += this.servicesDR;
  }

  private void setDefaults() {
    this.services = 0;
    this.revenue = 0;
    this.revenueRate = 0;
    this.servicesDR = 0;
    this.revenueNew = 0;
    this.revenueRateDR = 0;
  }

  private Boolean isGroupNull(CostCenterILVCreation ccGroup) {
    return ccGroup == null;
  }
}